### ISSUE TITLE
0crat failed on a non assigned closed task

### ISSUE THREAD

**Issue by biboran** [zerocracy/farm#1000]
@0crat asked me to submit the issue for him for BlockStoreApp/Web3Swift/issues/49

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@biboran yes, it's a dup of #1003

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
