### ISSUE TITLE
Upgrade qulice to 0.17.3

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1002]
New qulice version brings following important changes:
- removal of `@author` tag (it is prohibited now)
- removal of `@version` tag (it is prohibited now)
- license header should start with `/*` instead of `/**`  - this will fix problem with IntelliJ reporting it as a javadoc that is not attached to any class
- checkstyle validation performance improvement (speedup of ~ 10%)
And few minor formatting changes.

Please upgrade the qulice and fix the new problems found.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1002](https://github.com/zerocracy/farm/issues/1002) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1002](https://github.com/zerocracy/farm/issues/1002) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1701418785); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #1041, cannot build and run all tests on my machine yet

**Comment by 0crat** [comment]
> @0crat wait for #1041, cannot build and run all tests on my machine yet ([here](https://github.com/zerocracy/farm/issues/1002#issuecomment-400282555))

@paulodamaso The impediment for [#1002](https://github.com/zerocracy/farm/issues/1002) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by krzyk** [comment]
@paulodamaso you can for now use `-DskipTests`, this wil allow you do do all checkstyle/PMD fixes and hope they will run in travis later

**Comment by paulodamaso** [comment]
@krzyk Thanks, but now I'm having other problems to build, you already knows it ;)

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/teamed/qulice/issues/909 , when qulice is fixed I'll be able to finish this task

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/teamed/qulice/issues/909 , when qulice is fixed I'll be able t... ([here](https://github.com/zerocracy/farm/issues/1002#issuecomment-403360858))

@paulodamaso Job [#1002](https://github.com/zerocracy/farm/issues/1002) is already on hold

**Comment by paulodamaso** [comment]
@krzyk Already merged, please close.

**Comment by krzyk** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1002](https://github.com/zerocracy/farm/issues/1002) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
