### ISSUE TITLE
package-info.java:24-27: Change 'com.zerocracy.pmo'...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1006]
The puzzle `715-1243e0dc` from #715 has to be resolved:

https://github.com/zerocracy/farm/blob/0ff4574278030b5972d54c3fdfa3f4685f2a3606/src/main/java/com/zerocracy/pmo/package-info.java#L24-L27

The puzzle was created by Yegor Bugayenko on 11-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1006](https://github.com/zerocracy/farm/issues/1006) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1006](https://github.com/zerocracy/farm/issues/1006) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1310414059); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zerocracy/farm/issues/1006#issuecomment-390425401))

@proshin-roman The impediment for [#1006](https://github.com/zerocracy/farm/issues/1006) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0pdd** [comment]
The puzzle `715-1243e0dc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1006](https://github.com/zerocracy/farm/issues/1006) is now out of scope

**Comment by ypshenychka** [comment]
@proshin-roman According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please provide more details in registered [impediment](https://github.com/zerocracy/farm/issues/1006#issuecomment-390425401).

**Comment by proshin-roman** [comment]
@ypshenychka hm, it looks like there is a bug in the Policy: it doesn't define any constraints for the DEV about a reason of impediments, but QA rules define such a constraint. About this specific ticket: I put it to waiting just because I wasn't able to finish it in 10 days.

**Comment by ypshenychka** [comment]
@proshin-roman Good, thanks. Feel free to submit an issue if you see any.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)
