### ISSUE TITLE
Redundant message for @0pdd

### ISSUE THREAD

**Issue by alex-semenyuk** [zerocracy/farm#1007]
It doesn't make sense to show this message

> @0pdd this project will fix the problem faster if you donate a few dollars to it; just click here and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@alex-semenyuk fixed in d1d0ea55 thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
