### ISSUE TITLE
0crat not taking points for invitations

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1008]
0crat is not charging mentors for inviting new students. I made an invite, the student already appears at team page, but I have not paid 128 points for the invitation, as sain in policy (http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@paulodamaso policy changed, now you will receive +32 points for invite

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1008` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
