### ISSUE TITLE
Not being assigned to any jobs in some projects

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1009]
~~I'm not sure if there is some kind of an internal block or an error.~~
~~I'm assigned currently to few projects, I'm getting tasks in two of them and not getting any tasks in another two: zerocracy and takes.~~

~~Right now my number of assigned jobs is 6 (max allowed is 8), and in zerocracy the ration of assigned jobs / unassigned ones is 62/106 (I don't know how it looks like for takes, as it is not published on the board).~~

~~I would assume I would get assigned one of the jobs available in one of those two projects.~~

EDIT: and suddently, after few hours after I reported it I got assigned two jobs in zerocracy, strange :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
