### ISSUE TITLE
Self (@you) page should diffrentiate between rev and dev jobs

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1010]
When I go to my page in zerocracy (`@krzyk` link) I see:
> Your currently open jobs: 6 (max allowed: 8).

Right now I don't have any REV jobs assigned, but when I had the text would look something like this:
> Your currently open jobs: 12 (max allowed: 8). 

REV jobs don't have a limit, so I would expect the above text to differentiate between REV and DEV jobs, e.g. like this:
> Your currently open jobs: 6 (max allowed: 8).
> Your currently open REV jobs: 4

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by krzyk** [comment]
@yegor256 Ah, OK now I understand.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
