### ISSUE TITLE
0crat may not pay 10 min for closed PR

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1012]
According to [policy#28](http://www.zerocracy.com/policy.html#28) architect should receive payment and reputation (10 minutes) for each merged PR, but if PR is small (less than 10 lines of code) 0crat skips ARC review bonus.
If it is expected behavior then policy have to be updated.

**Comment by yegor256** [comment]
@g4s8 see: https://github.com/zerocracy/zerocracy.github.io/commit/3a8b759d5c8d49aa1c1b2f17ab3352cc0dff4435

**Comment by yegor256** [comment]
@g4s8 see bbb12a28

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
