### ISSUE TITLE
Unrecoverable failure on Ocrat

### ISSUE THREAD

**Issue by elenavolokhova** [zerocracy/farm#1018]
Happened [here](https://github.com/yegor256/cactoos/issues/799#issuecomment-388869099) and [here](https://github.com/yegor256/cactoos/issues/518#issuecomment-388876945):
```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: AsyncFlush-1
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/qa/complete_qa_review.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.DomParser[112] java.lang.IllegalArgumentException: Invalid XML: "<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="Policy of Zerocrat, a project manager
that never sleeps, owned and maintained by Zerocracy.
"/>
...
```

**Comment by victornoel** [comment]
@yegor256 also [here](https://github.com/yegor256/cactoos/pull/856#issuecomment-388865415)

**Comment by llorllale** [comment]
@yegor256 same [here](https://github.com/yegor256/cactoos/issues/747#issuecomment-388904966)

**Comment by amihaiemil** [comment]
@yegor256 don't just fix that ``<img/>`` tag, but separate some concerns there. What does the validation of some HTML page have to do with making payments or completin QA review? It's embarassing!

**Comment by yegor256** [comment]
@amihaiemil we keep all our configuration data in that HTML page. I agree, it's not stable now. I will do something in order to make it more reliable.

**Comment by yegor256** [comment]
@elenavolokhova fixed: https://github.com/zerocracy/zerocracy.github.io/commit/6d07b7690dcb1d81a68a62dca1671706ed26806a

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by elenavolokhova** [comment]
@yegor256 what about payment for all these tickets? 0crat refuses my review now. No one was paid.

**Comment by paulodamaso** [comment]
@elenavolokhova The payment for https://github.com/yegor256/cactoos/issues/747 was added to my wallet some minutes ago.
