### ISSUE TITLE
Reduce extra payment penalty

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1019]
0crat can miss payments because of bugs (e.g. it didn't pay anything for few hours yesterday), so ARC have to pay to all team manually with `extra` command. It may dramatically decrease ARC reputation (e.g. 5 jobs * 120 penalty = -600 reputation), so I'd suggest to change the penalty to `-30` until 0crat payments will be stable.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 agreed, fixed: https://github.com/zerocracy/zerocracy.github.io/commit/0888811c83f786ec21e6793cb77465df82ec2c80

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by g4s8** [comment]
@yegor256 thanks
