### ISSUE TITLE
Unrecoverable failure

### ISSUE THREAD

**Issue by VsSekorin** [zerocracy/farm#1020]
```
PID: 4@1d215df6-c9a5-427f-8e41-c8a961917344, thread: AsyncFlush-8
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.GeneratedMethodAccessor104[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/vssekorin.xml" is not accessible in "PMO"
```
Happened in https://github.com/yegor256/cactoos/pull/810#issuecomment-386884228

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vssekorin[/z](https://www.0crat.com/u/vssekorin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@VsSekorin it's fixed already, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
