### ISSUE TITLE
https://www.0crat.com/board not working

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1021]
https://www.0crat.com/board and all pages that I think require DB connection (e.g. agenda, team, self page) are not working, there is a heroku "Application Error" page.

The only page working right now is the main one (https://www.0crat.com), terms and policy.

Please make it work.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
