### ISSUE TITLE
breakup is adding 256 points, not deducting

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#1026]
The `breakup` command is doing the opposite of what the policy says: it's actually adding 256 points to the mentor instead of deducting them. 

For example, I just broke up with a student and this was my award:

```xml
<tr>
  <td style="text-align:right">
    <span xmlns:xs="http://www.w3.org/1999/xhtml" style="color:orange;">+256</span>
    <span style="line-height:0.8em;font-size:0.8em;color:gray;display:block;">
      <span xmlns:xs="http://www.w3.org/1999/xhtml" title="$ ago at 2018-05-18T17:48:14.38Z">1 mins</span>
    </span>
  </td>
  <td>
    <code xmlns:xs="http://www.w3.org/1999/xhtml" style="background-color:lightcoral;">
      <a href="https://www.0crat.com/p/PMO" title="Project PMO">PMO</a>
    </code>
  </td>
  <td>
    <a xmlns:xs="http://www.w3.org/1999/xhtml" href="https://github.com/zerocracy/datum/issues/1" title="Issue #1 in zerocracy/datum GitHub repository">zerocracy/datum#1</a>
  </td>
  <td>Penalize for breakup</td>
</tr>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#1026](https://github.com/zerocracy/farm/issues/1026) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1391414098); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1026` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@llorllale thanks, fixed in 16c35b7

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1026](https://github.com/zerocracy/farm/issues/1026) is now out of scope
