### ISSUE TITLE
Penalty for ARC if PR is not merged

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1028]
ARC doesn't have enough motivation to close (merge) pull requests which was reviewed. I think we can add a penalty for ARC if PR was approved (we can check review status via GitHub API) but not merged or closed within 10? days.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
This seems like a very important feature.

**Comment by yegor256** [comment]
@g4s8 but there is money involved? The ARC gets a payment when the code is merged and a PR is closed. Aside from that, how a bot can understand that the PR _must_ be approved or not?

**Comment by SilasReinagel** [comment]
@yegor256 Good project managers know that speed of delivery is one of the most valuable things for a project. 0crat should do everything he can to get PRs merged in as fast and frequently as possible. This must mean disincentives/punishment for anyone who slows down the project. 

All PRs should be merged/rejected as fast as possible. Anything that prevents the timely resolution of a PR should be filed as a bug and structurally fixed.

**Comment by g4s8** [comment]
@yegor256 yes, not money, but ARC can get negative reputation if  he/she didn't merge PR within 10 days. We can know PR review status via GitHub API: https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

**Comment by yegor256** [comment]
@g4s8 @SilasReinagel how about a penalty for long REV tasks? When a PR is merged, the task is closed. We know how long it took. If it was longer than X days, the ARC gets a penalty. If longer than Y days, a very big penalty. Make sense?

**Comment by SilasReinagel** [comment]
@yegor256 Is the completion of the REV task always simultaneous with the merging of the PR?

If those are different, then that seems insufficient.

**Comment by g4s8** [comment]
@yegor256 yes, it make sense.

**Comment by yegor256** [comment]
@SilasReinagel completion of REV task and closing the PR are same things.

**Comment by yegor256** [comment]
@g4s8 let's do -15 for "over 8 days" and -60 for "over 16 days"?

**Comment by 0crat** [comment]
Job [#1028](https://github.com/zerocracy/farm/issues/1028) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks)  ([here](https://github.com/zerocracy/farm/issues/1028#issuecomment-414095310))

@carlosmiranda The impediment for [#1028](https://github.com/zerocracy/farm/issues/1028) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1028#issuecomment-416456704))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1028](https://github.com/zerocracy/farm/issues/1028), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1028](https://github.com/zerocracy/farm/issues/1028), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
done in #1703

**Comment by 0crat** [comment]
Job [#1028](https://github.com/zerocracy/farm/issues/1028) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1028](https://github.com/zerocracy/farm/issues/1028) is now out of scope
