### ISSUE TITLE
QA rule improvement

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1029]
This QA rule looks redundant if pull request has a link to ticket, because GitHub automatically add a reference to pull request in a ticket:
> Some of ticket messages must mention all pull requests where the problem was actually fixed;

I'd change it to:
> Ticket must have references to all pull requests where the problem was actually fixed;

So this rule accept both ticket comments and GitHub links.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed, thanks https://github.com/zerocracy/zerocracy.github.io/commit/c20dbfec40d07608654bfe5e529d086b246bd36b

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
