### ISSUE TITLE
Options.java:33-36: Options are not used. Election should...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1035]
The puzzle `703-5f3e27dc` from #703 has to be resolved:

https://github.com/zerocracy/farm/blob/563619f5122e47543f287b567238bb26a852f28a/src/main/java/com/zerocracy/pmo/Options.java#L33-L36

The puzzle was created by Yegor Bugayenko on 21-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1035](https://github.com/zerocracy/farm/issues/1035) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
> @0crat waiting for PR #1161 review  ([here](https://github.com/zerocracy/farm/issues/1035#issuecomment-398172632))

@krzyk The impediment for [#1035](https://github.com/zerocracy/farm/issues/1035) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `703-5f3e27dc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1185](https://github.com/zerocracy/farm/issues/1185), [#1186](https://github.com/zerocracy/farm/issues/1186), [#1187](https://github.com/zerocracy/farm/issues/1187) are still not solved.

**Comment by 0crat** [comment]
The job [#1035](https://github.com/zerocracy/farm/issues/1035) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1185](https://github.com/zerocracy/farm/issues/1185), [#1186](https://github.com/zerocracy/farm/issues/1186) are still not solved; solved: [#1187](https://github.com/zerocracy/farm/issues/1187).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1185](https://github.com/zerocracy/farm/issues/1185), [#1186](https://github.com/zerocracy/farm/issues/1186), [#1472](https://github.com/zerocracy/farm/issues/1472) are still not solved; solved: [#1187](https://github.com/zerocracy/farm/issues/1187).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1185](https://github.com/zerocracy/farm/issues/1185), [#1472](https://github.com/zerocracy/farm/issues/1472) are still not solved; solved: [#1186](https://github.com/zerocracy/farm/issues/1186), [#1187](https://github.com/zerocracy/farm/issues/1187).
