### ISSUE TITLE
_after.groovy:23-27: Implement stakeholder...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1036]
The puzzle `889-ebed2d87` from #889 has to be resolved:

https://github.com/zerocracy/farm/blob/563619f5122e47543f287b567238bb26a852f28a/src/test/resources/com/zerocracy/bundles/turn_on_vacation_for_too_many_negative_awards/_after.groovy#L23-L27

The puzzle was created by Yegor Bugayenko on 21-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1036](https://github.com/zerocracy/farm/issues/1036) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1036](https://github.com/zerocracy/farm/issues/1036) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1611065244); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0pdd PR in #1154

**Comment by 0pdd** [comment]
The puzzle `889-ebed2d87` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1036](https://github.com/zerocracy/farm/issues/1036) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
