### ISSUE TITLE
There is no CI on Windows OS (Appveyor)

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1042]
I have a problem that the project doesn't build on Windows OS (see #1041). 

Having CI process on [Appveyor](https://www.appveyor.com/) (which is Windows-based) could identify the problem immediately when it was introduced.

**TODO:**
- configure CI process on [Appveyor](https://www.appveyor.com/) for the project

P.S. The build will fail until #1041 is fixed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@proshin-roman done in a50df6269ca2d38dbbd1540ced5538253fe89efc Thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
