### ISSUE TITLE
0crat assign task but it does not appear in agenda

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1043]
PR https://github.com/yegor256/cactoos/pull/866 was assigned to my by 0crat, but it does not appear in my agenda and github not does mark me as its owner.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso this was the issue: #987 :(

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
