### ISSUE TITLE
0crat didn't paid me for llorllale/cactoos-matchers/#9

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1044]
Recently I've reviewed PR https://github.com/llorllale/cactoos-matchers/pull/9 , the requested changes were made and QA was assured, marking review with a good quality mark. `ARC` and `QA` received their points, but none came to me, `REV`. Ididn't received any payment either; this issues does not show in my agenda, neither in wallet, and it's already been closed by QA reviewer.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@yegor256 Please take a look at this.

**Comment by yegor256** [comment]
@paulodamaso this is what happened: #987 :(

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
