### ISSUE TITLE
Automatically setup webhooks for repo

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1048]
Some GitHub application can add webhooks to repository (e.g. Codecov, Shippable),
I think 0crat should do the same

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 yes, I agree, when we do `links add github ...` we should try to add a webhook, if we have enough permissions for that. If not, we should tell the user that if he would give us permissions, we would configure the webhook too.

**Comment by 0crat** [comment]
Job [#1048](https://github.com/zerocracy/farm/issues/1048) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1048](https://github.com/zerocracy/farm/issues/1048) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1710754379); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@g4s8 Is there a specific list of events 0crat should subscribe to, or just all?

**Comment by g4s8** [comment]
@krzyk now we are using "Send me everything" checkbox to configure webhook.
![scrot-2018-06-20-15 41 47](https://user-images.githubusercontent.com/1524988/41658890-809a9f46-74a0-11e8-953c-2b202f42cf14.png)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1226](https://github.com/zerocracy/farm/issues/1226) is still not solved.

**Comment by krzyk** [comment]
@g4s8 changes have been merged to master in #1216, please close this issue

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1048](https://github.com/zerocracy/farm/issues/1048) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1550](https://github.com/zerocracy/farm/issues/1550) is still not solved; solved: [#1226](https://github.com/zerocracy/farm/issues/1226).
