### ISSUE TITLE
Can't destroy a project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1049]
0crat failed to destroy a project with error:
```
PID: 4@fa07475b-299d-4e6f-abbf-66307a6d6029, thread: AsyncFlush-8
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/destroy.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[121] java.lang.IllegalArgumentException: File "agenda/g4s8.xml" is not allowed in project "C6NU9QBJR"


1.0-SNAPSHOT: CID: 1461926497, Type: "Destroy", Author: "g4s8"
```

**Comment by 0crat** [comment]
The job [#1049](https://github.com/zerocracy/farm/issues/1049) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1481136645); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@3d763471

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1049` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 fixed, thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1049](https://github.com/zerocracy/farm/issues/1049) is now out of scope
