### ISSUE TITLE
Unrecoverable failure on refusing the issue

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1052]
The problem happened [here](https://github.com/zerocracy/farm/issues/601#issuecomment-392322059).

```
PID: 4@2b7a3737-162c-475c-82b8-037c82174a7a, thread: pool-21-thread-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```
1.0-SNAPSHOT: Issue: zerocracy/farm#601, Comment: 392322048

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@proshin-roman I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1052` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
