### ISSUE TITLE
Unrecoverable failure on inviting a new member

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1053]
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: AsyncFlush-2
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/invite_friend.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl[252] java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString
```

1.0-SNAPSHOT (https://github.com/zerocracy/farm): CID: 1471814497 (https://www.0crat.com/PMO/1471814497), Type: "Invite a friend", Author: "proshin-roman"

Possibly, there was a race condition as my second attempt wasn't successful too because somebody has already invited the person.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@proshin-roman I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1053` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
