### ISSUE TITLE
PO has to be invited by someone

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1054]
PO can't just create a project in Slack and invite architect to bootstrap a project because 0crat says that he must be invited by someone else. I think we need another flow for POs.

**Comment by yegor256** [comment]
@g4s8 I don't think it's true... Where exactly 0crat says that? How can I reproduce?

**Comment by g4s8** [comment]
@yegor256 when somebody creates a project in Zerocracy he can't see profile page (where he can find link to the project) until he has a mentor.

**Comment by yegor256** [comment]
@g4s8 what is "creates a project in Zerocracy"? Can you explain step by step?

**Comment by g4s8** [comment]
@yegor256 
1. PO authorized via GitHub in Zerocracy
2. I bootstrapped a project and assigned `PO` role to PO
3. PO can't see his profile page, because he doesn't have a mentor

**Comment by g4s8** [comment]
@yegor256 to see project link to add funds and see project links, such as Ledger, Estimates etc
Looks like he can access project by id without mentor, but it's not comfortable to remember id or save a link, because he can access 0crat from another device or forget project id

**Comment by yegor256** [comment]
@g4s8 so basically we should render his profile page, but with just a list of links to his project. That will be enough. Correct?

**Comment by g4s8** [comment]
@yegor256 yes

**Comment by 0crat** [comment]
Job [#1054](https://github.com/zerocracy/farm/issues/1054) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@g4s8 please close this issue, it has been fixed in #1266

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1054](https://github.com/zerocracy/farm/issues/1054) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#1278](https://github.com/zerocracy/farm/issues/1278), [#1279](https://github.com/zerocracy/farm/issues/1279).
