### ISSUE TITLE
0crat didn't pay job completion after QA review 

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1056]
See yegor256/cactoos#588.

QA reviewed with `good` and no points were awarded to the job assignee.

This happened silently, without any exception.

Also the contrib ledger of the project seems to contain something about the payment but from my point of view, nothing happened at all.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by carlosmiranda** [comment]
@g4s8 I received no payment nor credit for #1438, and neither did QA it seems. There was an [error](https://github.com/zerocracy/farm/issues/1438#issuecomment-407725989) this time.

**Comment by victornoel** [comment]
@carlosmiranda I haven't seen this for some time, what about you? If not I will close this issue :)

**Comment by carlosmiranda** [comment]
@victornoel yep, looks like this has been fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1056` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
