### ISSUE TITLE
Can't specify role on apply

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1073]
Person can't specify role when apply to a project, slack channel always says:
> &lt;username&gt; wants to join .... just assign DEV role

I think 0crat should say in channel what role person wants (or maybe few roles: `DEV REV`).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1073` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
