### ISSUE TITLE
Let's pay ZLD to developers

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1074]
Let's make it possible to pay ZLD to developers.

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/1074#issuecomment-393533302))

@yegor256 The job [#1074](https://github.com/zerocracy/farm/issues/1074) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1511352796); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that g4s8 is on vacation; this ticket may be delayedcom.zerocracy.Par@1a6f507f

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@0crat waiting zerocracy/datum#334 to resolve

**Comment by 0crat** [comment]
> @0crat waiting zerocracy/datum#334 to resolve ([here](https://github.com/zerocracy/farm/issues/1074#issuecomment-393581223))

@g4s8 The impediment for [#1074](https://github.com/zerocracy/farm/issues/1074) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1079](https://github.com/zerocracy/farm/issues/1079) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PR #1075 was merged with puzzle #1079 to continue, can we close this job?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1074](https://github.com/zerocracy/farm/issues/1074) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1079](https://github.com/zerocracy/farm/issues/1079) is solved here.
