### ISSUE TITLE
Zold.java:27-29: Zold payments are not implemented, we...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1079]
The puzzle `1074-b36594a1` from #1074 has to be resolved:

https://github.com/zerocracy/farm/blob/1b5ead82abe0a440ee0d0415bf968cdd9284f13a/src/main/java/com/zerocracy/pmo/banks/Zold.java#L27-L29

The puzzle was created by rultor on 02-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1079](https://github.com/zerocracy/farm/issues/1079) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1079](https://github.com/zerocracy/farm/issues/1079) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1801338972); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1074-b36594a1` has disappeared from the source code, that's why I closed this issue.
