### ISSUE TITLE
Few issues with builds

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1093]
1. In PR https://github.com/zerocracy/farm/pull/1027 I noticed that pdd validation and XML formatting (using xcop) is not performed in travis nor appveyor builds.

2. In rultor config architects section g4s8 should be first, so rultor won't spam Yegor with merge confirmations.

3. MaxPermSize should be removed from all builds (rultor, Travis,  appveyor).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1093#issuecomment-396170558))

@g4s8 The job [#1093](https://github.com/zerocracy/farm/issues/1093) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1620894508); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@krzyk fixed in 9dd4d3bbffc339ba2f9871643758702fd416ff2f, also added `pdd` check to validate `@todo` puzzles, can we close now?

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1093](https://github.com/zerocracy/farm/issues/1093) is now out of scope
