### ISSUE TITLE
update_verbosity.groovy:35-37: Commit messages are not...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1096]
The puzzle `783-b88b1a6d` from #783 has to be resolved:

https://github.com/zerocracy/farm/blob/74e3b0828f4d3d0a591091ab98a5347581f767fc/src/main/groovy/com/zerocracy/stk/pm/in/orders/update_verbosity.groovy#L35-L37

The puzzle was created by g4s8 on 04-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1096](https://github.com/zerocracy/farm/issues/1096) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1096](https://github.com/zerocracy/farm/issues/1096) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1830857651); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for better implementation of the solution

**Comment by 0crat** [comment]
> @0crat waiting for better implementation of the solution ([here](https://github.com/zerocracy/farm/issues/1096#issuecomment-403144076))

@krzyk The impediment for [#1096](https://github.com/zerocracy/farm/issues/1096) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `783-b88b1a6d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1096](https://github.com/zerocracy/farm/issues/1096) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
