### ISSUE TITLE
Pulse graph

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1098]
We need pulse graph similar to http://www.rultor.com/ as discussed in https://github.com/zerocracy/farm/issues/622#issuecomment-394476343

`/pulse` endpoint is already implemented in #622

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1098#issuecomment-394840282))

@g4s8 Job [#1098](https://github.com/zerocracy/farm/issues/1098) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1098](https://github.com/zerocracy/farm/issues/1098) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2251440519); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/zerocracy/farm/pull/1604 review

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/zerocracy/farm/pull/1604 review ([here](https://github.com/zerocracy/farm/issues/1098#issuecomment-413744317))

@paulodamaso The impediment for [#1098](https://github.com/zerocracy/farm/issues/1098) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1098](https://github.com/zerocracy/farm/issues/1098) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
