### ISSUE TITLE
Crop speed of delivery 

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1099]
In length of time speed of delivery barely affected by new tasks, e.g. if user have not good speed for a while, and wants to improve it, he have to spend a lot of time to change current value. I think speed metric should be implemented similar to reputation: remove entries from `speed.xml` which are older than 90 days.
@yegor256 what do you think about it?

**Comment by yegor256** [comment]
@g4s8 definitely

**Comment by yegor256** [comment]
@g4s8 the same for all other metrics (don't forget to update the Policy)

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1099#issuecomment-394970023))

@g4s8 Job [#1099](https://github.com/zerocracy/farm/issues/1099) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1099](https://github.com/zerocracy/farm/issues/1099) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2041503568); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #1499

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1499  ([here](https://github.com/zerocracy/farm/issues/1099#issuecomment-408686405))

@krzyk The impediment for [#1099](https://github.com/zerocracy/farm/issues/1099) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1513](https://github.com/zerocracy/farm/issues/1513) is still not solved.

**Comment by krzyk** [comment]
@g4s8 please close this issue it has been solved in #1499

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
