### ISSUE TITLE
auto-assign REV role

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1100]
When PO/ARC assigns DEV role to someone, we should automatically assign REV role too. And notify the PO (in the same message we are sending now) that if this is not what they wanted, they can immediately say `resign REV`. In most cases we do need developers to be reviewers too. Let's make it easier.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1100#issuecomment-394969992))

@g4s8 Job [#1100](https://github.com/zerocracy/farm/issues/1100) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1100](https://github.com/zerocracy/farm/issues/1100) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2251457819); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/zerocracy/farm/pull/1593 merge.

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/zerocracy/farm/pull/1593 merge. ([here](https://github.com/zerocracy/farm/issues/1100#issuecomment-413293506))

@paulodamaso The impediment for [#1100](https://github.com/zerocracy/farm/issues/1100) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@paulodamaso thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1100](https://github.com/zerocracy/farm/issues/1100) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
