### ISSUE TITLE
0crat tries to assign Issue twice

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1101]
Starting recently, if I manually assign myself, 0crat tries to do the assignment twice and complains:

https://github.com/amihaiemil/docker-java-api/issues/130#event-1665288352

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1101#issuecomment-394969818))

@g4s8 Job [#1101](https://github.com/zerocracy/farm/issues/1101) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1101](https://github.com/zerocracy/farm/issues/1101) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2251447720); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1101#issuecomment-413558112))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1101](https://github.com/zerocracy/farm/issues/1101), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by rgevaerd** [comment]
@amihaiemil Can you provide the footprint of https://github.com/amihaiemil/docker-java-api/issues/130?

**Comment by amihaiemil** [comment]
@rgevaerd I don't really know how. I said ``@0crat footpring`` on that issue, but it didn't respond yet. 

@g4s8 How can I get the footprint of a certain Issue, exactly?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/1101#issuecomment-414116311); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by g4s8** [comment]
@amihaiemil you can use `@0crat status` to see footprint link

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/1101#issuecomment-414117484); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by rgevaerd** [comment]
@amihaiemil Thanks.

**Comment by amihaiemil** [comment]
@rgevaerd I would look into the stakeholders which do something about assignments. All those stakeholders are run independently, in arbitrary order and know nothing about eachother.

So, if the bug is still present it means there are probably 2 different stakeholders who are doing something about Issue assignment.

**Comment by rgevaerd** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1101#issuecomment-414516949))

@rgevaerd The user @rgevaerd[/z](https://www.0crat.com/u/rgevaerd) resigned from [#1101](https://github.com/zerocracy/farm/issues/1101), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @rgevaerd[/z](https://www.0crat.com/u/rgevaerd)

**Comment by 0crat** [comment]
The job [#1101](https://github.com/zerocracy/farm/issues/1101) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2662311724); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1101` already assigned to @carlosmiranda, can't assign to @carlosmiranda

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1101#issuecomment-425509358))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1101](https://github.com/zerocracy/farm/issues/1101), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by g4s8** [comment]
Should be fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1101` is not assigned, can't get performer
