### ISSUE TITLE
0crat should not add job to WBS and create order if issue is already closed

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1102]
If 0crat is down for whatever reason, and an Issue gets opened and closed in the meantime, then 0crat should not act upon it at all -- it should only try to do a payment to the Github assignee and complain to the ARC (so they can do it manually) if this is not possible.

Check out [this](https://github.com/amihaiemil/docker-java-api/issues/123) behaviour. Not only 0crat started working upon the Issue *after* it was closed, it also warned me that 5 days had passed and I had to reopen/close the issue in order to get get payment.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil it's a bug, I think 0crat should not add job to WBS and create order if issue was closed before.

**Comment by g4s8** [comment]
@amihaiemil could you please change title to make this bug more specific?

**Comment by amihaiemil** [comment]
@g4s8 I think it is already implemented, I saw the message "Order is not in WBS, won't start" in the past (or something similar)... maybe the mechanism is broken

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1102](https://github.com/zerocracy/farm/issues/1102) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2301114591); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@amihaiemil Merged, please close

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1102](https://github.com/zerocracy/farm/issues/1102) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#unknown]() is still not solved.
