### ISSUE TITLE
§1 is not hyperlinked in the warning message

### ISSUE THREAD

**Issue by scriptnull** [zerocracy/farm#1104]
When a user logs in for the first time without being invited, a warning is shown like this

![image](https://user-images.githubusercontent.com/4211715/41036860-14a5ef76-69af-11e8-8dd9-4543d3b75460.png)

It says "You (@scriptnull) must be invited to us by someone we already know, see §1" . Users who haven't visited http://www.zerocracy.com/policy.html page would be wondering what §1 is. 

So, I suggest we add a hyperlink that points to http://www.zerocracy.com/policy.html#1 in the warning message for the text  §1

https://github.com/zerocracy/farm/blob/fcf52e8f35b75dbe2152e16da281735f20e90e77/src/main/java/com/zerocracy/tk/RqUser.java#L112-L113

(not sure if actual html could be written inside it)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scriptnull[/z](https://www.0crat.com/u/scriptnull) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1104#issuecomment-395706468))

@g4s8 Job [#1104](https://github.com/zerocracy/farm/issues/1104) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @scriptnull[/z](https://www.0crat.com/u/scriptnull)

**Comment by 0crat** [comment]
The job [#1104](https://github.com/zerocracy/farm/issues/1104) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2310052783); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@scriptnull Please close this issue, fix has been merge to master in #1616

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1104](https://github.com/zerocracy/farm/issues/1104) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
