### ISSUE TITLE
Blanks is not used

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1113]
There is the ``Blanks`` metric which is incremented in the ``close_job.groovy``, but is otherwise not used anywhere else (I imagine there should be a voter that should use it in the election process). There is also no puzzle or open Issue for continuing implementation.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil right. @yegor256 how does `blanks.xml` supposed to be used? It was reported  in #536 without usage details.

**Comment by 0crat** [comment]
Job [#1113](https://github.com/zerocracy/farm/issues/1113) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.24`

**Comment by g4s8** [comment]
@rultor release, tag=0.45.24

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.24`

**Comment by g4s8** [comment]
@amihaiemil done, now `blanks.xml` will be counted in election process

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1113` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1113](https://github.com/zerocracy/farm/issues/1113) is now out of scope
