### ISSUE TITLE
Bug in Ledger.deficit()?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1116]
According to [this if()](https://github.com/zerocracy/farm/blob/master/src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy#L22) in ``resign_on_delay.groovy``, the delay rule should not apply for non-funded projects.

However, it happened several times in one of my non-funded projects, in the past 1-2 months. For instance: https://github.com/amihaiemil/docker-java-api/issues/77#issuecomment-383309803, https://github.com/amihaiemil/docker-java-api/issues/85#issuecomment-389106856 and https://github.com/amihaiemil/docker-java-api/issues/71#issuecomment-379806361

According to the ``if()`` linked above, ``Ledger.deficit()`` should return ``true`` in my project's case and it doesn't.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil right, looks like a bug in the logic in `resign_on_delay.groovy`, it should check for `ledger.cash() > 0` instead of `ledger.deficit()`, because deficit is set only when estimates are greater than cash:
```groovy
Cash locked = new Estimates(project).bootstrap().total()
...
  if (!ledger.deficit() && cash < locked) {
    ledger.deficit(true)
```
I suppose your project doesn't have this `locked` cash, so it's always no deficit.

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1116#issuecomment-395554291))

@g4s8 Job [#1116](https://github.com/zerocracy/farm/issues/1116) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1116](https://github.com/zerocracy/farm/issues/1116) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1861721749); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for #1364 to be done before proceeding here (blocks testing)

**Comment by 0crat** [comment]
> @0crat waiting for #1364 to be done before proceeding here (blocks testing) ([here](https://github.com/zerocracy/farm/issues/1116#issuecomment-405021532))

@krzyk The impediment for [#1116](https://github.com/zerocracy/farm/issues/1116) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@amihaiemil please close this issue, it has been merged in #1474

**Comment by amihaiemil** [comment]
@krzyk Right, thanks a lot! :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1116](https://github.com/zerocracy/farm/issues/1116) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat ping

**Comment by 0crat** [comment]
> @0crat ping ([here](https://github.com/zerocracy/farm/issues/1116#issuecomment-408335208))

@ypshenychka Can't understand "ping", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by ypshenychka** [comment]
@g4s8 no payment done here

**Comment by g4s8** [comment]
Missing payments due to "duplicate claim error":

|  job  | role | assignee | QA | quality | payment for job | payment for QA |
|--------|-------|--------------|------|-----------|------------------------|------------------------|
| #1116| `DEV` | @krzyk | @ypshenychka | good | `35min` | `8min`       |
| #1475| `REV` | @krzyk | @ypshenychka | good | `20min` | `8min`       |
| #1432| `DEV` | @krzyk | @ypshenychka | good | `35min` | `8min`       |
| #1381| `DEV` | @krzyk | @ypshenychka | good | `35min` | `8min`       |

@ypshenychka @krzyk please see this table, is it correct and full?

**Comment by ypshenychka** [comment]
@g4s8 Three tickets are missed in this table - #1467 , #1352 and https://github.com/Harvest-foundation/telegram/pull/129

**Comment by g4s8** [comment]
@ypshenychka thanks, updated table with #1467 and #1352,  Harvest-foundation/telegram#129 is not related to this project

**Comment by ypshenychka** [comment]
@g4s8 Thanks. Now all tickets with missed payment from farm are in table (at least from my side).

**Comment by g4s8** [comment]
@0crat pay 40min @ypshenychka

**Comment by krzyk** [comment]
@g4s8 looks correct

**Comment by g4s8** [comment]
@0crat pay 105min @krzyk

**Comment by 0crat** [comment]
Direct payment from @g4s8[/z](https://www.0crat.com/u/g4s8): +40 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Direct payment to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) in #1116, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Direct payment from @g4s8[/z](https://www.0crat.com/u/g4s8): +105 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Direct payment to @krzyk[/z](https://www.0crat.com/u/krzyk) in #1116, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
