### ISSUE TITLE
Let's send ZLD to all project sponsors

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1119]
Every time a project gets funds lets send ZLD to the person who paid us. To do that you just make an HTTPS PUT request to `https://wts.zold.io/send` with these query params:

  * `bnf`: GitHub name of the recepient
  * `wallet`: 16-chars wallet ID of the sender
  * `pass`: 8-chars secret pass code of the sender

Both `wallet` and `pass` will be available in `props.xml`. Let's not forget to notify the person, explaining to them that ZLD has been transferred to them through wts.zold.io

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1119#issuecomment-395874171))

@g4s8 Job [#1119](https://github.com/zerocracy/farm/issues/1119) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1119](https://github.com/zerocracy/farm/issues/1119) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1781432153); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 do we have some docs for this API? If no, how to specify amount of ZLD to send and what is format of username?

**Comment by yegor256** [comment]
@g4s8 check wts.zold.io. Click "API" in the top menu. You will understand how it works.

**Comment by yegor256** [comment]
@g4s8 I added `zold.secret` to the props for Rultor

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.9`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1325](https://github.com/zerocracy/farm/issues/1325) is still not solved.

**Comment by g4s8** [comment]
@yegor256 it should be implemented in #1289, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1119](https://github.com/zerocracy/farm/issues/1119) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1325](https://github.com/zerocracy/farm/issues/1325) is solved here.
