### ISSUE TITLE
TkTeam.java:46-48: Speed and Agenda is skipped now...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1123]
The puzzle `1121-f96bc81e` from #1121 has to be resolved:

https://github.com/zerocracy/farm/blob/58175f9beec5337ba267adee36d9b3b6f0c26ea2/src/main/java/com/zerocracy/tk/TkTeam.java#L46-L48

The puzzle was created by g4s8 on 08-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1123](https://github.com/zerocracy/farm/issues/1123) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1123#issuecomment-400707391))

@g4s8 The job [#1123](https://github.com/zerocracy/farm/issues/1123) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1781520949); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@0crat wait for #1121

**Comment by 0crat** [comment]
> @0crat wait for #1121 ([here](https://github.com/zerocracy/farm/issues/1123#issuecomment-400708033))

@carlosmiranda The impediment for [#1123](https://github.com/zerocracy/farm/issues/1123) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@0crat wait for #841 and #1267

**Comment by 0crat** [comment]
> @0crat wait for #841 and #1267 ([here](https://github.com/zerocracy/farm/issues/1123#issuecomment-400990354))

@carlosmiranda Job [#1123](https://github.com/zerocracy/farm/issues/1123) is already on hold

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1382

**Comment by 0pdd** [comment]
The puzzle `1121-f96bc81e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1123](https://github.com/zerocracy/farm/issues/1123) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
