### ISSUE TITLE
Too short javadocs in the project

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1126]
There is a general problem in the project: existing JavaDocs are too short to understand the goals of the classes/interfaces. The most common javadoc for Java class just repeats a name of the class. A few examples:
- https://github.com/zerocracy/farm/blob/c61072e3435b128d7bb1e2ece0d7a974c120e066/src/main/java/com/zerocracy/radars/github/Rebound.java#L28-L35
- https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/cash/ApiLayerQuotes.java#L30-L37

As well there are classes with good enough docs:
- https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/Farm.java#L22-L34
- https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/Par.java#L30-L39 (not perfect, but better than others)

As a consequent of the problem, me as a developer should spend more than 30 minutes to find the "start point" of features. e.g. "How does ping work in general? Where can I start to understand the feature?"

**How it should be:**
- JavaDocs must be well-writen so that even newbie can understand what the purpose of the class is and how it works in general.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1126#issuecomment-396050143))

@g4s8 The job [#1126](https://github.com/zerocracy/farm/issues/1126) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1611389346); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@proshin-roman added javadocs for some classes in #1128, can we close it?

**Comment by proshin-roman** [comment]
@g4s8 well, yeah, let's close it for now. And then a new bug can be submitted in future in case if the problem occurs again. As well I see there is another ticket https://github.com/zerocracy/farm/issues/1130 that says about needing architecture explanation - it will help too to understand the project.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1126](https://github.com/zerocracy/farm/issues/1126) is now out of scope
