### ISSUE TITLE
User can be assigned to issues only from one project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1127]
If project has many issues in WBS and user (who has role in this project and other projects) has small agenda (e.g. 2 of 8 jobs) e.g. if he/she just turns vacation mode off, most probably this user will be assigned to tasks only from one project.

I think it's a bug in `elect_performer`: when it receive a ping from a project it try to process as much jobs as possible, so it assign all jobs to user with empty agenda and election for next project can't assign any job to this user.

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1127#issuecomment-396060462))

@g4s8 Job [#1127](https://github.com/zerocracy/farm/issues/1127) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1127](https://github.com/zerocracy/farm/issues/1127) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2310106903); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1127#issuecomment-414151042))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1127](https://github.com/zerocracy/farm/issues/1127), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1127](https://github.com/zerocracy/farm/issues/1127) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2662318801); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1127#issuecomment-425648373))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1127](https://github.com/zerocracy/farm/issues/1127), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1127` is not assigned, can't get performer
