### ISSUE TITLE
VsReputation logic

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1129]
`VsReputation` gives highest vote for lowest reputation, e.g. in this election: https://www.0crat.com/footprint/C3NDPUA8L/1611606822:
```
  +3.33=0.67x5 Reputation +1470 jobs is no.2
  +1.67=0.33x5 Reputation +1884 jobs is no.3
  +5.00=1.00x5 Reputation +1233 jobs is no.1
```
It's not correct according to [policy](http://www.zerocracy.com/policy.html#3).

**Comment by amihaiemil** [comment]
@g4s8 I think so. This is also how you told me to do in ``VsNegligence``: the voter itself gives the highest points to the least desirable person but it is declared with a low (maybe even negative) weight. Thus, the highest rank actually works agains the user, since it has a negative weight.

**Comment by 0crat** [comment]
Job [#1129](https://github.com/zerocracy/farm/issues/1129) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1129#issuecomment-401743346))

@g4s8 The job [#1129](https://github.com/zerocracy/farm/issues/1129) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1830966840); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1319

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1319

**Comment by 0crat** [comment]
> @0crat wait for merge of #1319 ([here](https://github.com/zerocracy/farm/issues/1129#issuecomment-402032856))

@carlosmiranda The impediment for [#1129](https://github.com/zerocracy/farm/issues/1129) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 can we close this now? PR #1319 is merged.

**Comment by g4s8** [comment]
@carlosmiranda yes, thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.1`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1129](https://github.com/zerocracy/farm/issues/1129) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@g4s8 I've got only points for this review. No payment

**Comment by ypshenychka** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1129#issuecomment-402947209))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1129](https://github.com/zerocracy/farm/issues/1129) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231129%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
