### ISSUE TITLE
Add architecture.md file

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1130]
Seeing that [I am not the only one](https://github.com/zerocracy/farm/issues/1126) with trouble in understanding the architecture, I insist on having the overall design explained in a document, since studying the Javadocs takes a longer time and they may not always provide the big picture.

Regarding the architecture, so far, I understood the following:

* There are the groovy scripts which are handling the Issue concurrently or without a specific order, they simply rely on the data to make sense of the current state of the Issue (so it is a very procedural process).

* The data in the project is represented in XML files -- each of these files (such a file is called an Item) are animated by Java classes which are actually used in the groovy scripts.

But, for instance, I have no idea where S3 and MongoDB are involved and how/when exactly does the data go from S3/Mongo into XML files.

As discussed on many occasions, the biggest concern regarding such an architectural document is that it may change often and may need a lot of maintenance: to avoid this, the file should contain only the **main** ideas, pillars of the project, stuff that won't change since it would mean rewriting the whole project.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by proshin-roman** [comment]
@amihaiemil @g4s8 I just would add a note that there is a life cycle of jobs in the project. This "cycle" is represented by transforming claims related to a job. It would be nice to see some explanation of existing "flows" in the project. I've submitted https://github.com/zerocracy/farm/issues/1135 that might be related to that problem.

**Comment by amihaiemil** [comment]
@proshin-roman as I said in the description, as far as I understand (also seeing how 0crat behaves), there is no "flow".

There are just the groovy scripts which are doing their job independently, always relying on the data's state to tell them what to do; they do not have an order of execution. This is why, I think, we see 0crat commenting 10 times uselessly on an Issue -- it does not "keep track" of the changes, so to speak, it does not have a session. Know what I mean?

**Comment by proshin-roman** [comment]
@amihaiemil well, there is no explicit flow and all stakeholders work concurrently. But every claim has a type and every type is kind of bound to some state (of a job, or of a user). And then it looks like a flow: `issue created` - a new claim is created and some stakeholders will react on it, `issue is in the scope` - again a new claim and other stakeholders will react on it. Isn't it a flow?

**Comment by amihaiemil** [comment]
@proshin-roman yes, of course, there is a theoretical flow. I just meant to say that the order of the stakeholder's execution is not guaranteed and no session is kept for a Job (again, this is my understanding, I may be wrong)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1130#issuecomment-397742713))

@g4s8 The job [#1130](https://github.com/zerocracy/farm/issues/1130) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1662123660); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@amihaiemil  please look at  https://github.com/zerocracy/farm/blob/master/doc/arc.md I think it's enough for beginning, if something is not clear you can submit new tickets. Can we close this?

**Comment by amihaiemil** [comment]
@g4s8 looks nice, thanks!
