### ISSUE TITLE
Claim types set is not defined nor restricted

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1135]
- If I want to find a list of all existing claim types - it's not possible (the only way is to find usages of some methods which receive claim type as a parameter). 
- I can add any new claim type - and it's not guaranteed that it's processed by stakeholder. 
- claim type is just a string - there is no way to check claim types for typos.

All that might lead the project to the "message-driven hell", when it's not possible to track ways how some specific claim type is processed.

**How it could be done:**
Usually, a project has a set of all possible types of messages/claims. 
As well it can be done by static typing: interface `ClaimType` and specific implementation for every claim type.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@proshin-roman I also raised this Issue in February and the conclusion was to implement some kind of "flow control": https://github.com/zerocracy/farm/issues/665

**Comment by proshin-roman** [comment]
@amihaiemil thanks for the link - I will close my ticket then as it's just a duplicate of #665

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1135` is not assigned, can't get performer
