### ISSUE TITLE
update_precedences.groovy:27-30: let's implement this...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1143]
The puzzle `185-4c683176` from #185 has to be resolved:

https://github.com/zerocracy/farm/blob/e213f51c372d74289fcdb25467f9c73749c7de6b/src/main/groovy/com/zerocracy/stk/pm/staff/milestones/update_precedences.groovy#L27-L30

The puzzle was created by amihaiemil on 07-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1143](https://github.com/zerocracy/farm/issues/1143) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1143](https://github.com/zerocracy/farm/issues/1143) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1640907162); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `185-4c683176` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1143](https://github.com/zerocracy/farm/issues/1143) is now out of scope

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
