### ISSUE TITLE
_after.groovy:32-36: MkGithub can't create private...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1145]
The puzzle `989-2e7ad176` from #989 has to be resolved:

https://github.com/zerocracy/farm/blob/4ce4467793e6a31728a0bd22a9ce48fa702d6ee9/src/test/resources/com/zerocracy/bundles/assign_role/_after.groovy#L32-L36

The puzzle was created by g4s8 on 08-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1145](https://github.com/zerocracy/farm/issues/1145) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1145](https://github.com/zerocracy/farm/issues/1145) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1641207705); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/jcabi/jcabi-github/issues/1421

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/jcabi/jcabi-github/issues/1421  ([here](https://github.com/zerocracy/farm/issues/1145#issuecomment-397206683))

@amihaiemil The impediment for [#1145](https://github.com/zerocracy/farm/issues/1145) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1145#issuecomment-472957083))

@g4s8 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#1145](https://github.com/zerocracy/farm/issues/1145), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1145](https://github.com/zerocracy/farm/issues/1145) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1d4a5f75-a515-40b4-b7b8-4184f2b7fef1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1145#issuecomment-541472531))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1145](https://github.com/zerocracy/farm/issues/1145), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 63 hours), see [§6](http://www.zerocracy.com/policy.html#6): -10 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#1145](https://github.com/zerocracy/farm/issues/1145) assigned to @loro2[/z](https://www.0crat.com/u/loro2), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/52f5774e-529d-43c0-8693-d372cc770788); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by loro2** [comment]
Created PR #2187 for this issue

**Comment by loro2** [comment]
@0crat wait #2200

**Comment by 0crat** [comment]
> @0crat wait #2200 ([here](https://github.com/zerocracy/farm/issues/1145#issuecomment-552794353))

@loro2 The impediment for [#1145](https://github.com/zerocracy/farm/issues/1145) was registered successfully by @loro2[/z](https://www.0crat.com/u/loro2)

**Comment by 0pdd** [comment]
The puzzle `989-2e7ad176` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1145](https://github.com/zerocracy/farm/issues/1145) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @loro2[/z](https://www.0crat.com/u/loro2), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@loro2 please make sure you start all your comments with the name of the user they are referred to, [see](https://github.com/zerocracy/farm/issues/1145#issuecomment-545828735)

**Comment by loro2** [comment]
@sereshqua confirmed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @loro2[/z](https://www.0crat.com/u/loro2)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
