### ISSUE TITLE
Resumes.java:32-37: Let's create new stakeholder to...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1146]
The puzzle `908-27b4bc69` from #908 has to be resolved:

https://github.com/zerocracy/farm/blob/37d048c4c51082ec0ab258c491e5665ee7ea8036/src/main/java/com/zerocracy/pmo/Resumes.java#L32-L37

The puzzle was created by g4s8 on 07-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1146](https://github.com/zerocracy/farm/issues/1146) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1146](https://github.com/zerocracy/farm/issues/1146) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1641307214); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `908-27b4bc69` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353) are still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1146](https://github.com/zerocracy/farm/issues/1146) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486) are still not solved; solved: [#1352](https://github.com/zerocracy/farm/issues/1352).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1353](https://github.com/zerocracy/farm/issues/1353), [#1552](https://github.com/zerocracy/farm/issues/1552) are still not solved; solved: [#1352](https://github.com/zerocracy/farm/issues/1352), [#1486](https://github.com/zerocracy/farm/issues/1486).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1552](https://github.com/zerocracy/farm/issues/1552) is still not solved; solved: [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1649](https://github.com/zerocracy/farm/issues/1649) is still not solved; solved: [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1552](https://github.com/zerocracy/farm/issues/1552).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1666](https://github.com/zerocracy/farm/issues/1666) is still not solved; solved: [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1649](https://github.com/zerocracy/farm/issues/1649).

**Comment by 0pdd** [comment]
@0pdd all 6 puzzles are solved here: [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666).
