### ISSUE TITLE
GitHub remove link is not working

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#1155]
### Background
I did a rebranding of my project [oo-atom](https://github.com/pragmatic-objects/oo-atom). The name of organization was changed, and I wanted to update the github link in 0crat by removing it and creating anew.

### Steps to reproduce:
0. You have a project on 0crat with links on github set-up.
1. Remove a github link by the Slack command `@0crat links remove <rel> <href>`

### Actual result
```
@0crat links remove github github:project-avral/oo-atom
```
```
@skapralov There is an unrecoverable failure on my side. Please, submit it here:

PID: 4@71cf45a5-b3f8-4d19-a7cb-8cae10af5ad7, thread: AsyncFlush-2
org.xembly.Xembler[131] java.lang.IllegalArgumentException: failed to apply to DOM quietly: XPATH "/catalog/project[@id=  &apos;C8Q9GUCCD&apos;]";STRICT "1";XPATH "links/link[@rel=&apos;github&apos; and @href=&apos;github:project-avral/oo-atom&apos;]";
3:STRICT "1";REMOVE;
org.xembly.Xembler[157] org.xembly.ImpossibleModificationException: directive #4: STRICT "1"
org.xembly.StrictDirective[71] org.xembly.ImpossibleModificationException: no current nodes while 1 expected
```

### Expected result
The link was removed, or a proper error message is placed in response.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@skapral please, try this: `@0crat links remove github project-avral/oo-atom` (not `github:project-avral/oo-atom`)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1155` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
