### ISSUE TITLE
Lost 500+ reputation in one day

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1157]
According to the Policy, only the reputation from the last 90 days is counted.

To my understanding this means that, after the first 90 days pass, one should start losing reputation **gradually**, as each day goes by and the frame of 90 days moves forward.

Or is there a different calculation mechanism? Becuse by that logic, I should lose max 30-60 points at a time; I have never earned 500 points in one day.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1157#issuecomment-397878049))

@g4s8 The job [#1157](https://github.com/zerocracy/farm/issues/1157) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1681312987); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@amihaiemil as I can see in footprint you've earned 435 reputation points more than 3 months ago only in Zerocracy project. Looks like your reputation was not refreshed for some period for unkown reason. I added new claim in d1e6f1d to track how much reputation was removed from awards in `refresh_awards` stakeholder.

**Comment by amihaiemil** [comment]
@g4s8 I see; no PR, you commited on master directly? :D 

Should I close this?

**Comment by g4s8** [comment]
@amihaiemil 
> you commited on master directly? :D

it's much faster and no need to fix review comments ;)

> Should I close this?

If you think that my changes will help to understand such cases in future better

**Comment by amihaiemil** [comment]
@g4s8 Well, I assume it's ok, but I can't be sure. I will close this and someone will report bugs if they find any.

I don't think it's ok to work on Master for 2 reasons:

1) The project's quality

2) We are not supposed to, according to the ZC model. If we cannot follow the model, it means it's broken, we need to file issues. If you think that the model is too slow, and you find working on Master as a good work-around, then it means the model is broken. As I said on Telegram today, it's still an experiment and we need to improve it: otherwise, it makes no sense :)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1157](https://github.com/zerocracy/farm/issues/1157) is now out of scope
