### ISSUE TITLE
_after.groovy:26-28: Fix the problem when PR job is...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1163]
The puzzle `1015-7cbe8f93` from #1015 has to be resolved:

https://github.com/zerocracy/farm/blob/7dcb0b45776c9c0f41825292f714dd23fd901b98/src/test/resources/com/zerocracy/bundles/assigns_performer_pr/_after.groovy#L26-L28

The puzzle was created by rultor on 17-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1163](https://github.com/zerocracy/farm/issues/1163) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1163](https://github.com/zerocracy/farm/issues/1163) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1841314378); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of #1387

**Comment by 0crat** [comment]
> @0crat waiting for review of #1387  ([here](https://github.com/zerocracy/farm/issues/1163#issuecomment-403495440))

@krzyk The impediment for [#1163](https://github.com/zerocracy/farm/issues/1163) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `1015-7cbe8f93` has disappeared from the source code, that's why I closed this issue.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
