### ISSUE TITLE
update_precedence stakeholder uses incorrect claim

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1170]
`update_precedence` stakeholder should be triggered when GitHub ticket gets assigned to a milestone, but it uses incorrect claim for it: `Add milestone`. We have to implement another reaction in `TkGithub` to handle `milestoned` [event action](https://developer.github.com/v3/activity/events/types/#issuesevent), e.g. like this:
```json
{
  "action": "milestoned",
  "issue": {
  }
}
```
and submit new claim with type: `Job milestoned` with params `milestone` and `job`.

**Comment by 0crat** [comment]
Job [#1170](https://github.com/zerocracy/farm/issues/1170) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1170](https://github.com/zerocracy/farm/issues/1170) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1852009505); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #1415

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1415  ([here](https://github.com/zerocracy/farm/issues/1170#issuecomment-404513175))

@krzyk The impediment for [#1170](https://github.com/zerocracy/farm/issues/1170) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@g4s8 changes have been merged in #1415, please close this issue

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1170](https://github.com/zerocracy/farm/issues/1170) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
