### ISSUE TITLE
Automatic vacation is broken

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1173]
According to [point 52](http://www.zerocracy.com/policy.html#52), automatic vacation happens if, in the last 16 days, the user has more than 8 consecutive negative awars. 

However, I see I was put on vacation automatically, yet I never had 8 consecutive negative awards (I did a few in the past 2 weeks, but I also got awards in between them)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil yes, same for me, it turns my vacation mode on

**Comment by 0crat** [comment]
Job [#1173](https://github.com/zerocracy/farm/issues/1173) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by krzyk** [comment]
@g4s8 I can take this, as I broke it :-)

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk ([here](https://github.com/zerocracy/farm/issues/1173#issuecomment-398307777))

@g4s8 The job [#1173](https://github.com/zerocracy/farm/issues/1173) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1700784696); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@amihaiemil fix has been merged to master in #1181, please close this issue

**Comment by amihaiemil** [comment]
@krzyk thanks :)

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.8`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2a5ea468-7e77-489c-80d0-c8be03a5d7e1, thread: AsyncFlush-4
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/krzyk.xml" in "PMO" in 1min: 61df0a5983f1/2min/0/3/true/false by QuartzScheduler_Worker-1
```

[0.22.7](https://github.com/zerocracy/farm): CID: [1711104726](https://www.0crat.com/C3NDPUA8L/1711104726), Type: "Close job", Author: "amihaiemil"

**Comment by krzyk** [comment]
@0crat ping

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: pool-30-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/25min/0/2/true/false by AsyncFlush-3
```

[0.22.8](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1173, Comment: 398726859

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: pool-30-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/25min/0/2/true/false by AsyncFlush-3
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/25min/0/2/true/false by AsyncFlush-3
```

[0.22.8](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1173, Action: `created`

**Comment by krzyk** [comment]
@0crat ping

**Comment by 0crat** [comment]
> @0crat ping ([here](https://github.com/zerocracy/farm/issues/1173#issuecomment-399327435))

@krzyk Can't understand "ping", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1173#issuecomment-399327525))

@krzyk This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1173](https://github.com/zerocracy/farm/issues/1173) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2days
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231173%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@ypshenychka looks like 0crat didn't send out, but he waits for your quality review here

**Comment by ypshenychka** [comment]
@krzyk Thank you for a notice! Looking into it.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1173#issuecomment-399453736))

@krzyk This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1173](https://github.com/zerocracy/farm/issues/1173) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231173%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@g4s8 This issue still exists in my agenda, although it was finished. Probably because of the earlier errors from 0crat.

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1173#issuecomment-399476293))

@g4s8 The job [#1173](https://github.com/zerocracy/farm/issues/1173) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
