### ISSUE TITLE
0crat made a wrong payment

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1175]
I've received a wrong payments last week:

For (https://github.com/yegor256/jpeek/issues/156), quality good, received 35 points but 5 extra minutes weren't added to cash payment.

I've received the following bot message:

>We are very sorry, but we failed to pay you $7.36 for #156 (https://github.com/yegor256/jpeek/issues/156): "The amount $7.36 is too small at: Payment for #156 (https://github.com/yegor256/jpeek/issues/156) (35 minutes): Order was finished, quality is "good""; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)the tuition fee $0.64 was deducted and sent to @g4s8/z (https://www.0crat.com/u/g4s8) (your mentor), according to §45 (http://www.zerocracy.com/policy.html#45)

I should have received $8.58:
- rate is $16
- quality is good (35 mins)
- tuition fee is deducted (0.08 per dollar)
`((16 * 35) / 60 ) * 0.92 = 8.58`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso you're right, [your claim](https://www.0crat.com/footprint/C7JGJ00DP/1651135973):
```
1651135973 4days "Make payment" (0.22.3)
  reason: Order was finished, quality is "good"
  issue: 156
  minutes: 35
  repo: yegor256/jpeek
  login: paulodamaso
  token: github;yegor256/jpeek;156;397262116
  quality: good
  comment: 397262116
  job: gh:yegor256/jpeek#156
  cash: $8.00
  flow: Complete QA review
```

**Comment by 0crat** [comment]
The job [#1175](https://github.com/zerocracy/farm/issues/1175) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1692117491); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1175` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@paulodamaso it happened because:
 1. you was assigned to a job
 2. you was kicked out from sanbox project because of your reputation
 3. your roles and rate was removed in this project
 4. your 'good quality bonus' was calculated as `$0`:
   ```groovy
    Cash bonus = Cash.ZERO
    if (rates.exists(performer)) {
      bonus = rates.rate(performer).mul(new Policy().get('31.bonus', 5)) / 60
    }
   ```


I think we have two solutions here:
 1. use `8%` instead of `5 minutes` bonus and calculate it from job estimate (not from user's rate)
 2. do not remove user's rate on `Resign all roles` and create a script which will check `roles.xml` once a day and remove rate for user which doesn't have any role in project and doesn't have any job assigned (in `orders.xml`)

@yegor256 which one is better?

**Comment by yegor256** [comment]
@g4s8 I like the first option

**Comment by g4s8** [comment]
@paulodamaso should be fixed now, you will receive 8% of job cost instead of 5 minutes.

**Comment by krzyk** [comment]
@g4s8 Hmm, I just got a +38 mins from a task #1064, I think this wasn't intended

**Comment by g4s8** [comment]
@krzyk as I can see in `reviews.xml` bonus cash is calculating correctly, right? Did you receive 30min payment + 8%?

**Comment by krzyk** [comment]
@g4s8 Everything was calculate just like for 38mins, but should be 30mins + 8% * 60 (rounded up), right?.
It started happening yesterday, because policy was published, so it made sense (fixed bonus of +5 was replaced with +8). But after this release it should be 35 mins (and 35 points).

**Comment by g4s8** [comment]
@krzyk I mean that your cash bonus should be calculated correctly (I can see it in `reviews.xml`), right? So only points bonus is wrong: should be 5 minutes instead of 8. Looks like we have 2 different places for cash bonus and minutes bonus. I think you can submit a ticket.

**Comment by krzyk** [comment]
@g4s8 I double check, yes you are right it is 38 points, and the cash value is +8% of the cash (not of the hourly rate), so for $16 rate, it is $8.64.

Shouldn't it be 8% of hourly rate (~ 5mins of an hour is 8%)?

Previous reward for "good" quality was 35mins for DEV and 20mins for REV (a consistent +5mins)
Now it is ~ 32.4 mins for DEV and ~16.2 mins for REV (so +2.4 mins or + 1.2 mins).
Was it intentionally lowered from previous bonus of 16% for DEV and 32% for REV?

**Comment by g4s8** [comment]
@krzyk we decided to turn bonus from fixed value for any job to percent of estimated price of a job (see https://github.com/zerocracy/farm/issues/1175#issuecomment-399737878). But it seems you're right about value, if we change it to 16% of job estimate we will have 2.4 minutes for `REV` job and 4.8 for `DEV`.

**Comment by krzyk** [comment]
@g4s8 It is harder to get `good` in REV than in DEV task, so maybe the bonus should take that into account?

**Comment by g4s8** [comment]
@krzyk maybe, please submit a ticket about it in https://github.com/zerocracy/zerocracy.github.io

**Comment by paulodamaso** [comment]
@g4s8 So the bonus is incorrect yet?

**Comment by krzyk** [comment]
@paulodamaso it has to be implemented in https://github.com/zerocracy/farm/issues/1287 (no assignee yet)

**Comment by paulodamaso** [comment]
@g4s8 And for `DEV`? It's 16% or 8% ?

**Comment by krzyk** [comment]
@paulodamaso Sorry for jumping in, but for now I see it is 8%. You can try creating bug similar to https://github.com/zerocracy/zerocracy.github.io/issues/25 for DEV.

**Comment by paulodamaso** [comment]
@krzyk Thanks for the tipo, look at https://github.com/zerocracy/zerocracy.github.io/issues/32 .

**Comment by g4s8** [comment]
@paulodamaso it was fixed in #1264

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1175](https://github.com/zerocracy/farm/issues/1175) is now out of scope
