### ISSUE TITLE
Tuition fee still being deducted after graduation

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1176]
`0crat` deducted tuition fee even after graduation from `REV` task (https://github.com/Harvest-foundation/telegram/pull/71).

- graduation date: 12/06/2018
- task assignment date: 14/06/2018
- task finished: 18/06/2018

`0crat` sent me the following message:

> We are very sorry, but we failed to pay you $4.60 for #71 (https://github.com/harvest-foundation/telegram/issues/71): "The amount $4.60 is too small at: Payment for #71 (https://github.com/harvest-foundation/telegram/issues/71) (15 minutes): Order was finished"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)the tuition fee $0.40 was deducted and sent to @g4s8/z (https://www.0crat.com/u/g4s8) (your mentor), according to §45 (http://www.zerocracy.com/policy.html#45)

**Comment by g4s8** [comment]
@paulodamaso according to [policy §43](http://www.zerocracy.com/policy.html#43) you will be graduated when you earn 2048 reputation points.

**Comment by paulodamaso** [comment]
@g4s8 Right, sorry, somehow I thought that was 1024.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1176` is not assigned, can't get performer
