### ISSUE TITLE
Ledger is not visible for non PO/ARC

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1177]
https://www.0crat.com/a/CAZPZR9FS?a=pm/cost/ledger

The project is published on the board. Its ledger must be visible for all registered users.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 we have another link for public ledger: https://www.0crat.com/contrib-ledger/CAZPZR9FS does it work?

**Comment by yegor256** [comment]
@g4s8 yes, definitely, totally forgot it. thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1177` is not assigned, can't get performer
