### ISSUE TITLE
0crat assigned closed tasks from paused project to an ARC on vacation

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#1182]
o_O

I have a 0crat account (skapral), which is currently on vacation mode. I also have paused project OO-atom on-board - I paused it intentionally to clean up a mess there after recent rebranding. During cleaning a mess, I closed some redundant issues. Today, I received from 0crat a serie of issue assignments on me. Closed issues. On me in vacation mode. From paused project.

My profile page currently speaks that:

> Your currently open jobs: 7 (max allowed: 3). 

I am not sure I can tell more than this. I have no idea why it is going that weird.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by skapral** [comment]
@g4s8, JFYI I decided to destroy the project. After destroying it, all incorrectly assigned tasks were gone.

**Comment by g4s8** [comment]
@skapral I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1182` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
