### ISSUE TITLE
Options.java:37-39: Options should be changeable by the...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1186]
The puzzle `1035-a9c9989f` from #1035 has to be resolved:

https://github.com/zerocracy/farm/blob/de7c160ab1980324320b30300911f80e665496b7/src/main/java/com/zerocracy/pmo/Options.java#L37-L39

The puzzle was created by Krzysztof Krason on 15-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1186](https://github.com/zerocracy/farm/issues/1186) is now in scope, role is `DEV`

**Comment by krzyk** [comment]
@g4s8 I think it would be better for users to be able to change the options using `0crat` in telegram not by uploading files. Was the file upload chosen as the easier option?

**Comment by g4s8** [comment]
@krzyk I suppose we choose file upload because of easier implementation comparing to chat bot commands, because we need to add many new commands for each option

**Comment by g4s8** [comment]
@krzyk you're right, it would be much easier. Didn't think about it. Let's do as you suggested.

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk ([here](https://github.com/zerocracy/farm/issues/1186#issuecomment-405873657))

@g4s8 The job [#1186](https://github.com/zerocracy/farm/issues/1186) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1990951443); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1472](https://github.com/zerocracy/farm/issues/1472) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `1035-a9c9989f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1186](https://github.com/zerocracy/farm/issues/1186) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
