### ISSUE TITLE
_after.groovy:23-25: Options are not used. Election...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1187]
The puzzle `1035-3b7a2d5a` from #1035 has to be resolved:

https://github.com/zerocracy/farm/blob/de7c160ab1980324320b30300911f80e665496b7/src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/_after.groovy#L23-L25

The puzzle was created by Krzysztof Krason on 15-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1187](https://github.com/zerocracy/farm/issues/1187) is now in scope, role is `DEV`

**Comment by krzyk** [comment]
@g4s8 I'm interested in this one (I get swamped with issues) and generally options feature in regard to changing the maxJobsInAgenda (so also https://github.com/zerocracy/farm/issues/1186)

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk ([here](https://github.com/zerocracy/farm/issues/1187#issuecomment-405873739))

@g4s8 The job [#1187](https://github.com/zerocracy/farm/issues/1187) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1990951444); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1035-3b7a2d5a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1187](https://github.com/zerocracy/farm/issues/1187) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
