### ISSUE TITLE
Debts table instead of text

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1193]
Currently the debts are simply listed in text one after another. I gathered a debt of $64 and I already have a prose text of ~30 lines -- very hard to read/understand and a complete mess on mobile view. 

We discussed this already [here](https://github.com/zerocracy/farm/issues/660) and the "solution" was to lower the payout rate to $20, so there could not be so much text in the debts area. However, now the payout is $64.

I think there should be a simple table with 4 columns: ``Date | Project | Amount | Link``. Amount would contain both the amount in cash and the minutes (e.g. ``$15/30min``) and Link would point to the Issue/PR for which the payment was made.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil I agree that it's hard to read profile page, esepcially when you have a lot of small payments like "tution fee for ..." which are usually less than $1. Now I need to scroll debts section about for 2.5 screen heights (25 payments - 45 lines of text) to find project links. But I think table will not solve this issue, because it will be as big as text now, if it inlude the same data. 
I think main problem here is that each debt can take more than 1 (or even 2) line, and it's not formatted at all.
Maybe it would be better to show only short debt info: time, about and job (e.g. `20 Jun $10 zerocracy/farm#1`) and show the reason as a hint on mouse hover? Also we can render debts as a list (one line for one debt) to easier understand it.
@yegor256 what do you think?

**Comment by amihaiemil** [comment]
@g4s8 Yes, I think it makes sense. As short and concise as possible + hover details.

**Comment by yegor256** [comment]
@g4s8 totally agree

**Comment by 0crat** [comment]
Job [#1193](https://github.com/zerocracy/farm/issues/1193) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1193#issuecomment-404912862))

@g4s8 The job [#1193](https://github.com/zerocracy/farm/issues/1193) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1941822667); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@amihaiemil I don't think I see usefulness of amount of minutes.
Would it be really minutes or points? Because those are currently different. And points are awared right away so they are not a debt.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #1452

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1452  ([here](https://github.com/zerocracy/farm/issues/1193#issuecomment-406551806))

@krzyk The impediment for [#1193](https://github.com/zerocracy/farm/issues/1193) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by amihaiemil** [comment]
@krzyk Right, reputation is awarded right away so it doesn't make much sense to specify it as a debt. We can go without that, then :)

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#1458](https://github.com/zerocracy/farm/issues/1458) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1193](https://github.com/zerocracy/farm/issues/1193) is now out of scope

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#1458](https://github.com/zerocracy/farm/issues/1458) is solved here.
