### ISSUE TITLE
TkBadge.java:34-36: TkBadge is temporary disabled because...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1196]
The puzzle `1168-91afb756` from #1168 has to be resolved:

https://github.com/zerocracy/farm/blob/bb38cc5e6e995b03a4acf130e44d496c29836f0f/src/main/java/com/zerocracy/tk/project/TkBadge.java#L34-L36

The puzzle was created by g4s8 on 20-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1196](https://github.com/zerocracy/farm/issues/1196) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1168-91afb756` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bb01a885-3862-4766-aef6-6e2490a37fa7, thread: pool-48-thread-1
com.zerocracy.farm.sync.SyncProject[78] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3NDPUA8L" in 1min: d9f5e85263a4/47min/0/0/false/false by BkParallel-4
```

[0.22.18](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1196, Action: `closed`

**Comment by 0crat** [comment]
The job [#1196](https://github.com/zerocracy/farm/issues/1196) is now out of scope
