### ISSUE TITLE
Pings fixing

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1200]
Pings are disabled now because application can't handle too much pings at the same time (about 75 pings every minute). We need to invent some solution to reduce the load on SyncFarm and keep Pings running.

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ebe86a51-560f-412e-b35a-3fd37757c01f, thread: pool-120-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/6min/0/3/true/false by zerocrat_bot Telegram Executor
```

[0.22.24](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1200, Comment: 399055974

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ebe86a51-560f-412e-b35a-3fd37757c01f, thread: pool-120-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/6min/0/3/true/false by zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/6min/0/3/true/false by zerocrat_bot Telegram Executor
```

[0.22.24](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1200, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ebe86a51-560f-412e-b35a-3fd37757c01f, thread: pool-130-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/8min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.24](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1200, Comment: 399056044

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ebe86a51-560f-412e-b35a-3fd37757c01f, thread: pool-130-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/8min/0/0/false/false by zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e955b9d45dd9/8min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.24](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1200, Action: `created`

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1200#issuecomment-399073569))

@g4s8 The job [#1200](https://github.com/zerocracy/farm/issues/1200) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1721138007); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/1200#issuecomment-399073700))

@g4s8 Boost 4x was set for [#1200](https://github.com/zerocracy/farm/issues/1200)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1200#issuecomment-399098755))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1200](https://github.com/zerocracy/farm/issues/1200) is [in scope](http://www.zerocracy.com/policy.html#14) for 2hr
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [2hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 100% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 60 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231200%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@g4s8 FYI I'm adding read locks besides the current write locks, hopefully this will fix the problem (or reduce it considerably).

**Comment by g4s8** [comment]
@krzyk maybe we can "spread" project pings in timeline somehow, I mean do not ping all projects every minute, but ping one batch (e.g. 5) of projects at same time, then ping next batch, then next, etc. What do you think?

**Comment by krzyk** [comment]
@g4s8 Yes, I was thinking about it also, until the 0crat failed after 90 mins. That's why went the ReadWriteLock route.

**Comment by g4s8** [comment]
@krzyk ok then, let's do as you suggested

**Comment by krzyk** [comment]
@g4s8 OK, so unfortunatelly my ReadWriteLock try didn't work, we have places where a read lock would need to be upgraded to write lock, which is not possible with ReentrantReadWriteLock (basically hangs forever).
So I have to throw that code away :(

I'll try with spreading the pings evenly, but I won't be able to do it today.
Did the 5 minute ping help much?

**Comment by g4s8** [comment]
@krzyk maybe I found main issue: when 0crat was down for few hours because of `OutOfMemoryError` because of leakage in `AsyncFlush` there were submitted a lot of claims in `PMO` (about 20MB of claims), then after restart ping tried to read claims and modify it but failed with new `OutOfMemoryError` in `Arrays.copy` in `Xocument.Modify` which causes `RejectedExecutionException` in `ExeutorService` in `Terminator.killer` this is why lock in `SyncFarm` was not unlocked and all requests failed with `IllegalStateException`.

Now I copied `claims.xml` from S3 and removed it on bucket, so looks like all claims are working now.

**Comment by krzyk** [comment]
@g4s8 Interesting, nice detective work :).
So is there a point in spreading out the pings now? From what you write this should be out of scope.

**Comment by g4s8** [comment]
@krzyk it's not critical now, however I think we should try to spread the load on the `SyncFarm`, `Flush` implementations and other claim related objects.

**Comment by krzyk** [comment]
@g4s8 OK

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1200](https://github.com/zerocracy/farm/issues/1200) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +65 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.2`

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1240](https://github.com/zerocracy/farm/issues/1240) is solved here.
