### ISSUE TITLE
AsyncFlush.java:43-46: Fix memory leak in async-flush....

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1202]
The puzzle `725-3ad115cb` from #725 has to be resolved:

https://github.com/zerocracy/farm/blob/079c843765bb768659db9391ec86173204cb033f/src/main/java/com/zerocracy/farm/reactive/AsyncFlush.java#L43-L46

The puzzle was created by g4s8 on 21-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1202](https://github.com/zerocracy/farm/issues/1202) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@carlosmiranda can you try to fix this one?  This bug is one of blockers now

**Comment by g4s8** [comment]
@0crat assigm me

**Comment by 0crat** [comment]
> @0crat assigm me ([here](https://github.com/zerocracy/farm/issues/1202#issuecomment-399096768))

@g4s8 Can't understand "assigm", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1202#issuecomment-399098582))

@g4s8 The job [#1202](https://github.com/zerocracy/farm/issues/1202) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1721313026); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `725-3ad115cb` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.26`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.27`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.28`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1202](https://github.com/zerocracy/farm/issues/1202) is now out of scope
