### ISSUE TITLE
Terminator.java:46-48: Fix memory leak in Terminator. It...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1203]
The puzzle `725-e530d946` from #725 has to be resolved:

https://github.com/zerocracy/farm/blob/079c843765bb768659db9391ec86173204cb033f/src/main/java/com/zerocracy/farm/sync/Terminator.java#L46-L48

The puzzle was created by g4s8 on 21-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: pool-140-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/13min/0/1/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1203, Comment: 399086919

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1203](https://github.com/zerocracy/farm/issues/1203) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: pool-180-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/35min/0/1/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1203, Comment: 399092801

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: pool-180-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/35min/0/1/true/false by zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/35min/0/1/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1203, Action: `created`

**Comment by 0pdd** [comment]
The puzzle `725-e530d946` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.26`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: AsyncFlush-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "agenda/g4s8.xml" in "PMO" in 2min: 6cc77ffce735/40min/0/1/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): CID: [1721257222](https://www.0crat.com/C3NDPUA8L/1721257222), Type: "Start order", Author: "g4s8"

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1203` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1203](https://github.com/zerocracy/farm/issues/1203) is now out of scope
