### ISSUE TITLE
Error while trying to go on vacation

### ISSUE THREAD

**Issue by StuporHero** [zerocracy/farm#1207]
Here is [a Gist](https://gist.github.com/StuporHero/657985c99b01cb99db704bccdc7d79a9) of the error message I received when I said `@0crat vacation` from my Slack chat.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@stuporhero[/z](https://www.0crat.com/u/stuporhero) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by StuporHero** [comment]
@g4s8 It works now, so I guess it was just a transient bug.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1207` is not assigned, can't get performer

**Comment by g4s8** [comment]
@StuporHero this bug was fixed with #1208
