### ISSUE TITLE
/vacation should show my status, when no flag given

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1210]
When I say `/vacation` I would expect to see my status. Instead, it's an error. Would be better if the bot replies: "You are NOT on vacation now. To change the status use `on` or `off` as an option."

<img width="559" alt="screen shot 2018-06-22 at 9 57 42 am" src="https://user-images.githubusercontent.com/526301/41762264-e21dd932-7602-11e8-8a24-a2a366a62eb9.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1210](https://github.com/zerocracy/farm/issues/1210) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1210](https://github.com/zerocracy/farm/issues/1210) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2041942286); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256 this issue was resolved in #1476 PR, please close.

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 Please close the issue, it's already been merged in #1476.

**Comment by g4s8** [comment]
@yegor256 @paulodamaso just tried `vacation` command and it's working

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1210](https://github.com/zerocracy/farm/issues/1210) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
