### ISSUE TITLE
Add uptime to the bottom of zerocracy webpage

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1212]
There are few metrics at the bottom of every page on zerocracy (like load average, memory usage, time taken to generate the page).

It would be useful to have an uptime there also, that would display the time in "humanized" way (automatically switch between seconds, minutes, hours, up to days I think).

And when hovering over it should say something like `Server started at 2018-06-22T09:34:00.000Z`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk we already have it, but only on main page: https://www.0crat.com/

**Comment by krzyk** [comment]
@g4s8 OK, I didn't notice it. So it looks like the 0crat is stable now.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1212` is not assigned, can't get performer
