### ISSUE TITLE
0crat can assign closed bug

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1214]
0crat can assign a bug that was already closed, see https://github.com/zerocracy/farm/issues/725#issuecomment-399333066

**Comment by 0crat** [comment]
Job [#1214](https://github.com/zerocracy/farm/issues/1214) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by amihaiemil** [comment]
@g4s8 It also happened in one of my projects

**Comment by 0crat** [comment]
The job [#1214](https://github.com/zerocracy/farm/issues/1214) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2050642193); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@amihaiemil Would you kindly point me to another github issue where this happened?

**Comment by g4s8** [comment]
@paulodamaso please see 
[assign-closed.txt](https://github.com/zerocracy/farm/files/2233558/assign-closed.txt)

**Comment by paulodamaso** [comment]
@g4s8 What I've found so far is that `0pdd` closed the github issue but `0crat` had a failure in removing it from WBS, so `0crat` assigned it again to someone. Proposed a solution in #1488.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1492](https://github.com/zerocracy/farm/issues/1492) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1214](https://github.com/zerocracy/farm/issues/1214) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
