### ISSUE TITLE
Claims.java:48-50: During #1208 fixing PMO claims was...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1215]
The puzzle `1208-ab499773` from #1208 has to be resolved:

https://github.com/zerocracy/farm/blob/0b58154a2c36100a798a16d5036165941c744090/src/main/java/com/zerocracy/pm/Claims.java#L48-L50

The puzzle was created by g4s8 on 22-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1215](https://github.com/zerocracy/farm/issues/1215) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1215](https://github.com/zerocracy/farm/issues/1215) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1730830487); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1215` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1208-ab499773` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1245](https://github.com/zerocracy/farm/issues/1245), [#1246](https://github.com/zerocracy/farm/issues/1246) are still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1215](https://github.com/zerocracy/farm/issues/1215) is now out of scope

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1246](https://github.com/zerocracy/farm/issues/1246) is still not solved; solved: [#1245](https://github.com/zerocracy/farm/issues/1245).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1245](https://github.com/zerocracy/farm/issues/1245), [#1246](https://github.com/zerocracy/farm/issues/1246).
