### ISSUE TITLE
No penalty on refuse

### ISSUE THREAD

**Issue by olenagerasimova** [zerocracy/farm#1217]
I refused to complete a job by saying `refuse` to 0crat and didn't get any penalty. According [§6](http://www.zerocracy.com/policy.html#6) refusal costs 15 points penalty. 

Attaching some screens:
Issue comments log:
![image](https://user-images.githubusercontent.com/14931449/41769742-f3eabe44-7618-11e8-9c69-e012b9ea900f.png)

My awards page
![image](https://user-images.githubusercontent.com/14931449/41769792-22c2ca68-7619-11e8-8baa-8b09430774ab.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@olenagerasimova I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1217` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
