### ISSUE TITLE
refresh_awards can submit empty claims

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1218]
Stakeholder `refresh_awards` submit claims for all users in Zerocracy even if reputation didn't change, it's about 100 claims simultaneously now. We should submit `Award points were added` claim only if reputation was changed (minutes != 0).

**Comment by 0crat** [comment]
Job [#1218](https://github.com/zerocracy/farm/issues/1218) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1218](https://github.com/zerocracy/farm/issues/1218) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2050647384); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 I have a doubt here, how do we check if a claim was submitted?

**Comment by g4s8** [comment]
@paulodamaso we can check it in the footpint, see `elects_and_assigns_performer/_after.groovy` for example

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1508](https://github.com/zerocracy/farm/issues/1508) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso #1493 was merged, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1218](https://github.com/zerocracy/farm/issues/1218) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1508](https://github.com/zerocracy/farm/issues/1508) is solved here.
