### ISSUE TITLE
Add "points" github command

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1224]
Add new tracker command to add points manually by `ARC` or `PO`,  because performer may receive negative reputation by external service breakdown (e.g. 0pdd like in this bug: https://github.com/yegor256/0pdd/issues/57#issuecomment-399738071).

The command may looks like this: `@0crat points @vl3 +30`. Also it should have a restriction: from -60 to +60 points.

**Comment by 0crat** [comment]
Job [#1224](https://github.com/zerocracy/farm/issues/1224) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1224` is not assigned, can't get performer
