### ISSUE TITLE
add_github_webhook.groovy:25-31: Implement logic for...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1226]
The puzzle `1048-04512f73` from #1048 has to be resolved:

https://github.com/zerocracy/farm/blob/84826cde352271896e68d9d170583f58b36e60b4/src/main/groovy/com/zerocracy/stk/pm/hooks/add_github_webhook/add_github_webhook.groovy#L25-L31

The puzzle was created by Krzysztof Krason on 24-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1226](https://github.com/zerocracy/farm/issues/1226) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1226](https://github.com/zerocracy/farm/issues/1226) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2050667645); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #1514 review

**Comment by 0crat** [comment]
> @0crat wait for #1514 review ([here](https://github.com/zerocracy/farm/issues/1226#issuecomment-409344175))

@paulodamaso The impediment for [#1226](https://github.com/zerocracy/farm/issues/1226) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `1048-04512f73` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ee5f821e-71b5-4706-b3c9-61ba92e4e645, thread: pool-296-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-04T14:59:22.564Z"
```

[0.28.15](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1226, Action: `closed`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1550](https://github.com/zerocracy/farm/issues/1550) is still not solved.

**Comment by krzyk** [comment]
@0crat out

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by paulodamaso** [comment]
@g4s8 0pdd closed the issue, but 0crat failed removing it from wbs; please remove it.

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1226#issuecomment-411532926))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ce1bb5b2-f136-41eb-a7c2-a85674933de4, thread: AsyncProc-4
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/farm#1226] declared for identity constraint of element "verbosity".
```

[0.29.8](https://github.com/zerocracy/farm): CID: [2201959856](https://www.0crat.com/C3NDPUA8L/2201959856), Type: "Close job", Author: "g4s8"

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1226#issuecomment-411532926))

@g4s8 The job [#1226](https://github.com/zerocracy/farm/issues/1226) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
