### ISSUE TITLE
update_heapdump.groovy:30-32: Add a unit test for this...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1232]
The puzzle `766-8d00e56f` from #766 has to be resolved:

https://github.com/zerocracy/farm/blob/e3ff4c4b05421b9581840a96852a85a953065294/src/main/groovy/com/zerocracy/stk/internal/update_heapdump.groovy#L30-L32

The puzzle was created by rultor on 25-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#1232](https://github.com/zerocracy/farm/issues/1232) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2050727879); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #1529 review

**Comment by paulodamaso** [comment]
@0crat wait for #1529 review

**Comment by 0crat** [comment]
> @0crat wait for #1529 review ([here](https://github.com/zerocracy/farm/issues/1232#issuecomment-410004840))

@paulodamaso The impediment for [#1232](https://github.com/zerocracy/farm/issues/1232) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `766-8d00e56f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1232](https://github.com/zerocracy/farm/issues/1232) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
