### ISSUE TITLE
Document Estimates

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1236]
I have to fix [this](https://github.com/zerocracy/farm/issues/876) task, but from a first code inspection, it is not clear to me how estimates work.

For instance, I am not sure if we can ``update`` an estimate with a negative value and this will count as removal, or if we need a ``remove`` method. Also, it seems to me QA tasks are already added, since I see usage of ``Estimates`` into ``start_order`` and ``finish_order``?

Please, document the ``Estimates`` process -- which tasks are added there and when, what is the effect etc.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1236](https://github.com/zerocracy/farm/issues/1236) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1761135503); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1236` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@amihaiemil please, see #1252

**Comment by g4s8** [comment]
@amihaiemil PR #1252 was merged, can we close?

**Comment by amihaiemil** [comment]
@g4s8 Sure, thanks :)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1236](https://github.com/zerocracy/farm/issues/1236) is now out of scope
