### ISSUE TITLE
pay mentor on graduation

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1242]
Let's pay a fixed fee to a mentor when his/her student is graduated. In `remove_mentor_when_graduated` let's drop a claim, in the end. Something like `A student graduated`. Then, let's create a new stakeholder to catch this claim and pay the mentor a bonus of 120 minutes. This will motivate mentors to move their students forward.

Let's not forget to update the policy.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1242#issuecomment-400005413))

@g4s8 The job [#1242](https://github.com/zerocracy/farm/issues/1242) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1761638700); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 please, see https://github.com/zerocracy/zerocracy.github.io/issues/19

**Comment by yegor256** [comment]
@g4s8 that ticket is fixed: zerocracy/zerocracy.github.io#19

**Comment by g4s8** [comment]
@yegor256 it was fixed in #1425, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1242](https://github.com/zerocracy/farm/issues/1242) is now out of scope
