### ISSUE TITLE
let's not penalize PMO members for breakup

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1243]
In `penalize_for_breakup.groovy` let's check whether the person is a member of PMO project (see how we check in many other places). If the user is from PMO, let's not penalize him/her.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1243#issuecomment-400005261))

@g4s8 The job [#1243](https://github.com/zerocracy/farm/issues/1243) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1761638676); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@yegor256 see PR #1274.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1274.

**Comment by 0crat** [comment]
> @0crat wait for merge of #1274. ([here](https://github.com/zerocracy/farm/issues/1243#issuecomment-400977434))

@carlosmiranda The impediment for [#1243](https://github.com/zerocracy/farm/issues/1243) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 #1243 merged, can we close this now?

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1243](https://github.com/zerocracy/farm/issues/1243) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
