### ISSUE TITLE
Claims.java:47-51: Invent mechanism to prevent huge...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1246]
The puzzle `1215-032c8ff3` from #1215 has to be resolved:

https://github.com/zerocracy/farm/blob/8085ab7425dbf10267b9fb6f2516bbe9c1327d50/src/main/java/com/zerocracy/pm/Claims.java#L47-L51

The puzzle was created by g4s8 on 25-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1246#issuecomment-407300894))

@g4s8 Job `gh:zerocracy/farm#1246` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1246#issuecomment-407300894))

@g4s8 The job [#1246](https://github.com/zerocracy/farm/issues/1246) is now out of scope

**Comment by 0pdd** [comment]
The puzzle `1215-032c8ff3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1246` is not assigned, can't get performer
