### ISSUE TITLE
claim.reply in remove_mentor_when_graduated is not working

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1248]
`remove_mentor_when_graduated` is trying to send a message to nobody, because it reacts to `Ping hourly` claim and using `claim.reply`:
```groovy
    claim.reply(
      new Par(
        'Since your reputation is over %d,',
        'you don\'t need a mentor anymore, as explained in §43;',
        'you successfully graduated and won\'t pay the tuition fee;',
        'congratulations!'
      ).say(threshold)
    ).postTo(pmo)
```
but origin claim doesn't have a token so this `reply` is submitting same message.

Also this stakeholder is failing because it submits duplicated claims:
`java.lang.IllegalStateException: Duplicate claims are not allowed in PMO, can't add this XML to 6 existing ones`

**Comment by 0crat** [comment]
Job [#1248](https://github.com/zerocracy/farm/issues/1248) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting busy with other higher priority tasks

**Comment by 0crat** [comment]
> @0crat waiting busy with other higher priority tasks ([here](https://github.com/zerocracy/farm/issues/1248#issuecomment-410646802))

@krzyk The impediment for [#1248](https://github.com/zerocracy/farm/issues/1248) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
