### ISSUE TITLE
boost can only be used by ARC or PO

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1263]
Check this out: https://github.com/zold-io/zold/issues/264#issuecomment-400604238 This is wrong. Boost can only be used by ARC or PO. Please, fix ASAP.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1263](https://github.com/zerocracy/farm/issues/1263) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1781453576); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1263` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.4`

**Comment by g4s8** [comment]
@yegor256 this bug was reproduced and fixed in https://github.com/zerocracy/farm/commit/ceb53cdc716ec33da4fbabd1cacadfa2aba6c455

**Comment by g4s8** [comment]
@yegor256 can we close this?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1263](https://github.com/zerocracy/farm/issues/1263) is now out of scope
