### ISSUE TITLE
reward to ARC on successful release

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1269]
I think we should pay some additional reward to a project ARC when a new release shows up in GitHub. I'm not sure how to calculate the size of the reward, but it must exist. Maybe by the amount of changes in the repository (lines)?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1269](https://github.com/zerocracy/farm/issues/1269) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
>  Maybe by the amount of changes in the repository (lines)?

@yegor256 maybe it's better to count finished orders (from `orders.xml`) in period from last release? I think it's more correct and easier to implement.

**Comment by g4s8** [comment]
@yegor256 also please see https://github.com/zerocracy/zerocracy.github.io/issues/23

**Comment by yegor256** [comment]
@g4s8 but `orders.xml` will be empty, if they are finished... Or I didn't understand you

**Comment by g4s8** [comment]
@yegor256 right, I forget about it. So maybe we can use footprint?

**Comment by yegor256** [comment]
@g4s8 I think that the amount of code contributed is more important than the amount of tasks. I may be wrong... Let's announce this in the chat and see all opinions?

**Comment by g4s8** [comment]
@yegor256 I'm just thinking that amount of code is not fully reflects amount of work. E.g. if someone rename class name during refactoring it can change many files and lines of code, but nothing really changed and it will take one-two minutes of work.
Anyhow we can ask opinions in chat.

**Comment by amihaiemil** [comment]
@yegor256 @g4s8 It should definetely take into account the number of closed Issues (even if they are not turned into Jobs, but simply Issues which were not accepted) -- beacuse the ARC can potentially have a lot of unpaid work with open tickets... he must spend at least 5min/ticket to analyze the situation and he is not paid if he rejects the ticket.

**Comment by botanicus** [comment]
I think the amount of tickets is a much better measure than LoC.

**Comment by g4s8** [comment]
@yegor256 yes, I think we can start with claims count, and change it later if needed.

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1269#issuecomment-402060823))

@g4s8 The job [#1269](https://github.com/zerocracy/farm/issues/1269) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1840845506); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@0crat wait (need more details on reward, see https://github.com/zerocracy/zerocracy.github.io/issues/23)

**Comment by 0crat** [comment]
> @0crat wait (need more details on reward, see https://github.com/zerocracy/zerocracy.github.io/is... ([here](https://github.com/zerocracy/farm/issues/1269#issuecomment-402617197))

@carlosmiranda The impediment for [#1269](https://github.com/zerocracy/farm/issues/1269) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 one question is how do we keep track of releases? Do pre-releases count? or just finalized ones?

Then how does `0crat` keep track of "new" releases in Github have been paid to the architect?

**Comment by g4s8** [comment]
@carlosmiranda zerocracy/zerocracy.github.io#23 was closed, please see https://github.com/zerocracy/zerocracy.github.io/commit/30401441f755b7d05c70b1d97df00e66303ab303

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 see PR #1355.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1366](https://github.com/zerocracy/farm/issues/1366) is still not solved.

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1269](https://github.com/zerocracy/farm/issues/1269) is now out of scope

**Comment by ypshenychka** [comment]
@botanicus According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/farm/issues/1269#issuecomment-401056300) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@botanicus ping

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1366](https://github.com/zerocracy/farm/issues/1366) is solved here.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
