### ISSUE TITLE
Agenda doesn't clear up

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1270]
I think this might be releated to #1254.

I have few items in my agenda that are already closed (QA did the review):
- https://github.com/zerocracy/farm/issues/1063
- https://github.com/zerocracy/farm/pull/1251

Also I think the total number of tasks assigned in agenda shoiuld exclude the ones under QA review (because they are not taken into account for the limit of jobs).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1270](https://github.com/zerocracy/farm/issues/1270) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1791116001); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1270` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.6`

**Comment by g4s8** [comment]
@ypshenychka please, dont submit QA-verdicts until `0.23.6` is released.

**Comment by g4s8** [comment]
@krzyk @ypshenychka should be fixed now, let's wait for next QA review

**Comment by g4s8** [comment]
@ypshenychka agenda of #1121 performer (@carlosmiranda) was updated successfully. @krzyk can we close now? Your agenda should be automatically fixed within few hours by `delete_stale_jobs` script.

**Comment by krzyk** [comment]
@g4s8 OK, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1270](https://github.com/zerocracy/farm/issues/1270) is now out of scope

**Comment by krzyk** [comment]
@g4s8 It's been over 24 hrs, and I still have some items in my agenda that have been closed and QA approved:
- https://github.com/sunsofterp/portal/pull/101
- https://github.com/zerocracy/farm/issues/1063
- https://github.com/zerocracy/farm/pull/1251
- https://github.com/zerocracy/farm/pull/1264

Removal of stale jobs is hourly, so the above ones should disappear long ago.

**Comment by g4s8** [comment]
@krzyk your agenda didn't updated, because it takes 10 random users each hour (see `delete_stale_jobs`), updated it manually, please check

**Comment by krzyk** [comment]
@g4s8 Random seed avoided me :) Now everything is good.
