### ISSUE TITLE
0crat website  said i need an invitation (screen shot)

### ISSUE THREAD

**Issue by blackout314** [zerocracy/farm#1273]
- You tell us what you are trying to do
i'm trying to login in my agenda

  - You explain the results you are getting
i cant log and see this message

0crat said i have 100 rep point, i have some tasks assigned from 0crat telegram bot (2 or 3)

![](https://i.imgur.com/J1g8ndG.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@blackout314 you see this message because you doesn't have a mentor because of [breakup](http://www.zerocracy.com/policy.html#47), to join back you can submit join form again or ask project architect to invite you.

**Comment by blackout314** [comment]
thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1273` is not assigned, can't get performer
