### ISSUE TITLE
no message from 0crat when mentor kick out student

### ISSUE THREAD

**Issue by blackout314** [zerocracy/farm#1276]
0crat dont send a message when mentor kick student

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1276](https://github.com/zerocracy/farm/issues/1276) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1276](https://github.com/zerocracy/farm/issues/1276) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2150751739); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #1554 review

**Comment by 0crat** [comment]
> @0crat wait for #1554 review ([here](https://github.com/zerocracy/farm/issues/1276#issuecomment-411138177))

@paulodamaso The impediment for [#1276](https://github.com/zerocracy/farm/issues/1276) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@blackout314 changes merged in #1554 , please close

**Comment by paulodamaso** [comment]
@blackout314 ping

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
