### ISSUE TITLE
RqUser.java:69-71: A check whether user is a PO in any of...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1279]
The puzzle `1054-30c8b97d` from #1054 has to be resolved:

https://github.com/zerocracy/farm/blob/b65870f81c3928ee09b0e6b858047bfc30c9d7ef/src/main/java/com/zerocracy/tk/RqUser.java#L69-L71

The puzzle was created by Krzysztof Krason on 27-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1279](https://github.com/zerocracy/farm/issues/1279) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1279](https://github.com/zerocracy/farm/issues/1279) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2410161329); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 21days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (busy on other tasks)

**Comment by 0crat** [comment]
> @0crat wait (busy on other tasks) ([here](https://github.com/zerocracy/farm/issues/1279#issuecomment-422593660))

@carlosmiranda The impediment for [#1279](https://github.com/zerocracy/farm/issues/1279) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 please see PR #1757

**Comment by 0pdd** [comment]
The puzzle `1054-30c8b97d` has disappeared from the source code, that's why I closed this issue.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
