### ISSUE TITLE
Shares paid for DEV job is calculated wrong

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1281]
When I receive my shares payment for jobs "acceptable" I get:
- for REV task 25% my rate (and 15 points)
- for DEV task ~31% of my rate (and 30 points)

For DEV task I should get 50% of my hourly rate (for tasks that are 30mins).

Example task #1084 

EDIT: Now I found a REV task where I also got a lower amount - https://github.com/zerocracy/datum/pull/351, it is consistent with the DEV task mentioned above. As if my hourly rate was calculated at ~ %61 of actual rate.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk did you substract cash part from it? You should receive `(vesting-rate - cash-rate) * minutes / 60` of shares. E.g. if your vesting rate is $20 and cash rate is $10 you should receive $5 of shares and $5 of cash for 30 minutes job.

**Comment by krzyk** [comment]
@g4s8 OK, so it makes sense know for the DEV rate, but it means now that the REV tasks are incorrectly calculated I get always (except few cases like zerocracy/datum#351) 25% rate, as if cash amount wasn't substracted.

**Comment by g4s8** [comment]
@krzyk yes, it seems that it's not calculated correctly

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1281#issuecomment-401096176))

@g4s8 The job [#1281](https://github.com/zerocracy/farm/issues/1281) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1791637273); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@krzyk @g4s8 here's what looks to be the problem. in `transfer_shares.groovy` we check whether the incoming `Make payment` claim has a `cash` parameter or not. If present, `Cash` is deducted. If not, no cash is deducted.

So for some reason, some completed tasks lack this `cash` parameter. Note that in `pay_architect_for_pull_request` no `cash` param is passed, but we do pass them in `finish_order` and also in `complete_qa_review` (through the claim returned by `Reviews.remove`. So I'm not sure why this is inconsistent for REV jobs.

**Comment by g4s8** [comment]
@carlosmiranda I think we should separate payment claim from reputation claims, so "Make payment" stakeholders will handle only payment requests (cash and shares) and reputation stakeholders only points. This issue is ralated: #1162

But now we need some hotfix to stop this bug, maybe just add cash param to all payment claims where needed?

**Comment by carlosmiranda** [comment]
@krzyk @g4s8 see PR #1294.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1294

**Comment by 0crat** [comment]
> @0crat wait for merge of #1294 ([here](https://github.com/zerocracy/farm/issues/1281#issuecomment-401521757))

@carlosmiranda The impediment for [#1281](https://github.com/zerocracy/farm/issues/1281) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@krzyk #1294 merged, may we close this now?

**Comment by krzyk** [comment]
@carlosmiranda thanks

**Comment by carlosmiranda** [comment]
@krzyk it's not closed yet :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1281](https://github.com/zerocracy/farm/issues/1281) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
