### ISSUE TITLE
TxnTest.java:81-83: Fix NullPointerException due...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1284]
The puzzle `993-2ea9b05d` from #993 has to be resolved:

https://github.com/zerocracy/farm/blob/c780d6640fd279043bed35e84e6f401fb4b4c18d/src/test/java/com/zerocracy/TxnTest.java#L81-L83

The puzzle was created by rultor on 29-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1284](https://github.com/zerocracy/farm/issues/1284) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1284](https://github.com/zerocracy/farm/issues/1284) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2651030851); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat wait I busy with other tasks

**Comment by 0crat** [comment]
> @0crat wait I busy with other tasks ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-425725748))

@krzyk The impediment for [#1284](https://github.com/zerocracy/farm/issues/1284) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-426303906))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1284](https://github.com/zerocracy/farm/issues/1284), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1284](https://github.com/zerocracy/farm/issues/1284) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2772147201); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The job [#1284](https://github.com/zerocracy/farm/issues/1284) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/5b194875-ac45-4847-822f-e1ec53cf57ab); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1284` already assigned to @carlosmiranda, can't assign to @carlosmiranda

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-541477411))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1284](https://github.com/zerocracy/farm/issues/1284), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-541477411))

@carlosmiranda Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#1284](https://github.com/zerocracy/farm/issues/1284) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1e8e276b-c611-42a2-a4af-b7648312f07c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-541478846))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1284](https://github.com/zerocracy/farm/issues/1284), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-541478846))

@carlosmiranda There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@5be12c6b-b56e-4607-80d0-04b769beebe8, thread: pool-6-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/farm#1284] declared for identity constraint of element "speed".
```

[0.49.19](https://github.com/zerocracy/farm): CID: [6387c034-cc7e-4162-a31d-73575ef0c5c5](https://www.0crat.com/footprint/C3NDPUA8L/6387c034-cc7e-4162-a31d-73575ef0c5c5), Type: "Order was canceled"

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1284#issuecomment-541478846))

@carlosmiranda Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0pdd** [comment]
The puzzle `993-2ea9b05d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1284` is not assigned, can't get performer
