### ISSUE TITLE
REV tasks should have higher bonus for good quality mark

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1287]
Based on discussion in https://github.com/zerocracy/zerocracy.github.io/issues/25 REV tasks should have (old) bonus of 5 mins - which will be in new calculation form a ~33% bonus.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1287](https://github.com/zerocracy/farm/issues/1287) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@carlosmiranda @amihaiemil @paulodamaso would you like to fix this one (and start getting +33% instead of +8% for good REV tasks?) :)

**Comment by g4s8** [comment]
@0crat assign @amihaiemil

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil  ([here](https://github.com/zerocracy/farm/issues/1287#issuecomment-406810592))

@g4s8 The job [#1287](https://github.com/zerocracy/farm/issues/1287) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2021717414); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by amihaiemil** [comment]
@krzyk I'm not sure, but wasn't this task fixed already, as [this](https://github.com/zerocracy/zerocracy.github.io/issues/25#issuecomment-402543844) comment says?

**Comment by amihaiemil** [comment]
@0crat refuse 

Going on vacation for 3 weeks

**Comment by krzyk** [comment]
@amihaiemil it was only the policy page, now we need to use it here

**Comment by 0crat** [comment]
> @0crat refuse Going on vacation for 3 weeks ([here](https://github.com/zerocracy/farm/issues/1287#issuecomment-408118359))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#1287](https://github.com/zerocracy/farm/issues/1287), please stop working. Reason for job resignation: Order was cancelled

**Comment by amihaiemil** [comment]
@krzyk Well, I'll take it up again after vacation if it's not fixed by then :)

**Comment by krzyk** [comment]
@g4s8 I know it is unorthodox, but I could work on this if no one else can.

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1287#issuecomment-408687721))

@g4s8 The job [#1287](https://github.com/zerocracy/farm/issues/1287) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2101607829); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@0crat done in #1509

**Comment by krzyk** [comment]
@g4s8 could you make a release with this change?

**Comment by 0crat** [comment]
> @0crat done in #1509  ([here](https://github.com/zerocracy/farm/issues/1287#issuecomment-409206670))

@krzyk Can't understand "done", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
Job was finished in 44 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1287](https://github.com/zerocracy/farm/issues/1287) is now out of scope

**Comment by g4s8** [comment]
@ypshenychka sure, I confirm

**Comment by g4s8** [comment]
@rultor release, tag=`0.27.5`

**Comment by ypshenychka** [comment]
@g4s8 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable
