### ISSUE TITLE
let's send ZLD to everybody on task closure

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1291]
Let's send ZLD every time (!) we make a payment to anyone. Some users will decided to earn ZLD and will setup their wallets. That's fine. But on top of that, let's send ZLD automatically to everybody. Thus, if someone decides to earn ZLD, he/she will select double amounts in ZLD.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1291` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1311](https://github.com/zerocracy/farm/issues/1311) is still not solved.

**Comment by g4s8** [comment]
@yegor256 can we close this? It shoud be implemented in #1306

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.2`

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by g4s8** [comment]
@0crat status

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.4`

**Comment by 0crat** [comment]
The job [#1291](https://github.com/zerocracy/farm/issues/1291) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.
