### ISSUE TITLE
Drop ETH support

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1298]
Result from #980:
We need to drop Etherium support from Zerocracy
- Remove ETH support mentioned in Policy (https://www.zerocracy.com/policy.html#20)
- Remove ETH wallets support informing that ETH cannot be used when user tries to use it.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso I think this taks should be submitted as a puzzle, as a result of #980 job.

**Comment by paulodamaso** [comment]
@g4s8 Take a look at https://github.com/zerocracy/farm/pull/1303.
