### ISSUE TITLE
Agenda `added` field is shifted by 1 day

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1299]
Today when I entered my agenda I see following entries:
![image](https://user-images.githubusercontent.com/105730/42132796-033c9360-7d1f-11e8-802f-e70507baa940.png)

It looks like the `added` field is shifted by `-1 day`. I'm not sure what might have caused that, but it makes harder to read and decide on tasks.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk your agenda has correct `added` values, but formatting in `xsl` is not working properly. Please resubmit this bug in https://github.com/zerocracy/datum repo.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1299` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
