### ISSUE TITLE
don't kick out REV from pull requests on delay

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1302]
I think we should not kick out REV (code reviewers) from pull requests on delay. They can't responsible for the delays there, since the code is not theirs.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1302](https://github.com/zerocracy/farm/issues/1302) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 seems like a bug in delay notification. So far I have not been kicked out of REV jobs for delays.

**Comment by paulodamaso** [comment]
@carlosmiranda Take a look at these, it happened to me:
- https://github.com/yegor256/jpeek/pull/247
- https://github.com/yegor256/jpeek/pull/256

**Comment by carlosmiranda** [comment]
@paulodamaso right, fair enough

**Comment by 0crat** [comment]
The job [#1302](https://github.com/zerocracy/farm/issues/1302) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1871158332); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1364](https://github.com/zerocracy/farm/issues/1364) is still not solved.

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1302](https://github.com/zerocracy/farm/issues/1302) is now out of scope
