### ISSUE TITLE
Crypto.java:43-45: We need to drop Etherium support from...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1304]
The puzzle `980-46a74068` from #980 has to be resolved:

https://github.com/zerocracy/farm/blob/cf9716d65c4d243cd375cd77b77b7bc85053ae63/src/main/java/com/zerocracy/pmo/banks/Crypto.java#L43-L45

The puzzle was created by Paulo Lobo on 02-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1304](https://github.com/zerocracy/farm/issues/1304) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1304](https://github.com/zerocracy/farm/issues/1304) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2370746067); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `980-46a74068` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1304](https://github.com/zerocracy/farm/issues/1304) is now out of scope

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1304#issuecomment-416177006))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1304](https://github.com/zerocracy/farm/issues/1304) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231304%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
