### ISSUE TITLE
0crat queues tickets to infinite when several QA verdicts were done one by one

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1307]
It happened already several times. 
I've finished QA reviews one by one in several tickets. Within some amount of time (up to 10 mins) 0crat gave the points for them. But two tickets #1296 and #1300 (that were reviewed even earlier than the tickets that were already rewarded by 0crat) were queued and there's no word from 0crat for 2 hours. 

NOTE: issue #841 was reviewed much later than the above ones and 0crat gave points for it.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by ypshenychka** [comment]
Now no repsonse in https://github.com/zold-io/zold/pull/317.

**Comment by 0crat** [comment]
The job [#1307](https://github.com/zerocracy/farm/issues/1307) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1832024027); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1307` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@0crat status

**Comment by g4s8** [comment]
@rultor release, tag=`0.24.5`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1307#issuecomment-401932723))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1307](https://github.com/zerocracy/farm/issues/1307) is [in scope](http://www.zerocracy.com/policy.html#14) for 32min
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [31min](http://www.zerocracy.com/policy.html#8)
  * @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation!
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ypshenychka[/z](https://www.0crat.com/u/ypshenychka): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231307%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@ypshenychka the puzzle [#1317](https://github.com/zerocracy/farm/issues/1317) is still not solved.

**Comment by g4s8** [comment]
@ypshenychka it should be fixed in a2f5821c23469a680485ae8bb6ac875316eb3b24
please say your verdict again, because 0crat loses previous verdicts.

**Comment by ypshenychka** [comment]
@g4s8 In all three issues received message fro 0crat "There is no quality review for <>, no performer". But no points or payment was done in zold-io/zold#317

**Comment by ypshenychka** [comment]
@g4s8 Could you please take a look at https://github.com/zold-io/zold/pull/317? No points or payments are done there.

**Comment by g4s8** [comment]
@ypshenychka looks like claim with payment to you was missed due to this issue, you can ask project's ARC for manual payment

**Comment by 0pdd** [comment]
@ypshenychka the only puzzle [#1317](https://github.com/zerocracy/farm/issues/1317) is solved here.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1307](https://github.com/zerocracy/farm/issues/1307) is now out of scope
