### ISSUE TITLE
Allow run of specific BundlesTest cases

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1308]
Right now the build takes a bit of time (around 20 minutes), and `BundlesTest` alone takes up around 9 minutes in my machine. This means that up to 1/3rd of my actual "development" time is just running `BundlesTest`.

This makes debugging one particular test case extremely tedious, not to mention financially inefficient, given that we work by microtasks.

Let's allow the option of running just one (or a few) specific test cases in `BundlesTest`, e.g.:

`mvn clean test -Dtest=BundlesTest -Dbundle=assign_role,cancel_order`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#1308](https://github.com/zerocracy/farm/issues/1308) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2681058119); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait busy on other tasks  ([here](https://github.com/zerocracy/farm/issues/1308#issuecomment-425728323))

@carlosmiranda The impediment for [#1308](https://github.com/zerocracy/farm/issues/1308) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 this is my own report, is it all right with you if I work on it?

**Comment by g4s8** [comment]
@carlosmiranda sure

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1745.

**Comment by carlosmiranda** [comment]
@g4s8 fixed in #1745

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1308](https://github.com/zerocracy/farm/issues/1308) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
