### ISSUE TITLE
Javadocs on stakeholders

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1310]
Right now the stakeholders are lacking javadocs. I think we should start writing javadocs on the existing ones and also on the ones to follow in the future.

This is not just a request for documentation, but it should be a habit -- they are very important parts of the system and I already found a few which I don't understand (for instance, I don't know what is the difference between ``contribute_by_stripe`` and ``fund_by_stripe``).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1310](https://github.com/zerocracy/farm/issues/1310) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1831449906); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1310` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@amihaiemil PR #1409 was merged, can we close?

**Comment by amihaiemil** [comment]
@g4s8 sure, sorry, I forgot about it

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1310](https://github.com/zerocracy/farm/issues/1310) is now out of scope
