### ISSUE TITLE
0crat is subtracting points instead of adding them

### ISSUE THREAD

**Issue by Vatavuk** [zerocracy/farm#1313]
Instead of gaining 15 points on accepted [issue](https://github.com/yegor256/cactoos/issues/826#issuecomment-388580671) 0crat
subtracted it from my total points. I had 745 points and now I have 730.

EDIT: I'm in vacation mode, maybe this is somehow connected to the problem

I'm copy-pasting 0crat messages from telegram:

You got +35 point(s) in the job #48 (https://github.com/yegor256/cactoos-http/issues/48) in Cactoos (https://www.0crat.com/p/C63314D6Z), your total is +745 (https://www.0crat.com/u/vatavuk/awards), see §18 (http://www.zerocracy.com/policy.html#18): Order was finished, quality is "good"

Inconsistent, non-OO or non-declarative tests should be improved #48
I noticed during my last PR that the quality standards of cactoos-http&#39;s tests are 

You got +15 point(s) in the job #826 (https://github.com/yegor256/cactoos/issues/826) in Cactoos (https://www.0crat.com/p/C63314D6Z), your total is +730 (https://www.0crat.com/u/vatavuk/awards), see §18 (http://www.zerocracy.com/policy.html#18): Bug was reported, see §29 (http://www.zerocracy.com/policy.html#29)

ScalarEnvelope and FuncEnvelope #826
Although Scalar and Func interfaces consist of only one method I think that it would be valuable for a user to be able to use envelo...

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@Vatavuk you have only positive reputation updates for last few weeks, see https://www.0crat.com/u/vatavuk/awards. It seems that your reputation was "cropped" according to https://www.zerocracy.com/policy.html#18
> Zerocrat takes into account only the points you earned over the last 90 days.

**Comment by Vatavuk** [comment]
@g4s8 I wasnt aware of this, thx. Closing
