### ISSUE TITLE
Add an alternative cash-based payout method

### ISSUE THREAD

**Issue by botanicus** [zerocracy/farm#1320]
As of now, the only _money-based_ payout method is PayPal. If for whatever reason PayPal doesn’t work for someone (as [reportedly in Paraguay](https://github.com/zerocracy/farm/issues/865)), then one is out of luck.

___

**My scenario:**
- I need to get the money to my [TransferWise borderless account](https://transferwise.com/gb/borderless/). It gives me a local US bank account, MasterCard and a great app to convert currencies for way cheaper than anything else on the market that I’d know of. (Arguably the best option if you’re earning in USD and living outside of the US, like most of us here.)
- My work machine is iPad Pro and unfortunately, the iPad mobile web doesn’t work well – for instance the _withdraw_ button does nothing when I tap it. Requesting the desktop side still sends the same mobile version, so no luck there either and when I install the (horrible) iPhone app, I cannot log in, because their captcha handling is broken (I’m experiencing same issue as [here](https://www.paypal-community.com/t5/My-Account/App-issues-and-I-can-t-even-complain-as-the-quot-message-us-quot/td-p/1502415)).
- Of course PayPal problems are not 0crat’s, but my point is there should be an alternative to PayPal. And, as linked above, I’m not the only one who has problems using it.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@botanicus you also can configure Bitcoin wallet to receive payments, does it work for you?

**Comment by botanicus** [comment]
@g4s8 I don’t know much about it, but if I understand how it works, then it’s certainly not preferred.

I think I’ll have to make one of these methods work at least for now anyway, but it’s probably still going to be bugging PayPal support rather than toying around with BTC (I really just want USD).

But that’s just as a workaround, I still believe in merit of this issue.

**Comment by krzyk** [comment]
@botanicus Could you propose alternative to paypal, it would be easier to add if we have a name?
Some time ago p[ayoneer was proposed](https://github.com/zerocracy/farm/issues/865), but they refused.

**Comment by botanicus** [comment]
@krzyk how about Stripe?

**Comment by krzyk** [comment]
@botanicus I know Stripe is used shop pages to pay for goods (so customer -> shop). Does it have a way to pay the other way around: shop -> customer?
I mean, is it a online "wallet" like paypal? Can I register there if I'm not a company(/don't have a website) to receive payments?

**Comment by botanicus** [comment]
@krzyk Stripe is pretty generic transfer solution.

It does support shop -> customer: https://stripe.com/blog/send-money-to-debit-cards

I believe you cannot just open your account by yourself, but you can through an app that integrates with Stripe.

I’m certainly not an expert, but I believe Stripe should support what we need.

**Comment by g4s8** [comment]
@yegor256 please see this issue, do we need to support new payment methods as Stripe?

**Comment by yegor256** [comment]
@botanicus @g4s8 this is what that blog page says: "While we can only support U.S. Visa and MasterCard debit cards at the moment, we’re actively working to bring our transfers API to our users in other countries." So, it's not really a solution.

**Comment by yegor256** [comment]
@botanicus @g4s8 @krzyk I think that in the very future we will simply pay in ZLD and they will be easily "sellable" at a number of exchanges. All a programmer will have to do is to register there, collect ZLD, sell them, and receive payments to his/her local bank.

**Comment by botanicus** [comment]
@yegor256 @g4s8 @krzyk how about https://api-docs.transferwise.com/v1/transfers/transfer then? TransferWise is in many countries.

**Comment by g4s8** [comment]
@botanicus all payments methods except ZLD was removed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1320` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
