### ISSUE TITLE
send_zold.groovy:44-46: Reason is not attached to...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1325]
The puzzle `1119-cdea2c77` from #1119 has to be resolved:

https://github.com/zerocracy/farm/blob/f749e9415d87aa8cd78209a898adfa0e3b59a64a/src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy#L44-L46

The puzzle was created by g4s8 on 03-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1325](https://github.com/zerocracy/farm/issues/1325) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1325](https://github.com/zerocracy/farm/issues/1325) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2681147711); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1325#issuecomment-427439558))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1325](https://github.com/zerocracy/farm/issues/1325), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `1119-cdea2c77` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1325` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1325](https://github.com/zerocracy/farm/issues/1325) is now out of scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1325` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
