### ISSUE TITLE
Unpayable tasks

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1330]
Zerocrat is letting some jobs reach a state where it's impossible to pay the performer for his / her work. It occurred when job sticks to job performer after graduation: by policy job performer is kicked out of sandbox projects after graduation, but retains any unfinished tasks of this project. This causes a bonus calculation problem (https://github.com/zerocracy/farm/issues/1175) and, if ever any problem happens with this issue (like https://github.com/llorllale/cactoos-matchers/pull/9 , https://github.com/yegor256/jpeek/pull/247 and https://github.com/yegor256/jpeek/pull/256) `ARC` cannot do anything about it (like a manual payment) because the performer isn't a project member anymore.

I think `ARC` should have a way of paying someone regardless his / her rate at the project; something like a direct cash transfer from the project to any zerocracy member. Project `ARC` would ask zerocrat to make this payment like `direct payment`. It would allow to `ARC` correct these unreachable payment cases, preventing them to happen in the future.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by llorllale** [comment]
@paulodamaso I would say that `0crat` should *automatically* make a payment for any job that you, as job performer, have completed, regardless of whether you're currently in the project or not.

As `ARC`, I certainly would *not* appreciate this little bit of extra work for myself. ;)

**Comment by paulodamaso** [comment]
@llorllale That would be a good idea, but it would just solve one of the problems listed above ( llorllale/cactoos-matchers#9 ), when paying time was lost due some system problem. In the other cases the system behaved as intended (removed `REV` from task on delay) but `REV` work was already done. `0crat` assumes that `REV` is done when PR is merged, but we have some delay between `REV` ask for merge and the effective merge of the PR, and `REV` can have the issue taken during this delay. So, if we want to let `0crat` pay automatically for completed jobs, we should think in somethin like I proposed in https://github.com/zerocracy/farm/issues/1164 . WDYT?

**Comment by paulodamaso** [comment]
@g4s8 Yes, but neither #1302 nor changes in QA calculations solves the problem that happened in https://github.com/llorllale/cactoos-matchers/pull/9 , so it is not enough to resolve this problem of unpaybale tasks.

**Comment by g4s8** [comment]
@paulodamaso but this situation should not happens again, because you will not be kicked out from PR job and QA bonus will be calculated correctly after you leave sandbox project. Add new mechanism to pass over existing restrictions looks not correct, because it solve only your problem but project will spent few hours to implement a workaround. Instead of this I can manually add you a payment for this job, can you please calculate the amount?
// CC @llorllale

**Comment by paulodamaso** [comment]
@g4s8 Right, I thought that you couldn't add these payments manually. I have three payments in that condition:
- For https://github.com/yegor256/jpeek/pull/247 is 15min @ 16USD/hr;
- For https://github.com/yegor256/jpeek/pull/256 is 15min @ 16USD/hr;
- For https://github.com/llorllale/cactoos-matchers/pull/9 is 20min @ 16USD/hr (as @llorllale stated)

**Comment by g4s8** [comment]
@paulodamaso done, please check your profile page (debts section) https://www.0crat.com/u/paulodamaso

**Comment by paulodamaso** [comment]
@g4s8 Thank you, they're all there.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1330` is not assigned, can't get performer
