### ISSUE TITLE
Master is broken by Checkstyle errors in StkSafe

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1331]
See CI build: https://ci.appveyor.com/project/yegor256/farm

```
[INFO] Checkstyle: C:\projects\farm\src\main\java\com\zerocracy\farm\StkSafe.java[74]: Cyclomatic Complexity is 11 (max allowed is 10). (CyclomaticComplexityCheck)
[INFO] Checkstyle: C:\projects\farm\src\main\java\com\zerocracy\farm\StkSafe.java[74]: Executable statement count is 22 (max allowed is 20). (ExecutableStatementCountCheck)
```

Caused by this change: https://github.com/zerocracy/farm/commit/32c9fc6e2599fd5672df6f2c98c6224fd01ca976

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@carlosmiranda thanks, fixed in https://github.com/zerocracy/farm/commit/59447371f9548bea3a974320adf42b676b63c779

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1331` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
