### ISSUE TITLE
Don't show inactive users on team page

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1332]
We have a lot of users without any activity more than 90 days on https://www.0crat.com/team page. It slows down rendering and loading, and make this page less valuable. I think we can mark user as inactive if his `awards.xml` is empty and don't show such users on team page. 
@yegor256 what do you think?

**Comment by g4s8** [comment]
@yegor256 ping, please see this issue

**Comment by yegor256** [comment]
@g4s8 yes, totally agree. But don't forget to explain this in the `/team` page somewhere at the bottom. Otherwise, developers will wonder why they don't show up there.

**Comment by 0crat** [comment]
Job [#1332](https://github.com/zerocracy/farm/issues/1332) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1332](https://github.com/zerocracy/farm/issues/1332) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2420255490); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for review of PR #1679

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1679  ([here](https://github.com/zerocracy/farm/issues/1332#issuecomment-417930085))

@krzyk The impediment for [#1332](https://github.com/zerocracy/farm/issues/1332) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1692](https://github.com/zerocracy/farm/issues/1692) is still not solved.

**Comment by krzyk** [comment]
@g4s8 please close this issue, it has been merged to master in #1679

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1332](https://github.com/zerocracy/farm/issues/1332) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1692](https://github.com/zerocracy/farm/issues/1692) is solved here.
