### ISSUE TITLE
Board page is slow

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1333]
We need to save all project properties which we display on board page in `catalog.xml` similar to team page.

**Comment by 0crat** [comment]
Job [#1333](https://github.com/zerocracy/farm/issues/1333) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1333](https://github.com/zerocracy/farm/issues/1333) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2350840794); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1657](https://github.com/zerocracy/farm/issues/1657) is still not solved.

**Comment by paulodamaso** [comment]
@g4s8 mereged, please close

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1333](https://github.com/zerocracy/farm/issues/1333) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#1952](https://github.com/zerocracy/farm/issues/1952), [#1953](https://github.com/zerocracy/farm/issues/1953) are still not solved; solved: [#1657](https://github.com/zerocracy/farm/issues/1657).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#1952](https://github.com/zerocracy/farm/issues/1952), [#1953](https://github.com/zerocracy/farm/issues/1953), [#1954](https://github.com/zerocracy/farm/issues/1954) are still not solved; solved: [#1657](https://github.com/zerocracy/farm/issues/1657).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#1953](https://github.com/zerocracy/farm/issues/1953), [#1954](https://github.com/zerocracy/farm/issues/1954) are still not solved; solved: [#1657](https://github.com/zerocracy/farm/issues/1657), [#1952](https://github.com/zerocracy/farm/issues/1952).
