### ISSUE TITLE
Bot's `/rate` command is broken

### ISSUE THREAD

**Issue by duker33** [zerocracy/farm#1334]
- i'm unregistered user
- sent `/rate` command
- got this answer from bot:

```
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@7029763d-567a-43e6-8426-2f46b4b74955, thread: zerocrat_bot Telegram Executor
com.zerocracy.pm.Claims[139] java.lang.IllegalStateException: Can't add, claims overflow in PMO, too many items: 175


0.24.10 (https://github.com/zerocracy/farm): ID: 344196417, From: duker33, ChatId: 100247439
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@duker33[/z](https://www.0crat.com/u/duker33) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by duker33** [comment]
tried 7 mins later and bot woke up.
Close issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1334` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
