### ISSUE TITLE
Crash occurs when ‘wait command issued

### ISSUE THREAD

**Issue by botanicus** [zerocracy/farm#1335]
When I (erroneously) ask 0crat to wait _on a PR rather than the ticket itself_, I get this:

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-388-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "CAZPZR9FS" in 2min: 0d35431ea14f/13min/0/1/true/false by AsyncFlush-4
```

[zold-io/zold#338](https://github.com/zold-io/zold/pull/338#issuecomment-402271870)

It’s not clear what’s going on. I’d expect a meaningful error message.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@botanicus I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1335` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
