### ISSUE TITLE
Applicants to projects should be able to specify role(s) they want

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1340]
In `apply_to_project.groovy`, the following message is sent to the architect when someone applies to the project:

```
        '@%s wants to join you guys;',
        'if you want to add them to the project %s,',
        'just assign `DEV` role and that\'s it;',
        'the hourly rate suggested is %s (profile rate is %s);',
        'you can use that rate or define another one, see §13'
```

It specifically says "assign `DEV` role". However, you can actually assign different roles like `QA`, or `REV`. This confused me initially when a QA person applied to a project I was handling, it was asking me to assign `DEV`.

We should allow an applicant to specify the type of role that they want. Of course, it is still the discretion of `ARC`/`PO` exactly which role(s) to assign, and subject to policy (e.g. REV and DEV cannot be QA, etc.).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1340](https://github.com/zerocracy/farm/issues/1340), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1340` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by g4s8** [comment]
@rultor release, tag=`0.44.2`

**Comment by g4s8** [comment]
@carlosmiranda it should be fixed in https://github.com/zerocracy/farm/commit/9e536506cab44dd4df9ac84414b72c176d4a2d45 and released `0.44.2`

**Comment by 0crat** [comment]
Job [#1340](https://github.com/zerocracy/farm/issues/1340) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1340](https://github.com/zerocracy/farm/issues/1340) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
