### ISSUE TITLE
Boost is apparently not working

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1344]
Issue https://github.com/zold-io/zold/issues/98 has been boosted 4x and by my understanding the budget should be 120 minutes.

As can be seen here https://github.com/zold-io/zold/issues/98#issuecomment-402635420 the budget is 60 minutes

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa default boost is 2x, it means 30 minutes, so 4x = 60 minutes, see https://www.zerocracy.com/policy.html#5

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1344` is not assigned, can't get performer
