### ISSUE TITLE
Incorrect Zold extra payments

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1346]
Zold extra payment should include not only cash part of payment but also shares part.

**Comment by 0crat** [comment]
Job [#1346](https://github.com/zerocracy/farm/issues/1346) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1346](https://github.com/zerocracy/farm/issues/1346) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2350847910); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 So Zold payment must be based in full $ / hour ratio and not on only effective (with shares part discounted) one, right?

**Comment by g4s8** [comment]
@paulodamaso yes, it should check versing rate if exists, othervise send cash param, something like this:
```groovy
Cash amount;
if (claim.hasParam('minutes') && vesting.exists(user)) {
  amount = vesting.rate(user).mul(claim.param('minutes') / 60
} else {
  amount = claim.param('amount')
}
```

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1648](https://github.com/zerocracy/farm/issues/1648) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso done, thanks

**Comment by 0crat** [comment]
Job was finished in 29 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1346](https://github.com/zerocracy/farm/issues/1346) is now out of scope

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1648](https://github.com/zerocracy/farm/issues/1648) is solved here.
