### ISSUE TITLE
0crat Makes Silent Payments

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1348]
Apparently, 0crat forgets to comment on Github about some payments, even though they are performed: see [here](https://github.com/zerocracy/farm/pull/1318) and [here](https://github.com/zerocracy/farm/pull/1306)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1348` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
