### ISSUE TITLE
Save user applications to project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1349]
If user apply to a project his application may be missed in chat log and PO or ARC can never see it.
I think it's better to save application in `applications.xml` and add new project page /applications where PO and ARC can see users who wants to apply. When user got a role in a project we can remove application from list.

**Comment by g4s8** [comment]
@yegor256 please look at this issue, what do you think?

**Comment by yegor256** [comment]
@g4s8 I like it, let's do it

**Comment by 0crat** [comment]
Job [#1349](https://github.com/zerocracy/farm/issues/1349) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1349](https://github.com/zerocracy/farm/issues/1349), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2102](https://github.com/zerocracy/farm/issues/2102) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.12`

**Comment by g4s8** [comment]
Done in #2101

**Comment by 0crat** [comment]
Job [#1349](https://github.com/zerocracy/farm/issues/1349) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 29 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1349](https://github.com/zerocracy/farm/issues/1349) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
