### ISSUE TITLE
How to receive ZLD?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#1350]
I have created ZLD wallet with my github, which is connected to ZC. Is it enough? I tried to issue the command to 0crat bot on telegram:
```bash
wallet zld my_wallet_id
```

But received
> Bank name zld is invalid, we accept only paypal, btc, bch, eth, or ltc, see §20

There is no information on Policy on how to configure ZLD. So, how to do it?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#1350](https://github.com/zerocracy/farm/issues/1350) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1881220815); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1350` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.4`

**Comment by g4s8** [comment]
@t-izbassar I updated the [policy](http://www.zerocracy.com/policy.html#20) and fixed wallet validation. To setup your Zold wallet use `wallet zld github-username` and receive Zold payments via https://wts.zold.io/
These changes will be available after next release https://github.com/zerocracy/farm/issues/1350#issuecomment-403721326

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1350](https://github.com/zerocracy/farm/issues/1350) is now out of scope
