### ISSUE TITLE
Notification claim failure should not fail the payment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1354]
If 0crat was failed to notify user about reputation update or any other claim before `make_payment` was failed, it will stop claims flow and user will not receive payment. We should ignore these failures and make payment in any case.

**Comment by 0crat** [comment]
Job [#1354](https://github.com/zerocracy/farm/issues/1354) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1354` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1354](https://github.com/zerocracy/farm/issues/1354) is now out of scope
