### ISSUE TITLE
Missing payment

### ISSUE THREAD

**Issue by botanicus** [zerocracy/farm#1357]
I finished https://github.com/zold-io/zold/issues/280 on time, it was QA’d, reviewed and the `ARC` was asked to close the issue.

That didn’t happen on time and I got -30 points and no money, even though the `ARC` reopened and closed the ticket.

Please rectify.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@botanicus this job is not completed yet, it's waiting for QA review, see https://github.com/zold-io/zold/issues/280#issuecomment-402997504  you will receive payment after QA verdict. (BTW you can check job status with `@0crat status` command) 
We have known issue about missing notifications on GitHub, this is why 0crat didn't asked QA to make a review in comments.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1357` is not assigned, can't get performer
