### ISSUE TITLE
Expired PR has been assigned for review

### ISSUE THREAD

**Issue by botanicus** [zerocracy/farm#1358]
The implementor of https://github.com/zold-io/zold/issues/287 took over 10 days and the bot told him to stop working.

Yet, 2 days after that, I was assigned the PR for review.

I don’t think it makes sense.

**Comment by g4s8** [comment]
@botanicus you can be assigned to a job when previous performer was resigned by delay, it's OK. But we are going to not resign on delay PR performers soon: https://github.com/zerocracy/farm/issues/1302

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1358` is not assigned, can't get performer
