### ISSUE TITLE
0crat does not understand deny

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1360]
The policy says that I can reject a resume with the `deny` command: http://www.zerocracy.com/policy.html#1

When I try it (in telegram), `deny username` 0crat tells me: Can't understand "deny", try one of these...

`deny` is not in the list of commands.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@victornoel it will be implemented with #1352

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1360` is not assigned, can't get performer
