### ISSUE TITLE
Verbosity only updated but never used

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1363]
0crat updates `verosity.xml` on each `Close job` claim, but this metric is never used. Origin issue #535 also says nothing about usage.
@yegor256 how exactly verbosity metric should be used?

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 the more verbose is the person the less likely he/she should get the next job. We have to use this metric in the election process. More verbose people should get less jobs.

**Comment by 0crat** [comment]
Job [#1363](https://github.com/zerocracy/farm/issues/1363) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1363](https://github.com/zerocracy/farm/issues/1363), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/b14d8f76f43b759a725b823ff8f607be5370d75e

**Comment by 0crat** [comment]
Job [#1363](https://github.com/zerocracy/farm/issues/1363) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1363](https://github.com/zerocracy/farm/issues/1363) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
