### ISSUE TITLE
RbRelease.java:30-34: Each time a release is published,...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1366]
The puzzle `1269-a1c2eb54` from #1269 has to be resolved:

https://github.com/zerocracy/farm/blob/25f9ad026123a728257530bc7b78eddee4a4a2cb/src/main/java/com/zerocracy/radars/github/RbRelease.java#L30-L34

The puzzle was created by Carlos Miranda on 06-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1366](https://github.com/zerocracy/farm/issues/1366) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1366](https://github.com/zerocracy/farm/issues/1366) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1910704163); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1269-a1c2eb54` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.26.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.26.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.26.3`
