### ISSUE TITLE
VsBalance should log information

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1372]
When I look at e.g. https://www.0crat.com/footprint/C3NDPUA8L/1881549436
I see entries like:
```
...
  +2.00=0.67x3 Average delivery time 6days is no.2
  +1.38=0.46x3 
  +0.92 Entropy
...
```

The one in the middle (`+1.38=0.46x3`) is from `VsBalance`. It should be replaced with a log explaining why given amount of points was added for user - in similar way as for other Voters.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk thanks, it was fixed in #1404

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1372` is not assigned, can't get performer
