### ISSUE TITLE
Rejected person can cause an exception

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1374]
We need to check that mentor exists in all possible places, because when person rejected it looses his mentor.
```
NodeNotFoundException: XPath '/people/person[@id='emilianodellacasa']/mentor/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<people x..82079..   </links>\uA   </person>\uA</people>\uA': Index (0) is out of bounds (size=0)
    at com.zerocracy.pmo.People.mentor(People.java:282)
    at com.zerocracy.pmo.People$mentor$7.call
    at com.zerocracy.stk.pmo.awards.reject_people_below_score.exec(reject_people_below_score.groovy:44)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:86)
...
(54 additional frame(s) were not displayed)
```

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1374#issuecomment-403233546))

@g4s8 Job [#1374](https://github.com/zerocracy/farm/issues/1374) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Outdated

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1374` is not assigned, can't get performer
