### ISSUE TITLE
Not every DEV has a REV role

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1377]
If you compare election for:
DEV - https://www.0crat.com/footprint/C3NDPUA8L/1880871146
REV - https://www.0crat.com/footprint/C3NDPUA8L/1882158371

You'll notice that REV role is most probably assigned only to 3 people, while DEV role is assigned to 7 (excluding ARC).

Every developer should have both DEV and REV roles.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by krzyk** [comment]
@krzyk closing as duplicate of #1100

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1377` is not assigned, can't get performer
