### ISSUE TITLE
VsOverElected.java:96-100: Refactor this method - extract...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1389]
The puzzle `926-0d29fc00` from #926 has to be resolved:

https://github.com/zerocracy/farm/blob/9f714dd33a5c6ca90d353d45a65cb0476d91438f/src/main/java/com/zerocracy/pm/staff/votes/VsOverElected.java#L96-L100

The puzzle was created by rultor on 09-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1389](https://github.com/zerocracy/farm/issues/1389) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `926-0d29fc00` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1389` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1389](https://github.com/zerocracy/farm/issues/1389) is now out of scope
