### ISSUE TITLE
Award too big for REV

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1395]
[Here](https://github.com/zerocracy/farm/pull/1368) and [here](https://github.com/zerocracy/farm/pull/1343) 0crat awarded me as if I were a ``DEV`` on the job. (30min instead of 15min), when in fact they are PRs and I was ``REV``. The cash payments are correct, it seems to be only a matter of reputation points and commenting.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by krzyk** [comment]
@g4s8 similar thing for DEV, for #1403 I got 46 points (hmm, 30 + 16, like the percentage was just added), cash payment was correct (rate + 16 %)

**Comment by g4s8** [comment]
@amihaiemil it was fixed in #1429 PR, can we close?

**Comment by amihaiemil** [comment]
@g4s8 sure, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1395](https://github.com/zerocracy/farm/issues/1395) is now out of scope

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#unknown]() is still not solved.
