### ISSUE TITLE
remove student limitation for QA members of the Farm project

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1410]
At the moment we don't allow a user to have more than X students. Let's remove this limitation for QA people of Farm project (C3NDPUA8L). We should do something like:

```
if new Roles(farm.find("@id=''C3NDPUA8L").get(0)).hasRole(user, "QA") {
  // allow to have as many students as possible
}
```

We need this in order to help QA people onboard new members for us.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1410](https://github.com/zerocracy/farm/issues/1410) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1921649982); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1410` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 it should be done in #1413, can we close?

**Comment by g4s8** [comment]
@yegor256 it was fixed in #1413

**Comment by 0crat** [comment]
The job [#1410](https://github.com/zerocracy/farm/issues/1410) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
