### ISSUE TITLE
QA agenda contains job that was reviewed 5 days ago and didn't receive any points\payment for it

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1414]
QA review of https://github.com/zerocracy/farm/pull/1336 was done 5 days ago. But this job is still shown in agenda. Also no points and payment was done for QA.

![image](https://user-images.githubusercontent.com/11703257/42592893-a9c03c28-8553-11e8-99b1-55dce47e1c60.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by ypshenychka** [comment]
@g4s8 Currently I have about 6 tickets that are awaiting QA verdict, but Agenda contains only 2. It's not functioning correctly.
![image](https://user-images.githubusercontent.com/11703257/42780734-bd5ed800-894c-11e8-81e5-c05a55c951f1.png)

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda ([here](https://github.com/zerocracy/farm/issues/1414#issuecomment-405447016))

@g4s8 The job [#1414](https://github.com/zerocracy/farm/issues/1414) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1980325165); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@ypshenychka there is a bug in `delete_stale_jobs` , it's not working properly for QA reviews. See PR #1440 for workaround.

**Comment by ypshenychka** [comment]
@carlosmiranda Thanks for figuring this out!

**Comment by 0pdd** [comment]
@ypshenychka the puzzle [#1448](https://github.com/zerocracy/farm/issues/1448) is still not solved.

**Comment by carlosmiranda** [comment]
@ypshenychka should be fixed in PR #1440, may we close this now?

**Comment by ypshenychka** [comment]
@carlosmiranda Thank you.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1414](https://github.com/zerocracy/farm/issues/1414) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@rultor release, tag=`0.26.4`

**Comment by 0pdd** [comment]
@ypshenychka the only puzzle [#1448](https://github.com/zerocracy/farm/issues/1448) is solved here.
