### ISSUE TITLE
Description missing on ZLD bonus after job completion

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1416]
When a job is completed on Zerocracy, a ZLD bonus is given to the DEV. 

I think that for clarity and tracebility, the description should contain the link of the job completed or a small description of the issue (maybe the title?).

Currently the description of the payments states"none"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa you're right, we can't send description now because of the bug in Zold API: https://github.com/zold-io/wts.zold.io/issues/36, we will fix it in #1325 after Zold bug resolved.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1416` is not assigned, can't get performer
