### ISSUE TITLE
0crat have put the PR REV out of the task illegaly

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#1419]
See this [PR](https://github.com/zold-io/java-api/pull/30)

It seems like the project creates two workers of 0crat for every action. So the first worker has put the job out of scope for review and the second one sees, that job is out of scope and then deletes the performer.

The idea of possible reason is that there might be two webhooks configured for the project. But I believe 0crat should handle it correctly.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@t-izbassar it seems, this bug was fixed already

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1419#issuecomment-472955986))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#1419](https://github.com/zerocracy/farm/issues/1419), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1419` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1419](https://github.com/zerocracy/farm/issues/1419) is now out of scope
