### ISSUE TITLE
@since javadoc tags should be for major releases

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1420]
`@since` tags with minor versions make sense for libraries (like cactoos, takes), but for projects like zerocracy they don't.

So I propose to change it only for major releases `1.0`, `2.0` etc.

All the classes that we have should have `0.x` replaced with `1.0`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk thanks, fixed in e6f0c4d5

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1420` is not assigned, can't get performer
