### ISSUE TITLE
Claims are not processed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1433]
0crat may not process `claims.xml` for some time, it always process them after restart and after some time, e.g. claim `Ping` can be submitted 2 hours ago, but processed only now.

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.11`

**Comment by 0crat** [comment]
The job [#1433](https://github.com/zerocracy/farm/issues/1433) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1970810016); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1433` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.15`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1435](https://github.com/zerocracy/farm/issues/1435) is still not solved.

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/1d22118ba00d888ff764312ba2fa95a435ba27b2

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.16`
