### ISSUE TITLE
VsOverElected.java:33-36: VsOverElected may cause...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1435]
The puzzle `1433-9a8228e9` from #1433 has to be resolved:

https://github.com/zerocracy/farm/blob/375d63a08d2cb25d7b745c28075953f36a7c5180/src/main/java/com/zerocracy/pm/staff/votes/VsOverElected.java#L33-L36

The puzzle was created by g4s8 on 16-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1435](https://github.com/zerocracy/farm/issues/1435) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1433-9a8228e9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1435` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1435](https://github.com/zerocracy/farm/issues/1435) is now out of scope
