### ISSUE TITLE
TmZerocrat doesn't have a mock

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1437]
It is right now impossible to test stakeholders that do notifications using telegram because there is no mock implementation.

I would expect a mock implementation that would be returned in tests from `ExtTelegram`. This mock should allow getting list of messages sent, and to whom they were sent to.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk we already have `test` messages for tests, see `apply_to_a_project` bundle test, it uses `test;` token to send all notifications to file `test.txt`, does it solve your issue?

**Comment by krzyk** [comment]
@g4s8 Nice. Yes I think it should

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1437` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
