### ISSUE TITLE
BundlesTest doesn't copy directories to projects

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1438]
Current BundlesTest implementation takes only files that end with `*.xml` and copies them to project/PMO.
But it should look recursively for files with *.xml and all directories that contain xml files, e.g. for options we have a structure like: `options/uid.xml`, this file should be also copied.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by krzyk** [comment]
@g4s8 This one will block all the stakeholders tests for "options" (e.g. https://github.com/zerocracy/farm/issues/1186, https://github.com/zerocracy/farm/issues/1185)

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1438#issuecomment-405849785))

@g4s8 The job [#1438](https://github.com/zerocracy/farm/issues/1438) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1990827272); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (busy on other tasks)

**Comment by 0crat** [comment]
> @0crat wait (busy on other tasks) ([here](https://github.com/zerocracy/farm/issues/1438#issuecomment-406998901))

@carlosmiranda The impediment for [#1438](https://github.com/zerocracy/farm/issues/1438) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@krzyk @g4s8 see PR #1471

**Comment by carlosmiranda** [comment]
@krzyk fixed in #1471, may we close this now?

**Comment by krzyk** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1438](https://github.com/zerocracy/farm/issues/1438) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ebc1688-5162-4130-b08c-36a07c786dac, thread: pool-172-thread-1
com.zerocracy.pm.ClaimsItem[104] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML to 7 existing ones (Agenda was updated;{reason=@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) asked to wait a bit, issue=1179, repo=zerocracy/farm, cause=2061138712, comment=407724182, job=gh:zerocracy/farm#1179, login=carlosmiranda, flow=Register impediment; Impediment was registered};github;zerocracy/farm;1179;407724182,Award points were added;{reason=Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6), issue=1167, minutes=-15, repo=zerocracy/farm, cause=2061138707, comment=407723933, voluntarily=true, job=gh:zerocracy/farm#1167, login=carlosmiranda, flow=Cancel order; Order was canceled; Make payment, points=-15};github;zerocracy/farm;1167;407723933,Complete `QA` review;{comment=407725787, job=gh:zerocracy/farm#1471, issue=1471, quality=acceptable, repo=zerocracy/farm};github;zerocracy/farm;1471;407725787,Complete `QA` review;{comment=407725953, job=gh:zerocracy/farm#1438, issue=1438, quality=good, repo=zerocracy/farm};github;zerocracy/farm;1438;407725953,Notify in GitHub;{issue=1179, repo=zerocracy/farm, cause=2061138711, comment=407724182, job=gh:zerocracy/farm#1179, message=The impediment for [#1179](https://github.com/zerocracy/farm/issues/1179) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda), flow=Register impediment; Notify};github;zerocracy/farm;1179;407724182,Ping;{};,Ping;{};):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="2061145788">
   <created>2018-07-25T11:44:02.623Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:zerocracy/farm#1438</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">1438</param>
      <param name="comment">407725953</param>
   </params>
   <token>github;zerocracy/farm;1438;407725953</token>
   <author>ypshenychka</author>
</claim>

```

[0.27.2](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1438, Comment: 407725953

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ebc1688-5162-4130-b08c-36a07c786dac, thread: pool-172-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML to 7 existing ones (Agenda was updated;{reason=@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) asked to wait a bit, issue=1179, repo=zerocracy/farm, cause=2061138712, comment=407724182, job=gh:zerocracy/farm#1179, login=carlosmiranda, flow=Register impediment; Impediment was registered};github;zerocracy/farm;1179;407724182,Award points were added;{reason=Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6), issue=1167, minutes=-15, repo=zerocracy/farm, cause=2061138707, comment=407723933, voluntarily=true, job=gh:zerocracy/farm#1167, login=carlosmiranda, flow=Cancel order; Order was canceled; Make payment, points=-15};github;zerocracy/farm;1167;407723933,Complete `QA` review;{comment=407725787, job=gh:zerocracy/farm#1471, issue=1471, quality=acceptable, repo=zerocracy/farm};github;zerocracy/farm;1471;407725787,Complete `QA` review;{comment=407725953, job=gh:zerocracy/farm#1438, issue=1438, quality=good, repo=zerocracy/farm};github;zerocracy/farm;1438;407725953,Notify in GitHub;{issue=1179, repo=zerocracy/farm, cause=2061138711, comment=407724182, job=gh:zerocracy/farm#1179, message=The impediment for [#1179](https://github.com/zerocracy/farm/issues/1179) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda), flow=Register impediment; Notify};github;zerocracy/farm;1179;407724182,Ping;{};,Ping;{};):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="2061145788">
   <created>2018-07-25T11:44:02.623Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:zerocracy/farm#1438</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">1438</param>
      <param name="comment">407725953</param>
   </params>
   <token>github;zerocracy/farm;1438;407725953</token>
   <author>ypshenychka</author>
</claim>

com.zerocracy.pm.ClaimsItem[104] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML to 7 existing ones (Agenda was updated;{reason=@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) asked to wait a bit, issue=1179, repo=zerocracy/farm, cause=2061138712, comment=407724182, job=gh:zerocracy/farm#1179, login=carlosmiranda, flow=Register impediment; Impediment was registered};github;zerocracy/farm;1179;407724182,Award points were added;{reason=Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6), issue=1167, minutes=-15, repo=zerocracy/farm, cause=2061138707, comment=407723933, voluntarily=true, job=gh:zerocracy/farm#1167, login=carlosmiranda, flow=Cancel order; Order was canceled; Make payment, points=-15};github;zerocracy/farm;1167;407723933,Complete `QA` review;{comment=407725787, job=gh:zerocracy/farm#1471, issue=1471, quality=acceptable, repo=zerocracy/farm};github;zerocracy/farm;1471;407725787,Complete `QA` review;{comment=407725953, job=gh:zerocracy/farm#1438, issue=1438, quality=good, repo=zerocracy/farm};github;zerocracy/farm;1438;407725953,Notify in GitHub;{issue=1179, repo=zerocracy/farm, cause=2061138711, comment=407724182, job=gh:zerocracy/farm#1179, message=The impediment for [#1179](https://github.com/zerocracy/farm/issues/1179) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda), flow=Register impediment; Notify};github;zerocracy/farm;1179;407724182,Ping;{};,Ping;{};):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="2061145788">
   <created>2018-07-25T11:44:02.623Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:zerocracy/farm#1438</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">1438</param>
      <param name="comment">407725953</param>
   </params>
   <token>github;zerocracy/farm;1438;407725953</token>
   <author>ypshenychka</author>
</claim>

```

[0.27.2](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1438, Action: `created`

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1438#issuecomment-407904944))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1438](https://github.com/zerocracy/farm/issues/1438) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231438%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by carlosmiranda** [comment]
@g4s8 help, I didn't get paid for this :(

**Comment by carlosmiranda** [comment]
@ypshenychka not sure whether you got any points nor payment for this either.

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1438#issuecomment-407953648))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1438](https://github.com/zerocracy/farm/issues/1438) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231438%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@carlosmiranda @g4s8 I didn't receive payment as well.

**Comment by g4s8** [comment]
@0crat pay 20min @carlosmiranda

**Comment by g4s8** [comment]
@0crat pay 8min @ypshenychka

**Comment by g4s8** [comment]
@carlosmiranda @ypshenychka same as here: https://github.com/zerocracy/farm/pull/1471#issuecomment-408013067

**Comment by carlosmiranda** [comment]
@g4s8 already got paid for 20 minutes (got notification from Telegram), but the amount is short by 15 minutes. https://github.com/zerocracy/farm/issues/1438#issuecomment-408018973

**Comment by 0crat** [comment]
Direct payment from @g4s8[/z](https://www.0crat.com/u/g4s8): +20 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Direct payment to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) in #1438, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Direct payment from @g4s8[/z](https://www.0crat.com/u/g4s8): +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Direct payment to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) in #1438, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@0crat pay 15min @carlosmiranda

**Comment by 0crat** [comment]
Direct payment from @g4s8[/z](https://www.0crat.com/u/g4s8): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Direct payment to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) in #1438, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 thanks!
