### ISSUE TITLE
Points for inviting a student are not added

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1444]
According to http://www.zerocracy.com/policy.html#1, examiner will get +32 reputation points if he invites or denies a student.

I haven't received any points when inviting assigned person.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@ypshenychka sorry, it's not implemented yet, will be fixed in #1352

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1444` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by g4s8** [comment]
@ypshenychka because we decided to use new rules and updated the policy, but feature was not implemented. So it's a bug that you didn't receive reputation points, but it was already submitted using 0pdd

**Comment by ypshenychka** [comment]
@g4s8 I see, Thanks for explanation
