### ISSUE TITLE
delete_stale_jobs.groovy:35-41: Cleanup of stale jobs is...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1448]
The puzzle `1414-beb41dc9` from #1414 has to be resolved:

https://github.com/zerocracy/farm/blob/07c10b476fc64c88105291d5a06637840308c8a9/src/main/groovy/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy#L35-L41

The puzzle was created by Carlos Miranda on 19-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1448](https://github.com/zerocracy/farm/issues/1448) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1448](https://github.com/zerocracy/farm/issues/1448) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2202046366); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1414-beb41dc9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1448](https://github.com/zerocracy/farm/issues/1448) is now out of scope

**Comment by krzyk** [comment]
@ypshenychka Did this change help with your agenda cleanup? I'm asking because it didn't in my case, I still see e.g. #1352 (and few others) as assigned to you in my agenda

**Comment by ypshenychka** [comment]
@krzyk Looks like only one redundant task is still in my agenda. #1474 wasn't cleaned up

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
