### ISSUE TITLE
Negligence.java:33-38: Use this metric inside...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1450]
The puzzle `1141-7253381b` from #1141 has to be resolved:

https://github.com/zerocracy/farm/blob/29ca6fb9b6f7e66d05df77178e74695a220b6fe5/src/main/java/com/zerocracy/pmo/Negligence.java#L33-L38

The puzzle was created by rultor on 20-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1450](https://github.com/zerocracy/farm/issues/1450) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1450](https://github.com/zerocracy/farm/issues/1450), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1141-7253381b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1450](https://github.com/zerocracy/farm/issues/1450) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1450](https://github.com/zerocracy/farm/issues/1450) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
