### ISSUE TITLE
Add or remove project to "sandbox"

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1453]
Let's allow to mark project as a "sandbox" project in Slack channel for PMO users (has role in `PMO`). Let's use `@0crat sandbox add|remove` commands to add or remove project to sandbox. Also we need to add `sandbox` flag to `<project>` in `catalog.xml` and use instead of `Catalog.sandbox()` method.

**Comment by 0crat** [comment]
Job [#1453](https://github.com/zerocracy/farm/issues/1453) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1453](https://github.com/zerocracy/farm/issues/1453), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2084](https://github.com/zerocracy/farm/issues/2084) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.6`

**Comment by g4s8** [comment]
Done in #2082

**Comment by 0crat** [comment]
Job [#1453](https://github.com/zerocracy/farm/issues/1453) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1453](https://github.com/zerocracy/farm/issues/1453) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#2084](https://github.com/zerocracy/farm/issues/2084) is solved here.
