### ISSUE TITLE
Award page content is outdated or incomplete

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1456]
I have noticed that my award page is showing outdated or incomplete information.
I believe the total sum of point is correct and coherent with the team page though.

There hasn't been any new award recorded there for 14 days even though I did get some points since that moment. One thing of importance is that the points I got since the last recorded award were tuition fees.

If it is only tuition fees, then I think they should appear on the awards page.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@victornoel can you please refer any job which was not included?

**Comment by victornoel** [comment]
@g4s8 I believe it is the tuition fees that are not included as explained in the description, but maybe the tuition fee themselves does not include points but only money?
If this is the case, I think we can close this issue.

**Comment by g4s8** [comment]
@victornoel correct, you get only cash from your student not points, see https://www.zerocracy.com/policy.html#45

**Comment by victornoel** [comment]
@g4s8 thx for the clarification, I'm closing this

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1456` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
