### ISSUE TITLE
profile.xsl:19-22: When...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1458]
The puzzle `1193-ee91f3f9` from #1193 has to be resolved:

https://github.com/zerocracy/farm/blob/4ae84683c0fc9802f4d04bd7bc3d5e319fd22ad4/src/main/resources/xsl/profile.xsl#L19-L22

The puzzle was created by rultor on 21-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1458](https://github.com/zerocracy/farm/issues/1458) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1193-ee91f3f9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1458` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1458](https://github.com/zerocracy/farm/issues/1458) is now out of scope
