### ISSUE TITLE
Claims.java:50-53: Use Amazon SQS instead of xml files...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1463]
The puzzle `773-d4aeb93a` from #773 has to be resolved:

https://github.com/zerocracy/farm/blob/b9a2c7e41c4aa10220976a0ba3db42f4636b8e50/src/main/java/com/zerocracy/pm/Claims.java#L50-L53

The puzzle was created by g4s8 on 22-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#1463](https://github.com/zerocracy/farm/issues/1463) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2031343349); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1463` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/1463#issuecomment-407087307))

@g4s8 Boost 4x was set for [#1463](https://github.com/zerocracy/farm/issues/1463)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/zerocracy/farm/issues/1463#issuecomment-407114237))

@g4s8 Hey, what's up, how is it going?

**Comment by 0pdd** [comment]
The puzzle `773-d4aeb93a` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.27.2`

**Comment by 0crat** [comment]
Order was finished: +60 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1463](https://github.com/zerocracy/farm/issues/1463) is now out of scope

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/zerocracy/farm/issues/1463#issuecomment-407692651))

@g4s8 Hey, what's up, how is it going?

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1463#issuecomment-407693095))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1463](https://github.com/zerocracy/farm/issues/1463) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231463%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
