### ISSUE TITLE
Flush.java:29-34: Use long-polling for claims instead of...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1464]
The puzzle `773-91937673` from #773 has to be resolved:

https://github.com/zerocracy/farm/blob/b9a2c7e41c4aa10220976a0ba3db42f4636b8e50/src/main/java/com/zerocracy/farm/reactive/Flush.java#L29-L34

The puzzle was created by g4s8 on 22-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1464](https://github.com/zerocracy/farm/issues/1464) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0pdd** [comment]
The puzzle `773-91937673` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1533](https://github.com/zerocracy/farm/issues/1533) is still not solved.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-713-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T14:00:29.075Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1464, Action: `closed`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.7`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.8`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1464#issuecomment-409970912))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1464](https://github.com/zerocracy/farm/issues/1464) is [in scope](http://www.zerocracy.com/policy.html#14) for 11days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [23hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231464%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat out

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.9`

**Comment by g4s8** [comment]
@rultor stop

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1464#issuecomment-409974526))

@g4s8 The job [#1464](https://github.com/zerocracy/farm/issues/1464) is now out of scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.11`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.13`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.3`

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1533](https://github.com/zerocracy/farm/issues/1533) is solved here.
