### ISSUE TITLE
SyncItem.java:29-32: Use external synchronization of...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1465]
The puzzle `773-13f5d30a` from #773 has to be resolved:

https://github.com/zerocracy/farm/blob/b9a2c7e41c4aa10220976a0ba3db42f4636b8e50/src/main/java/com/zerocracy/farm/sync/SyncItem.java#L29-L32

The puzzle was created by g4s8 on 22-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1465](https://github.com/zerocracy/farm/issues/1465) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1465](https://github.com/zerocracy/farm/issues/1465) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2241423127); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1465#issuecomment-413517465))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1465](https://github.com/zerocracy/farm/issues/1465), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1465](https://github.com/zerocracy/farm/issues/1465) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2291052337); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 Of which type of resources are we talking about here? Files?

**Comment by g4s8** [comment]
@paulodamaso `Item`s in `Project` - there will be multiple farm instances which may access same item simultaneously. Now it's solved in `SyncFarm`/`SyncProject` which protect parallel access with help of `Lock` from `java.util.concurrent.locks`, but it won't work for multi-instance application.

**Comment by paulodamaso** [comment]
@g4s8 How could we test this?

**Comment by paulodamaso** [comment]
@g4s8 Apart from testing, I have a suggestion here: we could still use `Lock` but instead of relying on `synchronized` blocks we could set the `Lock` to work with some file in filesystem or some register in `Lock` table `MongoDB`, WDYT?

**Comment by g4s8** [comment]
@paulodamaso I like the idea to reuse existing interfaces, but we can't rely on file in filesystem, because instances may be run on different machines, MongoDB can work.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `773-13f5d30a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1644](https://github.com/zerocracy/farm/issues/1644) is still not solved.

**Comment by 0crat** [comment]
The job [#1465](https://github.com/zerocracy/farm/issues/1465) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1680](https://github.com/zerocracy/farm/issues/1680), [#1681](https://github.com/zerocracy/farm/issues/1681) are still not solved; solved: [#1644](https://github.com/zerocracy/farm/issues/1644).
