### ISSUE TITLE
Claims.java:27-29: Add SQS claims implementation and...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1480]
The puzzle `1436-66b5a846` from #1436 has to be resolved:

https://github.com/zerocracy/farm/blob/a0abaf804d8fbf3b91279f2fed8e436d2388389f/src/main/java/com/zerocracy/pm/Claims.java#L27-L29

The puzzle was created by g4s8 on 24-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1480](https://github.com/zerocracy/farm/issues/1480) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1480](https://github.com/zerocracy/farm/issues/1480) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2060870341); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 could you please create new AWS user with policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl",
                "sqs:ChangeMessageVisibility",
                "sqs:SendMessageBatch",
                "sqs:UntagQueue",
                "sqs:ReceiveMessage",
                "sqs:SendMessage",
                "sqs:GetQueueAttributes",
                "sqs:ListQueueTags",
                "sqs:TagQueue",
                "sqs:ListDeadLetterSourceQueues",
                "sqs:DeleteMessageBatch",
                "sqs:PurgeQueue",
                "sqs:DeleteQueue",
                "sqs:CreateQueue",
                "sqs:ChangeMessageVisibilityBatch",
                "sqs:SetQueueAttributes"
            ],
            "Resource": "arn:aws:sqs:*:*:*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "sqs:ListQueues",
            "Resource": "*"
        }
    ]
}
```
and add credentials for `props.xml`: `sqs.key` and `sqs.secret`?

**Comment by yegor256** [comment]
@g4s8 done. You can create/edit/modify SQS queues that start with `0crat-`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.3`

**Comment by 0pdd** [comment]
The puzzle `1436-66b5a846` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.28.5`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@3b70dd04-85ce-403d-b558-e2b13a0c31a0, thread: pool-17-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-01T17:09:16.008Z"
```

[0.28.4](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1480, Action: `closed`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1532](https://github.com/zerocracy/farm/issues/1532) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1532](https://github.com/zerocracy/farm/issues/1532) is solved here.

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1480#issuecomment-409987910))

@g4s8 The job [#1480](https://github.com/zerocracy/farm/issues/1480) is now out of scope
