### ISSUE TITLE
When 0bot makes a payment it doesn't consider what it owes the DEV

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1491]
Today I received a payment from 0bot for a completed task, however 0bot owes me money for past contribution that isn't going thru because it's a small amount (total $40 more or mess).

I think that, before making a payment, 0bot should check it it owes a DEV money and send everything in a single transaction, to avoid paying unnecessary transaction fees.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
@paulodamaso It is definitely the same, sorry for creating a duplicate and thank you for pointing out

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1491` is not assigned, can't get performer

**Comment by paulodamaso** [comment]
@emilianodellacasa No problem, I've only saw that because the other ticket is assigned to me ;)
