### ISSUE TITLE
0crat ignored a PR

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1496]
After I opened zold-io/java-api#52, 0crat did nothing and simply ignored it.
I had to close and reopen it for it to be taken into account.

I don't know if it is lost event between github and 0crat, or if something else went wrong though.

In the first case, I really think we should do something about making things more robust.
In the second case, I think the situation should have raised some error somewhere.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I haven't seen this for some time so I'm closing this

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1496` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
