### ISSUE TITLE
Code style definition for eclipse

### ISSUE THREAD

**Issue by rgevaerd** [zerocracy/farm#1498]
Is there a code style file to be used in Eclipse for this project? It would be much easier let the Eclipse IDE do most of the code style formatting than have to manually adjust all checkstyle errors.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rgevaerd we are using https://www.qulice.com/ for quality control , you can configure these [rules](https://www.qulice.com/quality.html) for your IDE and share with others if you want, but I don't think that this job is related to this particular project.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1498` is not assigned, can't get performer
