### ISSUE TITLE
Few stakeholder issues

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1500]
There are few issues with groovy code:
1. notify_job.groovy: `farm` is not defined but it is used in the code
2. penalize_for_breakup.groovy: `farm` is not defined but it is used in the code
3. set_parent.groovy: `claim.reply...postTo(pmo)` - can't post to project directly, need to use ClaimsOf
4. purchase_rfp.groovy: `awards.add` called but there is no `awards` defined

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1500](https://github.com/zerocracy/farm/issues/1500) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2102038990); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1500` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@krzyk the puzzle [#1586](https://github.com/zerocracy/farm/issues/1586) is still not solved.

**Comment by g4s8** [comment]
@krzyk I tried to find the way to 'treat warnings as errors' in groovy at compile time, but didn't find anything, so I added todo #1586. These issues was fixed in https://github.com/zerocracy/farm/commit/d3b54072879b3e42eea2205c7ffc3441a7fa31ee, can we close?

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1500](https://github.com/zerocracy/farm/issues/1500) is now out of scope

**Comment by 0pdd** [comment]
@krzyk the puzzle [#unknown]() is still not solved.
