### ISSUE TITLE
No new issues/PRs assigned

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1502]
At least since yesterday there are no new issues/PRs assigned to me in any of the projects, but  my agenda has free space.
It looks like there is a general problem with the elections because PRs in projects are also not assigned, few examples:
1. https://github.com/zerocracy/farm/pull/1501
2. https://github.com/zerocracy/farm/pull/1499
3. https://github.com/Harvest-foundation/telegram/pull/138

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1502](https://github.com/zerocracy/farm/issues/1502) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2110807788); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1502` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@krzyk it's strange looks like `Ping` claim was stopped, but `Ping hourly` and `Ping daily` works fine.

**Comment by g4s8** [comment]
@krzyk fix was merged in #1505, can we close?

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1502](https://github.com/zerocracy/farm/issues/1502) is now out of scope
