### ISSUE TITLE
Crop Blanks, Verbosity, Negligence to 90 days

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1507]
Blanks, Verbosity and Negligence should be cropped to 90 days, similar to reputation and speed of delivery.
This would make all metrics consistent.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1507](https://github.com/zerocracy/farm/issues/1507) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1507](https://github.com/zerocracy/farm/issues/1507), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@krzyk the puzzle [#1996](https://github.com/zerocracy/farm/issues/1996) is still not solved.

**Comment by g4s8** [comment]
@krzyk it was implemented in #1995 - now all metrics will be removed after 90 days

**Comment by 0crat** [comment]
Job [#1507](https://github.com/zerocracy/farm/issues/1507) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1507](https://github.com/zerocracy/farm/issues/1507) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@krzyk the puzzle [#unknown]() is still not solved.
