### ISSUE TITLE
refresh_awards.groovy:40-44: refresh_awards.groovy is...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1508]
The puzzle `1218-6ccd8af1` from #1218 has to be resolved:

https://github.com/zerocracy/farm/blob/14b7f13120002ccd690f3abc3b40ea7f66db0906/src/main/groovy/com/zerocracy/stk/pmo/awards/refresh_awards.groovy#L40-L44

The puzzle was created by Paulo Lobo on 28-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1508](https://github.com/zerocracy/farm/issues/1508) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1508](https://github.com/zerocracy/farm/issues/1508), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1218-6ccd8af1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1508](https://github.com/zerocracy/farm/issues/1508) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
