### ISSUE TITLE
Issue prioritization

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1518]
We should add priorities to issues in projects managed by 0crat bot, maybe as a tag. 

It should be the ARC's job to add a priority (if he/she thinks the issue deserves it) and the bot should assign first the highest priorities ones

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa duplicate of #1183

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1518` is not assigned, can't get performer
