### ISSUE TITLE
Verbosity.java:56-60: Verbosity.add is throwing an...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1519]
The puzzle `1233-8e345196` from #1233 has to be resolved:

https://github.com/zerocracy/farm/blob/893de298a5d54f41f76d92e0eda5c4ab1548ac5f/src/main/java/com/zerocracy/pmo/Verbosity.java#L56-L60

The puzzle was created by rultor on 01-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1519](https://github.com/zerocracy/farm/issues/1519), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1233-8e345196` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1519](https://github.com/zerocracy/farm/issues/1519) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1519](https://github.com/zerocracy/farm/issues/1519) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
