### ISSUE TITLE
Can't receive bonus payment for student graduation

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1520]
We are trying to send bonus payment for student graduation in `remove_mentor_when_graduated.groovy`, this is `PMO` claim and it doesn't belong to any project. But this payment is ignored because `PMO` doesn't accept payment transactions (`PMO` project doesn't have funds and all `make_payment` stakeholders has check `Assume.notPmo`).
@yegor256 what is correct way to send this bonus?

**Comment by g4s8** [comment]
@yegor256 ping, please see this bug

**Comment by yegor256** [comment]
@g4s8 well... I don't know. maybe we should create a new project, something like "HR", fund it and send payment from there?

**Comment by g4s8** [comment]
@yegor256 can't we use `PMO` for that? We can update it's balance on each Zerocracy fee for closing task and then send bonuses.
Also we're using `FkProject` to pay debts:
```groovy
      String pid = new Payroll(farm).pay(
        new Ledger(new FkProject()).bootstrap(),
        uid, debt,
        new Par('Debt repayment, per §46: %s').say(details)
      )
```
it looks not correct, maybe it would be better to send transaction from one project to `PMO` on new debt and then pay debts from `PMO`?

**Comment by yegor256** [comment]
@g4s8 well, we don't have cross-project transactions now, right? We can't send a payment from a project to PMO or the other way around. I guess we can simply allow a negative balance in PMO project and send payments from it.

**Comment by 0crat** [comment]
Job [#1520](https://github.com/zerocracy/farm/issues/1520) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1520](https://github.com/zerocracy/farm/issues/1520), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
was fixed already

**Comment by 0crat** [comment]
Job [#1520](https://github.com/zerocracy/farm/issues/1520) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1520](https://github.com/zerocracy/farm/issues/1520) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
