### ISSUE TITLE
ClaimsSqs.java:39-41: Prevent claims duplication, let's...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1532]
The puzzle `1480-7db2565f` from #1480 has to be resolved:

https://github.com/zerocracy/farm/blob/987780e9517bfb8c965167c4501c08bb35521f01/src/main/java/com/zerocracy/pm/ClaimsSqs.java#L39-L41

The puzzle was created by g4s8 on 02-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0pdd** [comment]
The puzzle `1480-7db2565f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-716-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T14:00:11.272Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1532, Action: `closed`

**Comment by krzyk** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1532#issuecomment-410476853))

@krzyk The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1532#issuecomment-410476853))

@krzyk Job `gh:zerocracy/farm#1532` is not assigned, can't get performer
