### ISSUE TITLE
Expiration time for pings

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1534]
Add expiration time 5 minutes for `Ping` claims as SQS message attribute and add new `Proc` for `ClaimsRoutine` to check this value: if `expiration time >= now()` then skip the claim.

**Comment by 0crat** [comment]
Job [#1534](https://github.com/zerocracy/farm/issues/1534) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/1534#issuecomment-411289099))

@carlosmiranda The impediment for [#1534](https://github.com/zerocracy/farm/issues/1534) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1599

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1606](https://github.com/zerocracy/farm/issues/1606) is still not solved.

**Comment by carlosmiranda** [comment]
@g4s8 #1599 merged, may we close this now?

**Comment by g4s8** [comment]
@carlosmiranda yes, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1534](https://github.com/zerocracy/farm/issues/1534) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1606](https://github.com/zerocracy/farm/issues/1606) is solved here.
