### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1535]
The build is failing due to errors in:

- Travis throws assertion errors in  `com/zerocracy/bundles/add_speed_bonus` and `com/zerocracy/bundles/close_job_with_quality_review`, Appveyor fails at PMD checks in `Pings.java` in https://github.com/zerocracy/farm/pull/1523 and https://github.com/zerocracy/farm/pull/1514
- Appveyor throws NPE in `ClaimOnQuestionTest.buildsClaim:65` in https://github.com/zerocracy/farm/pull/1515

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1535](https://github.com/zerocracy/farm/issues/1535) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@paulodamaso I've fixed PMD checks and commented assertions in failing tests, so the task is to fix these tests: `com/zerocracy/bundles/add_speed_bonus` and `com/zerocracy/bundles/close_job_with_quality_review`

**Comment by paulodamaso** [comment]
@g4s8 I have something to add, the tests doesn't fail when I run them on my windows laptop. They just fail in Travis and Appveyor.

**Comment by g4s8** [comment]
@paulodamaso it was fixed already

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1535` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1535](https://github.com/zerocracy/farm/issues/1535) is now out of scope
