### ISSUE TITLE
Project advisers are not receiving payments

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1536]
According to #546 project's advisers should receive 4% of every project funding operation.
It seems that the task was not fully implmented but was closed. Let's continue to implement it.

**Comment by 0crat** [comment]
Job [#1536](https://github.com/zerocracy/farm/issues/1536) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1536](https://github.com/zerocracy/farm/issues/1536) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2360630301); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 So on every `Recharge project` claims we give 4% of the value to the advisor, correct?

**Comment by g4s8** [comment]
@yegor256 please see https://github.com/zerocracy/farm/issues/1536#issuecomment-415860748, is it correct?

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1658](https://github.com/zerocracy/farm/issues/1658) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso PR #1652 was merged, thanks

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
The job [#1536](https://github.com/zerocracy/farm/issues/1536) is now out of scope

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1536#issuecomment-416215614))

@paulodamaso This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1536](https://github.com/zerocracy/farm/issues/1536) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 60min
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231536%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by yegor256** [comment]
@g4s8 yes, correct, that's what the Policy says (about 4%) or not? If it doesn't, it should.

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#1790](https://github.com/zerocracy/farm/issues/1790), [#1791](https://github.com/zerocracy/farm/issues/1791), [#1792](https://github.com/zerocracy/farm/issues/1792) are still not solved; solved: [#1658](https://github.com/zerocracy/farm/issues/1658).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#1791](https://github.com/zerocracy/farm/issues/1791), [#1792](https://github.com/zerocracy/farm/issues/1792) are still not solved; solved: [#1658](https://github.com/zerocracy/farm/issues/1658), [#1790](https://github.com/zerocracy/farm/issues/1790).
