### ISSUE TITLE
Skip claims loading if workers are busy

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1539]
Let's count busy workers in `BrigadeProc` and check this value in `ClaimsRoutine` - if all workers are busy (busy >= threads in `AsyncProc`) then skip run.

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1539#issuecomment-410227728))

@g4s8 The job [#1539](https://github.com/zerocracy/farm/issues/1539) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2151154400); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #1578

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1578  ([here](https://github.com/zerocracy/farm/issues/1539#issuecomment-412068968))

@krzyk The impediment for [#1539](https://github.com/zerocracy/farm/issues/1539) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1584](https://github.com/zerocracy/farm/issues/1584) is still not solved.

**Comment by g4s8** [comment]
@krzyk PR #1578 was merged, thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.30.1`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1539](https://github.com/zerocracy/farm/issues/1539) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
