### ISSUE TITLE
Transaction can be added to ledger when debts failed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1540]
0crat can add transaction to `ledger.xml` but failed to add debt to `debts.xml` (e.g. due to duplicate debt), see `make_payment.groovy`:
```groovy
    Cash commission = price.mul(3) / 100
    ledger.add(
      new Ledger.Transaction(
        price.add(commission),
        'liabilities', 'debt',
        'assets', 'cash',
        reason + new Par(' (amount:%s, commission:%s)').say(price, commission)
      ),
      new Ledger.Transaction(
        commission,
        'expenses', 'jobs',
        'liabilities', 'debt',
        "${commission} (commission)"
      ),
      new Ledger.Transaction(
        price,
        'expenses', 'jobs',
        'liabilities', "@${login}",
        reason
      )
    )
    Debts debts = new Debts(farm).bootstrap()
    debts.add(login, price, "${reason} at ${job}", ex.message)
```
this is why we can get not-existing transaction in ledger.
Let's add debt first to `debts.xml` and only then add transaction to ledger.
Also we should unit test this code well.

**Comment by 0crat** [comment]
Job [#1540](https://github.com/zerocracy/farm/issues/1540) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1540](https://github.com/zerocracy/farm/issues/1540), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
fixed in https://github.com/zerocracy/farm/commit/d2c93db3d15df88e2e7745ea0c3e1f33e226afa2

**Comment by 0crat** [comment]
Job [#1540](https://github.com/zerocracy/farm/issues/1540) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1540](https://github.com/zerocracy/farm/issues/1540) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
