### ISSUE TITLE
_before.groovy:31-33: Finish implementation of...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1544]
The puzzle `1139-7ab7e83e` from #1139 has to be resolved:

https://github.com/zerocracy/farm/blob/a99ae7aca984ba36cbbb2f96db7775a90f14637c/src/test/resources/com/zerocracy/bundles/notify_in_slack_without_user/_before.groovy#L31-L33

The puzzle was created by Paulo Lobo on 01-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1544](https://github.com/zerocracy/farm/issues/1544) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1544](https://github.com/zerocracy/farm/issues/1544) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/d51e63cf-e6ee-49b6-abfc-7742ed5c8315); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #2276 to be answered

**Comment by 0crat** [comment]
> @0crat wait for #2276 to be answered ([here](https://github.com/zerocracy/farm/issues/1544#issuecomment-619362374))

@victornoel The impediment for [#1544](https://github.com/zerocracy/farm/issues/1544) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/zerocracy/farm/issues/1544#issuecomment-619384940))

@victornoel @victornoel[/z](https://www.0crat.com/u/victornoel) continued working on job [#1544](https://github.com/zerocracy/farm/issues/1544)

**Comment by victornoel** [comment]
@0crat wait for #2277 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #2277 to be merged ([here](https://github.com/zerocracy/farm/issues/1544#issuecomment-619385180))

@victornoel The impediment for [#1544](https://github.com/zerocracy/farm/issues/1544) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `1139-7ab7e83e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2282](https://github.com/zerocracy/farm/issues/2282), [#2283](https://github.com/zerocracy/farm/issues/2283), [#2284](https://github.com/zerocracy/farm/issues/2284) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#unknown](), [#unknown](), [#unknown]() are still not solved.
