### ISSUE TITLE
0crat NumberFormatException on issue close

### ISSUE THREAD

**Issue by rgevaerd** [zerocracy/farm#1551]
A 0crat unrecoverable error occurred here: https://github.com/zerocracy/farm/issues/721#issuecomment-410428205

I guess that due to that error, #721 is not continuing on 0crat workflow.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rgevaerd it's a duplicate of #1537

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1551` is not assigned, can't get performer
