### ISSUE TITLE
assign_examiner.groovy:39-41: On invite we should notify...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1552]
The puzzle `1486-f5becce5` from #1486 has to be resolved:

https://github.com/zerocracy/farm/blob/88ec324cf146458acb3f79c01a279b8245ca9d8b/src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy#L39-L41

The puzzle was created by g4s8 on 04-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1552](https://github.com/zerocracy/farm/issues/1552) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1486-f5becce5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1649](https://github.com/zerocracy/farm/issues/1649) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1552](https://github.com/zerocracy/farm/issues/1552) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1666](https://github.com/zerocracy/farm/issues/1666) is still not solved; solved: [#1649](https://github.com/zerocracy/farm/issues/1649).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666).
