### ISSUE TITLE
optimize assign_performer and elect_performer

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1553]
Stakeholder `assign_performer` is too long for big projects, e.g. in this project it can be completed in ~120 seconds, `elect_performer` is also very long ~50 seconds. Project stats: WBS: 187 items, jobs in `elections.xml`: 963 items, let's optimize election mechanism and make it faster, because it's executing on every `Ping`.

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/1553#issuecomment-410471939))

@g4s8 Boost 4x was set for [#1553](https://github.com/zerocracy/farm/issues/1553)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@carlosmiranda please try to see this bug first, it has high priority (boosted twice)

**Comment by carlosmiranda** [comment]
@g4s8 all right, I'm on it.

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1563

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1563

**Comment by 0crat** [comment]
> @0crat wait for merge of #1563 ([here](https://github.com/zerocracy/farm/issues/1553#issuecomment-410923273))

@carlosmiranda The impediment for [#1553](https://github.com/zerocracy/farm/issues/1553) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1564](https://github.com/zerocracy/farm/issues/1564) is still not solved.

**Comment by carlosmiranda** [comment]
@g4s8 fixed in #1563, may we close this now?

**Comment by g4s8** [comment]
@carlosmiranda sure, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.7`

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +65 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1583](https://github.com/zerocracy/farm/issues/1583) is still not solved; solved: [#1564](https://github.com/zerocracy/farm/issues/1564).
