### ISSUE TITLE
0crat refuses to `out` issues closed by creator

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1555]
0crate refuses to `out` a feature that was closed by 0pdd, stating that:
```
@krzyk/z the issue is closed not by @0pdd/z (its creator); I won't close the order; please, re-open it and ask @0pdd/z to close it
```

Issues in farm (that were closed by 0pdd, but 0crat didn't recognize that after `out` command):
1. https://github.com/zerocracy/farm/issues/1139.
2. https://github.com/zerocracy/farm/issues/1257
3. https://github.com/zerocracy/farm/issues/1226
4. https://github.com/zerocracy/farm/issues/1231

And now issue that was closed by someone else, with similar error:
- https://github.com/zerocracy/farm/issues/1180#issuecomment-410478092

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@g4s8 please take a look, I have some issues in that condition

**Comment by g4s8** [comment]
@krzyk it seems that 0crat didn't close orders for these issues because of #1537 bug, but this message:
```
@krzyk/z the issue is closed not by @0pdd/z (its creator); I won't close the order; please, re-open it and ask @0pdd/z to close it
```
was addressed to you, because you've asked 0crat to close orders with `@0crat out` command, but you was not issue created in that bugs, creator was `@0pdd`, this is why 0crat responded with such message.

**Comment by krzyk** [comment]
@g4s8 should 0crat look at the github closer and not who did `out`?

**Comment by krzyk** [comment]
@g4s8 Oh, in that case this is a different issue - why I was allowed to do it? :)

**Comment by g4s8** [comment]
@krzyk the bug here is that 0crat uses same message when issue was closed by you and if you ask `out`. Response message should be fixed in https://github.com/zerocracy/farm/commit/1945a2aae154fdeebfeaa05ffca8f803b89a2d5c

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1555` is not assigned, can't get performer
