### ISSUE TITLE
Stale entries with inspector in agenda

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1558]
In my agenda I have 3 entries that are stale and should be removed, but weren't:
1. https://github.com/zerocracy/farm/issues/1352
2. https://github.com/zerocracy/farm/issues/1381
3. https://github.com/zerocracy/farm/issues/1471

They were closed and paid, but they still exist in my agenda as under review by QA.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk looks like a duplicate of #1448, isn't it?

**Comment by krzyk** [comment]
@g4s8 yeah

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1558` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
