### ISSUE TITLE
Not receiving REV role

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1560]
Because of a past bug, I lost enough points to see REV role removed from my profile.

Now I have recovered my reputation to 170 and to my knowledge and, to my understanding, I should get the role back but nothing happened after few days have passed.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa sorry, I didn't understand where is the bug, please specify what is not working and what do you expect.

**Comment by emilianodellacasa** [comment]
@g4s8 Never mind, closing this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1560` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
