### ISSUE TITLE
Elections.java:63-77: This 'stylesheet' is not merely a...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1564]
The puzzle `1553-3bca3cf4` from #1553 has to be resolved:

https://github.com/zerocracy/farm/blob/b29fcce0aa5dd6098e55b80f63e14d94b90b8f93/src/main/java/com/zerocracy/pm/staff/Elections.java#L63-L77

The puzzle was created by Carlos Miranda on 07-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1564](https://github.com/zerocracy/farm/issues/1564) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2210957949); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@carlosmiranda both stakeholders `elect_performer` and `assign_performer` are triggered by `Ping` claims, so after election, `assign_performer` just takes all winners from `elections.xm` and start orders for them. It looks like these actions can be chained: `assign_performer` can listen for `Performer was elected` claim, not `Ping` and start the otder for performer from claim parameter `login`. With such implementation `assign_performer` will be much faster, because it will not iterate over WBS and will not try to match election result for each WBS item.
@carlosmiranda @krzyk  What do you think, didn't I miss something?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@g4s8 makes sense for me

**Comment by 0pdd** [comment]
The puzzle `1553-3bca3cf4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1583](https://github.com/zerocracy/farm/issues/1583) is still not solved.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1564#issuecomment-412351578))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1564](https://github.com/zerocracy/farm/issues/1564) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231564%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1564](https://github.com/zerocracy/farm/issues/1564) is now out of scope
