### ISSUE TITLE
Deny command not found

### ISSUE THREAD

**Issue by Vatavuk** [zerocracy/farm#1565]
According to [§1](http://www.zerocracy.com/policy.html#1) examiner can refuse an applicant by issuing the command `deny {user}` to 0crat.
However when I trigger this command 0crat respond with:

```
Can't understand "deny", try one of these:
  - apply Send your profile to the project, intending to join them
  - breakup An opposite command to invite
  - hello Just say hello
  - invite Invite a friend
  - option Change user option
  - quit Immediately exit the project
  - rate Change your current hourly rate
  - rfp Purchase a single RFP, 256 points will be charged
  - vacation Change vacation mode
  - version Print current version of the bot
  - wallet Change your payment information
```

There is no command for refusing candidates..

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Vatavuk** [comment]
@g4s8 Is there a way I can refuse an applicant? I'm not receiving any new applications because I'm stuck on examination process and `deny` command is not working.

**Comment by g4s8** [comment]
@Vatavuk this command is not implemented yet. This issue is a duplicate of #1552

**Comment by Vatavuk** [comment]
@g4s8 ok, closing this

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1565` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @vatavuk[/z](https://www.0crat.com/u/vatavuk) need to have one of these roles in order to do "Remove job from WBS": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
