### ISSUE TITLE
One claim can be processed few times

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1567]
It's possible to process one claim multiple times, the claim has same `cid` and same `signature` it means that this claim was submitted once (it's not possible to submit few claims with same signature to SQS, because this field is used as `DeduplicationId` and it's tested in IT-case), but processed multiple times - this claim exist in footprint (with same `cid`) .

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.8`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 this was a bit tricky. See PR #1587 for the solution.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #1587

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #1587 ([here](https://github.com/zerocracy/farm/issues/1567#issuecomment-412425159))

@carlosmiranda The impediment for [#1567](https://github.com/zerocracy/farm/issues/1567) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1589](https://github.com/zerocracy/farm/issues/1589) is still not solved.

**Comment by g4s8** [comment]
@carlosmiranda PR #1587 was merged, thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.30.2`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1567](https://github.com/zerocracy/farm/issues/1567) is now out of scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.30.3`

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1589](https://github.com/zerocracy/farm/issues/1589) is solved here.

**Comment by g4s8** [comment]
@rultor release, tag=`0.30.4`

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
