### ISSUE TITLE
Resumes.java:31-35: Implement resumes.resume(login),...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1569]
The puzzle `1506-9a48ed63` from #1506 has to be resolved:

https://github.com/zerocracy/farm/blob/71867595574c61f5cf0d0e78a727f51121d9c4c5/src/main/java/com/zerocracy/pmo/Resumes.java#L31-L35

The puzzle was created by Paulo Lobo on 07-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1569](https://github.com/zerocracy/farm/issues/1569) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1569](https://github.com/zerocracy/farm/issues/1569) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2331142016); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1506-9a48ed63` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1645](https://github.com/zerocracy/farm/issues/1645) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1569](https://github.com/zerocracy/farm/issues/1569) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1774](https://github.com/zerocracy/farm/issues/1774) is still not solved; solved: [#1645](https://github.com/zerocracy/farm/issues/1645).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1645](https://github.com/zerocracy/farm/issues/1645), [#1774](https://github.com/zerocracy/farm/issues/1774).
