### ISSUE TITLE
No QA/payment for closed issue; still in Agenda

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#1582]
`0pdd` closed [this](https://github.com/harvest-foundation/telegram/issues/104) issue, then `0crat` promptly removed it from scope. However, no QA was assigned nor performed, I didn't get paid, and it's still in my agenda.

Please take a look.

**Comment by llorllale** [comment]
@victornoel it's no longer in my agenda

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1582` is not assigned, can't get performer
