### ISSUE TITLE
set_parent stakeholder

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1585]
We have `Set parent` stakeholder and `<parent>` element in `catalog.xml`, but the claim with such type is never submitted and xml element is never read.
@yegor256 what is the idea behind this parent elemnt and how it should be used?

**Comment by g4s8** [comment]
@yegor256 done in https://github.com/zerocracy/farm/commit/28f82ca56f89df27d0be05a09e9e94f24e9bfcd5

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1585` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
