### ISSUE TITLE
AsyncProc.java:134-139: This method is too complicated at...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1589]
The puzzle `1567-45090e1f` from #1567 has to be resolved:

https://github.com/zerocracy/farm/blob/e744542d6492cf0924176d16481c7e12edc83c73/src/main/java/com/zerocracy/claims/proc/AsyncProc.java#L134-L139

The puzzle was created by Carlos Miranda on 13-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1567-45090e1f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1589` is not assigned, can't get performer
