### ISSUE TITLE
Refund command for project chat

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1611]
Let's add a new command to project's chat: `refund <charge-id>`, it should refund stripe payment by charge id (see `Stripe.charge()`). Stripe has API for refunds, charge id is required, see https://stripe.com/docs/refunds and https://stripe.com/docs/api#create_refund
This command can be sent only by PO.

**Comment by 0crat** [comment]
Job [#1611](https://github.com/zerocracy/farm/issues/1611) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 I would close this one and continue in #2007 I don't think it's a good idea to refund a specific Stripe payment. Better let's make this operation manual, as #2007 suggests.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1611` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1611](https://github.com/zerocracy/farm/issues/1611) is now out of scope
