### ISSUE TITLE
0crat should advertise ZC?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1615]
For projects where there are not enough contributors, 0crat could do a little advertisement, maybe among top Github Trending developers? For instance, it keeps bugging me [here](https://github.com/amihaiemil/docker-java-api/issues/85) about not having enough contributors.

It would be interesting if 0crat asked Github users if they would like to join Zerocracy and contribute to these under-staffed projects. Or maybe do it for all projects, from time to time. WDYT?

**Comment by g4s8** [comment]
@yegor256 please look at this issue

**Comment by amihaiemil** [comment]
@yegor256 right, I did't think about that. I guess if it does it for only a few users than it's not worth it and if it advertises to many users, it will be spam. 

Closing then...

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1615` is not assigned, can't get performer
