### ISSUE TITLE
BatchClaimsTest.java:33-35: We should use Fake classes...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1622]
The puzzle `1545-78dce506` from #1545 has to be resolved:

https://github.com/zerocracy/farm/blob/8084713cadf4b37f9ecec21bdb644e681247df9c/src/test/java/com/zerocracy/claims/BatchClaimsTest.java#L33-L35

The puzzle was created by Paulo Lobo on 17-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1622](https://github.com/zerocracy/farm/issues/1622) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1622](https://github.com/zerocracy/farm/issues/1622) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2331147236); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 I forgot to remove the todo, so ` 0pdd` won't close the task. What do we do?

**Comment by 0pdd** [comment]
The puzzle `1545-78dce506` has disappeared from the source code, that's why I closed this issue.

**Comment by paulodamaso** [comment]
@g4s8 Thanks!

**Comment by ypshenychka** [comment]
@0crat quality good
