### ISSUE TITLE
new keys

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1629]
I will revoke some access keys and deploy again

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.9`

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1629](https://github.com/zerocracy/farm/issues/1629) is now out of scope
