### ISSUE TITLE
MessageMonitorProcTest was killed

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1633]
I deleted it at https://github.com/zerocracy/farm/commit/a52c61d96703ff2b102921e191774f3a1286423e because it didn't work, see http://www.rultor.com/t/15739-414909435 Let's put it back and make sure it actually compiles and works.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 there was incorrect import (`javafx.utils.Duration` instead of `java.time.Duration`), it was fixed in #1634

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1633` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
