### ISSUE TITLE
ARC release bonuses are not balanced

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1635]
ARC release bonuses doesn't reflect actual amount of work spent by ARC in a project.
Right now it depends on total amount of claims exluding system (`Ping*`, `Notify*`) claims since last release.
I think instead of exluding some claim types we should filter claims by whitelist:
 * `Order was given` (ARC can checks who was assigned to a ticket)
 * `Order was cancelled` (ARC cancel order)
 * `Order was finished` (ARC checks that order was closed correctly)
 * `Request order start` (ARC manually assign performer)
 * `Job removed from WBS` (ARC checks that job was done)
 * `Job was added to WBS` (ARC checks that job is valid)
 * `Quality review completed`  (ARC checks review result)
 * `Register impediment`, `Remove impediment` (ARC checks the job with impediment)
 * `Set boost` (ARC changes boost factor)
 * `Assign role`, `Resign role` - (ARC add/remove new user)
and add new claim to include: `Job was declined` to submit when issue was closed, but not added to WBS.
I think these claims will reflect ARC bonus more correctly and only this claims should be counted in release bonus calculation (the list may be extended later).

@yegor256 please look at this issue, what do you think?

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1635#issuecomment-416291383))

@g4s8 The job [#1635](https://github.com/zerocracy/farm/issues/1635) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2391662346); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1667

**Comment by g4s8** [comment]
@carlosmiranda PR #1667 was merged, thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.1`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1635](https://github.com/zerocracy/farm/issues/1635) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
