### ISSUE TITLE
Wbs.java:42-44: Modify add method to accept user that...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1640]
The puzzle `1159-ca75469b` from #1159 has to be resolved:

https://github.com/zerocracy/farm/blob/5b444ab0764a726f64468137ebe5ce3d32fe4067/src/main/java/com/zerocracy/pm/scope/Wbs.java#L42-L44

The puzzle was created by rultor on 23-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1640](https://github.com/zerocracy/farm/issues/1640) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1640](https://github.com/zerocracy/farm/issues/1640) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/41ee4c97-f17c-4ae7-9b64-478ad9c8eab7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #2193 review

**Comment by 0crat** [comment]
> @0crat wait for #2193 review ([here](https://github.com/zerocracy/farm/issues/1640#issuecomment-547123887))

@paulodamaso The impediment for [#1640](https://github.com/zerocracy/farm/issues/1640) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1640#issuecomment-594547395))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1640](https://github.com/zerocracy/farm/issues/1640), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 3279 hours), see [§6](http://www.zerocracy.com/policy.html#6): -20 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `1159-ca75469b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2279](https://github.com/zerocracy/farm/issues/2279) is still not solved.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1640` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
