### ISSUE TITLE
Add BCH payments

### ISSUE THREAD

**Issue by pinaf** [zerocracy/farm#1651]
Let's add BCC/BCH (bitcoin cash) payments as coinbase already supports them.

**Comment by g4s8** [comment]
@pinaf please see this conversation: https://github.com/zerocracy/farm/issues/980

**Comment by pinaf** [comment]
@g4s8 argh, thanks. so it's either ZLD or waiting for the java implementation for coinbase v2.

**Comment by pinaf** [comment]
@g4s8 they have v2 libraries for php and ruby but not java.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1651` is not assigned, can't get performer
