### ISSUE TITLE
CatalogTest.java:51-53: Board page is slow, load all...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1657]
The puzzle `1333-6882f9fb` from #1333 has to be resolved:

https://github.com/zerocracy/farm/blob/ffcdf7d6d683d04a11aa93ebc9dcb82583789354/src/test/java/com/zerocracy/pmo/CatalogTest.java#L51-L53

The puzzle was created by rultor on 27-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1657](https://github.com/zerocracy/farm/issues/1657) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1657](https://github.com/zerocracy/farm/issues/1657), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1333-6882f9fb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1952](https://github.com/zerocracy/farm/issues/1952), [#1953](https://github.com/zerocracy/farm/issues/1953) are still not solved.

**Comment by 0crat** [comment]
Job [#1657](https://github.com/zerocracy/farm/issues/1657) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 14 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1657](https://github.com/zerocracy/farm/issues/1657) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1952](https://github.com/zerocracy/farm/issues/1952), [#1953](https://github.com/zerocracy/farm/issues/1953), [#1954](https://github.com/zerocracy/farm/issues/1954) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1953](https://github.com/zerocracy/farm/issues/1953), [#1954](https://github.com/zerocracy/farm/issues/1954) are still not solved; solved: [#1952](https://github.com/zerocracy/farm/issues/1952).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
