### ISSUE TITLE
_after.groovy:22-25: Project is not paying adviser when...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1658]
The puzzle `1536-7b5e8444` from #1536 has to be resolved:

https://github.com/zerocracy/farm/blob/c304906679aecd7642afdcf195cb40e332acc774/src/test/resources/com/zerocracy/bundles/pays_adviser_on_funding/_after.groovy#L22-L25

The puzzle was created by Paulo Lobo on 24-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1658](https://github.com/zerocracy/farm/issues/1658), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1536-7b5e8444` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1790](https://github.com/zerocracy/farm/issues/1790), [#1791](https://github.com/zerocracy/farm/issues/1791), [#1792](https://github.com/zerocracy/farm/issues/1792) are still not solved.

**Comment by 0crat** [comment]
Job [#1658](https://github.com/zerocracy/farm/issues/1658) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1658](https://github.com/zerocracy/farm/issues/1658) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.2`

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1791](https://github.com/zerocracy/farm/issues/1791), [#1792](https://github.com/zerocracy/farm/issues/1792) are still not solved; solved: [#1790](https://github.com/zerocracy/farm/issues/1790).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
