### ISSUE TITLE
make_payment is very slow in some projects

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1662]
`make_payment` stakeholder can be completed in 50-60 seconds in some projects (e.g. in Zerocracy). I suppose the reason of this is big `ledger.xml` which is about ~42000 lines here.
```
['com.zerocracy.stk.pm.cost.make_payment' in 'C3NDPUA8L' for claim 'Make payment'] in 51971ms
```
We need to find the reason or prove that it's because of ledger and fix it.

**Comment by 0crat** [comment]
Job [#1662](https://github.com/zerocracy/farm/issues/1662) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1662](https://github.com/zerocracy/farm/issues/1662) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2391615731); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@g4s8 it is the ledger. I created the following test:

```java
    @Test
    public void addsLotsOFTransactions() throws Exception {
        final Ledger ledger = new Ledger(new FkProject()).bootstrap();
        final Stopwatch stopwatch = Stopwatch.createStarted();
        System.out.println();
        for (int i = 0; i < 1000; ++i) {
            stopwatch.reset();
            stopwatch.start();
            ledger.add(
                    new Ledger.Transaction(
                            new Cash.S("$77"),
                            "assets", "cash",
                            "income", "sponsor",
                            "There is some funding just arrived to us"
                    )
            );
            System.out.format("entry %d took %d ms%n", i, stopwatch.elapsed(TimeUnit.MILLISECONDS));
        }
    }
```

On my machine, until around the 130th entryy, each `add` operation takes anywhere from 60 to 100 ms - basically just noise. However, beyond that the size of the ledger becomes noticeable, with each new entry taking an extra 50ms per 100 existing entries. So for example, it takes 300ms to add if the ledger has 600 entries, 500ms if it has 1000 entries, etc.

So, for a project with 42000 entries will take about a minute to add the three new transactions made by `make_payment.groovy`. The machine Zerocracy is on takes 52 seconds to do it, and it's probably a bit faster too.

How do you think we should proceed?

**Comment by g4s8** [comment]
@carlosmiranda I think we can keep only `<balance>` section in `ledger.xml` file and store all transactions in Mongo. @yegor256 what do you think, can we use Mongo for that?

**Comment by yegor256** [comment]
@g4s8 you think Mongo is the right place for financial transactions? Maybe something like PostgreSQL will be a better choice? Heroku can provide that for us.

**Comment by g4s8** [comment]
@yegor256 right, Postgres looks better, can you enable plugin on Heroku for that?

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/1662#issuecomment-419782082))

@carlosmiranda The impediment for [#1662](https://github.com/zerocracy/farm/issues/1662) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by yegor256** [comment]
@g4s8 we already have PostgreSQL enabled there, we use it for the Quartz tasks, remember? You can use the same DB connection. Just make sure you also use Liquibase, in order to create and maintain the DB schema. See how it works in this project, for example: https://github.com/aintshy/hub

**Comment by g4s8** [comment]
@carlosmiranda you've already found the reason of this issue, can you submit a PR with a todo to fix it using Postgres as in https://github.com/zerocracy/farm/issues/1662#issuecomment-422759929 and we will close this task

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1716

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1662](https://github.com/zerocracy/farm/issues/1662) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1764](https://github.com/zerocracy/farm/issues/1764) is still not solved; solved: [#unknown]().

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
