### ISSUE TITLE
elections.xml can be very huge

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1663]
In some projects `election.xml` file is very huge (~0.5Gb), it contains many jobs where all users are banned and completed jobs.
```
Completed ['com.zerocracy.stk.pm.staff.elections.elect_performer' in 'C3NDPUA8L' for claim 'Ping'] in 1251669ms
```

**Comment by 0crat** [comment]
The job [#1663](https://github.com/zerocracy/farm/issues/1663) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2391556503); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1663` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1670](https://github.com/zerocracy/farm/issues/1670) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.31.1`

**Comment by g4s8** [comment]
Done in #1664

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
