### ISSUE TITLE
cleanup_comments.groovy:31-36: cleanup_comments often...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1669]
The puzzle `1570-01eb7ff8` from #1570 has to be resolved:

https://github.com/zerocracy/farm/blob/18028474ccceb6b475fce04897309848127f787b/src/main/groovy/com/zerocracy/stk/internal/cleanup_comments.groovy#L31-L36

The puzzle was created by Paulo Lobo on 27-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1669](https://github.com/zerocracy/farm/issues/1669) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1570-01eb7ff8` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.48.5`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1669](https://github.com/zerocracy/farm/issues/1669), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.48.5`

**Comment by 0crat** [comment]
Job [#1669](https://github.com/zerocracy/farm/issues/1669) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1669](https://github.com/zerocracy/farm/issues/1669) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
