### ISSUE TITLE
_after.groovy:24-26: Elections.remove is not working for...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1670]
The puzzle `1663-4d268a0e` from #1663 has to be resolved:

https://github.com/zerocracy/farm/blob/2fc77cce1ffe63e4cfbef30f50a5812abd1e29ad/src/test/resources/com/zerocracy/bundles/remove_invalid_elections/_after.groovy#L24-L26

The puzzle was created by g4s8 on 27-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1670](https://github.com/zerocracy/farm/issues/1670) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1663-4d268a0e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1670` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1670](https://github.com/zerocracy/farm/issues/1670) is now out of scope
