### ISSUE TITLE
0crat returned all refused jobs

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1671]
After last update, 0crat returned me all recently refused jobs (https://github.com/zerocracy/farm/issues/1533, https://github.com/zerocracy/farm/issues/1347, https://github.com/sunsofterp/portal/issues/128) and even some ones that were stuck in `REV` status for some long time ago (https://github.com/yegor256/takes/pull/836). It can be related to elections changes.
There is no need to take these tasks out from me again, I'll give another shot to them.

Updated in 31/08/2018:
I've refused https://github.com/yegor256/takes/pull/836 in 28/08/2018 for the second time, but 0crat insisted and assigned it to me again in 31/08/2018, see https://github.com/yegor256/takes/pull/836#issuecomment-417820191

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso it looks like a duplicate of #1396

**Comment by paulodamaso** [comment]
@g4s8 transcripted to #1396, closing

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1671` is not assigned, can't get performer
