### ISSUE TITLE
Project got recharged twice

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1672]
A project I was working on got recharged twice:

From Footprint (only showing "Recharge Project" and its triggers "Ping hourly", and "Make payment"):
```
2410937637 15hr "Recharge project" (0.31.1)
  signature: kfqBs8hVT9F/3jBmpTYEknkMfzcImwVo6BdTjsGJnt0=
...
2410942772 15hr "Ping hourly" (0.31.1)
  signature: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
...
2410826977 16hr "Recharge project" (0.31.1)
  signature: kfqBs8hVT9F/3jBmpTYEknkMfzcImwVo6BdTjsGJnt0=
...
2410842113 16hr "Ping hourly" (0.31.1)
  signature: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
...
2410747620 17hr "Make payment" (0.31.1)
  reason: Bug was reported, see [Â§29](http://www.zerocracy.com/policy.html#29)
  role: DEV
  signature: NxD4C+LSBHVu71R0DWbJpAcNT/WpWzYF+MIcl8ID/gc=
  minutes: 15
  login: carlosmiranda
  token: github;January-ai/estimated-gl;17
  _parent_sig: vOpprQCf0Jgx7AZM0dKBckKvaFiOAwhGlTYUQSjSO34=
  job: gh:january-ai/estimated-gl#17
  flow: Add job to WBS; Job was added to WBS
```

The delay between the two is roughly an hour. Notifications came in at 17:35 and 18:29. So it appears that they were both triggered by "Make payment".

The second one should not have occurred since the first "recharge project" event happened an hour ago, and the ledger should have been updated by then. Let's check what's going on.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1672](https://github.com/zerocracy/farm/issues/1672) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2430639132); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1672` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@carlosmiranda it should be fixed in #1676 and release in `0.32.2`, can we close?

**Comment by carlosmiranda** [comment]
@g4s8 seems like recharge is not working? `Zerocracy` project has no funds now. Or is it something else?

**Comment by g4s8** [comment]
@carlosmiranda Zerocracy doesn't have linked Stripe account, it can't be recharged automatically

**Comment by carlosmiranda** [comment]
@g4s8 right, ok. In any case, I'll raise a new issues if I find any new problems. Thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1672](https://github.com/zerocracy/farm/issues/1672) is now out of scope
