### ISSUE TITLE
Elections assigns DEV jobs even if # > maxJobsInAgenda

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1674]
Recently (last few days) I was given few DEV jobs even when my number of jobs is higher than maxJobsInAgenda.

`elect_performer` has correct code (the max shouldn't be used if it is a REV job):
```
(new VsSafe(new VsOptionsMaxJobs(pmo)))                    : role == 'REV' ? 0 : -100,
```

So somewhere else there is a bug that assigns jobs regardless of the limit.
Maybe the `role` is set to REV, even for DEV jobs?

Exampe:
1. https://www.0crat.com/footprint/C3NDPUA8L/2420255490
2. https://www.0crat.com/footprint/C3NDPUA8L/2420254470

EDIT:
Same issue is with `VsNoRoom`, which uses exaclty the same ternary: `role == 'REV' ? 0 : -100`.

Here's a part from election messages:
```
  +0.00=0.00x0 14 jobs out of 24
  +0.00=1.00x0 14 job(s) already, maxJobsInAgenda option is 4
```

But it should be (e.g. in https://www.0crat.com/footprint/C3NDPUA8L/2360533730):
```
  +0.00=0.00x-100 14 jobs out of 24
  +0.00=1.00x-100 14 job(s) already, maxJobsInAgenda option is 4
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by krzyk** [comment]
@g4s8 this one is very annoying, unfortunately I couldn't find the root cause

**Comment by 0crat** [comment]
Job [#1674](https://github.com/zerocracy/farm/issues/1674) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1674#issuecomment-417908229))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1674](https://github.com/zerocracy/farm/issues/1674), see [§21](http://www.zerocracy.com/policy.html#21); @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 16days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@carlosmiranda I don't see this problem anymore, not sure what it was

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by carlosmiranda** [comment]
@krzyk maybe we can close it then

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/1674#issuecomment-422608610))

@carlosmiranda The impediment for [#1674](https://github.com/zerocracy/farm/issues/1674) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/1674#issuecomment-422608610))

@carlosmiranda Job [#1674](https://github.com/zerocracy/farm/issues/1674) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't set impediment

**Comment by krzyk** [comment]
@carlosmiranda I need to check again when I hit the max number of tasks, because recently there weren't any tasks available at all

**Comment by krzyk** [comment]
@carlosmiranda nope, problem still exists, see https://www.0crat.com/footprint/C3NDPUA8L/2621053799 and go to my election results, I got 11 jobs, but my maxJobsInAgenda is set to 10

**Comment by g4s8** [comment]
@krzyk it seems that this bug was fixed and is not reproducing anymore, can we close it?

**Comment by krzyk** [comment]
@g4s8 yes, you are right

**Comment by 0crat** [comment]
Job [#1674](https://github.com/zerocracy/farm/issues/1674) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1674](https://github.com/zerocracy/farm/issues/1674) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)
