### ISSUE TITLE
TkBoard.java:188-190: Right now we are displaying all...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1687]
The puzzle `930-ecca0a03` from #930 has to be resolved:

https://github.com/zerocracy/farm/blob/f77cb9d8630bc77c7c454bdec68f7c3e1c3c5644/src/main/java/com/zerocracy/tk/TkBoard.java#L188-L190

The puzzle was created by Carlos Miranda on 03-Sep-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1687](https://github.com/zerocracy/farm/issues/1687) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `930-ecca0a03` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1687` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1687](https://github.com/zerocracy/farm/issues/1687) is now out of scope
