### ISSUE TITLE
TkTeam.java:66-71: After zerocracy/datum#386 is done...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1692]
The puzzle `1332-94d9282c` from #1332 has to be resolved:

https://github.com/zerocracy/farm/blob/6698915227fb7fc0ebbc7629e004d3fd6a48f5aa/src/main/java/com/zerocracy/tk/TkTeam.java#L66-L71

The puzzle was created by Krzysztof Krason on 06-Sep-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1692](https://github.com/zerocracy/farm/issues/1692) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1692](https://github.com/zerocracy/farm/issues/1692) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2611420365); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@g4s8 could you add https://github.com/zerocracy/datum/issues/386 to `performance` milestone also?

**Comment by 0crat** [comment]
> @0crat waiting for zerocracy/datum#386 to be finished ([here](https://github.com/zerocracy/farm/issues/1692#issuecomment-423572181))

@krzyk Can't understand "waitign", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
> @0crat waiting for zerocracy/datum#386 to be finished ([here](https://github.com/zerocracy/farm/issues/1692#issuecomment-423592775))

@krzyk The impediment for [#1692](https://github.com/zerocracy/farm/issues/1692) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1692#issuecomment-433615198))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1692](https://github.com/zerocracy/farm/issues/1692), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1692](https://github.com/zerocracy/farm/issues/1692), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1332-94d9282c` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.0`

**Comment by 0crat** [comment]
Job [#1692](https://github.com/zerocracy/farm/issues/1692) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1692](https://github.com/zerocracy/farm/issues/1692) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.1`
