### ISSUE TITLE
Recharge project is broken

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1697]
I am on a project now which is well under deficit (cash $78.95, locked funds $128.75). However, it's not being recharged, despite "Recharge project" claims:

```
2492347537 52min "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2492244968 2hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2492145408 3hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2492044847 4hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491955381 5hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491928019 5hr "Recharge project" (0.32.3)
  reason: Order was finished, quality is "acceptable"
  issue: 27
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  minutes: 30
  repo: January-ai/estimated-gl
  login: vatavuk
  token: github;January-ai/estimated-gl;27;419211300
  quality: acceptable
  _parent_sig: 7XW+07ircfi878OMIPwzTKQn1Ni5qR4aOem1OxkDC64=
  comment: 419211300
  job: gh:january-ai/estimated-gl#27
  cash: $15.00
  flow: Complete QA review; Make payment

2491844610 6hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491743024 7hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491642504 8hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491540956 9hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly

2491444536 10hr "Recharge project" (0.32.3)
  signature: /nKAy+2IYI8WusTJDQvDcA0+rj1q8We+l16Ur7uSEJM=
  _parent_sig: UZKC5cry2AA0AOvMSCnKIBmo5q8xCudOY3EglxWeQ00=
  flow: Ping hourly
```

This is the culprit: https://github.com/zerocracy/farm/blob/4bc8f9a1ede13856a41f447df8fdc3d73eddfb5e/src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_project.groovy#L42-L52

Note that based on that code, if there is a "Recharge project" claim that is an hour old _or newer_, it won't recharge. Given that we entered this stakeholder _right after_ seeing a "Recharge project" claim, it won't do anything.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1697#issuecomment-419306287))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1697](https://github.com/zerocracy/farm/issues/1697), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.4`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.32.5`

**Comment by g4s8** [comment]
@carlosmiranda it was fixed, see this claim: https://www.0crat.com/footprint/CC71RLB2B/2500643443

**Comment by carlosmiranda** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#1697](https://github.com/zerocracy/farm/issues/1697) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1697](https://github.com/zerocracy/farm/issues/1697) is now out of scope
