### ISSUE TITLE
Build with tests failed

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1711]
Following the advice of the How to Contribute section [here](https://github.com/zerocracy/farm#how-to-contribute) had caused the build to fail:
```java
java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/freebsd/mongodb-freebsd-x86_64-3.5.5.tgz
```
The mentioned resource is not present. For more information please refer to
the attached build log - [tests-failed.log](https://github.com/zerocracy/farm/files/2396885/tests-failed.log).

I assume that this is specific to running the tests on FreeBSD OS, which I am using on my machine. Is there a chance to work around this by letting tests know that there is a locally available MongoDB under some path in the system?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko can you contribute with a pull-request (I can assign this task to you)? I think there can be maven profile with system properties to specify local mongo for tests. E.g. you put it in your local `~/.m2/settings.xml`:
```xml
<profile>
  <id>localMongo</id>
  <properties>
    <test.mongo.host></test.mongo.host>
   <!-- other props -->
  </peroperties>
</profile>
```
and enable it for your OS in `pom.xml`:
```xml
<profile>
  <id>localMongo</id>
  <activation><os>OS_NAME</os></activation>
</profile>
```
then check it in `ExtMongo`:
```java
if (System.getProperty("test.mongo.host") != null) {
}
```

**Comment by denis-konovalyenko** [comment]
@g4s8 , thanks for replying! Sure, I can make and the proposed changes.

**Comment by g4s8** [comment]
@0crat assign @denis-konovalyenko

**Comment by 0crat** [comment]
> @0crat assign @denis-konovalyenko  ([here](https://github.com/zerocracy/farm/issues/1711#issuecomment-422813652))

@g4s8 The job [#1711](https://github.com/zerocracy/farm/issues/1711) assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2621423090); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by denis-konovalyenko** [comment]
@0crat wait (impediments: #1714 )

**Comment by 0crat** [comment]
> @0crat wait (impediments: #1714 ) ([here](https://github.com/zerocracy/farm/issues/1711#issuecomment-422950676))

@denis-konovalyenko The impediment for [#1711](https://github.com/zerocracy/farm/issues/1711) was registered successfully by @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0pdd** [comment]
@denis-konovalyenko 3 puzzles [#1767](https://github.com/zerocracy/farm/issues/1767), [#1768](https://github.com/zerocracy/farm/issues/1768), [#1769](https://github.com/zerocracy/farm/issues/1769) are still not solved.

**Comment by g4s8** [comment]
@denis-konovalyenko it was fixed in #1713 thanks

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#1711](https://github.com/zerocracy/farm/issues/1711) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0pdd** [comment]
@denis-konovalyenko 3 puzzles [#unknown](), [#unknown](), [#unknown]() are still not solved.
