### ISSUE TITLE
How to properlly setup and run farm in my local environment

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1712]
[The How to contribute section](https://github.com/zerocracy/farm#how-to-contribute) does not help a new starter to properly build, configure and run the project. It is a vital information to get started!

**Building**
What software do I need to have installed and configured in my system (e.g. which database) before running the build process?
What does every of the build options (profiles) mean and what are the cases of their applicability?

**Configuring and running**
How to accurately configure the dependent software (e.g. database)?
Are there any project files which have to be filled in with essential data? Are there any examples of possible configurations then?
What are the running command and its options?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko it is a big work, you'll need to create and configure a lot of AWS services (which may be not free BTW). Why do you need it?

**Comment by denis-konovalyenko** [comment]
@g4s8 , my main concern is that I do not know how to actually verify that, for example, one or another issue has been solved and it has not caused new ones to appear... I assume we are not allowed to debug production, so how I can get into the code execution flow then? Maybe, I have missed something and this is not the way the work has to be done here - could you please point me out in the right direction in this case?

I guess it is no fun for a starter to find out how to set up something on their own for some days. Moreover, as far as I understand, such activity is not recommended or even prohibited in the microtasking approach as it leads to a task scope skyrocketing with all consequential "punishing" things happening.

For now, I think it would be fair to have at least the main parts of the project documented (how to configure them Locally with possible limitations). One more time, this is all about a build on my local machine without entailing any kind of other services if possible (AWS for instance).

**Comment by g4s8** [comment]
@denis-konovalyenko please read this: https://www.yegor256.com/2016/02/09/are-you-still-debugging.html

If you need to prove that some class is working as expected, you can write a unit-test for that class, e.g. see `ExtMongoTest` which has tests for `ExtMongo` class; if you're testing a class which requires external service, you can write integration test, e.g. `ClaimsSqsITCase` connects to AWS SQS service in `setup()` method.

**Comment by g4s8** [comment]
@denis-konovalyenko added some details to README, see https://github.com/zerocracy/farm/commit/449531dae18873c507886d2f71fac17604db82a7

If something is not clear, please submit a ticket about that (you can combine multiple issues about documentation in one ticket)

**Comment by denis-konovalyenko** [comment]
@g4s8 , the changes look good - thanks for your efforts!

Here are more thoughts on the build configuration options. For sure, there are some profiles that affect the build behaviour in one or another way. Would it be possible to say some words about that as well, at least about the mentioned in [the How to contribute section](https://github.com/zerocracy/farm#how-to-contribute)?

Yet another thing for documenting I can think of for now is the ability to run tests with a real MongoDB instance and as a consequence the required configuration settings for the dbs, but this probably has to be in the scope of a separate issue, hasn't it?

**Comment by SergeyKutsko** [comment]
@g4s8 Could you provide template for settings.xml?

**Comment by g4s8** [comment]
@SergeyKutsko we don't have such template

**Comment by SergeyKutsko** [comment]
@g4s8 What a structure of this file?

**Comment by g4s8** [comment]
@SergeyKutsko https://maven.apache.org/settings.html

**Comment by SergeyKutsko** [comment]
thx

сб, 15 дек. 2018 г., 20:43 Kirill notifications@github.com:

**Comment by g4s8** [comment]
@denis-konovalyenko described maven profiles in https://github.com/zerocracy/farm/commit/8613edcae38705ea659766040b19d98c26539b0c
