### ISSUE TITLE
0crat sends ZLD when the specified wallet is for BTC

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1715]
I had set my wallet to BTC, however, 0crat informed me that the fee went to ZLD wallet somehow... For more details please observe my chat with 0crat below.
![sending-zld-when-specified-btc](https://user-images.githubusercontent.com/15904097/45781697-65c81700-bc69-11e8-80b9-9a61449c0419.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko it's a bonus ZLD, we're sending extra ZLD with base payment (with same amount). You BTC payment wasn't sent because it's too small, 0crat accumulates small payments in debts and send them all together when the amount is big enough, see https://www.zerocracy.com/policy.html#46

**Comment by denis-konovalyenko** [comment]
@g4s8 , thank you for the clarification! Wouldn't it be better to state this somewhere in the document then? By the way, does this also mean that I have to set my wallet to ZLD to earn the bonus?

Regarding the accumulation of payments in debts, I knew about that from the policy. Thanks for the direct reference!

**Comment by g4s8** [comment]
@denis-konovalyenko no, you don't need to setup it, you can access it via https://wts.zold.io/
This is a temporary bonus just to attract attention to ZLD, so I don't think it should be placed in a policy.

**Comment by denis-konovalyenko** [comment]
@g4s8 , got it - thanks! Can I close the issue then?

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1715` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
