### ISSUE TITLE
Claims priority

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1717]
The problem: scheduled jobs (aka pings) may produce a high load, every minute election is running for all projects, and job to resign by delay, every hour a lot of routine jobs are started together. If a user tries to send a command in a chat-bot or make some action in github which produces a webhook, while ping jobs are running, this claim (from chat-bot or webhook) will be placed in the end of the queue (which is very big on "pings time") and user may see the response after few minutes.
   
I think that some claims should be processed faster than others, e.g. requests in chat bot to manage users profile or project requires faster response than webhooks processing, but webhooks processing is more important than jobs from pings. So I'm suggesting to add `priority` property to claim structure and process the queue depends on this property. So chat bot requests may have `high` priority, webhook claims - `medium` and ping claims - `low`.

**Comment by g4s8** [comment]
@yegor256 please look at this issue

**Comment by g4s8** [comment]
@yegor256 ping, please look here

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 I like it, let's do it.

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.2`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1717](https://github.com/zerocracy/farm/issues/1717), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1717` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.6`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.12`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.14`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1717#issuecomment-464889655))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1717](https://github.com/zerocracy/farm/issues/1717) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231717%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1717#issuecomment-464896829))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1717](https://github.com/zerocracy/farm/issues/1717) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231717%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
done

**Comment by 0crat** [comment]
Job [#1717](https://github.com/zerocracy/farm/issues/1717) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1717](https://github.com/zerocracy/farm/issues/1717) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
