### ISSUE TITLE
Too many temporary rdfarm files

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1728]
`RdFarm` produces a lot of temporary files on production (e.g. `/tmp/rdfarm5919867088714710480.xml`). Because of that farm app throws `java.nio.file.FileSystemException: No space left on device` after few days of working. We should remove these teporary xml files after using.

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1728#issuecomment-424715894))

@g4s8 The job [#1728](https://github.com/zerocracy/farm/issues/1728) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2691334058); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait, busy on other tasks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e4f8ee5b-3d56-4c0d-a75d-076be7cbe648, thread: pool-116-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: PgLock[free](PMO:ANY)
```

[0.36.2](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1728, Comment: 431553879

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e4f8ee5b-3d56-4c0d-a75d-076be7cbe648, thread: pool-116-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: PgLock[free](PMO:ANY)
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: PgLock[free](PMO:ANY)
```

[0.36.2](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1728, Action: `created`

**Comment by g4s8** [comment]
@carlosmiranda PR #1759 was merged, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1728](https://github.com/zerocracy/farm/issues/1728) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
