### ISSUE TITLE
Incoherent point taking/giving when inviting student

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1733]
I've invited a student: zerocracy both took 128 points from my reputation AND gave me 32 point.

0crat told me I would get 32 point for inviting, not loose so much reputation.

This should be clarifier and fixed so that one or the other happens...

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1733](https://github.com/zerocracy/farm/issues/1733) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2710455796); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1733` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@victornoel PR for policy: https://github.com/zerocracy/zerocracy.github.io/pull/59

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@victornoel PR with fix: #1734

**Comment by g4s8** [comment]
@rultor release, tag=`0.34.4`

**Comment by g4s8** [comment]
@victornoel it was fixed in #1734 PR, can we close?

**Comment by victornoel** [comment]
@g4s8 thanks!
