### ISSUE TITLE
0crat produces too many messages in telegram for payment

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1741]
When I finish a task I usually get 4 (or 3) messages fom 0crat:
- about additional reputation points
- about cash payment
- about zold payment
- about shares payment

It is quite annoying to see so many messages for basically a single transaction.
I would prefer to have those 4 types of messages (and any future messages related to a single transaction for given job) merged into one telegram message.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk it looks like a duplicate of #729

**Comment by krzyk** [comment]
@g4s8 yeah, you are right

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1741` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
