### ISSUE TITLE
0crat assigns free issue without notification nor agenda presence

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1748]
Apparently 0crat assigned an issue to me without notifying me nor adding it to my agenda and on top of that there is no fund for paying it so it's free: https://github.com/zerocracy/farm/issues/915#issuecomment-427338555

I think there is something broken somewhere, I would have expected the 3 following things;
- that if there is no fund, the issue is not assigned at all
- that if it is assigned to me, I am notified explicitly
- that if it is assigned to me, it shows up in my agenda

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I haven't seen this for some time so I'm closing

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1748` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
