### ISSUE TITLE
0crat did not payed ARC for merge

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1752]
0crat did not payed `ARC` for merged PR in https://github.com/yegor256/takes/pull/848

It may be related to the fact that PR was to small and there was no code reviewer.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso as you can see in https://github.com/yegor256/takes/pull/848#issuecomment-428770672 this job was not in WBS, whereas 0crat pays only for "in scope" jobs: https://www.zerocracy.com/policy.html#28

**Comment by paulodamaso** [comment]
@g4s8 this is related to the fact that no reviewer was assigned? Looks like 0crat is not putting small PR on scope to avoid it being added as a review task, but in spite of that `ARC` should receive for closing that PR.

**Comment by g4s8** [comment]
@paulodamaso please look at issue https://github.com/zerocracy/farm/issues/1012
it seems that this issue is a duplicate

**Comment by paulodamaso** [comment]
@g4s8 Right, the rule is in policy, thanks, closing this issue then.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1752` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
