### ISSUE TITLE
make_payment.groovy:40-42: In continuation of #1162, add...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1765]
The puzzle `1162-5bbf3bac` from #1162 has to be resolved: 

https://github.com/zerocracy/farm/blob/079ed29ba854506cf02210af46512bb7ae382379/src/main/groovy/com/zerocracy/stk/pm/cost/make_payment.groovy#L40-L42

The puzzle was created by rultor on 05-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1765](https://github.com/zerocracy/farm/issues/1765) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1765](https://github.com/zerocracy/farm/issues/1765), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1162-5bbf3bac` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.3`

**Comment by 0crat** [comment]
Job [#1765](https://github.com/zerocracy/farm/issues/1765) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1765](https://github.com/zerocracy/farm/issues/1765) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.4`
