### ISSUE TITLE
Slack integration is offline

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1771]
The Slack integration bot has been offline for the past three or four days. I have been trying to bootstrap a new project but unable to do so because of this issue.

![image](https://user-images.githubusercontent.com/1917892/47325329-c9dd6100-d695-11e8-9ef2-4303b316ec2b.png)

![image](https://user-images.githubusercontent.com/1917892/47325656-8126a780-d697-11e8-826a-531695de48ad.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1771](https://github.com/zerocracy/farm/issues/1771), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1771` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@carlosmiranda same for Zerocracy project, related stacktrace: https://sentry.io/zerocracy/farm/issues/728275007
can you send me you project id?

**Comment by carlosmiranda** [comment]
@g4s8 PMed you via Telegram

**Comment by g4s8** [comment]
@rultor release, tag=`0.37.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.37.4`

**Comment by g4s8** [comment]
@carlosmiranda it seems that it was caused by #1760 bug, I temporary replaced `PgLocks` in `Main` with simple locks, now it's working fine for me, can you also check your slack channels?

**Comment by carlosmiranda** [comment]
@g4s8 it's working now. Thanks!

**Comment by 0crat** [comment]
Job [#1771](https://github.com/zerocracy/farm/issues/1771) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add
