### ISSUE TITLE
ResumesTest.java:41-43: Handle resume not found in...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1774]
The puzzle `1645-dc067a6a` from #1645 has to be resolved: 

https://github.com/zerocracy/farm/blob/b9737d55567076a687284e0d1e795e29da6f2b29/src/test/java/com/zerocracy/pmo/ResumesTest.java#L41-L43

The puzzle was created by Victor Noël on 07-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1774](https://github.com/zerocracy/farm/issues/1774) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1645-dc067a6a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1774` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1774](https://github.com/zerocracy/farm/issues/1774) is now out of scope
