### ISSUE TITLE
Receiving notifications for new users not assigned to me

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1775]
When a new user sends a request of invite, I receive a notification on Telegram to accept or reject its application.

However, usually when I try to invite the user, the bot answers that the user is not assigned to me. A couple of times happened that the user was actually assigned to me and I could invite him/her.

So, what's the point in receiving a notification of a user I cannot invite? I think it would be better to just receive notifications on things I can act.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa right, we should send this notification when resume assigned, not on join-form submit. But I'd also send few words to PMO users when form submitted, e.g. `user \@github-account subbmited join form; https://link-to-resume`.

**Comment by 0crat** [comment]
Job [#1775](https://github.com/zerocracy/farm/issues/1775) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@g4s8 Don't forget to add me into list of users that receive all notifications :)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1775](https://github.com/zerocracy/farm/issues/1775), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#1905](https://github.com/zerocracy/farm/issues/1905) is still not solved.

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed with next release, you'll receive only resumes assigned to you.
Notifications about each new resume will receive only PMO users and @ypshenychka

**Comment by emilianodellacasa** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#1775](https://github.com/zerocracy/farm/issues/1775) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1775](https://github.com/zerocracy/farm/issues/1775) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1775#issuecomment-466184619))

@ypshenychka This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1775](https://github.com/zerocracy/farm/issues/1775) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231775%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@emilianodellacasa the only puzzle [#1905](https://github.com/zerocracy/farm/issues/1905) is solved here.
