### ISSUE TITLE
Layout issues on board page

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1778]
There are some layout issues on board page:
![photo_2018-10-26_15-13-32](https://user-images.githubusercontent.com/1524988/47565634-d8e03f80-d931-11e8-82b3-d91f6122617f.jpg)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by olenagerasimova** [comment]
@g4s8 I've just detected similar problems with `team` and `@me` page from on the phone
<img src="https://user-images.githubusercontent.com/14931449/47748024-dca9f400-dc9a-11e8-8c7b-3bcd0dc50e1e.jpg" alt="drawing" width="250"/> <img src="https://user-images.githubusercontent.com/14931449/47748035-df0c4e00-dc9a-11e8-9019-de069f60b1ff.jpg" alt="drawing" width="250"/>

**Comment by yegor256** [comment]
@g4s8 here is the problem: https://github.com/yegor256/tacit/issues/188

**Comment by filfreire** [comment]
@g4s8 I believe we can close this issue now.

**Comment by g4s8** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1778` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1778](https://github.com/zerocracy/farm/issues/1778) is now out of scope
