### ISSUE TITLE
0crat telegram bot should show help on non-commands

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1782]
I just realised the telegram bot stopped answering to messages and now answers to slash commands.

I have talked to it many time in the last weeks and was wondering if it was broken because I never got answers.

I propose that when someone talks to the bot, the help message should be shown to explain how the bot works.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 the bot now behaves as expected, I'm closing this

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1782` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
