### ISSUE TITLE
Join form should not be accessible for unknown users

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1783]
We're using github to identify a user when join form is submitted, user should not be able to see this form before login because it causes redirect to main page on form submit.

**Comment by 0crat** [comment]
Job [#1783](https://github.com/zerocracy/farm/issues/1783) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1783` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1783](https://github.com/zerocracy/farm/issues/1783) is now out of scope
