### ISSUE TITLE
Remind ARCs about regular reports to POs

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1784]
Check this out: https://www.yegor256.com/2015/05/11/software-architect-responsibilities.html

Any PO would expect such a report from an architect, regularly. Let's create a new stakeholder, which will `Notify` each ARC every 14 days that it's time to email a report to the PO, about the situation in a project

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1784](https://github.com/zerocracy/farm/issues/1784), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1784` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 reminders are implemented and configured to ping ARC every 2 weeks

**Comment by 0crat** [comment]
Job [#1784](https://github.com/zerocracy/farm/issues/1784) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1784](https://github.com/zerocracy/farm/issues/1784) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
