### ISSUE TITLE
Error when purchasing a RFP

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1789]
I purchased a RFP and an error happened:

PID: 4@babed9de-7cc6-46c6-a7f5-a828c6af2a1a, thread: AsyncProc-1
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[66] groovy.lang.MissingPropertyException: No such property: owner for class: com.zerocracy.stk.pmo.profile.purchase_rfp

Also, I expected my reputation to _decrease_ of 64 point, but actually it **increased** for the same amount

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1789](https://github.com/zerocracy/farm/issues/1789), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
@emilianodellacasa related stacktrace: https://sentry.io/zerocracy/farm/issues/770260825

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1789` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@emilianodellacasa should be fixed now, see https://github.com/zerocracy/farm/commit/8acf8cc6ee51ec859cdb3d119704ed07c593c9ac

**Comment by emilianodellacasa** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1789](https://github.com/zerocracy/farm/issues/1789) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1789](https://github.com/zerocracy/farm/issues/1789) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.1`
