### ISSUE TITLE
WBS page looks like it doesn't work

### ISSUE THREAD

**Issue by Serranya** [zerocracy/farm#1800]
I am opening the WBS page with my current user (https://www.0crat.com/u/Serranya/wbs)
The page is completly empty. When I try to view the source there is also none there.

I as a user can not know whether this is intentional or a bug.

If it is intentional maybe add a text stating something like "There is nothing currently to see here".
Or remove the WBS button when there is nothing to show.

![grafik](https://user-images.githubusercontent.com/1206309/49004661-07398080-f165-11e8-84c7-50cb0dcf1424.png)

![grafik](https://user-images.githubusercontent.com/1206309/49004677-14ef0600-f165-11e8-9a7c-8f01d0a5f452.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@Serranya it's uncompleted feature, see #1640

**Comment by Serranya** [comment]
Ahh I see. So should I close the ticket?

**Comment by g4s8** [comment]
@Serranya yes please

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1800` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
