### ISSUE TITLE
TkJoinTest.java:38-41: TkJoinTest is not checking if join...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1805]
The puzzle `1568-f8e630b6` from #1568 has to be resolved: 

https://github.com/zerocracy/farm/blob/317bd2c140a0149abfe073597b098927d3d9ea8d/src/test/java/com/zerocracy/tk/TkJoinTest.java#L38-L41

The puzzle was created by paulodamaso on 28-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1805](https://github.com/zerocracy/farm/issues/1805) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat assign @sbzdev

**Comment by 0crat** [comment]
> @0crat assign @sbzdev ([here](https://github.com/zerocracy/farm/issues/1805#issuecomment-496278295))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1805](https://github.com/zerocracy/farm/issues/1805), see [§21](http://www.zerocracy.com/policy.html#21); @sbzdev[/z](https://www.0crat.com/u/sbzdev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1805#issuecomment-496280345))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1805](https://github.com/zerocracy/farm/issues/1805) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [14min](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231805%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment]
@g4s8 hi! please review second commit with fixes the PR's comments & validation issues.

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1805#issuecomment-496405930))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1805](https://github.com/zerocracy/farm/issues/1805) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [14hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231805%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `1568-f8e630b6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1805](https://github.com/zerocracy/farm/issues/1805) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 15 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#1805](https://github.com/zerocracy/farm/issues/1805) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't inspect

**Comment by 0crat** [comment]
The job [#1805](https://github.com/zerocracy/farm/issues/1805) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sbzdev[/z](https://www.0crat.com/u/sbzdev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/1805#issuecomment-496450649))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/1805#issuecomment-496450649))

@sereshqua The project doesn't have enough funds, can't make a payment
