### ISSUE TITLE
@0crat failed to pay and didn't increase debt

### ISSUE THREAD

**Issue by verkhovin** [zerocracy/farm#1808]
I created an issue #1806 which was deserved to be a job so  @0crat awarded 15 minutes to me, this fact is reflected on my awards page. But there is no any notifications about transactions (and i didn't recieved anything). It is seems ok because amount is very small [(§29)](http://www.zerocracy.com/policy.html#46).

But also there is no any records about this transaction in project's [Ledger](https://www.0crat.com/contrib-ledger/C3NDPUA8L), so i do not know if there is any debt to me or not.
I am not sure it is wrong behavior, but it seems I should be notified about any payment attempt and I should see debt to me in the [Ledger](https://www.0crat.com/contrib-ledger/C3NDPUA8L)

Correct me if I'm wrong. Thank you!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@verkhovin[/z](https://www.0crat.com/u/verkhovin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@verkhovin 0crat pays cash or equity only to project members, if you don't have any role in the project 0crat will pay you with reputation points only.

**Comment by verkhovin** [comment]
@g4s8 I got it.Thank you for the answer!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1808` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
