### ISSUE TITLE
0crat failed to pay debt

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1815]
>We tried to pay your debt of $74.55, but failed (Failed to buy at Coinbase); don't worry, we will retry very soon

This is what I received from 0crat 6 minutes ago. My Wallet is configured to Bitcoin.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1815](https://github.com/zerocracy/farm/issues/1815), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1815` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@ypshenychka coinbase deprecated v1 API:
```
Caused by: com.coinbase.api.exception.CoinbaseException: The V1 API has been deprecated
	at com.coinbase.api.CoinbaseImpl.handleErrors(CoinbaseImpl.java:1330)
	at com.coinbase.api.CoinbaseImpl.doHttp(CoinbaseImpl.java:1276)
	at com.coinbase.api.CoinbaseImpl.getBalance(CoinbaseImpl.java:202)
	at com.zerocracy.pmo.banks.Crypto.fund(Crypto.java:131)
	... 85 more
```
and they doesn't have v2 library for java, so it may take some time to implement it using [HTTP API](https://developers.coinbase.com/api/v2).
If possible try to use Paypal wallet until fix.

**Comment by ypshenychka** [comment]
@g4s8 Unfortunately I can't use PayPal :( How long do you think a fix could take?

**Comment by ypshenychka** [comment]
@g4s8 Wouldn't it be easier to connect support for Payoneer? A while ago @yegor256 was looking into it, but I don't know the results.

**Comment by g4s8** [comment]
@ypshenychka I'll try to solve it today

**Comment by g4s8** [comment]
@0crat boost x8

**Comment by 0crat** [comment]
> @0crat boost x8 ([here](https://github.com/zerocracy/farm/issues/1815#issuecomment-445273367))

@g4s8 Argument "x8" doesn't match regex `\d+x`

**Comment by g4s8** [comment]
@0crat boost 8x

**Comment by 0crat** [comment]
> @0crat boost 8x ([here](https://github.com/zerocracy/farm/issues/1815#issuecomment-445275268))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1815](https://github.com/zerocracy/farm/issues/1815), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.1`

**Comment by 0pdd** [comment]
@ypshenychka the puzzle [#1819](https://github.com/zerocracy/farm/issues/1819) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.4`

**Comment by g4s8** [comment]
@ypshenychka yes, I think it should work soon

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.6`

**Comment by g4s8** [comment]
@ypshenychka can we close this?

**Comment by ypshenychka** [comment]
@g4s8 probably it's better to wait and see hot it goes with next debt payment?

**Comment by g4s8** [comment]
@ypshenychka sure, let's wait. BTW I'm receiving BTC paymants successfully

**Comment by ypshenychka** [comment]
@g4s8 Thanks. Payment was made successfully.

**Comment by 0crat** [comment]
The job [#1815](https://github.com/zerocracy/farm/issues/1815) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@ypshenychka the only puzzle [#1819](https://github.com/zerocracy/farm/issues/1819) is solved here.
