### ISSUE TITLE
Coinbase.java:136-139: We're loading all transactions...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1819]
The puzzle `1815-c9e7ebc3` from #1815 has to be resolved: 

https://github.com/zerocracy/farm/blob/3296b04158c0858bc75bb90f7a64958d84eb8621/src/main/java/com/zerocracy/pmo/banks/coinbase/Coinbase.java#L136-L139

The puzzle was created by Kirill on 07-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1819](https://github.com/zerocracy/farm/issues/1819) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1815-c9e7ebc3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1819` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1819](https://github.com/zerocracy/farm/issues/1819) is now out of scope
