### ISSUE TITLE
Problem in paying Zold

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1821]
Apparently payment in Zold is not working correctly, see [here](https://github.com/zold-io/zold/pull/617#issuecomment-445979466)

PID: 4@e837183b-5828-47d4-af8c-cb6d98ed3cd9, thread: AsyncProc-8
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.funding.send_zold
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [emilianodellacasa, $11.75, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[71] groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [emilianodellacasa, $11.75, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by victornoel** [comment]
Same here : https://github.com/yegor256/takes/issues/804#issuecomment-446202379

**Comment by victornoel** [comment]
@g4s8 same here : https://github.com/yegor256/takes/issues/804#issuecomment-446202379

**Comment by g4s8** [comment]
@emilianodellacasa @victornoel it should be fixed with https://github.com/zerocracy/farm/issues/1820

**Comment by emilianodellacasa** [comment]
@g4s8 Ok, I will open a new issue in case the problem appears again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1821` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
