### ISSUE TITLE
0crat not assigning tasks

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1824]
Project `takes`:
- 0crat is not assigning tasks even when some project members have $0 rate. The project does not have funds, but it should assign tasks to people who works for free.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by llorllale** [comment]
@g4s8 I'm having this same issue in `cactoos`

**Comment by paulodamaso** [comment]
@g4s8 ping
