### ISSUE TITLE
Confusion in 0crat and 0pdd integration

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1832]
The ticket is https://github.com/yegor256/jpeek/issues/122 and the PR is https://github.com/yegor256/jpeek/pull/283 :

The issue has been resolved as usual, and after merge 0pdd closed the issue (https://github.com/yegor256/jpeek/pull/283#commitcomment-31735010):
>Puzzle 93-12454465 disappeared from src/test/java/org/jpeek/MetricsTest.java, that's why I closed #122. Please, remember that the puzzle was not necessarily removed in this particular commit. Maybe it happened earlier, but we discovered this fact only now.

Soon after, 0crat informed me that he could not close order because 0pdd should close it (https://github.com/yegor256/jpeek/issues/122#issuecomment-448706836):
>@rultor/z the issue is closed not by @0pdd/z (its creator); I won't close the order; please, re-open it and ask @0pdd/z to close it

And 0pdd stated this message in another related puzzle (https://github.com/yegor256/jpeek/issues/93#issuecomment-448701460):
>@yegor256 the puzzle #121 is still not solved; solved: #122.

Asking job status 0crat told me this:
>@0crat status (here)

>@paulodamaso This is what I know about this job in C7JGJ00DP, as in §32:

>The job #122 is in scope for 3days
The role is DEV
The job is assigned to @Serranya/z for 3days
There is no monetary reward attached, it's a free job
The job doesn't have any impediments
The budget is 30 minutes/points
These users are banned and won't be assigned:
@0pdd/z: This user reported the ticket
Job footprint (restricted area)

I then re-opened it and closed it manuallly. 0crat failed(https://github.com/yegor256/jpeek/issues/122#issuecomment-448827627):
>There is an unrecoverable failure on my side. Please, submit it here:
PID: 4@84dc7f7b-3da2-44bd-8c3f-224d4a698be6, thread: AsyncProc-4
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1: -1 : Duplicate unique value [gh:yegor256/jpeek#122] declared for identity constraint of element "verbosity".
0.39.7: CID: 86784cc7-4423-434f-85ad-3a254dd08054, Type: "Close job"

~~How can I close this issue so the performer get his points?~~

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@g4s8 Looks like opening and closing it manually did the trick. I'll close this issue then.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1832` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
