### ISSUE TITLE
/known/<user-name>

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1835]
Let's add a new HTTP entry point `/known/<user-name>`, which will either return 200, if the user is known to us, or 404 if we don't know him/her. We need this for this feature in Zold: https://github.com/zold-io/wts.zold.io/issues/90

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1835](https://github.com/zerocracy/farm/issues/1835), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1835` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 done in https://github.com/zerocracy/farm/commit/78e5f9c18466c6ac8928e483bcd47a3375660ae2, you can check it with `curl -v https://www.0crat.com/known/yegor256`

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#1835](https://github.com/zerocracy/farm/issues/1835) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1835](https://github.com/zerocracy/farm/issues/1835) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
