### ISSUE TITLE
boost doesn't work

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#184]
Boost command doesn't work, but it has to. We started in #63, but never implemented the user interface. It should work as `@0crat boost 3x`, for example.

**Comment by g4s8** [comment]
@yegor256 #459 was merged, can we close?

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#184](https://github.com/zerocracy/farm/issues/184), please stop working

**Comment by yegor256** [comment]
@0crat boost 2x

**Comment by yegor256** [comment]
@0crat hey

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/zerocracy/farm/issues/184#issuecomment-365620332))

@yegor256 Hey, what's up, how is it going?

**Comment by yegor256** [comment]
@0crat boost 2x

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/184#issuecomment-365629493))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#184](https://github.com/zerocracy/farm/issues/184) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket

**Comment by yegor256** [comment]
@g4s8 thanks (6 months!)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#184` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#184](https://github.com/zerocracy/farm/issues/184) is now out of scope
