### ISSUE TITLE
0crat resigned me from jobs after I quit a projeect

### ISSUE THREAD

**Issue by ammaratef45** [zerocracy/farm#1841]
I quit a project while having 3 tasks (one of them as a REV while it's a known issue with him as I'm not supposed to be a REV)
I must have all three jobs still assigned to me even if I quit but when I tried to tell him I'm waiting for some clarifications from ARCH he told me
@ammaratef45 Job (issue) is not assigned, can't put it on hold

In policy
§35 “Quit.” You can always quit a project, just say quit to Zerocrat. You will still have to finish the jobs assigned to you in the project.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ammaratef45 please add more details:
 - project id or github link
 - job ids or github links

**Comment by ammaratef45** [comment]
@g4s8 
The project is Cactoos (C63314D6Z) , the ticket number 884
You can find the thread [here](https://github.com/yegor256/cactoos/issues/884)

**Comment by g4s8** [comment]
@yegor256 please look here, you did some changes in `quit_project` stakeholder:
05.03.2018 https://github.com/zerocracy/farm/commit/ba7546e85f6d8f568ebbf244d82fb562aa96bc4a#diff-7501549d6d080dc7453ec4cd8ef0f429R45
but didn't update the policy, so current policy version is contradicting your changes:
22.02.2018 https://github.com/zerocracy/zerocracy.github.io/blame/c63d03d013d0436e674fd76b3408b8db6698ea63/_posts/2018/02/2018-02-22-policy.md#L233

so what is the correct behavior here: do we need to cancel all jobs on quit or not?
In first case this job is to update the policy, in second case - change the logic.

**Comment by yegor256** [comment]
@g4s8 I think that we should update the policy. When someone quits, all jobs should be cancelled.

**Comment by g4s8** [comment]
@ammaratef45 @yegor256 see https://github.com/zerocracy/zerocracy.github.io/pull/88

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1841` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
