### ISSUE TITLE
Daily donation limits

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1842]
We are planning to announce Zold at bitcointalks.org, which may lead to a splash of interest. Many people may want to donate via Stripe and that may cause issues with them. That's why, let's configure daily limits. When we render the `/contrib` page, we should fist check via Stripe API what was our daily revenue. If it's over $2048, render another page, saying that "we are sorry, please come back tomorrow or use our [BTC-to-ZLD gateway](https://blog.zold.io/2018/12/09/btc-to-zld.html)".

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1842](https://github.com/zerocracy/farm/issues/1842), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1842` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 would be great if you can fix this ASAP, thanks!

**Comment by g4s8** [comment]
@yegor256 working on it

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.3`

**Comment by llorllale** [comment]
@yegor256 @g4s8 wait, what? Why? What issues?

**Comment by g4s8** [comment]
@yegor256 it should be done in https://github.com/zerocracy/farm/commit/f92238b48cc1e888d9ba835d0f87ef84b0ba9828 and released in `0.40.3`

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#1842](https://github.com/zerocracy/farm/issues/1842) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1842](https://github.com/zerocracy/farm/issues/1842) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
