### ISSUE TITLE
remove BTC payment option

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1843]
Let's get rid of Bitcoin payment option and completely remove the Coinbase gateway. If users want to get paid in crypto, they just get ZLD and then convert ZLD to BTC at wts.zold.io.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 here is the JSON you need when paying in ZLD (to convert USD to ZLD): https://wts.zold.io/rate.json (use `usd_rate` attribute)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1843](https://github.com/zerocracy/farm/issues/1843), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1843` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.43.1`

**Comment by g4s8** [comment]
@yegor256 coinbase payment option was removed

**Comment by 0crat** [comment]
Job [#1843](https://github.com/zerocracy/farm/issues/1843) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1843](https://github.com/zerocracy/farm/issues/1843) is now out of scope
