### ISSUE TITLE
Can't set PayPal wallet: Invalid email

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1848]
I keep trying to set up my PayPal wallet but 0crat keeps telling me that the email address is not valid:

![screenshot_20190113-095718_slack](https://user-images.githubusercontent.com/6305156/51082969-fd221000-1719-11e9-9d5b-5cd101a209b2.jpg)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1848](https://github.com/zerocracy/farm/issues/1848), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1848` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@amihaiemil according to the footprint you're trying to set this value as email address: `<mailto:amihaiemil@gmail.com|amihaiemil@gmail.com>`. It seems you've copied a link to your email from somewhere and Slack app applied formatting. If I'm right, can you try to write email address by yourself without copying links?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@g4s8 yes, I figured the formatting was the problem, but I wrote the address manually so this means Slack converted it to ``mailto:...`` automatically :)

**Comment by amihaiemil** [comment]
@g4s8 Furthermore, it's trange that 0crat can print the email address correctly in the error message: it means that even though it may receive ``mailto:`` HTML, it parses it and obtains the email address after all

**Comment by g4s8** [comment]
@amihaiemil ok, it seems we need to handle such links on 0crat side

> it's strange that 0crat can print the email address correctly in the error message

actually it doesn't, it prints same `<mailto:...>`, but Slack transforms it back to link:
![scrot-2019-01-14-13 36 28](https://user-images.githubusercontent.com/1524988/51107952-9710b800-1801-11e9-9abe-037681caeda2.png)

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.5`

**Comment by g4s8** [comment]
@amihaiemil it was reproduced, fixed in https://github.com/zerocracy/farm/commit/51cdc39d7e164508ec96394a81118714a9efa52d and should be released soon

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.5`

**Comment by amihaiemil** [comment]
@g4s8 nice, thanks :)

**Comment by 0crat** [comment]
Job [#1848](https://github.com/zerocracy/farm/issues/1848) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1848](https://github.com/zerocracy/farm/issues/1848) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
