### ISSUE TITLE
update_precedences.groovy:28-30: let's implement this stakeholder. It...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#185]
The puzzle `166-540fefdb` (from #166) in [`src/main/resources/com/zerocracy/stk/pm/staff/milestones/update_precedences.groovy`](https://github.com/zerocracy/farm/blob/master/src/main/resources/com/zerocracy/stk/pm/staff/milestones/update_precedences.groovy) (lines 28-30) has to be resolved: "let's implement this stakeholder. It will update precedences.xml. The update should occur whenever a GitHub ticket gets assigned to a milestone."

The puzzle was created by Carlos Miranda on 08-Aug-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/185#issuecomment-366430122))

@neonailol The impediment for [#185](https://github.com/zerocracy/farm/issues/185) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by neonailol** [comment]
@yegor256 this puzzle are solved

**Comment by neonailol** [comment]
@yegor256 please close this

**Comment by neonailol** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/185#issuecomment-371895757))

@neonailol This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#185](https://github.com/zerocracy/farm/issues/185) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol) for [27days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @neonailol[/z](https://www.0crat.com/u/neonailol) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23185%27%7D) (restricted area)

**Comment by neonailol** [comment]
@yegor256 ping

**Comment by neonailol** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/185#issuecomment-372366527))

@neonailol The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#185](https://github.com/zerocracy/farm/issues/185), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#185](https://github.com/zerocracy/farm/issues/185) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/750820659). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken ([here](https://github.com/zerocracy/farm/issues/185#issuecomment-373762193))

@amihaiemil The impediment for [#185](https://github.com/zerocracy/farm/issues/185) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@amihaiemil how it's going here? I suppose #819 was fixed already

**Comment by amihaiemil** [comment]
@g4s8 Right, it's been a while since I did DEV work on /farm (I was busy with my projects), but I want to start again. 

I will make a PR for this tonight, with the scaffolding. If you think it's urgent, I can ressign so you assign someone else.

**Comment by g4s8** [comment]
@amihaiemil it's not urgent, just wanted to remind that such ticket exist ;)

**Comment by amihaiemil** [comment]
@g4s8 Where are the ``.groovy`` stakeholders gone? I can't find them anywhere bellow ``src/main/resources``. My IDE also doesn't find anything when I search for ``*.groovy``.

**Comment by g4s8** [comment]
@amihaiemil groovy files were moved to `src/main/groovy`, see: #949

**Comment by amihaiemil** [comment]
@g4s8 I see, thanks

**Comment by 0pdd** [comment]
The puzzle `166-540fefdb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1143](https://github.com/zerocracy/farm/issues/1143) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#185](https://github.com/zerocracy/farm/issues/185) is now out of scope

**Comment by ypshenychka** [comment]
@neonailol According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/185#issuecomment-366430122).

**Comment by amihaiemil** [comment]
@ypshenychka Apparently, ``neonailol`` is not even with us anymore (he is not present on the Team page. I think we can finish here.

**Comment by ypshenychka** [comment]
@amihaiemil I see, thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1143](https://github.com/zerocracy/farm/issues/1143) is solved here.
