### ISSUE TITLE
Add configurable gateways for payments 

### ISSUE THREAD

**Issue by SergeyKutsko** [zerocracy/farm#1852]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@SergeyKutsko please add more details, this issue is unclear
