### ISSUE TITLE
How do I know if I am the examiner?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1855]
Until now, I thought that if I receive a Slack notification about a user's application, I am the examiner. 

However, I recently received such a notification, tried to invite the user and 0crat complained that I am not the allocated examiner.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1855` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.8`

**Comment by g4s8** [comment]
@amihaiemil please check https://www.0crat.com/resumes to see resumes where you are examiner

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.9`

**Comment by amihaiemil** [comment]
@g4s8 thanks :)

**Comment by 0crat** [comment]
Job [#1855](https://github.com/zerocracy/farm/issues/1855) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1855](https://github.com/zerocracy/farm/issues/1855) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
