### ISSUE TITLE
update_milestones.groovy:28-31: let's implement this stakeholder. It...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#186]
The puzzle `166-073320e4` (from #166) in [`src/main/resources/com/zerocracy/stk/pm/staff/milestones/update_milestones.groovy`](https://github.com/zerocracy/farm/blob/master/src/main/resources/com/zerocracy/stk/pm/staff/milestones/update_milestones.groovy) (lines 28-31) has to be resolved: "let's implement this stakeholder. It will update milestones.xml, taking information from GitHub milestones. It has to be triggered by GitHub webhook: when milestones are updated. For each milestone, it has to add gh: prefix to the name found on GitHub."

The puzzle was created by Carlos Miranda on 08-Aug-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#186](https://github.com/zerocracy/farm/issues/186), please stop working

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/186#issuecomment-366430117))

@neonailol The impediment for [#186](https://github.com/zerocracy/farm/issues/186) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0pdd** [comment]
The puzzle `166-073320e4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+600](https://www.0crat.com/u/neonailol)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd this puzzle is still not solved: [609](https://github.com/zerocracy/farm/issues/609)

**Comment by 0pdd** [comment]
@0pdd the last puzzle [#609](https://github.com/zerocracy/farm/issues/609) is solved here.
