### ISSUE TITLE
ZLD payment amount is not correct

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1861]
1 ZLD != 1 USD
we should calculate ZLD amount using https://blockchain.info/ticker to convert USD to BTC and then https://wts.zold.io/rate.json to convert BTC to ZLD.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1861](https://github.com/zerocracy/farm/issues/1861), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1861` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
fixed in https://github.com/zerocracy/farm/commit/b7776451c3bbcb0dab38ea85e4c94043c1e85bc0

**Comment by 0crat** [comment]
Job [#1861](https://github.com/zerocracy/farm/issues/1861) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1861](https://github.com/zerocracy/farm/issues/1861) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
