### ISSUE TITLE
resumes page shows very old resumes which are expected to have expired

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1862]
On the new http://0crat.com/resumes page, I can see lots of old resumes dating from June 2018.

I can't find any information about expiration date for resumes, but the policy says that one can re-apply to 0crat every 16 days (http://www.zerocracy.com/policy.html#1) so I would expect those resumes to have disappeared from my page.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel right, also we have to notify a student when his resume expired

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1862#issuecomment-466086359))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1862](https://github.com/zerocracy/farm/issues/1862), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by g4s8** [comment]
@victornoel it should be fixed with next release

**Comment by victornoel** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1862](https://github.com/zerocracy/farm/issues/1862) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 46 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1862](https://github.com/zerocracy/farm/issues/1862) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
