### ISSUE TITLE
resumes page shows resume from people that have already been accepted to zerocary

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1863]
In the new http://0crat.com/resumes pages, there are resumes from people that I can't invite because they are already in the system.

I would expect those resumes to be removed from the page.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1863](https://github.com/zerocracy/farm/issues/1863), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1863` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by g4s8** [comment]
@victornoel it was fixed with #1862 and #1910

**Comment by victornoel** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1863](https://github.com/zerocracy/farm/issues/1863) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1863](https://github.com/zerocracy/farm/issues/1863) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
