### ISSUE TITLE
0crat did not removed task on issue close

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1864]
I've closed an issue, but 0crat neither did removed it from scope nor paide the developer on closure, see https://github.com/yegor256/takes/issues/893#issuecomment-456473514

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@g4s8 looked like a performance problema, there's no bug, sorry

**Comment by g4s8** [comment]
@paulodamaso yes, firstly we have a delay of 15 minutes, so when you close a ticket 0crat will see the claim only 15 minutes later, it was made intentionally, so if you closed a ticket by mistake you can reopen it in 15 minutes and 0crat will ignore it.
And we have some performance issues too.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1864` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@g4s8 Thanks for the explanation, I did not knew about this 15 minute delay. Shouldn't it be documented somewhere?
