### ISSUE TITLE
Student should see how to contact mentor

### ISSUE THREAD

**Issue by korthout** [zerocracy/farm#1870]
According to the FAQ page
> If you have any non-technical questions, ask your mentor.

The mentor's zerocrat page only shows the Github user associated to the mentor, but no way to contact the mentor. A student should be able to contact the mentor. A possible solution would be to show the Telegram account associated to the mentor, only visible to the student.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@korthout[/z](https://www.0crat.com/u/korthout) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@korthout thanks for reporting, but it's a duplicate of #1828

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1870` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
