### ISSUE TITLE
PgLocks.java:30-31: Implement ReadWriteLock in PgLock and...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1872]
The puzzle `1706-2d297284` from #1706 has to be resolved: 

https://github.com/zerocracy/farm/blob/4a62a3abf3f4e26e290776e2ca4032bc4ab00da1/src/main/java/com/zerocracy/farm/sync/PgLocks.java#L30-L31

The puzzle was created by Kirill on 27-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1872](https://github.com/zerocracy/farm/issues/1872) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `1706-2d297284` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1872](https://github.com/zerocracy/farm/issues/1872) is now out of scope
