### ISSUE TITLE
Error on zerocracy on Team page

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1873]
While assigning a QA in a private project, this error appeared

PID: 4@a9471c69-e56c-4d9f-9493-18c6abad9f91, thread: pool-104-thread-1
com.zerocracy.farm.sync.SyncProject[98] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock@3a613201[Unlocked]

Also, Tem page is down:

https://www.0crat.com/team

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
@g4s8 Solved now, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1873` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
