### ISSUE TITLE
Problems to invite a student

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#1876]
When I try invite a student (I'm using the command `/invite student-github-login` I receive the following error:

![image](https://user-images.githubusercontent.com/1964562/51914824-71b2ab00-23b8-11e9-8c72-aad4298204c9.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@fabriciofx right, we should show a message that "there is no such student with username {username}" instead of stacktrace

**Comment by 0crat** [comment]
Job [#1876](https://github.com/zerocracy/farm/issues/1876) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by g4s8** [comment]
@fabriciofx it should be fixed with next release

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1876` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1876](https://github.com/zerocracy/farm/issues/1876) is now out of scope
