### ISSUE TITLE
Lack of a feedback when send a job application

### ISSUE THREAD

**Issue by kaldown** [zerocracy/farm#1879]
Yesterday I fill and sent a job application form.
There were problems with application, which was discussed in telegram channel:
```
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@de00ab27-a2e4-4101-8382-b09a2841d519, thread: AsyncProc-2
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/resumes/resume[@login='kaldown']/examiner/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<resumes ..91241../telegram>\uA   </resume>\uA</resumes>\uA': Index (0) is out of bounds (size=0)


0.40.15 (https://github.com/zerocracy/farm): CID: 27cda280-d926-44ae-b923-e5fcee8159b3 (https://www.0crat.com/footprint/PMO/27cda280-d926-44ae-b923-e5fcee8159b3), Type: "Invite a friend"
```
After that - no response what so ever.

I think it's would be nice to give a feedback to an applicant about the reason he(she) was rejected.
To fix problems and be better prepared next time.
Otherwise, it would be infinite cycle (or luck ass a matter).

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1879` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@kaldown should be fixed in https://github.com/zerocracy/farm/commit/17b712aad23059fd3bfeff9d7e82d8629dad42d3
now the reason is required for `deny` command

**Comment by 0crat** [comment]
Job [#1879](https://github.com/zerocracy/farm/issues/1879) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1879](https://github.com/zerocracy/farm/issues/1879) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
