### ISSUE TITLE
Link to resumes page should be added to the main dashboard page

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1881]
STR:
1. Log in to www.0crat.com
2. Navigate to your dashboard page

Actual Result: no link to resumes page. Currently if team member doesn't see message in telegram chat or issues in this repository - he won't know that this page exists.

Expected Result: next to "agenda", "team" etc. new link should be added that will redirect to  https://www.0crat.com/resumes

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 also why is the page named `/resumes` while all the other pages related to my user are under `/u/victornoel`?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1881](https://github.com/zerocracy/farm/issues/1881), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1881` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@rultor release, tag=`0.43.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.43.5`

**Comment by g4s8** [comment]
@ypshenychka @victornoel moved resumes page to `/u/login/resumes` (added fallback for `/resumes`), added link to filter `all` resumes and `my` resumes for @ypshenychka

**Comment by ypshenychka** [comment]
@g4s8 Thanks. Closing it.

**Comment by 0crat** [comment]
Job [#1881](https://github.com/zerocracy/farm/issues/1881) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1881](https://github.com/zerocracy/farm/issues/1881) is now out of scope
