### ISSUE TITLE
Allow someone who was kicked out sandbox project for reached more than 1024 points, return if he/she want to

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#1882]
@yegor256 @g4s8 Let's allow someone who was kicked out sandbox project for reached more than 1024 points, return if he/she want to. WDYT?

**Comment by fabriciofx** [comment]
@yegor256 @g4s8 A suggestion: the *veteran* who choose return to a sandbox will work for free, but will just receive points.

**Comment by g4s8** [comment]
@fabriciofx it's a duplicate of #2030

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1882` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
