### ISSUE TITLE
Replace the role of "QA" with a "Tester" role in the policy

### ISSUE THREAD

**Issue by filfreire** [zerocracy/farm#1889]
@g4s8 and @yegor256, I propose we change the naming of the current "QA" role to something more appropriate, like `Tester (TST)` taking into account the current description of the role in the [policy](http://www.zerocracy.com/policy.html#35).

There is a difference between what is quality assurance, quality control and testing, fairly documented throughout many sources of expertise in the testing craft. (Examples of books where this difference is discussed: [Lessons Learned in Software Testing](https://www.goodreads.com/book/show/599997.Lessons_Learned_in_Software_Testing) and [Testing Computer Software](https://www.goodreads.com/book/show/663621.Testing_Computer_Software)).

There's also a [podcast](https://www.yegor256.com/shift-m/2017/13.html) done by @yegor256 also looking into the difference between the role of a tester and the role of someone who works on "Quality Assurance".

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@filfreire we already has different roles: `QA` and `TST`. `QA` checks the quality of each job according to these rules: https://www.zerocracy.com/policy.html#42 `QA` doesn't test the software somehow, but `TST` does, `TST` gets cash for bug-reporting.

**Comment by filfreire** [comment]
@g4s8 should we document the `TST` role in the policy then? (It seems missing)

**Comment by g4s8** [comment]
@filfreire please see https://github.com/zerocracy/zerocracy.github.io/pull/71

**Comment by filfreire** [comment]
@g4s8 ok 👍 
Closing this issue then.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1889` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
