### ISSUE TITLE
election results must be randomized

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#189]
Look at this one, for example:

```
@yegor256 (-100.00 of -2100):
  -100.00=1.00x-100 There are 11 open jobs already
  0.00=0.00x-1000 There are no bans
  0.00=0.00x-1000 
@carlosmiranda (0.00 of -2100):
  0.00=0.00x-100 There are just 5 open jobs
  0.00=0.00x-1000 There are no bans
  0.00=0.00x-1000 
@caarlos0 (0.00 of -2100):
  0.00=0.00x-100 There are just 5 open jobs
  0.00=0.00x-1000 There are no bans
  0.00=0.00x-1000 
@g4s8 (-1100.00 of -2100):
  -100.00=1.00x-100 There are 11 open jobs already
  -1000.00=1.00x-1000 Banned from this job because: This user reported the ticket
  0.00=0.00x-1000 
@fabriciofx (-100.00 of -2100):
  -100.00=1.00x-100 There are 7 open jobs already
  0.00=0.00x-1000 There are no bans
  0.00=0.00x-1000 
```

Looks like we have two winners here: carlosmiranda (0 points) and caarlos0 (0 points). But all tasks are assigned to the first one in the list (carlosmiranda). It's wrong. We must randomize the final list, if all winners have the same amount of points.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#189](https://github.com/zerocracy/farm/issues/189), please stop working

**Comment by 0crat** [comment]
The job [#189](https://github.com/zerocracy/farm/issues/189) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting #517

**Comment by 0crat** [comment]
> @0crat waiting #517 ([here](https://github.com/zerocracy/farm/issues/189#issuecomment-364481505))

@g4s8 The impediment for [#189](https://github.com/zerocracy/farm/issues/189) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 added random voter in #517, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.21`

**Comment by g4s8** [comment]
@yegor256 seems to be working: https://www.0crat.com/footprint/C3FFK3YAY/460913167

**Comment by yegor256** [comment]
@g4s8 yes, thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4015](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#189](https://github.com/zerocracy/farm/issues/189) is now out of scope
