### ISSUE TITLE
Wallet on a project basis

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1891]
It would be awesome if users could define the payment method on a project basis, the same that is for the rate - that is, having a default one and one depending on the project.

That could allow people to work on paid projects and on sandbox (or open source) projects at the same time.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa you can set different rates for different projects (https://www.zerocracy.com/policy.html#13), doesn't it solve the issue? ARC of sandbox project can set zero rate for sandbox project for example. Payment method is not about the project, it's a gateway for receiving cash, which should be configured by user itself.

**Comment by emilianodellacasa** [comment]
@g4s8 True, however I may want to work for ZLD in a project and for USD in another (actually it's my case)

**Comment by g4s8** [comment]
@emilianodellacasa we've removed wallets functionality from 0crat and fully moved it to https://wts.zold.io, so this ticket is not valid anymore.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1891` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
