### ISSUE TITLE
PR can be assigned as DEV job

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1892]
When `ARC` assign performer for pull request manually 0crat sets the boost as 2x and put to scope as `REV` job. E.g.: https://github.com/timelesslounge/timelessis/pull/137
// cc @emilianodellacasa

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1892](https://github.com/zerocracy/farm/issues/1892), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1892` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1893](https://github.com/zerocracy/farm/issues/1893) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.41.1`

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed in `0.41.1`

**Comment by 0crat** [comment]
Job [#1892](https://github.com/zerocracy/farm/issues/1892) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1892](https://github.com/zerocracy/farm/issues/1892) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
