### ISSUE TITLE
Only pay ARC when branch is merged

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1897]
It may happen that a PR is created by a DEV and assigned to a REV but then, for some reason, DEV decides to close it without notice.

I noticed that in this case ARC gets the payment and I think this is not correct, ARC should be paid only if PR is merged

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa you're right, according to policy ARC should receive 10min only for merged PRs: https://www.zerocracy.com/policy.html#28

**Comment by 0crat** [comment]
Job [#1897](https://github.com/zerocracy/farm/issues/1897) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#1989](https://github.com/zerocracy/farm/issues/1989) is still not solved.

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed in #1987

**Comment by emilianodellacasa** [comment]
@g4s8 great, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1897` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1897](https://github.com/zerocracy/farm/issues/1897) is now out of scope

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#unknown]() is still not solved.
