### ISSUE TITLE
Payment to wallet ZLD disappeared :(

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1901]
I was expecting a payment to my ZLD wallet from Zerocracy, but now I can't see those payments in my debts (so supposedly Zerocracy should have been made the payment), but I cannot see it in my wallet 25e0819b40cf7eb6 .

For your reference, I cannot even see the payment on the new General Ledger https://wts.zold.io/gl

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa related #1902

**Comment by emilianodellacasa** [comment]
@g4s8 is this fixing payment problem too?

**Comment by g4s8** [comment]
@emilianodellacasa no, it will fix only log message after success payment. The main issue is that we can't track Zold payments because they doesn't have any id, see https://github.com/zold-io/wts.zold.io/issues/139

**Comment by yegor256** [comment]
@emilianodellacasa this seems to be the bug in Farm. It has to check the status of the job before confirming that the payment has been successfully sent.

**Comment by emilianodellacasa** [comment]
@g4s8 @yegor256 whom can I request a refund to? Zerocracy?

**Comment by g4s8** [comment]
@emilianodellacasa Zold didn't process this payment, so I'm going to add your debt back.

**Comment by emilianodellacasa** [comment]
@g4s8 Thanks

**Comment by g4s8** [comment]
@yegor256 it seems wts API changed and now it requires `keygap` parameter, could you please add it to `props.xml` file under `/zold/keygap` xpath?

**Comment by g4s8** [comment]
@yegor256 I added `keygap` property for `_props.xml` (see https://github.com/zerocracy/farm/commit/f154bcb654e0654bfc180318a8407b747fe76f71) can you add keygap value for props?

**Comment by g4s8** [comment]
@yegor256 ping, please see https://github.com/zerocracy/farm/issues/1901#issuecomment-466023527

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1901](https://github.com/zerocracy/farm/issues/1901), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@g4s8 this is what we have in the file now:

```
        <zold.login>0crat</zold.login>
        <zold.token>0crat-0798db7d......366b4f30</zold.token>
        <zold.keygap>...</zold.keygap>
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.7`

**Comment by g4s8** [comment]
@emilianodellacasa @yegor256 now it's working, I just received debt payment via Zold.

**Comment by 0crat** [comment]
Job [#1901](https://github.com/zerocracy/farm/issues/1901) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1901](https://github.com/zerocracy/farm/issues/1901) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
