### ISSUE TITLE
0crat bot often skip message to QA

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1904]
Recently it is happening often that as soon as an issue is closed, QA is not notified about it in the messages.

However, the issue correctly states that is waiting for QA to review the job.

Example: https://github.com/timelesslounge/timelessis/issues/57#issuecomment-466027697

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1904](https://github.com/zerocracy/farm/issues/1904) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
It seems that 0crat failed to notify because can't find the job in agenda https://github.com/timelesslounge/timelessis/issues/57#issuecomment-465964810

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@g4s8 It happens really often last days. More often than ever. And it's really uncomfortable.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#1908](https://github.com/zerocracy/farm/issues/1908) is still not solved.

**Comment by g4s8** [comment]
@emilianodellacasa @ypshenychka I added temporary workaround to post this message before actual bug reproduced and todo to fix it later. It will be availabel with next release.

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.42.2`

**Comment by 0crat** [comment]
Job [#1904](https://github.com/zerocracy/farm/issues/1904) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1904](https://github.com/zerocracy/farm/issues/1904) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
