### ISSUE TITLE
GlobalInviters.java:30-32: Reimplement this class - it...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1905]
The puzzle `1775-79469cb7` from #1775 has to be resolved: 

https://github.com/zerocracy/farm/blob/0c0935de1b65ec3ed3dc4d22bd496392395cc64c/src/main/java/com/zerocracy/pm/staff/GlobalInviters.java#L30-L32

The puzzle was created by @g4s8 on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1905](https://github.com/zerocracy/farm/issues/1905) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1905](https://github.com/zerocracy/farm/issues/1905), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1775-79469cb7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1905](https://github.com/zerocracy/farm/issues/1905) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 14 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1905](https://github.com/zerocracy/farm/issues/1905) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
