### ISSUE TITLE
Remove application expired message when user has been accepted

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1910]
A couple of people asked me why they were receiving an "application expired" message even though they were accepted on Zerocracy.

I think this message should be removed (and should be a very easy task to do) as it is confusing for newbies.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa it seems that 0crat is not removing resume when someone invites a student.

**Comment by 0crat** [comment]
Job [#1910](https://github.com/zerocracy/farm/issues/1910) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@emilianodellacasa reproduced and fixed in https://github.com/zerocracy/farm/commit/6a3e3f5deae4dcc8bfc6d689251b023712c531cf

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1910` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1910](https://github.com/zerocracy/farm/issues/1910) is now out of scope
