### ISSUE TITLE
Tacit is Invisible/Unpublished?

### ISSUE THREAD

**Issue by filfreire** [zerocracy/farm#1915]
@g4s8, @yegor256 for some reason Tacit (`Tacit/C7BNDNSNR`) is set as `Invisible`. Why is this the case?

<img width="354" alt="screen shot 2019-03-01 at 00 30 11" src="https://user-images.githubusercontent.com/11976836/53605927-383cad80-3bb9-11e9-9b56-4fb15498d9b5.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by filfreire** [comment]
@g4s8 closing this issue.

Solution is: ARC needs to publish the project.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1915` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
