### ISSUE TITLE
Agenda Error - Added 7 days in all my jobs

### ISSUE THREAD

**Issue by marceloamadeu** [zerocracy/farm#1916]
Added 7 days to each of my jobs.

In the agenda shows with 8 days and in issue is 18 hours.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1916` is not assigned, can't get performer
