### ISSUE TITLE
No spaces in the language list on the board

### ISSUE THREAD

**Issue by wholegroup** [zerocracy/farm#1919]
There are no spaces in the language list on the board. It looks like one long single word for an html rendering engine. In some cases it can breaks the layout.

![image](https://user-images.githubusercontent.com/553191/53655917-113eb400-3c6b-11e9-8477-e03922e676cb.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1919` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
