### ISSUE TITLE
Unsupported payment methods have to be removed from Policy

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1920]
>We tried to pay your debt of $76.97, but failed (@ypshenychka/z has an unsupported payment method "btc"); don't worry, we will retry very soon

However in [Policy](http://www.zerocracy.com/policy.html#20) we still have mentioned Bitcoin as a payment method.

Policy has to be either updated, or it's bug with BTC payments not working.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 executing `/wallet` command with 0crat bots gives this answer:
```
Option <wallet> is missing in wallet <bank> <wallet>:
  * <bank>: Bank, like "paypal|btc|bch|eth|ltc|zld"
  * <wallet>: Technical payment details, e.g. PayPal email or Bitcoin wallet number or Zold address

Remember, this chat is for managing your personal profile; to manage a project, please open or create a new Slack channel and invite the bot there.
```

Since only paypal and zold are left in the policy, this should be reflected here too.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1920](https://github.com/zerocracy/farm/issues/1920), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1920` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@ypshenychka @victornoel thanks, it should be fixed now:
 - policy update: https://github.com/zerocracy/zerocracy.github.io/pull/69
 - wallet command update: https://github.com/zerocracy/farm/commit/e77238ed4c0b752092002894f0bdfee33af9c9c6

**Comment by 0crat** [comment]
Job [#1920](https://github.com/zerocracy/farm/issues/1920) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1920](https://github.com/zerocracy/farm/issues/1920) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
