### ISSUE TITLE
/known page to return more details

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1923]
This page returns 200 or 404: https://www.0crat.com/known/yegor256

Would be great to make it return JSON document (in case of success):

```json
{
  "login": "yegor256",
  "reputation": 1234,
  "identified": true
}
```

We need this information for WTS in Zold.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1923](https://github.com/zerocracy/farm/issues/1923), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 it was implemented in https://github.com/zerocracy/farm/commit/7173d45dfe260fa1c49002429ec436e2b88d03d0 and will be available with next release

**Comment by 0crat** [comment]
Job [#1923](https://github.com/zerocracy/farm/issues/1923) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1923](https://github.com/zerocracy/farm/issues/1923) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
