### ISSUE TITLE
One zold payment is missing in wallet

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1924]
I didn't receive actual payment for https://github.com/timelesslounge/timelessis/pull/445.

Although it was mentioned on the chat
![image](https://user-images.githubusercontent.com/11703257/53713284-08a8d200-3e53-11e9-8a8c-e0ca487b1afe.png)

I don't see it on the list in my wallet.
![image](https://user-images.githubusercontent.com/11703257/53713316-25450a00-3e53-11e9-97df-75ecd2102f29.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@ypshenychka please submit it here: https://github.com/zold-io/wts.zold.io/
0crat is sending ZLD via WTS API, so if you can see your payment in WTS Telegram channel it means that 0crat did send the payment correctly.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1924` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
