### ISSUE TITLE
Pay through PayPal while being in Ukraine is broken

### ISSUE THREAD

**Issue by ekondrashev** [zerocracy/farm#1925]
Zerocrat complains it fails to pay a debt with a following details:
```
java.io.IOException Failed to pay through PayPal: ERROR APPLICATION The email account Receiver not in receive money enabled country is based in a country that isn't enabled to receive payments)
```
I'm from Ukraine, but I was receiving payments to PayPal with no problems on other platforms.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ekondrashev it's not Zerocracy issue, Paypal doesn't allow some payments based on sender and reaceiver countries. As I know you can receive payment in Ukraine only from Ukraine or from approved by paypal accounts. As you can see we're going to remove Paypal option at all https://github.com/zerocracy/farm/issues/1860 so I'd suggest to switch to Zold wallets and excange it using https://wts.zold.io/

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1925` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
