### ISSUE TITLE
Penalty for expired resume

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1927]
Add penalty for reviewer if assigned resume was  expired but user was not invited or rejected.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1927](https://github.com/zerocracy/farm/issues/1927), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1927` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by victornoel** [comment]
@g4s8 if the user is penalized when he doesn't review a resume, then I believe he should be reminded after 8 days (half of the 16days for review) that he has pending reviews.

Actually, this review process looks more and more like a DEV job, maybe the logic used to handle jobs, their timeout, penalties, reward and co should be used to handle resume reviews?

**Comment by g4s8** [comment]
@rultor release, tag=`0.43.6`

**Comment by g4s8** [comment]
@victornoel now examiner will be penalized with -32 pints for expired resume, see http://www.zerocracy.com/policy.html#1

> Actually, this review process looks more and more like a DEV job, maybe the logic used to handle jobs, their timeout, penalties, reward and co should be used to handle resume reviews?

I think it will be enough just a penalti for now, but you can suggest this feature in a new ticket.

**Comment by 0crat** [comment]
Job [#1927](https://github.com/zerocracy/farm/issues/1927) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1927](https://github.com/zerocracy/farm/issues/1927) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
