### ISSUE TITLE
Zold Wallets: Wait until debt accumulates before payment

### ISSUE THREAD

**Issue by pinaf** [zerocracy/farm#1929]
After switching wallets from BTC to ZLD, payments started coming in immediately after each issue was closed.

The behavior while on the BTC wallet was that payments would accumulate into a "debt" account and only be payed after it passed a certain threshold (of USD 64).

In order to significantly reduce the number of zold transactions we should use the same "debt account" scheme that existed for BTC wallets. Ideally, this threshold should be configurable by the account owner through the zerocrat bot.

Acceptance criteria:
- [ ] Add "debt account" behavior for accounts on the ZLD wallet
- [ ] Allow for the debt threshold to be configured through the zerocrat bot

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@pinaf[/z](https://www.0crat.com/u/pinaf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@pinaf why do we need to reduce amount of transactions? They are free. Debt mechanism was invented for Paypal and Coinbase because these services takes some commission for each payment, to avoid high commissions 0crat accumulated payments to debts. Now we don't have commission in Zold, so we can pay immediately.

Related: https://github.com/zerocracy/farm/issues/1900

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1929` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by pinaf** [comment]
@g4s8 because there's no need to clog up a zold wallet with lots of microtransactions unnecessarily, adding strain to the network, unless the receiver wants to get paid that way. I'm proposing we make it an option: setting the threshhold to zero (which could be the default value) would keep the current behavior of immediate payments.
