### ISSUE TITLE
Automatic tweet should be disabled 

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1931]
At the moment zerocracy bot has been temporarily banned from Twitter.

This is causing a lot of errors when adding a new project or user, and this should be avoided as it causes confusion.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa I think we just need to catch all exceptions when sending to Twitter and log it to Sentry (do not show to user)

**Comment by emilianodellacasa** [comment]
@g4s8 that could work for me, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1931` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1931](https://github.com/zerocracy/farm/issues/1931), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed in https://github.com/zerocracy/farm/commit/d16af88a0d10ca0ea8f50b115f6c9eb113967c65

**Comment by emilianodellacasa** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1931](https://github.com/zerocracy/farm/issues/1931) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1931](https://github.com/zerocracy/farm/issues/1931) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1931#issuecomment-471408722))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1931](https://github.com/zerocracy/farm/issues/1931) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231931%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
