### ISSUE TITLE
Command for POs to modify project default values

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1937]
It would be very useful for POs (and also for ARCs?) to have a command to modify some zerocracy settings, like days to close task, bonus for fast delivery, and rewards (issue creation, QA, ARC payment and so on).

Default values should be current values, but ability to change would be a remendous plus.

Command to be issued on Slack should be like

`@ 0crat option daysToCloseTask 4`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1937](https://github.com/zerocracy/farm/issues/1937), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1937` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.9`

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed in #2024 PR, try `@0crat option daysToCloseTask 7` in Slack channel

**Comment by emilianodellacasa** [comment]
@g4s8 Working, thanks. Are all the options documented somewhere? Shall I open an issue for it, otherwise?

**Comment by 0crat** [comment]
Job [#1937](https://github.com/zerocracy/farm/issues/1937) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1937](https://github.com/zerocracy/farm/issues/1937) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@emilianodellacasa right, I forgot about it, see zerocracy/zerocracy.github.io#87

**Comment by emilianodellacasa** [comment]
@g4s8 great, thanks
