### ISSUE TITLE
our GitHub responses are not case-sensitive

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#194]
See what happened here: https://github.com/DronMDF/telebot/issues/1#issuecomment-321579558 We started our response with `@dronmdf`, while the real GitHub name is `@DronMDF`. We keep `dronmdf` everywhere in our documents and it's correct. But when we respond in GitHub we should first ask GitHub to give us the information about the user and then use his real GitHub handler.

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/194#issuecomment-366430132))

@neonailol The impediment for [#194](https://github.com/zerocracy/farm/issues/194) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by neonailol** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/194#issuecomment-371760503))

@neonailol The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#194](https://github.com/zerocracy/farm/issues/194), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#194](https://github.com/zerocracy/farm/issues/194) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/681451490). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@yegor256 is this issue is still relevant? Seems like it was one-time bug?

**Comment by yegor256** [comment]
@t-izbassar I don't think so. I don't remember us fixing it anywhere. When I do:

```
Par("Hi, @%s!").say("johndoe");
```

This text will be printed to GitHub:

```
Hi, @johndoe!
```

Even if it's `JohnDoe` in GitHub. Or I'm wrong?

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 21days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 21days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/194#issuecomment-388640562))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#194](https://github.com/zerocracy/farm/issues/194), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#194](https://github.com/zerocracy/farm/issues/194) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1331712121); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by TestUserHere** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/zerocracy/farm/issues/194#issuecomment-389431847))

@TestUserHere Hey, what's up, how is it going?

**Comment by TestUserHere** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/194#issuecomment-389432491))

@TestUserHere This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#194](https://github.com/zerocracy/farm/issues/194) is [in scope](http://www.zerocracy.com/policy.html#14) for 9mon
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
    * @neonailol[/z](https://www.0crat.com/u/neonailol): User was resigned from the ticket
    * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23194%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@yegor256 This looks like it is working, see the [above](https://github.com/zerocracy/farm/issues/194#issuecomment-389432719) from my @TestUserHere account, it correctly uses letter case above

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bfcbac29-24ca-4d88-997c-cfa5a1e45b63, thread: AsyncFlush-2
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1391354486, Type: 'Close job', Author: yegor256

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#194](https://github.com/zerocracy/farm/issues/194) is now out of scope

**Comment by ypshenychka** [comment]
@yegor256 Please advice, how should I evaluate the ticket in this case. In fact no solution was provided. but on the other hand @krzyk spent some time to reproduce and check if it's working or not.

**Comment by yegor256** [comment]
@ypshenychka I would say it's "acceptable"
