### ISSUE TITLE
Refusal of REV job by ARC on behalf of user should be penalized

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1940]
I noticed multiple times that when a REV wasn't responding and ARC refused the task for him so that the job could be assigned to an active user, 0crat does not penalize the REV.

Example: https://github.com/yegor256/cactoos/pull/1078#issuecomment-469479920

I would expect those user to be penalized so that it reduces the chance for them to be assigned task later on.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel but ARC may refuse a job for another reason, e.g. if the job is not valid anymore and it should be removed from WBS without payment, or if ARC wants to assign the job to someone else, in these cases.

I don't think we should penalize someone if that person didn't violate the policy somehow, the policy doesn't say something about PR time limit for REV, but it says about penalty for ARC in case of long reviews, see https://www.zerocracy.com/policy.html#55 so it's a responsibility of ARC to make PRs move faster.

**Comment by victornoel** [comment]
@g4s8 you are right, I understand, thanks for the explanation!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1940` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
