### ISSUE TITLE
Error while closing issue

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1941]
I received an error while trying to close an issue:

```
PID: 4@5a9c191d-aa49-466c-9de2-b5b7e38b6498, thread: pool-5-thread-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:stryvers/life-lens-app#49] declared for identity constraint of element "verbosity".
```

Link to the [comment ](https://github.com/stryvers/life-lens-app/issues/49#issuecomment-472755136)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa it's a duplicate of https://github.com/zerocracy/farm/issues/1519 (origin issue https://github.com/zerocracy/farm/issues/1233)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1941` is not assigned, can't get performer
