### ISSUE TITLE
Assigned closed issue

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1942]
This bug is quite strange, I will try to detail what happened:

- An issue was closed because PR was merged;
- ARC mistakenly assigned the issue to himself;
- Original assignee was correctly paid after quality assessment;
- ARC issued `out `command to remove the issue from scope;
- ARC was paid;

I think that shouldn't ever happen, in general we should check if there was already a payment on a issue (excluding the case of a `pay` command).

EDIT: After discussion with @g4s8 we saw the real problem is that I was able to assign a closed issue, and it went into scope. Maybe the bot should check if the issue is open before putting it in scope

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa `out` means remove from scope = close the ticket, so the logic is correct. The only issue is that you was able to assign closed ticket.
If you want to remove the issue from scope without payment, you need to `refuse` first to unassign performer, and then `out` to remove from scope.

**Comment by emilianodellacasa** [comment]
@g4s8 will change title of the issue and edit the description then

**Comment by 0crat** [comment]
Job [#1942](https://github.com/zerocracy/farm/issues/1942) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@rultor release, tag=`0.44.1`

**Comment by g4s8** [comment]
@emilianodellacasa it should be fixed in https://github.com/zerocracy/farm/commit/a5e614c0747fcba7e9fc84323c4afd43e394040f and realeased in `0.44.1`, so I'm closing this ticket to verify that I can't assign it after close

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1942` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
The job [#1942](https://github.com/zerocracy/farm/issues/1942) is now out of scope

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1942#issuecomment-473396569))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1942](https://github.com/zerocracy/farm/issues/1942) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231942%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1942#issuecomment-473397504))

@g4s8 Job [#1942](https://github.com/zerocracy/farm/issues/1942) is closed, can't start order

**Comment by g4s8** [comment]
@emilianodellacasa see https://github.com/zerocracy/farm/issues/1942#issuecomment-473399502 it's fixed now
