### ISSUE TITLE
Payments when project is paused

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1943]
By my understanding, payments on a paused project shouldn't happen, but I just got paid on a issue of a paused project.

Link [here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472758862)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa I updated the policy to explain pause behavior, please take a look: https://www.zerocracy.com/policy.html#24

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1943` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
