### ISSUE TITLE
not enough details in the invitation to review a candidate

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1944]
I just received a message in Telegram: "A new applicant, @nermeen78/z (https://www.0crat.com/u/nermeen78), has been assigned to you. Please review the resume, and either invite or reject the applicant. In either case you will receive +32 reputation points as in §1 (http://www.zerocracy.com/policy.html#1)" I have to review the person, but I don't know where to click... Would be great if I would have a link right here in the message.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1944](https://github.com/zerocracy/farm/issues/1944) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 thanks, it should be fixed now, added link to resume in message

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1944` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1944](https://github.com/zerocracy/farm/issues/1944) is now out of scope
