### ISSUE TITLE
Telegram nickname is not displayed in resume

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1950]
I was assigned for an application form and when I followed the link to resume - there was no Telegram nickname in it. So it's quite difficult to find and contact that person.
This issue is actual for resumes assigned to other examiners as well (I could check this as far as I have access to all of them).

Please add Telegram field back to resume.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1950](https://github.com/zerocracy/farm/issues/1950) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1950](https://github.com/zerocracy/farm/issues/1950), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.8`

**Comment by g4s8** [comment]
@ypshenychka done, please look at the resumes page

**Comment by ypshenychka** [comment]
@g4s8 Thanks

**Comment by 0crat** [comment]
Job [#1950](https://github.com/zerocracy/farm/issues/1950) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1950](https://github.com/zerocracy/farm/issues/1950) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
