### ISSUE TITLE
TkBoard.java:45-49: Implement stakeholders to update...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1952]
The puzzle `1657-8629e708` from #1657 has to be resolved: 

https://github.com/zerocracy/farm/blob/a07091e03268da4de09d8cb8b7aade9e12a26ad6/src/main/java/com/zerocracy/tk/TkBoard.java#L45-L49

The puzzle was created by @g4s8 on 20-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1952](https://github.com/zerocracy/farm/issues/1952) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1954](https://github.com/zerocracy/farm/issues/1954) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.1`

**Comment by 0pdd** [comment]
The puzzle `1657-8629e708` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1952` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1952](https://github.com/zerocracy/farm/issues/1952) is now out of scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.5`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
