### ISSUE TITLE
0crat assigned me a PR as REV that I had submitted

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1965]
See https://github.com/yegor256/cactoos/pull/1087

I would expect not to be assigned such PR :)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 it happened again: https://github.com/yegor256/cactoos/pull/1092

**Comment by g4s8** [comment]
@victornoel thanks, but it's a duplicate of #1787

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1965` is not assigned, can't get performer
