### ISSUE TITLE
0crat sent my payment to wrong zold address

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1966]
I switched from paypal to zold payments and provided 0crat with the address of my wallet:
```
/wallet zold MY_WALLET_ID_IN_ALPHANUMERICALS
```

Later that day 0crat said that if `We just paid you the debt of .... (01bcbbc8-7466-4310-b932-6fb948666753)`.

I went to wts.zold.io, but my wallet is still at 0.00 ZLD.
But there is a transaction with my user id, but for a different wallet: http://www.zold.io/ledger.html?wallet=2c1a58718d817ab2

Where did 0crat get that wallet? Why is it different from the one I provided?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1966](https://github.com/zerocracy/farm/issues/1966) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1966](https://github.com/zerocracy/farm/issues/1966), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1966` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@krzyk the puzzle [#1968](https://github.com/zerocracy/farm/issues/1968) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.12`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@krzyk it should be fixed now

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1966](https://github.com/zerocracy/farm/issues/1966) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1966](https://github.com/zerocracy/farm/issues/1966) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
