### ISSUE TITLE
Recharge project if direct payment failed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1969]
IF project doesn't have enough amount of cash to make direct payment (`@0crat pay` or `@0crat extra`) we should try to recharge project and fail the claim. Now only reputation points are added.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1969](https://github.com/zerocracy/farm/issues/1969), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1969` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.16`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.18`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.19`

**Comment by g4s8** [comment]
fixed

**Comment by 0crat** [comment]
Job [#1969](https://github.com/zerocracy/farm/issues/1969) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 12 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1969](https://github.com/zerocracy/farm/issues/1969) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.20`
