### ISSUE TITLE
An unrecoverable failure on closing a job

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1974]
There is an unrecoverable failure on my side.
```
PID: 4@198e86bb-a7ed-4bdd-80b4-d2a4404db1dc, thread: pool-5-thread-4
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:stryvers/life-lens-app#176] declared for identity constraint of element "blanks".
```
0.45.20: CID: [4f8a8d8d-e5bf-42d6-b8b3-1a67398c8ca4](https://www.0crat.com/footprint/GFV03LPPY/4f8a8d8d-e5bf-42d6-b8b3-1a67398c8ca4), Type: "Close job"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko it's similar to https://github.com/zerocracy/farm/issues/1233

**Comment by 0crat** [comment]
Job [#1974](https://github.com/zerocracy/farm/issues/1974) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1974](https://github.com/zerocracy/farm/issues/1974), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@denis-konovalyenko it should be fixed in #2021 PR, can we close?

**Comment by denis-konovalyenko** [comment]
@g4s8 , thanks for addressing this!

**Comment by 0crat** [comment]
Job [#1974](https://github.com/zerocracy/farm/issues/1974) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1974](https://github.com/zerocracy/farm/issues/1974) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
