### ISSUE TITLE
/funded callback

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1975]
Every time a project receives funding via Stripe, we have to `GET` call `https://www.rehttp.net/p/https://wts.zold.io/funded?amount=29.95`. Here `29.95` is the amount in dollars we charged via Stripe.

It will be received: https://github.com/zold-io/wts.zold.io/issues/201

Don't forget to provide the authenticating token, to make sure the call is made by 0crat.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1975#issuecomment-478968704))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1975](https://github.com/zerocracy/farm/issues/1975), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 this is pretty urgent, thanks!

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.21`

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#1975](https://github.com/zerocracy/farm/issues/1975) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1975](https://github.com/zerocracy/farm/issues/1975) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
