### ISSUE TITLE
catalog.xml is broken

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1979]
File `catalog.xml` in `PMO` becomes broken, it contains only project ids.
[catalog.gz](https://github.com/zerocracy/farm/files/3045282/catalog.gz)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/zerocracy/farm/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zerocracy/farm` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `zerocracy/farm` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8a469c43-3a3d-420d-9bb4-d7980bd8f664, thread: pool-262-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zerocracy/farm#1979: I'm not managing `zerocracy/farm` GitHub repository, you have to contact me in Slack first, see [§11
```

[0.45.21](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1979, Action: `labeled`

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1979#issuecomment-480090244))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1979](https://github.com/zerocracy/farm/issues/1979), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.22`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.22`

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.22`

**Comment by g4s8** [comment]
should be fixed

**Comment by 0crat** [comment]
Job [#1979](https://github.com/zerocracy/farm/issues/1979) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1979](https://github.com/zerocracy/farm/issues/1979) is now out of scope
