### ISSUE TITLE
0crat assigned the issue with closed PR

### ISSUE THREAD

**Issue by atapin** [zerocracy/farm#1980]
The issue [cactoos#941](https://github.com/yegor256/cactoos/issues/941) has a closed [PR](https://github.com/yegor256/cactoos/pull/995). But the issue was not closed, so 0crat [wants](https://www.0crat.com/footprint/C63314D6Z/8249f7c5-ba0c-4a80-b928-09fb2e1c3e91) to reassign it to me.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@atapin[/z](https://www.0crat.com/u/atapin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@atapin 0crat doesn't link issues and PRs, if issue is open it can assign a performer to it.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1980` is not assigned, can't get performer
