### ISSUE TITLE
WBS link leads to blank page

### ISSUE THREAD

**Issue by alex-semenyuk** [zerocracy/farm#1981]
https://www.0crat.com/u/{user-name}/wbs leads to blank page

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by aivinog1** [comment]
@alex-semenyuk and @g4s8 I also see this in the log.
[www.0crat.com-1563011173789.log](https://github.com/zerocracy/farm/files/3388677/www.0crat.com-1563011173789.log)

**Comment by g4s8** [comment]
@alex-semenyuk thanks for reporting, but it's a duplicate of #1641

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1981` is not assigned, can't get performer
