### ISSUE TITLE
@0crat does not react on GitHub message when it is being tagged via edit 

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#1983]
**Steps to reproduce**:

- [ ] 1) Tag @0pdd (by mistake) instead of @0pdd (see [here](https://github.com/yegor256/cactoos/issues/939#issuecomment-480496552)) to write a result of quality review

- [ ] 2) Edit message to tag @0crat instead of @0pdd and see if @0crat is working correctly

- [ ] 3) See that nothing happens

**Expected result**: When user by mistake does not tag @0crat firstly and tags it via edit GitHub message, @0crat should react and proceed as it usually does

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by sereshqua** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@sereshqua it will be hard to implement: if we just handle any update of comment from Github, 0crat may process similar claim multiple times (e.g. if you assign performer to ticket and then edit performers name - 0crat will asign first performer then second, but first message will be lost); also we can keep on 0crat side full comment history, but it'd be very complex solution just to accept typo edits in comments. So I don't think it's important bug (read as: bug fix is too complex for this kind of bug).

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1983` is not assigned, can't get performer
