### ISSUE TITLE
BUG in my Agenda

### ISSUE THREAD

**Issue by ebercamargo** [zerocracy/farm#1984]
Item 181 left my Agenda in less than 10 days.

Id Project: GFV03LPPY

https://github.com/stryvers/life-lens-app/issues/181

This is one image of my Agenda today:

![image](https://user-images.githubusercontent.com/37782410/55672745-e6044180-5874-11e9-8a2f-ea49f2b45e04.png)

I request that my reputation be adjusted:

![image](https://user-images.githubusercontent.com/37782410/55672774-3c718000-5875-11e9-8ecf-8cee0f100fda.png)

I keep my items on the agenda, can't I trust her anymore?

Do the other items have a certain cotangem? Can I trust you?

My Agenda now:
![image](https://user-images.githubusercontent.com/37782410/55673242-ae4cc800-587b-11e9-9ead-641c5b43f795.png)

tks.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ebercamargo sorry, I don't understand you, please clarify your bug-report and include in your report such sections as: "what is broken" and "what are you expecting to see", also this post may help you: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by ebercamargo** [comment]
@g4s8 You answered minah question, I can not trust the bot. Even though this is a bug, you do not want to or can not understand how. Thank you.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1984` is not assigned, can't get performer
