### ISSUE TITLE
There is a message from 0crat that there is a new applicant but their resume is absent

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1992]
0crat chat message:
```
A new applicant, @cviniciussdias/z (https://www.0crat.com/u/cviniciussdias), has been assigned to you: resume by cviniciussdias (https://www.0crat.com/u/denis-konovalyenko/resumes#resume-cviniciussdias). Please review the resume, and either invite or reject the applicant. In either case you will receive +32 reputation points as in §1 (http://www.zerocracy.com/policy.html#1)
```
By following the link - https://www.0crat.com/u/denis-konovalyenko/resumes#resume-cviniciussdias I faced with an empty list page:

![image](https://user-images.githubusercontent.com/15904097/55939565-becbbc80-5c46-11e9-9f99-59717ec496ae.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko you can't see the resume because this user was invited already:

> New user @cviniciussdias/z (https://www.0crat.com/u/cviniciussdias) was invited by @ypshenychka/z (https://www.0crat.com/u/ypshenychka)

**Comment by denis-konovalyenko** [comment]
@g4s8 , thanks for the clarification! Do you happen to know if there an issue for being more informative about that from 0crat?

**Comment by denis-konovalyenko** [comment]
@g4s8 , I have creaed the issue #1993. Thanks again!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1992` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
