### ISSUE TITLE
Be more informative on the applicant's resume status

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1993]
It is possible to be an examiner and get into the situation when an applicant's resume is not available for the reasons that someone else has already invited him/her before you even get to the resumes page (for more information please refer to issue #1992).

It would be fair to make another notice from 0crat about the changes. E.g.:

_Since you were not managed to look at the resume for more than 4 hours, it can be forcibly ejected from you by our special mentor forces. Be faster next time. Good luck!_

And finally

_Please stop examining @ new-user/z resume as they were invited by @ someone-else._

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko correct, we should notify mentor when student invited by someone else

**Comment by 0crat** [comment]
Job [#1993](https://github.com/zerocracy/farm/issues/1993) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1993` already assigned to @victornoel, can't assign to @victornoel

**Comment by 0crat** [comment]
The job [#1993](https://github.com/zerocracy/farm/issues/1993) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/3918003f-f8f9-4752-9630-2c42cb0dfc63); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #2169 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #2169 to be merged ([here](https://github.com/zerocracy/farm/issues/1993#issuecomment-541340094))

@victornoel The impediment for [#1993](https://github.com/zerocracy/farm/issues/1993) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@denis-konovalyenko the PR has been merged, could you close the ticket? Thanks

**Comment by denis-konovalyenko** [comment]
@victornoel , thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
The job [#1993](https://github.com/zerocracy/farm/issues/1993) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
