### ISSUE TITLE
There is no full reference of Zerocrat's commands

### ISSUE THREAD

**Issue by vzurauskas** [zerocracy/farm#1997]
There should be a highly visible page (e.g. linked from [policy](http://www.zerocracy.com/policy.html)) with:
- all possible Zerocrat's commands
- all possible parameters for these commands
- descriptions of what the commands and parameters do.

Currently, the closest thing to this as far as I can tell is Zerocrat's Telegram chat, where if I enter "/" I get some possible commands, but not all (e.g. there is no `maxagenda` command), and no possible parameters.

A halfway solution could be just linking to Zerocrat's source file where all his commands are registered, assuming they are all in one place.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@vzurauskas you can use `help` (or any invalid command) to get full list of supported commands in chat bot

**Comment by vzurauskas** [comment]
@g4s8 I tried it, but not all commands are listed there, e.g. `maxagenda` is missing.

If I try some of them, I get a list of possible parameters with descriptions, so that part is ok. I guess it's just that the list of commands needs to be updated.

**Comment by vzurauskas** [comment]
@g4s8 Actually, `maxagenda` command doesn't seem to exist, but there used to be some command to set the max number of jobs in your agenda which sounded something like that, and it's not in the list. That's why I suspect there might be other commands missing.

**Comment by g4s8** [comment]
@vzurauskas 
>  I tried it, but not all commands are listed there, e.g. maxagenda is missing.

it always prints full list of supported commands (it's generated programmatically, the list is not static)

The command you are looking for called `option`, it changes user options, e.g. to change max-agenda items use `option maxJobsInAgenda 1`

**Comment by vzurauskas** [comment]
Ah, ok, thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1997` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
