### ISSUE TITLE
0crat sends same messages to the ticket multiple times

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#1999]
**Steps to reproduce**:

1. Do a Quality Review and write `@0crat quality good` in the ticket

2. See same 0crat multiple messages about project NOT having enough funds:

[Here](https://github.com/Harvest-foundation/core/issues/428#issuecomment-478939031), [here (2nd)](https://github.com/Harvest-foundation/core/issues/428#issuecomment-478939738) [and here (3rd)](https://github.com/Harvest-foundation/core/issues/428#issuecomment-478940933)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua related to #876

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1999` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
