### ISSUE TITLE
0crat elections broken

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2002]
Elections in 0crat is broken: it is assigning issues that doesn't have the tag `scope` to performers

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso election process and scope label have nothing in common, this label should be added when ticket added to scope, but sometimes 0crat failed to do that because of GitHub API limits, it doesn't mean that ticket isn't in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2002` is not assigned, can't get performer
