### ISSUE TITLE
0crat does not assign performer on github

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2003]
0crat is assigning the performer in its registers but not assigning it in github issue, for example in https://github.com/yegor256/jpeek/issues/261

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso footprint: https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23261%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D

**Comment by 0crat** [comment]
Job [#2003](https://github.com/zerocracy/farm/issues/2003) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by g4s8** [comment]
@paulodamaso this is a limitation of Github system - no one can assign new user to the ticket (even repo admin or owner), this is why 0crat failed to assign people to the ticket before first contribution.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2003` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2003](https://github.com/zerocracy/farm/issues/2003) is now out of scope
