### ISSUE TITLE
refund command

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2007]
Let's add a new command `refund` to Slack. Product owner should have an ability to say `refund` and we should add a new transaction to the ledger: Ct:CASH, Dt:Payables. 

And then we should inform PMO that it's time to send the specified amount by check to the user.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 would be great if we can implement it ASAP

**Comment by g4s8** [comment]
@yegor256 isn't it a duplicate of #1611 ticket?
Could you please clarify what did you mean by "it's time to send the specified amount by check to the user.", should we just inform PO with a message or make some action? If yes what exactly we should do?

**Comment by yegor256** [comment]
@g4s8 I would suggest closing #1611 and continue here. I think it should be a manual operation always. When a PO makes `refund` request, we immediately add the transaction to the ledger (to prevent further funds spending) and send a message to the PMO. No action, just a message. The PMO will decide how to make a refund, either via Zold or paper check. After the message to the PMO is sent, the farm calls this operation "done".

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2007](https://github.com/zerocracy/farm/issues/2007), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2007` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 got it. One more question: do we need to set project on pause? If we don't, 0crat may automaticlly recharge project on refund.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 now, we shouldn't. It's a problem of PO. Let's just do the refund. Let's not forget to update the policy.

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.5`

**Comment by g4s8** [comment]
@yegor256 it should be fixed in new release

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#2007](https://github.com/zerocracy/farm/issues/2007) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 12 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2007](https://github.com/zerocracy/farm/issues/2007) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
