### ISSUE TITLE
Update maven-compiler-plugin and fix bug on it to allow incremental compilation

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#2011]
Let's update `maven-compiler-plugin` to 3.8.0 version and fix a bug in this plugin which doesn't allow incremental compilation that increase compile and running time. To fix both we need change `pom.xml` to:
```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
Please, pay attention to `<version>` and `<useIncrementalCompilation>` tag.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@fabriciofx thanks a lot! Fixed in https://github.com/zerocracy/farm/commit/e3b2b37b3ca397c2ba6871f2baf859892bb81159

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2011` is not assigned, can't get performer
