### ISSUE TITLE
BUG BOT 0crat - Tickets in WAIT

### ISSUE THREAD

**Issue by ebercamargo** [zerocracy/farm#2016]
Even puttinged the ticket on WAIT, in the bot 0crat, he counted the days and withdrew my tickets. I'm leaving the projects, I'm missing a lot of points on 0crat by BOT BUGS. This is very bad,I hope in the future the developers of bot 0crat will pay more attention to it. 

project: GFV03LPPY

![image](https://user-images.githubusercontent.com/37782410/56805567-d175f200-67ff-11e9-9279-f91332c75195.png)

All in WAIT:

https://github.com/stryvers/life-lens-app/issues/223

https://github.com/stryvers/life-lens-app/issues/224

![image](https://user-images.githubusercontent.com/37782410/56805647-20bc2280-6800-11e9-82c8-52c7d1d462dd.png)

tks,

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ebercamargo it's not a bug - as I can see, project's architect (@paulodamaso) removed impediment for these issues. Actually, you must have a very good reason to put a job into waiting state.
E.g. see https://www.0crat.com/footprint/GFV03LPPY/96dbd0da-132d-46bd-8521-64bbf9783e2f

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2016` is not assigned, can't get performer
