### ISSUE TITLE
When I am on vacation mode, 0crat still assigns me to jobs

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2017]
**Steps to reproduce**:

1) Tell 0crat in TG `vacation on` (I did at 12:32 PM GMT +2)

2) See that 0crat still assigns me to a [job](https://github.com/llorllale/cactoos-matchers/pull/115#issuecomment-487031772) (0crat assigned me at 2:59 PM GMT +2)

**Expected result**: 

When I am on vacation mode, 0crat should NOT assign me to jobs

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2017](https://github.com/zerocracy/farm/issues/2017) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by sbzDev** [comment]
@g4s8 Can I take it? 

Clarifications:
1. How to test it locally?
2. According to Policy, job can't be assigned to performers on Vacation, but user can be elected and be assigned to job with note '**we should be aware that @%s is on vacation; this ticket may be delayed**' in
`com/zerocracy/stk/pm/in/orders/start_order.groovy:99 `
 will be enough to add only check if performer on vacation during assign job to him?

**Comment by g4s8** [comment]
@sbzDev the issue here is that @sereshqua has QA role in projects and 0crat assigned tickets after complete for QA review (it's not about DEV, REV jobs) when he was on vacation. The bug should be in `start_qa_review`.

> How to test it locally?

To reproduce it you can write a bundle test, check `BundlesTest` class and bundle scripts in `src/test/resources/com/zerocracy/bundles`, or even better - you can update `upUGY6_adds_reviews_to_qa_agenda` existing test.

**Comment by g4s8** [comment]
@0crat assign @sbzDev

**Comment by sbzDev** [comment]
@g4s8 maybe you meant `upaiXM_assigns_and_notifies_on_vacation` test ?

**Comment by g4s8** [comment]
@sbzDev no, it's about `DEV` / `REV` jobs, `upUGY6_adds_reviews_to_qa_agenda` test checks that a job is assigned for QA review on completion, we need to check that a job can't be assigned to QA on vacation

**Comment by 0crat** [comment]
> @0crat assign @sbzDev  ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-496554500))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2017](https://github.com/zerocracy/farm/issues/2017), see [§21](http://www.zerocracy.com/policy.html#21); @sbzdev[/z](https://www.0crat.com/u/sbzdev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sbzDev** [comment]
@g4s8 The PR is ready for REVIEW

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-497080387))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2017](https://github.com/zerocracy/farm/issues/2017) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @sereshqua[/z](https://www.0crat.com/u/sereshqua): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232017%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment]
@g4s8 PR is ready

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-497691657))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2017](https://github.com/zerocracy/farm/issues/2017) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @sereshqua[/z](https://www.0crat.com/u/sereshqua): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232017%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment]
@g4s8 if PR is ok. Can this issue be closed?

**Comment by g4s8** [comment]
@sbzDev please ask issue author to close it

**Comment by sereshqua** [comment]
@0crat close

**Comment by 0crat** [comment]
> @0crat close ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-497700727))

@sereshqua Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
Job [#2017](https://github.com/zerocracy/farm/issues/2017) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#2017](https://github.com/zerocracy/farm/issues/2017) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sbzdev[/z](https://www.0crat.com/u/sbzdev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#2017](https://github.com/zerocracy/farm/issues/2017) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-497707868))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/2017#issuecomment-497707868))

@sereshqua The project doesn't have enough funds, can't make a payment
