### ISSUE TITLE
Notify performer on wait/continue

### ISSUE THREAD

**Issue by ebercamargo** [zerocracy/farm#2018]
I request that when the ticket is placed with WAIT status, and ARK removes this status, the BOT send a notification "Message Telegram" indicating withdrawal from this "WAIT" status for example, or whenever there is one change in the status of ticket.

Maybe this is not a BUG, ​​but it would be an interesting improvement and would help everyone.

Tks,

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#2018](https://github.com/zerocracy/farm/issues/2018) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by sbzDev** [comment]
@g4s8 can I take it?

**Comment by g4s8** [comment]
@0crat status

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat assign @sbzDev  ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-496556850))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2018](https://github.com/zerocracy/farm/issues/2018), see [§21](http://www.zerocracy.com/policy.html#21); @sbzdev[/z](https://www.0crat.com/u/sbzdev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-496590853))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2018](https://github.com/zerocracy/farm/issues/2018) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [1hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232018%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-496604035))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2018](https://github.com/zerocracy/farm/issues/2018) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [2hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232018%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-497080288))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2018](https://github.com/zerocracy/farm/issues/2018) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232018%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment]
@g4s8 PR is ready

**Comment by sbzDev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-497691568))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2018](https://github.com/zerocracy/farm/issues/2018) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232018%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment]
@ebercamargo please close the issue

**Comment by sbzDev** [comment]
@g4s8 can you close this issue due to no answer from reporter?

**Comment by ebercamargo** [comment]
@0crat close

**Comment by ebercamargo** [comment]
@sbzDev tks.

**Comment by 0crat** [comment]
Job [#2018](https://github.com/zerocracy/farm/issues/2018) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sbzdev[/z](https://www.0crat.com/u/sbzdev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#2018](https://github.com/zerocracy/farm/issues/2018) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't inspect

**Comment by 0crat** [comment]
The job [#2018](https://github.com/zerocracy/farm/issues/2018) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-500495774))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/zerocracy/farm/issues/2018#issuecomment-500495774))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
