### ISSUE TITLE
Architect Review Bonus is not applied when there is no REV or QA

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#2020]
Qulice doesn't have any participants (no DEV/REV/QA) and as such when someone provides a PR only ARC reviews it and then merges it, but in such case (when there is no QA or maybe no REV) ARC doesn't get bonus for merging the PR as mentioned in http://www.zerocracy.com/policy.html#28.

This paragraph doesn't state that a QA/REV is needed to get the bonus, so I would expect to get it for all merged PRs.

Example: https://github.com/teamed/qulice/pull/1042

**Comment by krzyk** [comment]
@g4s8 this was a problem in qulice for almost forever, excluding a short time when there was an active DEV/REV +QA there.

**Comment by g4s8** [comment]
@krzyk looks like you can receive a bonus only if a job was assigned to someone before closing. But 0crat should pay this bonus when job removed from wbs, not when order was finished.

**Comment by 0crat** [comment]
Job [#2020](https://github.com/zerocracy/farm/issues/2020) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2020](https://github.com/zerocracy/farm/issues/2020), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.8`

**Comment by g4s8** [comment]
@krzyk it was fixed in #2022 PR, see https://github.com/zerocracy/farm/pull/2021#issuecomment-488255777 (received 10min bonus after release)

**Comment by krzyk** [comment]
@g4s8 works, thanks

**Comment by 0crat** [comment]
Job [#2020](https://github.com/zerocracy/farm/issues/2020) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2020](https://github.com/zerocracy/farm/issues/2020) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
