### ISSUE TITLE
0crat removed me from sandbox even though I graduated and rejoined before

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2030]
Lately I was removed from sandbox project because I graduated.

Today I asked cactoos' ARC to add me again to the project.

A few time later, 0crat removed me again from the cactoos project, saying I was over 1024 points.

I would expect that once being re-added after I graduated, 0crat wouldn't kick me out again.
According to @g4s8 this should be the expected behaviour: https://t.me/zerocracy/5538

Note that:
- the first time, I was removed, but it happened in a strange way (see #2028) so maybe this is a remnant of a previous inconsistent state
- this time it explicitly told me that I got kicked because of my number of points
- looking at the code (https://github.com/zerocracy/farm/blob/f53547aa19cd51d1267f87ea3d9de503002d71c7/src/main/groovy/com/zerocracy/stk/pm/staff/roles/kickout_from_sandbox.groovy#L44) I would expect me to be ignored by 0crat since I don't have a mentor anymore... I'm not sure this is actually explicit in the policy though...

**Comment by victornoel** [comment]
@g4s8 ping, and furthermore 0crat removed me from the jobs I was working on in cactoos... is there a bug already open for this?

**Comment by 0crat** [comment]
Job [#2030](https://github.com/zerocracy/farm/issues/2030) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 any way to some investigation on this? I would like to be able to resume work on cactoos as soon as possible.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2030](https://github.com/zerocracy/farm/issues/2030), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@victornoel the puzzle [#2049](https://github.com/zerocracy/farm/issues/2049) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.3`

**Comment by g4s8** [comment]
@victornoel should be fixed in https://github.com/zerocracy/farm/commit/778190662da5d6a0bdb1c0f7bdb41118129b5482
try to join the project after release https://github.com/zerocracy/farm/issues/2030#issuecomment-495689693

**Comment by victornoel** [comment]
@g4s8 thanks, I joined cactoos again and will close this issue in a few days when I can confirm I am not kicked out again :)

**Comment by 0crat** [comment]
Job [#2030](https://github.com/zerocracy/farm/issues/2030) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't set title

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@victornoel the puzzle [#unknown]() is still not solved.
