### ISSUE TITLE
new metrics: team statistics

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2036]
Let's add a few more metrics. Let's collect them every 24 hours. They all are visible here: https://www.0crat.com/team

1. Active users (27 now)

2. Total reputation (66364 now)

3. Visible users (67 now)

Let's show them in the regular report to the PMO.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2036](https://github.com/zerocracy/farm/issues/2036), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2036` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 it was fixed in #2037 PR, can we close?

**Comment by 0crat** [comment]
Job [#2036](https://github.com/zerocracy/farm/issues/2036) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#2036](https://github.com/zerocracy/farm/issues/2036) is now out of scope
