### ISSUE TITLE
After doing CV's examination, I haven't received any email confirming that I am awarded with 32 points

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2040]
Generally, there is always an email from 0crat, that is set to send messages about rewarding the points of job completion. 

However, after doing CV's examination, I haven't received any email confirming that I am awarded with 32 points. I have just received a TG message from 0crat: `You received bonus 32 points for @...username/z resume examination`.

Can this feature of sending emails of rewarding bonus points for CV examination be implemented?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua did you receive 32 points?

**Comment by sereshqua** [comment]
@g4s8 I did receive, but the was not any email notification and usual, so I thought it would be nice to have feature

**Comment by victornoel** [comment]
@sereshqua I think you should have received a message via telegram. Note that 0crat never send any email, at all. All the emails you receive are from github.

**Comment by sereshqua** [comment]
@victornoel i got it, then it would be nice to configure such notification in GitHub if possible :)

**Comment by g4s8** [comment]
@sereshqua GitHub doesn't know about Zerocracy resumes and reviews, so we can't notify you via GitHub about examinations. Also, we don't have email notifications for now, so it's not possible to receive such emails.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2040` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
