### ISSUE TITLE
/rate command is not working 

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2047]
After the `wallet` functionality has been changed, as it is being created automatically on first payment, the address is 0crat (github) username - `/rate` command does not work and new user is not able to set up his rate via 0crat.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua can you please attach error message from 0crat? I can't find it in logs.

**Comment by sereshqua** [comment]
@g4s8 I was told by [https://www.0crat.com/u/ankitshah2272m](https://www.0crat.com/u/ankitshah2272m) that it was not working at the beginning of the day;

as I see now we has able to set him rate

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2047` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
