### ISSUE TITLE
0crat is down - Application error

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2053]
1) Go to personal page - [https://www.0crat.com/u/sereshqua](https://www.0crat.com/u/sereshqua)

2) See the error

<img width="521" alt="Screenshot 2019-05-28 at 15 53 26" src="https://user-images.githubusercontent.com/10097808/58479336-c09f0000-8160-11e9-8ed1-a3289fb9013b.png">

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@591f6eb4-422a-4795-89f2-b98281fe0551, thread: pool-988-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.47.3](https://github.com/zerocracy/farm): Issue: zerocracy/farm#2053, Action: `opened`

**Comment by sereshqua** [comment]
@g4s8 FYI

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2053](https://github.com/zerocracy/farm/issues/2053), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by g4s8** [comment]
@sereshqua I think it was fixed

**Comment by 0crat** [comment]
Job [#2053](https://github.com/zerocracy/farm/issues/2053) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2053](https://github.com/zerocracy/farm/issues/2053) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
