### ISSUE TITLE
User identified as null - null via Yoti

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2054]
User can be identified as `null - null` via Yoti, see https://github.com/zerocracy/farm/issues/1977#issuecomment-495722870

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2054](https://github.com/zerocracy/farm/issues/2054), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.4`

**Comment by vassilevsky** [comment]
So right now I see this:

> We know you as: null null 2-11-1980 @Yoti.

Should I re-identify myself? Where can I find a link to do that?

**Comment by g4s8** [comment]
@vassilevsky yes please, I've reset all `null null` identities.

**Comment by 0crat** [comment]
Job [#2054](https://github.com/zerocracy/farm/issues/2054) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 41 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2054](https://github.com/zerocracy/farm/issues/2054) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
