### ISSUE TITLE
An unrecoverbale failure on closing a job 2

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#2060]
There is an unrecoverable failure on my side. Please, submit it here:
```
PID: 4@ffe0d280-8f07-4cdf-afc6-dd05873ebac7, thread: pool-6-thread-1
org.cactoos.scalar.UncheckedScalar[60] java.io.UncheckedIOException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```
0.47.4: CID: [18e75328-98d4-4db2-b0d4-d7d5d8c4765e](https://www.0crat.com/footprint/GFV03LPPY/18e75328-98d4-4db2-b0d4-d7d5d8c4765e), Type: "Close job"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@denis-konovalyenko it was temporary failure, Github API didn't respond with 4 attempts, it looks it was down for some time

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2060` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
