### ISSUE TITLE
When all QAs on vacation in the project, notify ARCs about that

### ISSUE THREAD

**Issue by sbzDev** [zerocracy/farm#2061]
When all QAs on vacation in the project, notify ARCs about that
related to https://github.com/zerocracy/farm/issues/2017

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2061](https://github.com/zerocracy/farm/issues/2061) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by sbzDev** [comment]
@g4s8 please assign it to me?

**Comment by g4s8** [comment]
@0crat assign @sbzDev

**Comment by 0crat** [comment]
> @0crat assign @sbzDev  ([here](https://github.com/zerocracy/farm/issues/2061#issuecomment-497691778))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2061](https://github.com/zerocracy/farm/issues/2061), see [§21](http://www.zerocracy.com/policy.html#21); @sbzdev[/z](https://www.0crat.com/u/sbzdev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sbzDev** [comment]
@g4s8  how can i close that?

**Comment by g4s8** [comment]
@sbzDev sure, thanks

**Comment by 0crat** [comment]
Job [#2061](https://github.com/zerocracy/farm/issues/2061) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sbzdev[/z](https://www.0crat.com/u/sbzdev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#2061](https://github.com/zerocracy/farm/issues/2061) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't inspect

**Comment by 0crat** [comment]
The job [#2061](https://github.com/zerocracy/farm/issues/2061) is now out of scope

**Comment by sereshqua** [comment]
@sbzDev & @g4s8 please make sure that next time problem reporter and problem solver will be 2 different persons (as written in [policy](http://www.zerocracy.com/policy.html#30))

> Problem reporter and problem solver are two different persons

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/zerocracy/farm/issues/2061#issuecomment-498156213))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/zerocracy/farm/issues/2061#issuecomment-498156213))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
