### ISSUE TITLE
Review assigned on already approved PR

### ISSUE THREAD

**Issue by scristalli** [zerocracy/farm#2066]
[PR #125 in cactoos-matchers](https://github.com/llorllale/cactoos-matchers/pull/125)

The PR has been approved and rultor is waiting for ARC to confirm merge, but it seems that 0crat assigned the review of the PR again.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@scristalli I just checked this PR - reviewer decided to quit the project this is why, the job was cancelled and assigned to new performer.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2066` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by scristalli** [comment]
Thanks for the explanation, this wasn't visible from the comments so I thought it might have been a bug.
