### ISSUE TITLE
Mentor may not receive tuition fees

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2067]
Mentor may not receive tuition fees when user get payments via pay extra command.
It seems it was introduced intentionally here:

https://github.com/zerocracy/farm/commit/3d88a06f3cab8ece6cee50f9b2d114c59d7603ac#diff-1f2fd793b201bd4080e3502d774f9109R67

for #627 ticket, but it's contradicting 45 policy rule: https://www.zerocracy.com/policy.html#45 :
> While you have a mentor (and it’s not Zerocrat), he/she gets 8 cents of every dollar you make.

@yegor256 please check this issue, since it's critical now.

**Comment by 0crat** [comment]
Job [#2067](https://github.com/zerocracy/farm/issues/2067) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2067](https://github.com/zerocracy/farm/issues/2067), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.5`

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/973bbf300828f048066a2afed55d5f2c98ddaa84

**Comment by 0crat** [comment]
Job [#2067](https://github.com/zerocracy/farm/issues/2067) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2067](https://github.com/zerocracy/farm/issues/2067) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
