### ISSUE TITLE
ARC not visible in project board

### ISSUE THREAD

**Issue by scristalli** [zerocracy/farm#2069]
ARC is not visible in the project board altought a column for ARC is present.
Piece of output from the board page, as you can see ARC's `<td>` is empty:
```
<tr style="opacity:0.5;">
	<td><a href="/p/C3NDPUA8L"><code>C3NDPUA8L</code></a><span style="display:block;font-size:0.8em;line-height:1em;"><span style="color:darkred;" title="The project has no funds, you will work for free">no funds</span></span></td>
	<td>Zerocracy</td>
	<td></td>
	<td><a href="https://github.com/zerocracy/farm">zerocracy/farm</a>, <a href="https://github.com/zerocracy/datum">zerocracy/datum</a>, <a href="https://github.com/zerocracy/zerocracy.github.io">zerocracy/zerocracy.github.io</a></td>
	<td>Java, CSS, Shell, TeX, XSLT, HTML, Groovy, Ruby</td>
	<td style="text-align:right;">13</td>
	<td style="text-align:right;"><span style="text-decoration:line-through;color:darkred;">27/217</span><a href="#2"><sup>2</sup></a></td>
</tr>
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2069](https://github.com/zerocracy/farm/issues/2069), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
Job [#2069](https://github.com/zerocracy/farm/issues/2069) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2069](https://github.com/zerocracy/farm/issues/2069) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
