### ISSUE TITLE
notify_user must send to all aliases/links

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#207]
At the moment `notify_user.groovy` only sends a message to the user in Slack. This is not correct, since the user may have other aliases, like Telegram, for example. We must take them all from the People and notify the user through all of them.

**Comment by 0crat** [comment]
The job [#207](https://github.com/zerocracy/farm/issues/207) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#207](https://github.com/zerocracy/farm/issues/207), please stop working

**Comment by 0crat** [comment]
The job [#207](https://github.com/zerocracy/farm/issues/207) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 it was already implemented: `notify_user` script sends a message to all user's slack and telegram links.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/207#issuecomment-363075317))

@yegor256 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#207](https://github.com/zerocracy/farm/issues/207), please stop working

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#207` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#207](https://github.com/zerocracy/farm/issues/207) is now out of scope
