### ISSUE TITLE
A job without impediment is not removed from assignee after 10 days

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2072]
In https://github.com/llorllale/cactoos-matchers/issues/106, the job has been assigned for 11 days but it hasn't been removed from assignee.

I think it should have, no?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 @llorllale this was because the project is not funded:

https://github.com/zerocracy/farm/blob/master/src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy#L55-L60

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2072` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
