### ISSUE TITLE
0crat did not react to `quality good` and `status` commands

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2075]
[See](https://github.com/harvest-foundation/core/issues/490#issuecomment-500580253) the ticket and comments

**Expected result**: 0crat should react to `quality good` and `status` commands as usual

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua 0crat may be sometimes slow (especially on high load)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2075` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
