### ISSUE TITLE
Zerocrat Configuration Guide

### ISSUE THREAD

**Issue by hkarakose** [zerocracy/farm#2078]
Hello
I am trying to setup this project. I am already seeing the homepage. But I don't know how to add a project, add new members, etc.

Is there a configuration guide of this project?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@hkarakose[/z](https://www.0crat.com/u/hkarakose) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@hkarakose please check this page: https://www.zerocracy.com/pfaq.html

**Comment by hkarakose** [comment]
Thanks @g4s8. 
How do I create a PO user and advisor user with reputation > 1024? 

![image](https://user-images.githubusercontent.com/406291/59529537-f9bdcb00-8ee9-11e9-8326-81b13567d0ae.png)

**Comment by g4s8** [comment]
@hkarakose you need to find adviser first, just submit [RFP](https://www.0crat.com/rfp) and someone will answer you, adviser will help you to bootstrap the project in your Slack channel and assign you PO role, then you'll be able to manage your project.

**Comment by hkarakose** [comment]
@g4s8 I am trying to setup another instance of zerocrat software in AWS. How can I create initial users?

**Comment by g4s8** [comment]
@hkarakose it's out of scope of Zerocracy issues, if you set up the instance somewhere you need to manage the data by yourself.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2078` is not assigned, can't get performer

**Comment by zerocratsubs** [comment]
This was a question about open source github repo: https://github.com/zerocracy/farm.

If this is out of scope, where can I ask? 

Can you share dynamodb configuration of this tool?

**Comment by g4s8** [comment]
@zerocratsubs it's open source project - you can read sources and understand the schema from it. But explaining the setup and deployment process of this project is out of scope, because deployment is working as expected now, no need to change something.
