### ISSUE TITLE
There is an unrecoverable failure 0crat's side

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2079]
[See](https://github.com/ammaratef45/zold-flutter-client/pull/116#issuecomment-501874951)

> PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
0.47.5: CID: 3143e865-e8ad-4f10-9303-68a0512f7d84, Type: "Transfer shares"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2079` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
