### ISSUE TITLE
Wrong assumption in notify_user and notify_project

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#208]
At the moment both `notify_user.groovy` and `notify_project.groovy` make wrong assumption. They assume that project.toString() is the Slack channel ID. It is valid at the moment, but only for now. Let's make sure they get that information from `Catalog`. For each project there has to be a `<link rel="slack" href="C3NDPUA8L"/>`. We should find it and use.

Also, that link should be automatically added there during the `bootstrap.groovy` execution.

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3460](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#208](https://github.com/zerocracy/farm/issues/208) is now out of scope
