### ISSUE TITLE
Getting telegram notification about merged PR being in continue status

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2085]
Since today I'm getting telegram message from 0crat saying things like:
```
The job #26 (https://github.com/g4s8/ghman/issues/26) in ghman (https://www.0crat.com/p/CJT4R32Q3) is in CONTINUE status
```

It is a PR that was just merged, I don't think I should be getting this notification in this situation.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2085](https://github.com/zerocracy/farm/issues/2085) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2085](https://github.com/zerocracy/farm/issues/2085), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@victornoel it should be fixed in #2103 PR

**Comment by victornoel** [comment]
@g4s8 cool, thx

**Comment by 0crat** [comment]
Job [#2085](https://github.com/zerocracy/farm/issues/2085) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2085](https://github.com/zerocracy/farm/issues/2085) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
