### ISSUE TITLE
command links add github fails

### ISSUE THREAD

**Issue by SergeyKutsko** [zerocracy/farm#2087]
PID: 13110@ip-172-31-12-121, thread: pool-5-thread-41
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[66] groovy.lang.MissingPropertyException: No such property: ref for class: com.zerocracy.stk.pm.in.links.add_link

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@SergeyKutsko it was fixed in #2089 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2087` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
