### ISSUE TITLE
Typo ref instead of href

### ISSUE THREAD

**Issue by SergeyKutsko** [zerocracy/farm#2088]
https://github.com/zerocracy/farm/blob/ebf50a7381f0ca952373ce2575e97d179fcb97a4/src/main/groovy/com/zerocracy/stk/pm/in/links/add_link.groovy#L45

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@SergeyKutsko it was fixed in #2089 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2088` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
