### ISSUE TITLE
Show the list of currently active projects and their ARCs

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2092]
In our daily report to the PMO let's also show the list of active projects now (which have at least one transaction over the last 16 days) and their ARC names.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2092](https://github.com/zerocracy/farm/issues/2092), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2092` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.47.11`

**Comment by g4s8** [comment]
@yegor256 it should be fixed

**Comment by 0crat** [comment]
Job [#2092](https://github.com/zerocracy/farm/issues/2092) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2092](https://github.com/zerocracy/farm/issues/2092) is now out of scope
