### ISSUE TITLE
After receiving > 1024 points - I am not graduated 

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2113]
I have received 1027 points already, however, I am still NOT graduated and have @g4s8 as my mentor

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua as I can see you was graduated yesterday evening, check your profile page https://www.0crat.com/u/sereshqua
![scrot-2019-07-12-10:06:50](https://user-images.githubusercontent.com/1524988/61109198-0273d380-a48d-11e9-944f-89eda06e4f15.png)

**Comment by sereshqua** [comment]
@g4s8 yeap, it came up a bit later at 23:13 UKR time, but the amount of points that I have had by that time already was 1027.

May be I gave QA verdict to few tickets and 0crat processes that jobs first, rather than processing graduation job? I think as user gets 1024 point, he / she has to be graduated straightaway.

**Comment by g4s8** [comment]
@sereshqua it may be so, 0crat is iterating users for potential graduation every hour, but within one hour user may complete few jobs but it doesn't happen frequently. So this technical limitations is not easy to solve, but  it's hard to reproduce.

**Comment by sereshqua** [comment]
@g4s8 alright, so you think it is NOT worth adding to scope? may be with low priority?

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2113` is not assigned, can't get performer
