### ISSUE TITLE
The zerocrat fails to setting of the impediment

### ISSUE THREAD

**Issue by aivinog1** [zerocracy/farm#2117]
See this: https://github.com/yegor256/sibit/issues/35#issuecomment-511334744

I see a successful message of setting the impediment(https://github.com/yegor256/sibit/issues/35#issuecomment-511334699) and a failure message(https://github.com/yegor256/sibit/issues/35#issuecomment-511334744). I've checked my agenda and I see that this job have a hold status: 
![image](https://user-images.githubusercontent.com/25925932/61209143-251f1a00-a723-11e9-97ea-1f55f3f53a39.png).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2117](https://github.com/zerocracy/farm/issues/2117), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by aivinog1** [comment]
@g4s8 If it helps I have another one: https://github.com/yegor256/sibit/issues/36#issuecomment-511765769.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2117#issuecomment-511813325))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2117](https://github.com/zerocracy/farm/issues/2117) is [in scope](http://www.zerocracy.com/policy.html#14) for 23hr
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [23hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232117%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@aivinog1 it should be fixed in https://github.com/zerocracy/farm/commit/5922f8fa31ffce220771fe8b8db7c2c6c9aa4291

**Comment by 0crat** [comment]
Job [#2117](https://github.com/zerocracy/farm/issues/2117) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2117](https://github.com/zerocracy/farm/issues/2117) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
