### ISSUE TITLE
Make REV jobs truly not count for maximum size of agenda

### ISSUE THREAD

**Issue by scristalli** [zerocracy/farm#2123]
Currently, 0crat will assign you a `REV` job even if your agenda is full, as per [§3](http://www.zerocracy.com/policy.html#3).
However, `REV` jobs count for the maximum size of agenda if one already has them, so for instance if I already have 4 `REV` jobs and my maximum is 3, 0crat will not assign any `DEV` jobs to me.
I think that the rule should be symmetrical, i.e. `REV` jobs should not count at all when evaluating the limit.
Rationale: why should order in which I receive tasks influence my capability of completing them?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2123` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
