### ISSUE TITLE
Wrong project count for users in team page

### ISSUE THREAD

**Issue by scristalli** [zerocracy/farm#2127]
Everyone is marked has being part of 0 projects, see the screenshot.

![zerocracy-team-issue](https://user-images.githubusercontent.com/7326295/62876210-bbdff600-bd24-11e9-8d4f-7f4a8575807b.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#2127](https://github.com/zerocracy/farm/issues/2127) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2127](https://github.com/zerocracy/farm/issues/2127), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.7`

**Comment by g4s8** [comment]
@scristalli it should be fixed in https://github.com/zerocracy/farm/commit/90b6f51f6577b02cd14457af837d02f94b7dba21

**Comment by 0crat** [comment]
Job [#2127](https://github.com/zerocracy/farm/issues/2127) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2127](https://github.com/zerocracy/farm/issues/2127) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
