### ISSUE TITLE
Zerocrat is not responding in Telegram chat

### ISSUE THREAD

**Issue by vzurauskas** [zerocracy/farm#2129]
I tried the following commands in Zerocrat Telegram chat (time is in UTC):

10:41 `/option maxRevJobsInAgenda 2`
11:05 `Hi`

It's 11:37 now and Zerocrat hasn't responded yet.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by vzurauskas** [comment]
Works now.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2129` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
