### ISSUE TITLE
Every project in project board is labeled as "sandbox"

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2130]
Every project in there has sandbox label under the title, which should not happen. There were 3 sandbox projects only before.

<img width="1042" alt="Screenshot 2019-08-23 at 13 16 52" src="https://user-images.githubusercontent.com/10097808/63585703-64ede280-c5a8-11e9-90d7-1672ff85dd76.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.3`

**Comment by g4s8** [comment]
@sereshqua thanks, it's fixed in https://github.com/zerocracy/farm/commit/d42ad30d252e73cc6be2f3eac5bb022f28a5dd2b

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2130` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
