### ISSUE TITLE
Every user in ZC has 0 projects assigned

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2131]
Please see the screen

<img width="499" alt="Screenshot 2019-08-30 at 15 18 11" src="https://user-images.githubusercontent.com/10097808/64020062-58820080-cb39-11e9-817f-541ecaddf648.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2131](https://github.com/zerocracy/farm/issues/2131) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by scristalli** [comment]
@g4s8 this is a duplicate of #2127

**Comment by g4s8** [comment]
@scristalli correct

**Comment by 0crat** [comment]
The job [#2131](https://github.com/zerocracy/farm/issues/2131) is now out of scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2131` is not assigned, can't get performer
