### ISSUE TITLE
Status Update doesn’t work 

### ISSUE THREAD

**Issue by disanza** [zerocracy/farm#2132]
When asking 0crat for a status update `status`, it is returning an error.

![DC61DC89-2823-4226-AC79-797925962A15](https://user-images.githubusercontent.com/9894480/64184162-0d1d6a00-ce39-11e9-98fb-2e913873908e.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@disanza[/z](https://www.0crat.com/u/disanza) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@disanza we need to make error messages more friendly, but this error means that the're no such command for profile management. `status` command should be used right in the ticket, not in the chat. (see next message)

**Comment by g4s8** [comment]
@0crat status

**Comment by disanza** [comment]
Ok. Thank you!

**Comment by 0crat** [comment]
Job [#2132](https://github.com/zerocracy/farm/issues/2132) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2132#issuecomment-527497374))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2132](https://github.com/zerocracy/farm/issues/2132) is [in scope](http://www.zerocracy.com/policy.html#14) for 8s
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232132%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2132` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#2132](https://github.com/zerocracy/farm/issues/2132) is now out of scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @disanza[/z](https://www.0crat.com/u/disanza)
