### ISSUE TITLE
Terminator should track Project by their pid instead of their Object

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2143]
Following the investigation in #2119, we should have the `Map` inside `Terminator` track `Project` by their pid instead of their `Object` because we are never sure that all the `Project` classes properly implements `equals`/`hashCode`.

By the way this is related to our discussion on telegram about envelopes and `equals`, `Map`s are not meant to hold behavioural objects but data that is clearly hashable.

This could/should solve some inconsistency problem in the behaviour of 0crat.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2143](https://github.com/zerocracy/farm/issues/2143) is now in scope, role is `DEV`

**Comment by victornoel** [comment]
@g4s8 closing this since Terminator was removed (see #2249)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2143` is not assigned, can't get performer
