### ISSUE TITLE
Terminator should rely on a ConcurrentMap

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2144]
Following the investigation in #2119, `Terminator` should rely on the `ConcurrentMap` abstraction to insert elements in it instead of using synchronized, it should improve performance and maybe even correctness in some odd cases.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2144](https://github.com/zerocracy/farm/issues/2144) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 looking at the code it seems this has been done at one point: https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/farm/sync/Terminator.java#L82

btw there is still #2143 on the same subject :)

**Comment by victornoel** [comment]
@g4s8 but I see that the code does not use the abstractions provided by concurrent map to ensure atomicity, I believe Terminator is still bugged, see for example: https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/farm/sync/Terminator.java#L113, one should use compute if absent or put if absent.

**Comment by g4s8** [comment]
@victornoel yes, please check #2249 terminator is not used anymore. All synchronization is implemented inside one method now, so there're no needs in additional classed to handle unlocking

**Comment by victornoel** [comment]
@g4s8 ah excellent, so we can close this issue I suppose? (or keep it open to track the deletion of `Terminator` ^^)

**Comment by victornoel** [comment]
@g4s8 ah, ok, sorry I didn't read the PR, it was about removal, let me close this then :)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2144` is not assigned, can't get performer
