### ISSUE TITLE
Terminator should be stress tested.

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2145]
Following the investigation in #2119.
.The behaviour of `Terminator` is not easy to understand, in order to validate it is actually doing its job, we should stress test it.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2145](https://github.com/zerocracy/farm/issues/2145) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 closing this since Terminator was removed (see #2249)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2145` is not assigned, can't get performer
