### ISSUE TITLE
Use fair ReentrantLocks to avoid starvation

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2146]
Following the investigation in #2119.

The currently used implementation for `Locks` is based on `ReentrantLock` but it is not using the fair scheduling.

This can lead to thread starving and thus timeouts during the handling of lots of request by 0crat.

We should use fair threading, this will make the behaviour of 0crat more deterministic (request will be handled in more or less the order of arrival) and will prevent starvation.

This means that this will reduce a lot the chances of having request handling timeouts.

This is a very small change with potentially a visible impact IMHO.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2146](https://github.com/zerocracy/farm/issues/2146), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@victornoel thanks, it should be fixed in https://github.com/zerocracy/farm/commit/af60a59ffca78a212aa4d7aa7158921e50607e23

**Comment by 0crat** [comment]
Job [#2146](https://github.com/zerocracy/farm/issues/2146) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2146](https://github.com/zerocracy/farm/issues/2146) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
