### ISSUE TITLE
Update performer speed on refuse

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2147]
Let's update job performer's speed metric on refuse, so if user refuses a job right after he/she get it, it should affect the speed in positive way, but if it was cancelled by delay or user refused it after few days, then it should negatively impact his metrics. REF:  https://t.me/zerocracy/7869

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2147](https://github.com/zerocracy/farm/issues/2147), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/ce834f5ee6213892813ecf71dc682807fe9631a6

**Comment by 0crat** [comment]
Job [#2147](https://github.com/zerocracy/farm/issues/2147) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2147](https://github.com/zerocracy/farm/issues/2147) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
