### ISSUE TITLE
Build is broken: pdd.xml is empty

### ISSUE THREAD

**Issue by magwas** [zerocracy/farm#2152]
I tried to build the project. I have created a docker image based on what I have found in travis.yml,
and ran .travis/run.sh

I got this:

```
[INFO] Qulice quality check completed in 22s
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (default) @ farm ---
[INFO] Executing tasks

main:
Thread.run(Thread.java:748)     [exec] ESC[32m<?xml version="1.0"?>\nESC[0m
     [exec] Invalid XML formatting in /build/pdd.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

in checking pdd.xml , it is empty.

The Dockerfile for the build environment looks like this:

```
FROM kodekonveyor/toolchain:master

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 58712A2291FA4AD5
RUN echo 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
RUN apt-get update
RUN apt-get -y remove openjdk-11-jre-headless mongodb-org
RUN apt-get -y install --allow-unauthenticated mongodb-org openjdk-8-jdk ruby-dev zlib1g-dev
RUN gem install pdd -v 0.20.5
RUN gem install xcop -v 0.6


ENTRYPOINT ["/usr/local/toolchain/tools/entrypoint"]
CMD ["/bin/bash"]

```

I guess I am missing something from the build environment.
What do I miss?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@magwas[/z](https://www.0crat.com/u/magwas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@magwas you need to run `mvn clean install -Pqulice` to build it, not `.travis/run.sh`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2152` is not assigned, can't get performer
