### ISSUE TITLE
Don't send adviser payments for free projects

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2153]
0crat should not send adviser payments for free projects. Instead of that, it should send a message that user could receive a bonus if the project was not free.

// cc @yegor256

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2153](https://github.com/zerocracy/farm/issues/2153), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2153` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.11`

**Comment by g4s8** [comment]
It should be fixed in https://github.com/zerocracy/farm/commit/f0c941fe872e162097b4b4447d510a607017b40c

**Comment by 0crat** [comment]
Job [#2153](https://github.com/zerocracy/farm/issues/2153) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2153](https://github.com/zerocracy/farm/issues/2153) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
