### ISSUE TITLE
If 0crat is down, it doesn't pay for a new ticket that was created -> assigned -> completed

### ISSUE THREAD

**Issue by SilasReinagel** [zerocracy/farm#2156]
Ticket was opened, assigned, and completed when 0crat apparently wasn't running.

See this card: https://github.com/EnigmaDragons/ProjectNeon/issues/131

This raises 2 questions:
1) Why is 0crat down so often? 
2) Why can't 0crat figure out whom to pay?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by SilasReinagel** [comment]
@g4s8 I am mistaken. 0crat was just down and runs very slowly. Apparently it eventually resolved the issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2156` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
