### ISSUE TITLE
0crat over pays for 0pdd-Opened Issue

### ISSUE THREAD

**Issue by SilasReinagel** [zerocracy/farm#2159]
0pdd opens a ticket for a puzzle explicitly setting the budget to 15mins.

0crat assigns issue using a budget of 30 minutes.

https://github.com/EnigmaDragons/ProjectNeon/issues/102

This is blatantly wrong! Yet another instance of 0crat stealing money.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@SilasReinagel 0crat didn't steal anything because it's not receiving money from your project. 0crat using default budget 30 minutes for each ticket, see https://www.zerocracy.com/policy.html#5

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2159` is not assigned, can't get performer

**Comment by SilasReinagel** [comment]
@g4s8 So, you're saying that 0pdd and 0crat are supposed to be incompatible?

If that's true, where is the support for 0crat to request a refund? I don't see it in the policy.
