### ISSUE TITLE
Setting rate at telegram after second application via github is broken

### ISSUE THREAD

**Issue by lavinj87** [zerocracy/farm#2160]
My original github name is lavinj.
Started the telegram bot being my username lavinj.
Changed my github account name to lavinj87.
Changed my telegram user name to lavinj87 as well.
I've applied a second time to 0cracy with this new account name.

When I issue a rate command, the telegram bot still refers to me as lavinj.

I would like to see that the telegram bot refers to me as lavinj87, so that I can interact with the actual 0cracy profile.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@lavinj87[/z](https://www.0crat.com/u/lavinj87) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@lavinj87 I've reset Telegram handle for `lavinj` user. 0crat Telegram bot will ask to authorize with next bot command, please follow the link and login with new user. Should work. Let me know about the result.

**Comment by lavinj87** [comment]
@g4s8 Worked like charm. Thank you very much.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2160` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
