### ISSUE TITLE
0crat did not react to QA verdict 

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2162]
I gave a QA verdict in one of the tickets - [here](https://github.com/yegor256/cactoos/pull/1187#issuecomment-538265314), however, nothing happened after 1 day

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua it looks like a temporary failure, 0crat sometimes loose Github comments due to network issues.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2162` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
