### ISSUE TITLE
0crat failed to retry payment after 1 attempt

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2164]
0crat is failing to retry payment when project is not funded after 1 attempt with message:
```
PID: 4@119e0eac-38c6-45e0-a3db-d696d0d82624, thread: pool-5-thread-7
com.jcabi.xml.XSLDocument[400] java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Duplicated flow detected, something is wrong: "Close job; Finish order; Order was finished; Remove job from WBS; Job removed from WBS; Make payment; Make payment; Make payment", seems to be an endless recursion in claims, Processing terminated by xsl:message at line 28 in file:///; SystemID: file:///; Line#: 28]
net.sf.saxon.expr.instruct.Message[223] net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 28 in file:///
```

See: https://github.com/sunsofterp/portal/pull/388

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.17`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2164](https://github.com/zerocracy/farm/issues/2164), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/d5ea5d105ab43218bb8a9eda699174f00e620f3a https://github.com/zerocracy/farm/commit/8b9eecffcfe8e4534d07ca537e5a59c75ac4e6ab

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job [#2164](https://github.com/zerocracy/farm/issues/2164) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2164](https://github.com/zerocracy/farm/issues/2164) is now out of scope

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
