### ISSUE TITLE
ExecFor.java:32-37: - Lets introduce new `Farm`,...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#2165]
The puzzle `2150-34dfa09b` from #2150 has to be resolved: 

https://github.com/zerocracy/farm/blob/bc26c026283fd0979a8482c827ef3df0cf096ed3/src/main/java/com/zerocracy/claims/proc/ExecFor.java#L32-L37

The puzzle was created by Kirill on 09-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2165](https://github.com/zerocracy/farm/issues/2165) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2165` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2165](https://github.com/zerocracy/farm/issues/2165), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `2150-34dfa09b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2170](https://github.com/zerocracy/farm/issues/2170) is still not solved.

**Comment by 0crat** [comment]
Job [#2165](https://github.com/zerocracy/farm/issues/2165) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#2165](https://github.com/zerocracy/farm/issues/2165) is now out of scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.4`

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2170](https://github.com/zerocracy/farm/issues/2170), [#2171](https://github.com/zerocracy/farm/issues/2171) are still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.7`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.7`

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
