### ISSUE TITLE
0crat can't seem to retrieve policy 

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2168]
This happened here: https://github.com/zold-io/java-api/issues/38#issuecomment-540876224

It said:
```
PID: 4@9b7f0750-f619-44d8-bdbc-fcfc0dc4b9ec, thread: pool-3-thread-4
com.zerocracy.Policy[105] java.lang.IllegalArgumentException: Policy item '6.penalty' not found

0.49.18: CID: 9cd01e2e-1058-4c0d-96e9-a799b4af09e3, Type: "Order was canceled"
```

In the end it didn't penalize the user.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel it should be fixed after https://github.com/zerocracy/farm/pull/2167#issuecomment-541155251 merge

**Comment by victornoel** [comment]
@g4s8 ok, thx, let me close this then

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2168` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
