### ISSUE TITLE
Print project queue metrics in `/guts`

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2175]
Let's print queue metrics in guts:
 - queue speed - amount of processed claims per second for last hour
 - brigade load - 1hour / time spent by brigade
 - brigade speed - time spent by brigade / amount of claims for last hour

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2175](https://github.com/zerocracy/farm/issues/2175), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2175` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.9`

**Comment by g4s8** [comment]
Done in https://github.com/zerocracy/farm/commit/a8cb2947c909479d8c632bf13799ef6913a36dc5 https://github.com/zerocracy/farm/commit/f3f8c202d6f1e10f2352b7dd711b5fc4377ca4e6

**Comment by 0crat** [comment]
Job [#2175](https://github.com/zerocracy/farm/issues/2175) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2175](https://github.com/zerocracy/farm/issues/2175) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
