### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2176]
Let's cleanup a code which is never used

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2176](https://github.com/zerocracy/farm/issues/2176), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2176` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Done in https://github.com/zerocracy/farm/commit/ae6b1457711c672967d8526d52da66af8e622f53

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#2176](https://github.com/zerocracy/farm/issues/2176), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#2176](https://github.com/zerocracy/farm/issues/2176) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bfb660cf-26fa-4ff3-bf0a-6258ad1da898, thread: PQ-C3NDPUA8L
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.50.30](https://github.com/zerocracy/farm): CID: [be4e3499-88f3-45f4-b08d-4baafcb49901](https://www.0crat.com/footprint/C3NDPUA8L/be4e3499-88f3-45f4-b08d-4baafcb49901), Type: "Order was canceled"
