### ISSUE TITLE
Try using read-write locks

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2177]
Try to replace some locks with `ReadWriteLock`s:
`project.acq(file, RW)` or `project.acq(flle, RO)`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.10`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2178](https://github.com/zerocracy/farm/issues/2178) is still not solved.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2177](https://github.com/zerocracy/farm/issues/2177), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2177` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Done in https://github.com/zerocracy/farm/commit/1147461035c15dd3049630de8cf284381722fb07

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.11`

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#2178](https://github.com/zerocracy/farm/issues/2178) is solved here.

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.13`

**Comment by 0crat** [comment]
The job [#2177](https://github.com/zerocracy/farm/issues/2177) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
