### ISSUE TITLE
Project.java:32-36: Continue replacing...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#2178]
The puzzle `2177-1b35d377` from #2177 has to be resolved: 

https://github.com/zerocracy/farm/blob/1147461035c15dd3049630de8cf284381722fb07/src/main/java/com/zerocracy/Project.java#L32-L36

The puzzle was created by @g4s8 on 15-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#2178](https://github.com/zerocracy/farm/issues/2178) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2178](https://github.com/zerocracy/farm/issues/2178), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `2177-1b35d377` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#2178](https://github.com/zerocracy/farm/issues/2178) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2178](https://github.com/zerocracy/farm/issues/2178) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
