### ISSUE TITLE
0crat is responding TM too long

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2180]
0crat bot is responding for Telegram messages for too long.

**Comment by g4s8** [comment]
@rultor release, tag=`0..50.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.14`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2180](https://github.com/zerocracy/farm/issues/2180), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2180` already assigned to @g4s8, can't assign to @g4s8

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.14`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.15`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.15`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.16`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.16`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.18`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.19`

**Comment by g4s8** [comment]
Fixed in https://github.com/zerocracy/farm/commit/762f2aa49ddcfe063117261d1aaf8f69f151f141

**Comment by 0crat** [comment]
Job [#2180](https://github.com/zerocracy/farm/issues/2180) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#2180](https://github.com/zerocracy/farm/issues/2180) is now out of scope
