### ISSUE TITLE
SQS: put message back if project queue is full

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2183]
Let's check project queue size after polling SQS message and put it back if queue is full.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2183](https://github.com/zerocracy/farm/issues/2183), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2183` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.20`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.22`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.22`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.22`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.23`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.24`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.25`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.26`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.26`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.27`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.28`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.29`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.30`

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job [#2183](https://github.com/zerocracy/farm/issues/2183) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#2183](https://github.com/zerocracy/farm/issues/2183) is now out of scope
