### ISSUE TITLE
migrate to Dokku

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2185]
Let's migrate to Dokku from Heroku. I will take care of this.

**Comment by yegor256** [comment]
@rultor release, tag is `0.50.31`

**Comment by yegor256** [comment]
@rultor release, tag is `0.50.31`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2185` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
