### ISSUE TITLE
Unable to hold the issue

### ISSUE THREAD

**Issue by iakunin** [zerocracy/farm#2188]
# Steps to reproduce
I'm trying to hold the issue (see https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545396374).

And 0crat said that it's already on hold (https://github.com/yegor256/cactoos-http/issues/99#issuecomment-545404469).

# Expected behavior
1. Issue has the label "waiting".
1. I can see in my [agenda-page](https://www.0crat.com/u/iakunin/agenda) that [job 99](https://github.com/yegor256/cactoos-http/issues/99) is on hold

# Actual behavior
1. Issue has no label "waiting".
1. I cannot see the result in my Agenda-page. 

Screenshot of my Agenda-page:
![image](https://user-images.githubusercontent.com/10430347/67494313-ad497f80-f681-11e9-93cc-13d95f170bbf.png)

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by iakunin** [comment]
Not actual anymore.
