### ISSUE TITLE
Election is very slow for huge WBS

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2194]
Election process is very slow for projects with huge WBS, e.g. election for `C3NDPUA8L` project with 250 WBS items takes about 15 minutes.

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.33`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.34`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2195](https://github.com/zerocracy/farm/issues/2195) is still not solved.

**Comment by g4s8** [comment]
Election was disabled for huge WBS: https://github.com/zerocracy/farm/commit/a80b4586a1f39440e693169d4bac70e94bba77d6, todo submitted: https://github.com/zerocracy/farm/issues/2195

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2194` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#2195](https://github.com/zerocracy/farm/issues/2195) is solved here.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2195](https://github.com/zerocracy/farm/issues/2195) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#unknown]() is still not solved.
