### ISSUE TITLE
elect_performer.groovy:63-67: Election is disabled for...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#2195]
The puzzle `2194-2e5e4df3` from #2194 has to be resolved: 

https://github.com/zerocracy/farm/blob/4a2fe9940b36f978d7f8943ca44589e2cea0f513/src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy#L63-L67

The puzzle was created by Yegor Bugayenko on 04-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `2194-2e5e4df3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2195` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
