### ISSUE TITLE
0crat is not penalizing for delays

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2196]
As happened in https://github.com/yegor256/cactoos-http/pull/100

@0crat Didn't unassigned the reviewer and the penalty was not applied, making the ticket to become locked / stuck.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso 0crat is not resigning code reviewers, since they can't control the speed of the ticket, e.g. when PR submitter delays CR fixes
See:

https://github.com/zerocracy/farm/blob/master/src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy#L84-L86

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2196` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
