### ISSUE TITLE
Agenda shows me negative amount of time (and in minutes)

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#2197]
Agenda shows me negative amount of time (and in minutes), as you can see in the picture below:

![image](https://user-images.githubusercontent.com/1964562/68515372-7a95ae80-025f-11ea-8f6f-51a7d31fcd68.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
Duplicate of #1686

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2197` is not assigned, can't get performer
