### ISSUE TITLE
Punish architect for tasks boosting

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#220]
0crat should add negative points to architect if he boosted a task.
Policy should be updated also.

**Comment by 0crat** [comment]
The job [#220](https://github.com/zerocracy/farm/issues/220) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#220](https://github.com/zerocracy/farm/issues/220), please stop working

**Comment by 0crat** [comment]
The job [#220](https://github.com/zerocracy/farm/issues/220) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/421116519). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-366430134))

@neonailol Job [#220](https://github.com/zerocracy/farm/issues/220) is not assigned, can't put it on hold

**Comment by yegor256** [comment]
@neonailol as I see, the PR is not merged yet. How can I help?

**Comment by neonailol** [comment]
@yegor256 https://github.com/zerocracy/farm/pull/585#issuecomment-366781290
Rultor failed to do it, bu all checks are suceeded

**Comment by yegor256** [comment]
@neonailol that's your business :) Rultor is part of the process. Until the PR is merged, the job is not completed. Why it happens, we don't really care.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-368302011))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#220](https://github.com/zerocracy/farm/issues/220) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
    * @neonailol[/z](https://www.0crat.com/u/neonailol): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23220%27%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#220](https://github.com/zerocracy/farm/issues/220) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/581022730). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting #674

**Comment by 0crat** [comment]
> @0crat waiting #674  ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-369351393))

@amihaiemil The impediment for [#220](https://github.com/zerocracy/farm/issues/220) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@g4s8 PR was merged, can we close this? :)

**Comment by g4s8** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/220#issuecomment-370864289). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
1. >Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

2. >All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please make the [registered impediment](https://github.com/zerocracy/farm/issues/220#issuecomment-369351393) more informative.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/220#issuecomment-370881569). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by amihaiemil** [comment]
@ypshenychka done, updated both comments.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/220#issuecomment-370883052). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by ypshenychka** [comment]
@amihaiemil Thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/220#issuecomment-370887481). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-370887512))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-370887512))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/qa/complete_qa_review.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.log.PreFormatter[155] java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-371209334))

@ypshenychka Thanks, but `QA` review is not required in this job

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-371275835))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#220](https://github.com/zerocracy/farm/issues/220) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
    * @neonailol[/z](https://www.0crat.com/u/neonailol): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23220%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@ypshenychka can you try again and open an Issue if it doesn't work? :D

**Comment by ypshenychka** [comment]
@amihaiemil Please see @yegor256 [comment](https://github.com/zerocracy/farm/issues/743#issuecomment-371194735).

**Comment by amihaiemil** [comment]
@ypshenychka thanks. Are you recording them or should I also keep track? :)

**Comment by ypshenychka** [comment]
@amihaiemil double control is always better :)

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-371892782))

@ypshenychka Thanks, but quality review is not required in this job

**Comment by amihaiemil** [comment]
@yegor256 could you do the payments here and take it out of scope?

**Comment by yegor256** [comment]
@0crat status

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-372258958))

@yegor256 The job [#220](https://github.com/zerocracy/farm/issues/220) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by ypshenychka** [comment]
@0crat ping

**Comment by 0crat** [comment]
> @0crat ping ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-372368746))

@ypshenychka Can't understand "ping", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/220#issuecomment-372354537))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/awards/notify_about_award_points.groovy
sun.reflect.GeneratedMethodAccessor197[-1] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@amihaiemil Did you get paid for this issue?

**Comment by amihaiemil** [comment]
@ypshenychka yes, according to the "Awards" page I was paid 16h ago, same as you :)
