### ISSUE TITLE
0crat assigns more jobs than allowed

### ISSUE THREAD

**Issue by fanifieiev** [zerocracy/farm#2215]
I have only 3 max jobs that can be assigned to me. 
Today `0crat `assigned 2 more.
![image](https://user-images.githubusercontent.com/3167940/71996890-fd5cca80-320a-11ea-99ab-1991dbf9b847.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@fanifieiev `REV` jobs has the highest priority, 0crat doesn't count your agenda size on assigning `REV` jobs, see [policy](https://www.zerocracy.com/policy.html#3):
> The maximum allowed size of agenda depends on your reputation:
>
>    3 jobs if less than +512 points,
>    8 if less than +2048,
>    16 if less than +4096,
>    24 otherwise;
>
> The size of agenda doesn’t matter if the job is a code review;

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2215` is not assigned, can't get performer

**Comment by fanifieiev** [comment]
@g4s8 Thanks, got it.
