### ISSUE TITLE
Zerocrat can't see my Github account

### ISSUE THREAD

**Issue by vzurauskas** [zerocracy/farm#2216]
Zerocrat just told me this:

```
We are very sorry, but we failed to pay you $x.xx for #xxx: "Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "vzurauskas" doesn't exist";
```

"vzurauskas" does exist, here it is: https://github.com/vzurauskas

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vzurauskas[/z](https://www.0crat.com/u/vzurauskas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@vzurauskas this error message comes from WTS API, so please re-submit this ticket here: https://github.com/zold-io/wts.zold.io/

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2216` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by vzurauskas** [comment]
@g4s8 Ok, thanks.
