### ISSUE TITLE
Reputation points were dropped by 0crat by no reason

### ISSUE THREAD

**Issue by fanifieiev** [zerocracy/farm#2217]
On Jan 13, 2020 I had +390 points in total(telegram message as a prove below), but today I am having only +360. Looks like one or two records were lost from my points history.
![image](https://user-images.githubusercontent.com/3167940/72351394-42bb4500-36ae-11ea-93bc-6d562424df0f.png)

![image](https://user-images.githubusercontent.com/3167940/72351426-52d32480-36ae-11ea-921d-9da106050b99.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@fanifieiev most probably it was dropped by 90-days rule: https://www.zerocracy.com/policy.html#18

> . Zerocrat takes into account only the points you earned over the last 90 days.

**Comment by fanifieiev** [comment]
@g4s8 Oh, that is right. Sorry, forgot about that rule.
Closing.

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2217` is not assigned, can't get performer
