### ISSUE TITLE
0crat/0pdd is not closing issue for merged PR.

### ISSUE THREAD

**Issue by fanifieiev** [zerocracy/farm#2218]
The issue: [998 ](https://github.com/yegor256/takes/issues/998) is not being closed, even though its PR: [1001](https://github.com/yegor256/takes/pull/1001) has been merged and finished.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@fanifieiev 0pdd bot is not a part of Zerocracy projects, please re-submit it here: https://github.com/yegor256/0pdd

**Comment by fanifieiev** [comment]
@g4s8 Thanks, moving this issue to https://github.com/yegor256/0pdd

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2218` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
