### ISSUE TITLE
restart

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2219]

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.39`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.39`

**Comment by g4s8** [comment]
@rultor release, tag=`0.50.40`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2219` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
