### ISSUE TITLE
Github links in slack

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#222]
Slack bot should post link to github ticket instead of job id in all possible messages.

**Comment by 0crat** [comment]
The job [#222](https://github.com/zerocracy/farm/issues/222) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472017250). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@g4s8 hi. Can you put an example of how this link is outputted in slack? The thing is that the message, that is used to be published using link:
> <param name="job">gh:test/test#1</param>

And it is used for example in `notify_abaout_award_points.groovy` like this:
```groovy
String job = claim.param('job')
new Par(
        farm,
        'You got %+d point(s) in the job %s in %s,',
        'your total is [%+d](/u/%s/awards), see §18: %s'
      ).say(points, job, project.pid(), awards.total(), login, reason)
```

So if slack doesn't understand the format of `gh:test/test#1` such links, then saving full link `https://github.com/test/test/issues/1` should resolve this issue. WDYT?

**Comment by g4s8** [comment]
@yegor256 @t-izbassar looks like this bug is outdated, now github links in slack are ok

**Comment by t-izbassar** [comment]
@g4s8 close issue then?

**Comment by t-izbassar** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@t-izbassar sure, closing

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#222](https://github.com/zerocracy/farm/issues/222) is now out of scope
