### ISSUE TITLE
0crat has not reacted to quality verdict in 15 days of time

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2220]
Please check the [issue](https://github.com/yegor256/cactoos/issues/1262#issuecomment-571909199)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2220` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
