### ISSUE TITLE
0crat failed to pay debt (GitHub user "iakunin" doesn't exist)

### ISSUE THREAD

**Issue by iakunin** [zerocracy/farm#2222]
> We tried to pay your debt of $34.80, but failed (Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "iakunin" doesn't exist); don't worry, we will retry very soon

I received this message from Zecocrat telegram-bot multiple times:
1. 2020-01-23T23:46
1. 2020-01-24T00:47
1. 2020-01-24T01:53
1. 2020-01-24T02:49
1. 2020-01-24T10:14
1. 2020-01-24T10:53
1. 2020-01-24T11:43
1. 2020-01-24T12:44
1. 2020-01-24T13:48
1. 2020-01-24T15:56
1. 2020-01-25T13:14

At the same time I can log in into https://wts.zold.io using my github account.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@iakunin this messages comes from WTS API, 0crat just shows this error response from WTS. Please submit it here: https://github.com/zold-io/wts.zold.io/ or ask via Telegram: https://t.me/zold_io

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2222` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
@g4s8 many thanks for explanation
