### ISSUE TITLE
Failed to pay debt, Zerocracy cannot find Github user

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#2224]
I have been getting the following error today repeatedly:

```
We tried to pay your debt of $xx.xx, but failed (Failed to pay: Zold payment failed; code=500 error=E189: GitHub user "carlosmiranda" doesn't exist); don't worry, we will retry very soon
```

I can log in to `0crat.com` and `wts.zold.io` just fine using my Github ID `carlosmiranda` in the meantime, so I am not sure why we are getting this error.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@carlosmiranda it's not Zerocracy issue, please see #2222

**Comment by carlosmiranda** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2224` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
