### ISSUE TITLE
Unrecoverable failure com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by fanifieiev** [zerocracy/farm#2227]
The issue was raised in scope of the task [149](https://github.com/llorllale/cactoos-matchers/issues/149).
The issue was resigned from me and then 0crat fired a failure message shown
[HERE](https://github.com/llorllale/cactoos-matchers/issues/149#issuecomment-581746132).
The pull request of this task was successfully merged but I have not received any points for this task.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2227](https://github.com/zerocracy/farm/issues/2227), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.51.2`

**Comment by g4s8** [comment]
@fanifieiev it should be fixed in #2228 PR

**Comment by fanifieiev** [comment]
> @fanifieiev it should be fixed in #2228 PR

@g4s8 Thanks

**Comment by 0crat** [comment]
Job [#2227](https://github.com/zerocracy/farm/issues/2227) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
