### ISSUE TITLE
Feature request: silent mode 

### ISSUE THREAD

**Issue by Sammers21** [zerocracy/farm#2236]
I would propose a silent mode feature. When enabled, @0crat only assign and tag issues/pr's, without any chatting.

As a result, @0crat would not turn github notifications into a trashcan. 

@g4s8, @yegor256 what do you think about it?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2236](https://github.com/zerocracy/farm/issues/2236), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by g4s8** [comment]
@rultor release, tag=`0.51.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.51.9`

**Comment by g4s8** [comment]
@Sammers21 it should be fixed in `0.51.9` release

**Comment by 0crat** [comment]
Job [#2236](https://github.com/zerocracy/farm/issues/2236) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by Sammers21** [comment]
@g4s8 , where I can found documentation on this mode?

**Comment by g4s8** [comment]
@Sammers21 it should be silent by default

**Comment by Sammers21** [comment]
@g4s8, how to check whether it silent or not?
