### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2250]
0crat files to open new files. It seems some files are not closed correctly. The error:
```
/tmp/farm_1230671004451623544.s3 (Too many open files)
```
https://sentry.io/organizations/zerocracy/issues/1583048658/?project=193755&query=is%3Aunresolved

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.1`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2250](https://github.com/zerocracy/farm/issues/2250), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.5`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.14`

**Comment by 0crat** [comment]
Job [#2250](https://github.com/zerocracy/farm/issues/2250) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't set title

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.14`
