### ISSUE TITLE
0crat ignores QA and assignee does not get paid

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2252]
Hi,

This happened twice to me already in the last days:
- https://github.com/yegor256/cactoos/pull/1321
- https://github.com/yegor256/cactoos/issues/1304

An because those are free projects, I can't even get the points from ARC (see https://github.com/yegor256/cactoos/issues/1304#issuecomment-601930582).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel as I can see you got 20 rep points for this job: https://www.0crat.com/footprint/C63314D6Z/617e9b90-eeef-4ff6-b403-011ea762ffba
I started to remove 0crat noise from Github tickets (such as reputation updates comments), but you are still able to check it in Telegram bot or at awards page: https://www.0crat.com/u/victornoel/awards

**Comment by victornoel** [comment]
@g4s8 indeed, I verified and it is the case.

I wonder if it is such a good idea to remove any feedback from the bot (maybe simply remove the scope tag only after QA has been done?) because even QA was confused by the situation.

Maybe @sereshqua can chip in to give an opinion?

**Comment by g4s8** [comment]
@victornoel @sereshqua we can't keep the job in scope for QA review, since the job was closed by the definition of done (it's logically incorrect to keep finished jobs in WBS). Maybe we can add `QA` github label when we put the job in QA stage and remove this label after verdict, WDYT?

**Comment by sereshqua** [comment]
@g4s8 @victornoel hello! thanks for tagging me; I believe adding / removing `QA` is a good solution

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2252](https://github.com/zerocracy/farm/issues/2252), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.52.15`

**Comment by g4s8** [comment]
@victornoel @sereshqua please check https://github.com/artipie/nuget-adapter/pull/65#event-3195691370 is it better now?

**Comment by victornoel** [comment]
@g4s8 it's great yes, I will let @sereshqua conclude since he is the primary stakeholder here :)

**Comment by sereshqua** [comment]
@g4s8 well done!

**Comment by 0crat** [comment]
Job [#2252](https://github.com/zerocracy/farm/issues/2252) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't set title

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
