### ISSUE TITLE
0crat does not add the scope and/or waiting labels to ticket

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2258]
In this ticket: https://github.com/llorllale/cactoos-matchers/issues/148

0crat never added the scope label, but also didn't add the waiting label.

While not adding the scope label is ok, because the bot told us the job was in scope, it didn't tell us anything about the task being on wait (I received the notification via the bog though).

Now there is no way to know the status of this issue except by reading its history or asking the status to 0crat bot.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 it seems to have been transient, let me close this.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2258` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
