### ISSUE TITLE
Slack direct messages

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#226]
Slack bot should understand direct messages without mentioning.
At this moment `@0crat2 hello` is working fine, but `hello` is not.

**Comment by 0crat** [comment]
The job [#226](https://github.com/zerocracy/farm/issues/226) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/581025831). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting #675

**Comment by 0crat** [comment]
> @0crat waiting #675  ([here](https://github.com/zerocracy/farm/issues/226#issuecomment-369351095))

@amihaiemil The impediment for [#226](https://github.com/zerocracy/farm/issues/226) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat waiting #676

**Comment by 0crat** [comment]
> @0crat waiting #676 ([here](https://github.com/zerocracy/farm/issues/226#issuecomment-369516306))

@amihaiemil Job [#226](https://github.com/zerocracy/farm/issues/226) is already on hold

**Comment by amihaiemil** [comment]
@g4s8 PR merged, please close this if it's ok :)

**Comment by g4s8** [comment]
@amihaiemil thanks, it's working

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#226](https://github.com/zerocracy/farm/issues/226) is now out of scope
