### ISSUE TITLE
PR may not get reviewer automatically

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2266]
0crat should assign a reviewer to pull requests with the highest priority, but it was not happened for some PRs. Let's investigate and fix

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2266](https://github.com/zerocracy/farm/issues/2266), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.5`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by yegor256** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.12`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.12`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6d493ca1-e1fd-4f5c-9139-8d69db279e5e, thread: PQ-C3NDPUA8L
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.13](https://github.com/zerocracy/farm): CID: [06737874-c14f-4786-9c50-165bfd77d7e2](https://www.0crat.com/footprint/C3NDPUA8L/06737874-c14f-4786-9c50-165bfd77d7e2), Type: "Order was canceled"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#2266](https://github.com/zerocracy/farm/issues/2266), since the job is not in scope anymore
