### ISSUE TITLE
No ability to write comment in pull-request for QA

### ISSUE THREAD

**Issue by sereshqua** [zerocracy/farm#2275]
I was assigned to a [pull-request](https://github.com/artipie/vertx-server/pull/13) for a quality review, it is in my agenda, but I can't write comments.

<img width="818" alt="Screenshot 2020-04-24 at 13 02 43" src="https://user-images.githubusercontent.com/10097808/80200975-18bddb00-862c-11ea-9a41-9e364f708c7b.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@sereshqua maybe it's Github issue? Can you try again in a few minutes?

**Comment by sereshqua** [comment]
@g4s8 will try lately today, now - still the same

**Comment by sereshqua** [comment]
@g4s8 i've seen you added me to GitHub organisation, but it did not help apparently, just FYI

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2275` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
