### ISSUE TITLE
OutOfMemory in Heroku container

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2278]
Let's use cgroups memory limits instead of machine limits, add `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` to JVM options.

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.13`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2278](https://github.com/zerocracy/farm/issues/2278), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
Job [#2278](https://github.com/zerocracy/farm/issues/2278) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't set title

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.14`

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.14`
