### ISSUE TITLE
Incorrect coversion from dolars to zolds upon payment

### ISSUE THREAD

**Issue by bkuzmic** [zerocracy/farm#2286]
For creating a bug report in portal project I got paid 8 dolars. Instead of receiving equivalent amount in zolds, I got 8 zolds instead. Here is Zerocrat message:

We just paid you $8.00 (038996ae-2a57-41c8-9f10-f4a899033463) for [#517](https://github.com/sunsofterp/portal/issues/517): Bug was reported, see §29

And my wallet id is: 8f3308ef3bf2fd7c
Transaction id on zold side: acf4b80f67a7875d

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 it seems that you don't pay attention to the `valid` element of the JSON: https://github.com/zold-io/wts.zold.io/blob/master/front/front_rate.rb#L132

**Comment by g4s8** [comment]
@yegor256 please check: https://github.com/zold-io/wts.zold.io/issues/359

**Comment by yegor256** [comment]
@g4s8 I fixed zold-io/wts.zold.io#359. I think you should make a fix to Zerocrat, to make sure it pays attention to the `valid` flag.

**Comment by g4s8** [comment]
@rultor release, tag=`0.53.15`

**Comment by g4s8** [comment]
@bkuzmic @yegor256 it should be fixed now. We'll fail to pay with invalid rate.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2286` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
