### ISSUE TITLE
assign_role.groovy must fail if GitHub user is absent

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#229]
`assign_role.groovy` must fail if GitHub user is absent. We must check the presence of the user and also add some information in the response message. For example, let's say:

```
Role DEV was assigned to @yegor256 (123 followers), see ...
```

Motivated by https://github.com/zerocracy/datum/issues/91

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/229#issuecomment-368977949))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#229](https://github.com/zerocracy/farm/issues/229) is [in scope](http://www.zerocracy.com/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [5hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23229%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@0crat waiting #675

**Comment by 0crat** [comment]
> @0crat waiting #675  ([here](https://github.com/zerocracy/farm/issues/229#issuecomment-369350974))

@amihaiemil The impediment for [#229](https://github.com/zerocracy/farm/issues/229) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat waiting #676

**Comment by 0crat** [comment]
> @0crat waiting #676 ([here](https://github.com/zerocracy/farm/issues/229#issuecomment-369516291))

@amihaiemil Job [#229](https://github.com/zerocracy/farm/issues/229) is already on hold

**Comment by amihaiemil** [comment]
@yegor256 I think this ticket is equivalent to [this](https://github.com/zerocracy/farm/issues/192) and was fixed -- user must be a registered person as verifier [here](https://github.com/zerocracy/farm/blob/master/src/main/resources/com/zerocracy/stk/pm/staff/roles/assign_role.groovy#L38)

**Comment by amihaiemil** [comment]
@yegor256 PR is merged, can you close this?

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/229#issuecomment-370837948). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/229#issuecomment-370890273). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by yegor256** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#229](https://github.com/zerocracy/farm/issues/229) is now out of scope

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
1. >Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to PR in any of your messages.

2. >All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary 

There were two registered impediments. Please add more details on them.

**Comment by amihaiemil** [comment]
@ypshenychka done, I updated the comments :)

**Comment by ypshenychka** [comment]
@amihaiemil thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/229#issuecomment-371072584))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/farm/issues/229#issuecomment-371072584))

@ypshenychka I didn't understand what is "acceptable"

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
