### ISSUE TITLE
0crat didn't add tags to issue put in scope

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2294]
Hi

Here: https://github.com/llorllale/cactoos-matchers/issues/135 I put an issue in scope, but 0crat didn't add the corresponding tags, so now it's really hard to know what is in scope or not from the github interface...

I think that's a bug, no?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 apparently it was because 0crat didn't have the repository rights, so it is not a bug in farm.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2294` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@victornoel yes, we've removed comment messages in favor of labels to reduce unnecessary verbosity. But maybe we need to fallback to ticket comments if 0crat doesn't have enough permissions to put a label. WFYT?

**Comment by victornoel** [comment]
@g4s8 yes, that could be a good idea actually… and notify the ARC or the PO to add the permission to zerocrat… I suppose we wouldn't have all those problems if 0crat was a github bot maybe? Since to add a bot you have to approve a given set of api permissions
