### ISSUE TITLE
basic authentication in GitHub is deprecated

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2306]
Let's move to OAuth2 tokens

**Comment by g4s8** [comment]
@rultor release, tag=`0.55`

**Comment by yegor256** [comment]
@g4s8 let's try again?

**Comment by yegor256** [comment]
@rultor release, tag is `0.55`

**Comment by yegor256** [comment]
@victornoel it's released, should work now, I believe

**Comment by victornoel** [comment]
@yegor256 yep, I see 0crat starting to react to all the past events, thx :+1:
