### ISSUE TITLE
Release & deploy

### ISSUE THREAD

**Issue by andreoss** [zerocracy/farm#2309]
In order for #2308 to take effect.

**Comment by victornoel** [comment]
@g4s8 @yegor256 can we do this? I want @andreoss in cactoos ;)

**Comment by yegor256** [comment]
@rultor release, tag is `0.55.1`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2309` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
