### ISSUE TITLE
StkSafe.java:40-42: Error handling in `StkSafe::process`...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#273]
The puzzle `272-5f75250e` (from #272) in [`src/main/java/com/zerocracy/farm/StkSafe.java`](https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/farm/StkSafe.java) (lines 40-42) has to be resolved: "Error handling in `StkSafe::process` method is similar to `ReSafe` in telegram, slack and github error handling. We need to refactor it. Let's use one class for it, now it's placed in `TxtUnrecoverableError`."

The puzzle was created by g4s8 on 02-Oct-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#273](https://github.com/zerocracy/farm/issues/273) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat waiting for #466  ([here](https://github.com/zerocracy/farm/issues/273#issuecomment-362794354))

@g4s8 Job [#273](https://github.com/zerocracy/farm/issues/273) is not assigned, can't put it on hold

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/273#issuecomment-363074918))

@yegor256 The job [#273](https://github.com/zerocracy/farm/issues/273) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9250](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `272-5f75250e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3835](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#273](https://github.com/zerocracy/farm/issues/273) is now out of scope

**Comment by g4s8** [comment]
@yegor256 you removed this `@todo` in aa4e41852edd01f73399ec635f91552d74251cf0 but I have opened PR #466 for this ticket. So how to deal with this PR now?

**Comment by yegor256** [comment]
@g4s8 I would close the PR. I don't really agree with the changes you made there, so I have big doubts it will pass the review without many changes.

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
