### ISSUE TITLE
Rename 0crat

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#279]
Slack bot renamed to `@zerocrat` but all help messages are still referring to `@0crat`.
I think we should rename them too.

**Comment by 0crat** [comment]
The job [#279](https://github.com/zerocracy/farm/issues/279) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#279](https://github.com/zerocracy/farm/issues/279), please stop working

**Comment by 0crat** [comment]
The job [#279](https://github.com/zerocracy/farm/issues/279) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591626591). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting #675

**Comment by 0crat** [comment]
> @0crat waiting #675  ([here](https://github.com/zerocracy/farm/issues/279#issuecomment-369350906))

@amihaiemil The impediment for [#279](https://github.com/zerocracy/farm/issues/279) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@g4s8 what are and where are these "help messages"?

**Comment by amihaiemil** [comment]
@0crat waiting #676

**Comment by 0crat** [comment]
> @0crat waiting #676 ([here](https://github.com/zerocracy/farm/issues/279#issuecomment-369516271))

@amihaiemil Job [#279](https://github.com/zerocracy/farm/issues/279) is already on hold

**Comment by amihaiemil** [comment]
@g4s8 Is this task still valid? I don't think so since, as I see, the Slack bot is named ``@0crat``, not ``@zerocrat``, as you say.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/279#issuecomment-369875355). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by g4s8** [comment]
@amihaiemil yes, looks like it was changed

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/279#issuecomment-369935405))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#279](https://github.com/zerocracy/farm/issues/279) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23279%27%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#279](https://github.com/zerocracy/farm/issues/279) is now out of scope
