### ISSUE TITLE
_after.groovy:23-26: This test started to fail after...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#281]
The puzzle `235-ca1d9c8f` (from #235) in [`src/test/resources/com/zerocracy/bundles/resigns_tasks_upon_quit/_after.groovy`](https://github.com/zerocracy/farm/blob/master/src/test/resources/com/zerocracy/bundles/resigns_tasks_upon_quit/_after.groovy) (lines 23-26) has to be resolved: "This test started to fail after `remove_assignee` script fix. In this test stakeholder can't find assignee in MkIssue which throws an exception: XPath '/github/repos/repo[@coords='test/test']/issues/issue[number='2']' not found"

The puzzle was created by g4s8 on 04-Oct-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#281](https://github.com/zerocracy/farm/issues/281) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/281#issuecomment-366082713))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/check_job_status.groovy
java.lang.reflect.InvocationTargetException: null
java.lang.IllegalArgumentException: There are 3 parameter(s) but only 2 format argument(s) were provided.
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

cc @yegor256

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/281#issuecomment-366085834))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#281](https://github.com/zerocracy/farm/issues/281) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [1days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23281%27%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat waiting #568

**Comment by 0crat** [comment]
> @0crat waiting #568  ([here](https://github.com/zerocracy/farm/issues/281#issuecomment-367288814))

@g4s8 The impediment for [#281](https://github.com/zerocracy/farm/issues/281) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `235-ca1d9c8f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4525](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
