### ISSUE TITLE
TkFootprintTest.java:41-45: This test and `FtParamTest` fail...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#284]
The puzzle `155-f2c0cacb` (from #155) in [`src/test/java/com/zerocracy/tk/project/TkFootprintTest.java`](https://github.com/zerocracy/farm/blob/master/src/test/java/com/zerocracy/tk/project/TkFootprintTest.java) (lines 41-45) has to be resolved: "This test and `FtParamTest` fail because they require proper 'mongod' installation. Locally test fails with error: "Cannot run program "mongod": error=2, No such file or directory", on Shippable it's 'MongoTimeoutException'."

The puzzle was created by g4s8 on 08-Oct-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#284](https://github.com/zerocracy/farm/issues/284) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591843435). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting #675

**Comment by 0crat** [comment]
> @0crat waiting #675  ([here](https://github.com/zerocracy/farm/issues/284#issuecomment-369350772))

@amihaiemil The impediment for [#284](https://github.com/zerocracy/farm/issues/284) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
The puzzle `155-f2c0cacb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#284](https://github.com/zerocracy/farm/issues/284) is now out of scope
