### ISSUE TITLE
com.github.mongobee.dao.LockDao: Duplicate key exception while acquireLock.

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#311]
In production:

```
com.github.mongobee.dao.LockDao: Duplicate key exception while acquireLock. Probably the lock has been already acquired.
```

**Comment by g4s8** [comment]
@yegor256 could you provide more details? Where exactly this exception was thrown, can you post full stack-trace here?

**Comment by yegor256** [comment]
@g4s8 I don't see it production since December... I guess, it's gone.

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#311](https://github.com/zerocracy/farm/issues/311), please stop working

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#311` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#311` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#311](https://github.com/zerocracy/farm/issues/311) is now out of scope

**Comment by 0crat** [comment]
Job [#311](https://github.com/zerocracy/farm/issues/311) was not in scope
