### ISSUE TITLE
Clean up agenda

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#328]
Agenda may contain completed or canceled orders,
we need to remove them regularly.
See #314 and  zerocracy/datum#133

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/328#issuecomment-360862474))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#328](https://github.com/zerocracy/farm/issues/328) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket

**Comment by g4s8** [comment]
@yegor256 I think this bug is not valid anymore

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#328` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#328](https://github.com/zerocracy/farm/issues/328) is now out of scope

**Comment by 0crat** [comment]
Job [#328](https://github.com/zerocracy/farm/issues/328) was not in scope
