### ISSUE TITLE
Duplicated claims from Slack

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#329]
I've got many `hello` messages and `bootstrap` responses in Slack for a new project. It seems that for one user message from Slack same claims can be created. See http://www.0crat.com/footprint/C7NJ258GL

responses for `bootstrap`:
```
@g4s8.public_test-0cra I'm ready to manage a project. Project ID is `C7NJ258GL`. When you're ready, you can start giving me commands, always prefixing your messages with my name. All project artifacts are here.
> claim: 2961741213 Mon Oct 23 17:41:52 UTC 2017
> session: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl@47d26a8e
> channel: SlackChannelImpl{topic='Company-wide announcements and work-based matters', purpose='This channel is for workspace-wide communication and announcements. All members are in this channel.', id='C7NJ258GL', name='general'}

@g4s8.public_test-0cra Oops! This project is already ready to go
> claim: 2961741214 Mon Oct 23 17:41:55 UTC 2017
> session: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl@47d26a8e
> channel: SlackChannelImpl{topic='Company-wide announcements and work-based matters', purpose='This channel is for workspace-wide communication and announcements. All members are in this channel.', id='C7NJ258GL', name='general'}

@g4s8.public_test-0cra Oops! This project is already ready to go
> claim: 2961741215 Mon Oct 23 17:41:59 UTC 2017
> session: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl@47d26a8e
> channel: SlackChannelImpl{topic='Company-wide announcements and work-based matters', purpose='This channel is for workspace-wide communication and announcements. All members are in this channel.', id='C7NJ258GL', name='general'}
```

**Comment by 0crat** [comment]
The job [#329](https://github.com/zerocracy/farm/issues/329) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#329](https://github.com/zerocracy/farm/issues/329), please stop working

**Comment by 0crat** [comment]
The job [#329](https://github.com/zerocracy/farm/issues/329) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591936288). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/329#issuecomment-369518849))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#329](https://github.com/zerocracy/farm/issues/329) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [13hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23329%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@0crat waiting #676

**Comment by 0crat** [comment]
> @0crat waiting #676 ([here](https://github.com/zerocracy/farm/issues/329#issuecomment-369908333))

@amihaiemil The impediment for [#329](https://github.com/zerocracy/farm/issues/329) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@yegor256 @g4s8 I think this should be taken out of scope and closed (w/o punishing anybody), since it's rather obscure, the suggestion doesn't make much improvements and bugs with SlackRadar should be found in [this task](https://github.com/zerocracy/farm/issues/687) and its future puzzle tree. What do you think?

**Comment by yegor256** [comment]
@amihaiemil @0crat I agree, I would close it with "bad" quality mark.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/329#issuecomment-371827824); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#329](https://github.com/zerocracy/farm/issues/329) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
