### ISSUE TITLE
IllegalArgumentException: Claim #3521328016 in C6KLDT6QG: type="Order was finished", stakeholder="com/zerocracy/stk/pm/staf...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#363]
https://sentry.io/zerocracy/farm/issues/418640135/

```
IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:dronmdf/telebot#89] declared for identity constraint of element "speed".
    at com.zerocracy.Xocument.modify(Xocument.java:232)
    at com.zerocracy.pmo.Speed.add(Speed.java:78)
    at com.zerocracy.pmo.Speed$add$0.call
    at com.zerocracy.stk.pm.staff.speed.collect_speed.exec(collect_speed.groovy:37)
...
(30 additional frame(s) were not displayed)

InvocationTargetException: None
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
...
(23 additional frame(s) were not displayed)

IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/speed/collect_speed.groovy
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
...
(20 additional frame(s) were not displayed)

IllegalArgumentException: Claim #3521328016 in C6KLDT6QG: type="Order was finished", stakeholder="com/zerocracy/stk/pm/staff/speed/collect_speed.groovy"
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:149)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
...
(19 additional frame(s) were not displayed)

Claim #3521328016 in C6KLDT6QG: type="Order was finished", stakeholder="com/zerocracy/stk/pm/staff/speed/collect_speed.groovy"
```

**Comment by 0crat** [comment]
The job [#363](https://github.com/zerocracy/farm/issues/363) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/363#issuecomment-369861774))

@t-izbassar This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#363](https://github.com/zerocracy/farm/issues/363) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) for [19min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23363%27%7D) (restricted area)

**Comment by t-izbassar** [comment]
@yegor256 can you put the full log? And with the most recent issue if possible, so they will be more accurate.

**Comment by yegor256** [comment]
@t-izbassar here it is:
[footprint.txt](https://github.com/zerocracy/farm/files/1790649/footprint.txt)

You see what was the problem. Zerocrat wasn't able to post anything here, since there were too many comment from him already :(

**Comment by t-izbassar** [comment]
@yegor256 yes. However, I was actually asking about log from issue from sentry, that was reported in this ticket). 

I created #755 to address the issue with too many comments.

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
The job [#363](https://github.com/zerocracy/farm/issues/363) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/711520494). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken ([here](https://github.com/zerocracy/farm/issues/363#issuecomment-373762088))

@amihaiemil The impediment for [#363](https://github.com/zerocracy/farm/issues/363) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@yegor256 Are you sure this is still a valid bug?

**Comment by yegor256** [comment]
@amihaiemil I think it's not valid anymore.

**Comment by 0crat** [comment]
The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#363](https://github.com/zerocracy/farm/issues/363), please stop working. Reason for job resignation: GitHub issue was closed as 'invalid' by @yegor256[/z](https://www.0crat.com/u/yegor256)[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#363](https://github.com/zerocracy/farm/issues/363) is now out of scope
