### ISSUE TITLE
clean up routine

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#376]
Let's create a new table in the DynamoDB, where we will store all GitHub comments we post with error messages and stacktraces. Then, in, say, 72 hours, we will go there again and delete them. That will clean up the mess we are leaving sometimes in GitHub tickets.

**Comment by g4s8** [comment]
@yegor256 PR #455 was merged, can we close?

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4195](https://www.0crat.com/u/g4s8)
