### ISSUE TITLE
@0crat rejects validly formatted rate when applying

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#377]
I'm trying to apply to a project via Slack. `@0crat` does not accept the request, telling me that my rate is invalidly formatted. But I used the correct format (e.g. $25)

![image](https://user-images.githubusercontent.com/1917892/34751237-5798bc2e-f5e6-11e7-826c-9146902110ba.png)

**Comment by 0crat** [comment]
The job [#377](https://github.com/zerocracy/farm/issues/377) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/422223570). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#377](https://github.com/zerocracy/farm/issues/377), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://datum.zerocracy.com/pages/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0), total is [+615](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#377](https://github.com/zerocracy/farm/issues/377) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/571023338). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting #713

**Comment by 0crat** [comment]
> @0crat waiting #713  ([here](https://github.com/zerocracy/farm/issues/377#issuecomment-370219511))

@g4s8 The impediment for [#377](https://github.com/zerocracy/farm/issues/377) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@carlosmiranda I can't reproduce it now, seems to be fixed with another bug, I added test #713 to verify that `apply` with $rate works correctly. Can we close then?

**Comment by carlosmiranda** [comment]
@g4s8 I don't think I'm seeing it now. The test should help. Thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#377](https://github.com/zerocracy/farm/issues/377) is now out of scope
