### ISSUE TITLE
make job election protocols web accessible

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#380]
Let's make it possible to view job assignment reasons in the web. Currently, we publish them in chat bots and it's not very convenient, since they are rather verbose. Would be better to just say "this job was assigned to you, here is why" and a link. When the user clicks the link, he sees the entire log. I guess, the best way to do that is through the Footprint, where we already keep this information. We 
just need to store the location of the right record in the URL.

**Comment by g4s8** [comment]
@yegor256 PR #461 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3610](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#380](https://github.com/zerocracy/farm/issues/380) is now out of scope

**Comment by 0crat** [comment]
Job [#380](https://github.com/zerocracy/farm/issues/380) was not in scope
