### ISSUE TITLE
candidates.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#382]
Each project should have a `candidates.xml` document. When someone applies to it, as in §2, we add a new line to the document. A PO can assign a new role to someone only if that person exists in the document, provided that person is not already in `roles.xml`. Also, when a role is assigned, the person should be removed from the document.

```xml
<candidates>
  <candidate login="yegor256">
    <applied>2017-01-02T12:00:00Z</applied>
  </candidate>
</candidates>
```

Also, we should remove people from here in 20 days, automatically.

**Comment by 0crat** [comment]
The job [#382](https://github.com/zerocracy/farm/issues/382) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
> A PO can assign a new role to someone only if that person exists in the document

@yegor256 I think it's not correct, what if you want to assign new role (e.g. `REV`) to some person which has another role (`DEV`) in the project?

**Comment by yegor256** [comment]
@g4s8 that person will have to "apply" anyway

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #265 #531

**Comment by 0crat** [comment]
> @0crat waiting #265 #531 ([here](https://github.com/zerocracy/farm/issues/382#issuecomment-364726402))

@g4s8 The impediment for [#382](https://github.com/zerocracy/farm/issues/382) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 https://github.com/zerocracy/datum/pull/268#issuecomment-366304555
> @g4s8 I changed my mind, we don't need this functionality. Please, delete this PR and let's close the job.

I've closed these PRs: zerocracy/datum#268 and #531

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by yegor256** [comment]
@g4s8 I changed my mind, we don't need this feature. It would block our clients from inviting their own people the projects, see: https://github.com/zerocracy/farm/issues/572#issuecomment-366276443

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4135](https://www.0crat.com/u/g4s8)
