### ISSUE TITLE
publish the list of candidates in the board

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#383]
Once #382 is implemented, let's show the full list of candidates in the `/board`. It should be visible who is waiting to join the project.

**Comment by 0crat** [comment]
The job [#383](https://github.com/zerocracy/farm/issues/383) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #382

**Comment by 0crat** [comment]
> @0crat waiting #382  ([here](https://github.com/zerocracy/farm/issues/383#issuecomment-365836976))

@g4s8 The impediment for [#383](https://github.com/zerocracy/farm/issues/383) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 I think this job should be closed for same reason https://github.com/zerocracy/datum/pull/268#issuecomment-366304555

**Comment by yegor256** [comment]
@g4s8 right, thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4165](https://www.0crat.com/u/g4s8)
