### ISSUE TITLE
notify everybody when a new project is published

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#384]
Every time a new project is published on the `/board`, let's send a notification to all users, who is not on vacation. Let's mention in the notification, that if they don't want to receive them anymore, they just have to turn the vacation mode ON.

**Comment by 0crat** [comment]
The job [#384](https://github.com/zerocracy/farm/issues/384) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #541

**Comment by 0crat** [comment]
> @0crat waiting #541  ([here](https://github.com/zerocracy/farm/issues/384#issuecomment-364900409))

@g4s8 The impediment for [#384](https://github.com/zerocracy/farm/issues/384) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 can we close it? #541 was merged, #545 puzzle was created

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3880](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#384](https://github.com/zerocracy/farm/issues/384) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/450613695). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/384#issuecomment-365515431))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#384](https://github.com/zerocracy/farm/issues/384) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0) for [56min](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/384#issuecomment-365684319))

@yegor256 The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#384](https://github.com/zerocracy/farm/issues/384), please stop working

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/384#issuecomment-365684342))

@yegor256 The job [#384](https://github.com/zerocracy/farm/issues/384) is now out of scope
