### ISSUE TITLE
Awards.total() doesn't obey the 90 days rule

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#386]
`Awards.total()` must take into account the rewards of the last 90 days only. Now it calculates them all. Let's fix.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/386#issuecomment-360665832))

@fabriciofx The impediment for [#386](https://github.com/zerocracy/farm/issues/386) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/386#issuecomment-371484512))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#386](https://github.com/zerocracy/farm/issues/386) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [2mon](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23386%27%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 looks like @fabriciofx has stopped doing this job, but didn't remove an impediment, maybe you can reassign it?

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/386#issuecomment-371538139))

@yegor256 The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#386](https://github.com/zerocracy/farm/issues/386), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#386](https://github.com/zerocracy/farm/issues/386) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/671632076). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#386](https://github.com/zerocracy/farm/issues/386) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
