### ISSUE TITLE
mentor has to pay for mistakes of his students

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#387]
Every time we give negative points to someone, let's give the same amount of points to his mentor. Let's inform the mentor about it and make it possible to "expel" the student. If it happens, the student loses the mentor and the record in `people.xml`. Thus, he will have to find someone again to invite him.

Let's not forget to update the policy.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/387#issuecomment-360665879))

@fabriciofx The impediment for [#387](https://github.com/zerocracy/farm/issues/387) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/387#issuecomment-394094005))

@g4s8 The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#387](https://github.com/zerocracy/farm/issues/387), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/387#issuecomment-394094207))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#387](https://github.com/zerocracy/farm/issues/387) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23387%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat out

**Comment by g4s8** [comment]
@yegor256 looks like this task was already implemented in 8772d0962ac6e47f44a5222a88d5fcc3bd1c8a32 `copy_negative_points_to_mentor.groovy`, can you close it?

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/387#issuecomment-394094261))

@g4s8 The job [#387](https://github.com/zerocracy/farm/issues/387) is now out of scope

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/387#issuecomment-394242520))

@yegor256 Job `gh:zerocracy/farm#387` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
