### ISSUE TITLE
mentor has to take 8% of what the student is earning (tuition fee)

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#388]
Every time we `"Make payment"` to anyone, we should check who is the mentor and pay that person 8% of what the student just made. We have to deduct this commission from the student.

Let's not forget to update the policy.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/388#issuecomment-360665867))

@fabriciofx The impediment for [#388](https://github.com/zerocracy/farm/issues/388) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/388#issuecomment-368124989))

@yegor256 The job [#388](https://github.com/zerocracy/farm/issues/388) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/542015444). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10814](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10814](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10849](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#388](https://github.com/zerocracy/farm/issues/388) is now out of scope
