### ISSUE TITLE
reject people when reputation is below -256

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#390]
When someone's reputation goes below `-256` we should delete that person from `people.xml` and add `+256` to the `awards.xml` (in order to help that person to get back on track later). 

Let's not forget to update the policy.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@yegor256 #442 merged, can we close this now?

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#390](https://github.com/zerocracy/farm/issues/390), please stop working

**Comment by carlosmiranda** [comment]
@yegor256 why was I unassigned?

**Comment by yegor256** [comment]
@carlosmiranda it seems you did it yourself. Didn't you?

**Comment by carlosmiranda** [comment]
@yegor256 I didn't unassign myself, in fact I don't have access to do that here. Perhaps it was a Github bug - can this be reassigned to me?

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/390#issuecomment-362251086))

@yegor256 The job [#390](https://github.com/zerocracy/farm/issues/390) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9040](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 can we close this now? merged in #442

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1230](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#390](https://github.com/zerocracy/farm/issues/390) is now out of scope
