### ISSUE TITLE
adding "bug" label causes duplicate "in" claim

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#391]
When a job is already in scope and I add `bug` label to the GitHub issue - a new `Add job to WBS` claim is sent. It is redundant and causes noise in the ticket. Let's make sure that when the job is already in scope adding `bug` doesn't lead to any new actions.

**Comment by 0crat** [comment]
The job [#391](https://github.com/zerocracy/farm/issues/391) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/461960346). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#391](https://github.com/zerocracy/farm/issues/391), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0), total is [+555](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#391](https://github.com/zerocracy/farm/issues/391) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/571134013). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting #727

**Comment by 0crat** [comment]
> @0crat waiting #727  ([here](https://github.com/zerocracy/farm/issues/391#issuecomment-370426879))

@g4s8 You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`, `REV`.

**Comment by 0crat** [comment]
> @0crat waiting #727  ([here](https://github.com/zerocracy/farm/issues/391#issuecomment-370426879))

@g4s8 The impediment for [#391](https://github.com/zerocracy/farm/issues/391) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat waiting #727  ([here](https://github.com/zerocracy/farm/issues/391#issuecomment-370426879))

@g4s8 You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`, `REV`.

**Comment by 0crat** [comment]
> @0crat waiting #727  ([here](https://github.com/zerocracy/farm/issues/391#issuecomment-370426879))

@g4s8 Job [#391](https://github.com/zerocracy/farm/issues/391) is already on hold

**Comment by g4s8** [comment]
@yegor256 PR #727 was merged, can we close?

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#391](https://github.com/zerocracy/farm/issues/391) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
