### ISSUE TITLE
Can't access hepdump.hprof file via web

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#400]
Now it's not possible to access `./hepdump.hprof` file via browser if OOM error occurred. Let's upload it to S3 storage as described in this comment: https://github.com/zerocracy/farm/issues/371#issuecomment-357262574

**Comment by 0crat** [comment]
The job [#400](https://github.com/zerocracy/farm/issues/400) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462136844). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#400](https://github.com/zerocracy/farm/issues/400), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0), total is [+465](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#400](https://github.com/zerocracy/farm/issues/400) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610873259). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@g4s8 what s3 storage are we using? Do we have ready to use credentials?

**Comment by g4s8** [comment]
@t-izbassar you can see how s3 was implemented in `S3Item` and `S3Farm`

**Comment by t-izbassar** [comment]
@0crat waiting for #738 to be merged

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/400#issuecomment-357645520). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/400#issuecomment-357750556). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/400#issuecomment-369917047). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/400#issuecomment-369921361). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
> @0crat waiting for #738 to be merged ([here](https://github.com/zerocracy/farm/issues/400#issuecomment-370895934))

@t-izbassar You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat waiting for #738 to be merged ([here](https://github.com/zerocracy/farm/issues/400#issuecomment-370895934))

@t-izbassar The impediment for [#400](https://github.com/zerocracy/farm/issues/400) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#765](https://github.com/zerocracy/farm/issues/765) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#766](https://github.com/zerocracy/farm/issues/766) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#767](https://github.com/zerocracy/farm/issues/767) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#768](https://github.com/zerocracy/farm/issues/768) is still not solved.

**Comment by t-izbassar** [comment]
@g4s8 can we close this one? The task was decomposed and have more granular puzzles to be resolved.

**Comment by g4s8** [comment]
@t-izbassar yes, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#400](https://github.com/zerocracy/farm/issues/400) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#765](https://github.com/zerocracy/farm/issues/765), [#766](https://github.com/zerocracy/farm/issues/766), [#767](https://github.com/zerocracy/farm/issues/767) are still not solved; solved: [#768](https://github.com/zerocracy/farm/issues/768).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1232](https://github.com/zerocracy/farm/issues/1232) is still not solved; solved: [#765](https://github.com/zerocracy/farm/issues/765), [#766](https://github.com/zerocracy/farm/issues/766), [#767](https://github.com/zerocracy/farm/issues/767), [#768](https://github.com/zerocracy/farm/issues/768).

**Comment by 0pdd** [comment]
@g4s8 all 5 puzzles are solved here: [#1232](https://github.com/zerocracy/farm/issues/1232), [#765](https://github.com/zerocracy/farm/issues/765), [#766](https://github.com/zerocracy/farm/issues/766), [#767](https://github.com/zerocracy/farm/issues/767), [#768](https://github.com/zerocracy/farm/issues/768).
