### ISSUE TITLE
Some pages are not working in Firefox

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#402]
E.g. agenda and awards:
![scrot-2018-01-15-12 09 28](https://user-images.githubusercontent.com/1524988/34935046-95da03ac-f9ed-11e7-9800-7f239578f984.png)

**Comment by 0crat** [comment]
The job [#402](https://github.com/zerocracy/farm/issues/402) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462030130). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#402](https://github.com/zerocracy/farm/issues/402), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0), total is [+525](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#402](https://github.com/zerocracy/farm/issues/402) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610871187). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting for #746 to be resolved.

**Comment by 0crat** [comment]
> @0crat waiting for #746 to be resolved. ([here](https://github.com/zerocracy/farm/issues/402#issuecomment-371729715))

@t-izbassar The impediment for [#402](https://github.com/zerocracy/farm/issues/402) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/402#issuecomment-388640592))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#402](https://github.com/zerocracy/farm/issues/402), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#402](https://github.com/zerocracy/farm/issues/402) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1351471320); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for @yegor256 approval

**Comment by 0crat** [comment]
> @0crat waiting for @yegor256 approval ([here](https://github.com/zerocracy/farm/issues/402#issuecomment-391228830))

@krzyk The impediment for [#402](https://github.com/zerocracy/farm/issues/402) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#1062](https://github.com/zerocracy/farm/issues/1062), [#1063](https://github.com/zerocracy/farm/issues/1063), [#1064](https://github.com/zerocracy/farm/issues/1064) are still not solved.

**Comment by krzyk** [comment]
@g4s8 please close this issue, changes in #1024 have been merged

**Comment by g4s8** [comment]
@krzyk thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#402](https://github.com/zerocracy/farm/issues/402) is now out of scope

**Comment by ypshenychka** [comment]
@SilasReinagel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/farm/issues/402#issuecomment-378439683) by indicating an addressee in the beginning. Let me know when you finish.

**Comment by SilasReinagel** [comment]
@ypshenychka The previous message is not directed at a particular person.

**Comment by ypshenychka** [comment]
@SilasReinagel To avoid noise we should always address our comments. Please read this [article](https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) and make appropriate correction. To my opinion, issue reporter or assigned person is the best addressee for your comment in this case.

**Comment by ypshenychka** [comment]
@SilasReinagel Issue reporter, issue solver, project architect - all these people can be addressed with your comment and it will make sense.

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#1062](https://github.com/zerocracy/farm/issues/1062), [#1064](https://github.com/zerocracy/farm/issues/1064) are still not solved; solved: [#1063](https://github.com/zerocracy/farm/issues/1063).
