### ISSUE TITLE
add GitHub label to all "in scope" tickets

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#403]
Every time we add a GitHub job to scope, we must add a label to the GitHub ticket. Let's make its name equal to `"in"` and its color to `#3a6622`. Also, when we take a job out of scope, this label has to be automatically removed.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@yegor256 can we close this now? PR #445 is closed

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1170](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#403](https://github.com/zerocracy/farm/issues/403) is now out of scope
