### ISSUE TITLE
tweet when a new project gets published

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#404]
When someone says `publish` and the project goes to the board, we should send a tweet about it.

**Comment by carlosmiranda** [comment]
@yegor256 see PR #454

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@yegor256 #454 merged, may we close this?

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#404](https://github.com/zerocracy/farm/issues/404), please stop working

**Comment by carlosmiranda** [comment]
@yegor256 why was I unassigned here?

**Comment by yegor256** [comment]
@carlosmiranda I think you did it yourself

**Comment by carlosmiranda** [comment]
@yegor256 no, I didn't, I don't have any assignment powers :) Might be a Github bug?

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/404#issuecomment-362257597))

@yegor256 The job [#404](https://github.com/zerocracy/farm/issues/404) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9050](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 can we close this now? merged in #454

**Comment by yegor256** [comment]
@carlosmiranda thanks

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/404#issuecomment-362948382))

@carlosmiranda This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#404](https://github.com/zerocracy/farm/issues/404) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 20days
  * The role is `DEV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [3days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#404](https://github.com/zerocracy/farm/issues/404), please stop working

**Comment by 0crat** [comment]
The job [#404](https://github.com/zerocracy/farm/issues/404) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462102979). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#404](https://github.com/zerocracy/farm/issues/404), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0), total is [+495](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#404](https://github.com/zerocracy/farm/issues/404) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/571722572). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 could you please remove this closed job from WBS?

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/404#issuecomment-368630849))

@yegor256 @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#404](https://github.com/zerocracy/farm/issues/404), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/404#issuecomment-368630849))

@yegor256 The job [#404](https://github.com/zerocracy/farm/issues/404) is now out of scope
