### ISSUE TITLE
Incorrect payment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#405]
I just received a payment 30 min for https://github.com/yegor256/takes/pull/760 PR, but I'm not a member of Takes project (in Zerocracy) and I'm not an author of this PR or issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#405` is not assigned, can't get start time

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8000](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#405](https://github.com/zerocracy/farm/issues/405) is now out of scope

**Comment by 0crat** [comment]
Job [#405](https://github.com/zerocracy/farm/issues/405) was not in scope
