### ISSUE TITLE
q-tracker.xml:83-86: Add command to rate the quality, the...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#408]
The puzzle `73-6d39317c` from #73 has to be resolved:

https://github.com/zerocracy/farm/blob/c0bf6140b8308f65d1364a05060a61e2a09c1cee/src/main/resources/com/zerocracy/radars/q-tracker.xml#L83-L86

The puzzle was created by g4s8 on 10-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #414

**Comment by 0crat** [comment]
> @0crat waiting #414  ([here](https://github.com/zerocracy/farm/issues/408#issuecomment-360092007))

@g4s8 The impediment for [#408](https://github.com/zerocracy/farm/issues/408) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `73-6d39317c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by g4s8** [comment]
@yegor256 #460 was merged, let's assign QA role to someone?

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4045](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#408](https://github.com/zerocracy/farm/issues/408) is now out of scope

**Comment by yegor256** [comment]
@g4s8 we already have QA roles in Cactoos, Takes, and jPeek. Let's see what happens...

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
