### ISSUE TITLE
Missing telegram bot commands

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#411]
It's needed to register telegram bot commands for `0crat` via Botfather chat:

1. Start speaking with Botfather bot in telegram
2. Send `/setcommands` command
3. Add commands in format `command - description`

Example:
> hello - Just say hello

See zerocracy/datum#188

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/411#issuecomment-360665887))

@fabriciofx The impediment for [#411](https://github.com/zerocracy/farm/issues/411) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by g4s8** [comment]
@yegor256 @fabriciofx actually, this job can be done only by Telegram bot `@zerocrat_bot` admin - @yegor256

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/411#issuecomment-366184199))

@yegor256 The job [#411](https://github.com/zerocracy/farm/issues/411) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/470940856). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9894](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 thanks! I can see them. Close #411

пт, 16 февр. 2018 г., 12:30 Yegor Bugayenko <notifications@github.com>:

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9924](https://www.0crat.com/u/yegor256)
