### ISSUE TITLE
pick up GitHub issue assignee on "scope in"

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#413]
When we add a new GitHub issue to the scope, we should look into its current assignee. If it's set, we should treat it a formal performer of the job and should automatically create an order.

**Comment by 0crat** [comment]
The job [#413](https://github.com/zerocracy/farm/issues/413) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462254053). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 could you please clarify:
> we should look into its current assignee

you mean Github issue assignee here? If so, what should we do if this user is not a Zerocracy user?

**Comment by yegor256** [comment]
@g4s8 yes, I meant the GitHub assignee. If the user is not known to us, we just ignore it.

**Comment by g4s8** [comment]
@yegor256 PR #578 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4360](https://www.0crat.com/u/g4s8)
