### ISSUE TITLE
Ticket titles in agenda

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#422]
It's hard to use agenda page for developers, especially if you have about 15 jobs in it. Let's add Github tiket titles to agenda items, it will make this page more useful.

**Comment by 0crat** [comment]
The job [#422](https://github.com/zerocracy/farm/issues/422) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/562007558). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/422#issuecomment-371250937))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#422](https://github.com/zerocracy/farm/issues/422) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0) for [10days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23422%27%7D) (restricted area)

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#422](https://github.com/zerocracy/farm/issues/422), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#422](https://github.com/zerocracy/farm/issues/422) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/671253338). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting I have to make a second PR in /datum

**Comment by 0crat** [comment]
> @0crat waiting I have to make a second PR in /datum ([here](https://github.com/zerocracy/farm/issues/422#issuecomment-372579013))

@amihaiemil The impediment for [#422](https://github.com/zerocracy/farm/issues/422) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#843](https://github.com/zerocracy/farm/issues/843) is still not solved.

**Comment by amihaiemil** [comment]
@g4s8 this was started in datum, with the xml model, and I left a puzzle here for continuation. Both PRs merged, can we close this?:)

**Comment by g4s8** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#422](https://github.com/zerocracy/farm/issues/422) is now out of scope

**Comment by ypshenychka** [comment]
@amihaiemil 
According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed

Please provide a link to corresponding PR in any of your messages.

**Comment by amihaiemil** [comment]
@ypshenychka done, updated my last comment :)

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1105](https://github.com/zerocracy/farm/issues/1105) is still not solved; solved: [#843](https://github.com/zerocracy/farm/issues/843).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1152](https://github.com/zerocracy/farm/issues/1152) is still not solved; solved: [#1105](https://github.com/zerocracy/farm/issues/1105), [#843](https://github.com/zerocracy/farm/issues/843).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#1105](https://github.com/zerocracy/farm/issues/1105), [#1152](https://github.com/zerocracy/farm/issues/1152), [#843](https://github.com/zerocracy/farm/issues/843).
