### ISSUE TITLE
Agenda schema changed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#423]
In `0.51.6` datum version `role` is required element in `agenda.xml` and `estimates.xml`. 
We should add it in `add()` methods in `Agenda.java` and `Estimates.java`.
See zerocracy/datum#214 PR for details.

**Comment by 0crat** [comment]
The job [#423](https://github.com/zerocracy/farm/issues/423) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/562037396). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#423](https://github.com/zerocracy/farm/issues/423), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0)

**Comment by 0crat** [comment]
The job [#423](https://github.com/zerocracy/farm/issues/423) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/671319950). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@g4s8 I checked `Agenda.java` and `Estimates.java` and it seems that they are already setting the role. I'm not quite sure if it's meaning that there is nothing to do or something else was meant by this task. Can you clarify?

**Comment by g4s8** [comment]
@t-izbassar you're right, it was fixed already, this ticket is outdated.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#423](https://github.com/zerocracy/farm/issues/423) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by t-izbassar** [comment]
@ypshenychka what QA rule was violated?

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@t-izbassar According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The quality of a job is “bad” if any of the following happens (these violations we can’t forgive):
>- The job is closed without a solution provided.
