### ISSUE TITLE
TkDump.java:39-42: Download and analyze heap dump from...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#425]
The puzzle `360-7aef014d` from #360 has to be resolved:

https://github.com/zerocracy/farm/blob/ae179aecb1bd64d6db8689d8aaad432fbf98a467/src/main/java/com/zerocracy/tk/TkDump.java#L39-L42

The puzzle was created by Yegor Bugayenko on 18-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#425](https://github.com/zerocracy/farm/issues/425), please stop working

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#425](https://github.com/zerocracy/farm/issues/425) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610918424). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/425#issuecomment-369874499))

@amihaiemil The impediment for [#425](https://github.com/zerocracy/farm/issues/425) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
The puzzle `360-7aef014d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#425](https://github.com/zerocracy/farm/issues/425) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1202](https://github.com/zerocracy/farm/issues/1202), [#1203](https://github.com/zerocracy/farm/issues/1203) are still not solved; solved: [#725](https://github.com/zerocracy/farm/issues/725).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1202](https://github.com/zerocracy/farm/issues/1202) is still not solved; solved: [#1203](https://github.com/zerocracy/farm/issues/1203), [#725](https://github.com/zerocracy/farm/issues/725).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1202](https://github.com/zerocracy/farm/issues/1202), [#1203](https://github.com/zerocracy/farm/issues/1203), [#725](https://github.com/zerocracy/farm/issues/725).
