### ISSUE TITLE
URL.openStream() does not support HTTP caching

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#427]
A lot of static resources (such as `xsd`, `xsl`) are hosted on Github, which support HTTP caching. For instance request to http://datum.zerocracy.com/0.51.1/xsd/pmo/agenda.xsd will return `Cache-Control: max-age=600` response header, so same request with `If-Modified-Since: Thu, 18 Jan 2018 16:12:13 GMT` header will return `304 Not Modified` response without body within 600 seconds. 
But `Xocument` use `InputOf` inside from Cactoos which use `URL.openStream()` from jdk, which does not support HTTP caching, so our `Xocument` loads full response from server every time.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#427` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
