### ISSUE TITLE
Some pages suggests me to use google-chrome in chrome

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#438]
I'm using google chrome to browse 0crat.com, but some pages (vesting, equity, reminders) still warn me about browser:
![scrot-2018-01-20-21 29 31](https://user-images.githubusercontent.com/1524988/35186712-a5d85566-fe29-11e7-9eab-cfb57441a70f.png)

**Comment by 0crat** [comment]
The job [#438](https://github.com/zerocracy/farm/issues/438) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610920509). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting for #746 to be resolved.

**Comment by 0crat** [comment]
> @0crat waiting for #746 to be resolved. ([here](https://github.com/zerocracy/farm/issues/438#issuecomment-371730025))

@t-izbassar The impediment for [#438](https://github.com/zerocracy/farm/issues/438) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/438#issuecomment-388640576))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#438](https://github.com/zerocracy/farm/issues/438), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#438](https://github.com/zerocracy/farm/issues/438) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1360861929); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for @yegor256 approval

**Comment by 0crat** [comment]
> @0crat waiting for @yegor256 approval ([here](https://github.com/zerocracy/farm/issues/438#issuecomment-391228871))

@krzyk The impediment for [#438](https://github.com/zerocracy/farm/issues/438) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@g4s8 changes in #1025 have been merged, please close this issue

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#438](https://github.com/zerocracy/farm/issues/438) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
