### ISSUE TITLE
Got a half from payment for PR review

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#443]
My rate in [Takes](https://github.com/yegor256/takes) project is $10:
![scrot-2018-01-23-00 52 38](https://user-images.githubusercontent.com/1524988/35246590-492a0b38-ffd8-11e7-822f-abf9b712b62f.png)
after https://github.com/yegor256/takes/pull/772 review `@0crat` [said me](https://github.com/yegor256/takes/pull/772#issuecomment-359575332):
> Order was successfully finished: +15 points just awarded to @g4s8/z, total is +3400

I've received +15 points to my awards, but only $1.25 to Paypal (7.5 points):
![scrot-2018-01-23-00 52 01](https://user-images.githubusercontent.com/1524988/35246841-2f4afece-ffd9-11e7-9ab8-b3bec6a6064f.png)

**Comment by 0crat** [comment]
The job [#443](https://github.com/zerocracy/farm/issues/443) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3475](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7955](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 was it a one time error or you keep seeing it?

**Comment by g4s8** [comment]
@yegor256 it was one time error. I received $2.5 for this PR review https://github.com/yegor256/takes/pull/761

**Comment by yegor256** [comment]
@g4s8 I can't find the cause of this trouble. It may be anything, including your lower rate set there for some period of time. In order to make such situations more fixable and searchable, I will introduce `cause` param into all claims we post. Also, in all GitHub comments, we will add comments, which will refer to claim IDs. Thus, it will be possible to find the exact claim easily, and then go up to the original claim and find the trouble. That's all I can do now.

**Comment by yegor256** [comment]
@g4s8 see 0f457cc and d3b3c6b I think we can close it

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/443#issuecomment-360485675))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#443](https://github.com/zerocracy/farm/issues/443) is in scope for 2days
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for 2days
  * These users are banned: @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8245](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#443](https://github.com/zerocracy/farm/issues/443) is now out of scope

**Comment by 0crat** [comment]
Job [#443](https://github.com/zerocracy/farm/issues/443) was not in scope

**Comment by g4s8** [comment]
@yegor256 I've got same bug for new PR: #439, should I post a new ticket or reopen this?

**Comment by yegor256** [comment]
@g4s8 post a new one pls. In general, it's better (and in your favor) to create new tickets.
