### ISSUE TITLE
four impediments total

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#447]
Let's make it possible to have only four impediments per user. In other words, a user should not be able to say `waiting` for more than four jobs. If there are already four jobs in impediments, we must refuse to wait. Let's not forget to update policy at http://datum.zerocracy.com/pages/policy.html#9

**Comment by 0crat** [comment]
Job [#447](https://github.com/zerocracy/farm/issues/447) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7885](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#447](https://github.com/zerocracy/farm/issues/447) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462300184). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 maybe we should make this limit dynamic? I.e. depend on max possible jobs:
 - 1 impediment for 3 max jobs
 - 2 impediments for 8 max jobs
 - 4 impediments for 16 max jobs
 - 6 impediments for 24 max jobs

**Comment by yegor256** [comment]
@g4s8 yes, I agree. Let's do it the way you suggested.

**Comment by yegor256** [comment]
@g4s8 let's make it 20% of the agenda limit.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #582

**Comment by 0crat** [comment]
> @0crat waiting #582  ([here](https://github.com/zerocracy/farm/issues/447#issuecomment-368209891))

@g4s8 The impediment for [#447](https://github.com/zerocracy/farm/issues/447) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 please see #648 PR with todo syntax correction

**Comment by g4s8** [comment]
@yegor256 PR #582 was merged and puzzle #652 was created, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4645](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#447](https://github.com/zerocracy/farm/issues/447) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.
