### ISSUE TITLE
show mentor and students

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#448]
In the profile page let's show the name of the mentor and the list of students of the user.

**Comment by 0crat** [comment]
Job [#448](https://github.com/zerocracy/farm/issues/448) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7945](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#448](https://github.com/zerocracy/farm/issues/448) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462304285). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256  PR #577  was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4465](https://www.0crat.com/u/g4s8)
