### ISSUE TITLE
no more than 16 students

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#449]
Let's make it possible to mentor only 16 students per user. If a user has more students already, we should reject all other requests.

**Comment by 0crat** [comment]
Job [#449](https://github.com/zerocracy/farm/issues/449) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7960](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#449](https://github.com/zerocracy/farm/issues/449) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/471954533). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 what should we do if someone already has more than 16 students?

**Comment by yegor256** [comment]
@g4s8 nothing. Just reject new `invite` requests.

**Comment by g4s8** [comment]
@yegor256 PR #586 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor254[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $5.00 to g4s8.public@gmail.com with memo "Payment for gh:zerocracy/farm#449 (30 minutes): Order was finished, quality was "acceptable"": java.io.IOException Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
com.zerocracy.pmo.banks.Paypal[202] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4435](https://www.0crat.com/u/g4s8)
