### ISSUE TITLE
breakup

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#450]
Let's add a new command `breakup`, as an opposite to `invite`. The `breakup` should remove the mentor of the user.

Also, when it happens, we should deduct 256 points from the mentor. Let's not forget to update the policy.

**Comment by 0crat** [comment]
Job [#450](https://github.com/zerocracy/farm/issues/450) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7975](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#450](https://github.com/zerocracy/farm/issues/450) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/471958631). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 what should happened with a user? Just remove his mentor, but keep in `people.xml`?

**Comment by yegor256** [comment]
@g4s8 set the mentor to `0crat`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #595

**Comment by 0crat** [comment]
> @0crat waiting #595  ([here](https://github.com/zerocracy/farm/issues/450#issuecomment-368330808))

@g4s8 The impediment for [#450](https://github.com/zerocracy/farm/issues/450) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 PR #595 was merged, todo #668 was created, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#450](https://github.com/zerocracy/farm/issues/450) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#668](https://github.com/zerocracy/farm/issues/668) is solved here.
