### ISSUE TITLE
0crat.com header list goes out of view on mobile

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#451]
On https://www.0crat.com/, on most pages there is this list of links in the header:

![image](https://user-images.githubusercontent.com/6305156/35267184-25617ad2-002e-11e8-891a-6fd7c19c2a09.png)

On mobile, it goes out of view, it doesn't fit well in the screen's width (I have a 5'' screen). I think on mobile the list should be hidden behind a button similar to this:

![image](https://user-images.githubusercontent.com/6305156/35267258-5909b304-002e-11e8-8809-dbf04f2d8466.png)

As discussed with Yegor, this will be fixed with yegor256/tacit#142. In this ticket, the tacit reference should be updated.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#451](https://github.com/zerocracy/farm/issues/451) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7965](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat hold

**Comment by 0crat** [comment]
> @0crat hold ([here](https://github.com/zerocracy/farm/issues/451#issuecomment-360259503))

@yegor256 The impediment for [#451](https://github.com/zerocracy/farm/issues/451) was registered successfully by @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by amihaiemil** [comment]
@yegor256 I think this is already solved?

**Comment by yegor256** [comment]
@amihaiemil not yet, the PR is not merged yet and Tacit is not released: https://github.com/yegor256/tacit/pull/142

**Comment by filfreire** [comment]
@amihaiemil @yegor256 merged and released https://github.com/yegor256/tacit/pull/142

What it looks like now:
<img width="582" alt="screen shot 2018-01-24 at 23 07 01" src="https://user-images.githubusercontent.com/11976836/35361971-5f5b915e-015b-11e8-9dd4-2bd5763fa487.png">

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8145](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#451](https://github.com/zerocracy/farm/issues/451) is now out of scope
