### ISSUE TITLE
Agenda filters

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#457]
It's hard to monitor job progress in /agenda page (if you have ~16 jobs). Let's add some filters:
* filter by project (show only Zerocracy jobs)
* filter by role (show only `DEV` jobs)
* filter impediments (don't show `waiting` jobs)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I will add more info to the agenda: https://github.com/zerocracy/datum/issues/250

**Comment by 0crat** [comment]
The job [#457](https://github.com/zerocracy/farm/issues/457) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3505](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8215](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 you should be able to sort the table now, just click the headers of the each column. Also, you will see the cost of each task and the impediment status. That's, I believe, the best we can do. Let me know.

**Comment by g4s8** [comment]
@yegor256 thanks, now it's much comfortable

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8290](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#457](https://github.com/zerocracy/farm/issues/457) is now out of scope
