### ISSUE TITLE
Project page bug

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#458]
It's some UI bug on Zerocracy project page in Chrome https://www.0crat.com/p/C3NDPUA8L
![scrot-2018-01-25-10 05 14](https://user-images.githubusercontent.com/1524988/35375369-d6969eec-01b7-11e8-8034-47aa8cd208a5.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 works for me... are you sure?

**Comment by g4s8** [comment]
@yegor256 yes, it's still reproducing, maybe because I'm using not latest Chrome `Version 63.0.3239.132 (Official Build) (64-bit)`.

**Comment by yegor256** [comment]
@g4s8 can you check some other browser/

**Comment by g4s8** [comment]
Same in Firefox:
![scrot-2018-01-25-20 18 49](https://user-images.githubusercontent.com/1524988/35402244-02a63628-020d-11e8-9fec-f7f421339c04.png)

Also I tried to clear caches and open in private tab

**Comment by g4s8** [comment]
@yegor256 Also same in Chrome on Android

**Comment by yegor256** [comment]
@g4s8 I can see it too, but in a different place

**Comment by 0crat** [comment]
Job [#458](https://github.com/zerocracy/farm/issues/458) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3655](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 fixed, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#458` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#458](https://github.com/zerocracy/farm/issues/458) is now out of scope

**Comment by 0crat** [comment]
Job [#458](https://github.com/zerocracy/farm/issues/458) was not in scope
