### ISSUE TITLE
0crat assigns a new reviewer when there is already one assigned

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#462]
I was assigned as CR to a [PR](https://github.com/yegor256/cactoos/pull/516#issuecomment-360429805) by mistake (manual assignment by the architect); that PR already had an assignee set by 0crat.

After I told 0crat ``resign``, it resigned me and then assigned someone else, not taking into account that there was a previous (not resigned) assignee. 

I think the problem is the fact that 0crat will simply replace the assignee when the architect manually assigns someone. The original assignee is simply removed (and not announced).

To prevent this, 0crat should complain when there is a manual assignment in a job that already has an assignee.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil it should be fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#462` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
