### ISSUE TITLE
Deadline for the reviewer?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#463]
In the past, the reviewer did not have a 'deadline', since it is the author's job to do the review changes as fast as possible and make the reviewer accept the PR.

Now, apparently, the CR has a deadline: https://github.com/yegor256/cactoos/pull/503#issuecomment-360445463

But what are the instruments for "hurrying things up"? I finished the review there, now I am simply waiting for the author to do the changes. 

I think this deadline should be checked differently: 0crat should complain about it only if the CR has taken no action (e.g. if I hadn't review that PR at all in the first 5 days), but once an initial review has been done, the 'deadline' seems useless... if the author won't do the changes they will lose the task anyway and the PR will be closed. 

What do you think?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it was a bug. We don't enforce ouf Ten Days Rule on code review jobs, see: http://datum.zerocracy.com/pages/policy.html#8

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#463` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#463](https://github.com/zerocracy/farm/issues/463) was not in scope
