### ISSUE TITLE
Elections are accessible without being logged in

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#464]
I can access elections of a project without being logged in via `https://www.0crat.com/a/<project-id>?a=pm/staff/elections`. On the other hand `https://www.0crat.com/p/<project-id>` is forbidden if you are not logged in, so I'd expect the same for the elections.

Looks like a bug to me. Please let me know if misunderstood anything.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rexim fixed in feb383d4f064fca282df821ba6fd83a76b36adc1

**Comment by 0crat** [comment]
Job [#464](https://github.com/zerocracy/farm/issues/464) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#464](https://github.com/zerocracy/farm/issues/464) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8785](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by rexim** [comment]
@yegor256 I confirm, the bug is fixed.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9200](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#464](https://github.com/zerocracy/farm/issues/464) is now out of scope
