### ISSUE TITLE
duplicate bans

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#465]
See this comment: https://github.com/yegor256/cactoos/issues/532#issuecomment-360322565 We must not allow duplicate bans, for the same user. If a user is already banned, there should be no ability to ban it again.

**Comment by 0crat** [comment]
Job [#465](https://github.com/zerocracy/farm/issues/465) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#465](https://github.com/zerocracy/farm/issues/465) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8220](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#465](https://github.com/zerocracy/farm/issues/465) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/471961714). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256  PR zerocracy/datum#285 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 I don't think it will help. The XML won't allow duplicates to happen, but the Farm will still try to create them. Or you think we should deal with that issue in a separate ticket, when the problem surfaces?

**Comment by g4s8** [comment]
@yegor256 now it's not possible to ban same user twice, as I can see `ban_cancelled_order` and `ban_github_reporter` will fail to add new ban because of exception in `Bans.ban()`, or you think there should be some check on groovy scripts level?

**Comment by yegor256** [comment]
@g4s8 yes, that's my point - we should prevent it from happening. Now it will just throw an exception in runtime. Also, we need to upgrade `Xocument` to the latest version of datum (which also has to be released).

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4555](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 damn it, I closed it by mistake :) We should configure Zerocrat to ignore those situations.

**Comment by g4s8** [comment]
@yegor256 please see #638 PR with fix

**Comment by g4s8** [comment]
@yegor256 can we close this bug now?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`
