### ISSUE TITLE
Notify programmers when a new project is published on the board

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#467]
When `Project was published` arrives to the PMO, we should send notifications to all users about it, if their reputation is over 256. We should ask them to review the project and apply to it, if they are interested.

**Comment by 0crat** [comment]
Job [#467](https://github.com/zerocracy/farm/issues/467) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8260](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#467](https://github.com/zerocracy/farm/issues/467) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472006864). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 looks like a duplicate of #384

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@g4s8 right, thanks

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/467#issuecomment-366700874))

@yegor256 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#467](https://github.com/zerocracy/farm/issues/467), please stop working

**Comment by 0crat** [comment]
The job [#467](https://github.com/zerocracy/farm/issues/467) is now out of scope
