### ISSUE TITLE
How to change rate in the project?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#469]
For example my current rate is $10 and now I feel that I have grown into 15$. What should I do?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar just apply to the project again, see 8c3c681

**Comment by t-izbassar** [comment]
@yegor256 make sense. However, that doesn't clear from policy.

**Comment by yegor256** [comment]
@t-izbassar see https://github.com/zerocracy/datum/commit/8c3c681cbfb58e94c31e0ad0c0e2d6e28878e29b In the future, please, submit policy related bugs to the Datum repo.

**Comment by t-izbassar** [comment]
@yegor256 ok thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#469` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#469](https://github.com/zerocracy/farm/issues/469) was not in scope
