### ISSUE TITLE
Ability to refuse given rate

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#470]
Scenario: I'm applying to project with rate 15$. `PO` let me in with rate $10. I should be able to refuse.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar you can quit: http://datum.zerocracy.com/pages/policy.html#35

**Comment by t-izbassar** [comment]
@yegor256 I've checked the message from telegram bot. It says:
> You just got role DEV in C3FFK3YAY

It might be useful to add with what rate I was included. Of course, I can check it in project page.

**Comment by yegor256** [comment]
@t-izbassar that's a separate problem, please submit it to the Farm repo

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#470` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#470](https://github.com/zerocracy/farm/issues/470) was not in scope
