### ISSUE TITLE
Remove (or fix) Shippable check

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#471]
The farm is now opensource. So, let's remove Shippable or fix it, because we already have Travis to do same thing.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx it's removed already

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#471` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#471](https://github.com/zerocracy/farm/issues/471) was not in scope
