### ISSUE TITLE
Add Codecov report

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#472]
Let's add Codecov report support.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#472` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
