### ISSUE TITLE
Let's Jacoco enforces minimum code coverage

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#474]
It's a common problem submit PRs and them not pass in Codecov. I think this problem could be minimized if Jacoco enforces minimum code coverage, as you can check [here](http://choudhury.com/blog/2014/02/25/enforcing-minimum-code-coverage/). Thus, you can check if the minimum code coverage is reach before submit your PR.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx I agree, see how it works in Cactoos: https://github.com/yegor256/cactoos/issues/250

**Comment by 0crat** [comment]
Job [#474](https://github.com/zerocracy/farm/issues/474) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+315](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#474](https://github.com/zerocracy/farm/issues/474) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472010036). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@fabriciofx PR #593 was merged, `todo` #613 was submitted, can we close?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 could you please close this issue? PR #593 was merged and new `todo` #613 was created.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting for close

**Comment by 0crat** [comment]
> @0crat waiting for close ([here](https://github.com/zerocracy/farm/issues/474#issuecomment-368330847))

@g4s8 The impediment for [#474](https://github.com/zerocracy/farm/issues/474) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4675](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#474](https://github.com/zerocracy/farm/issues/474) is now out of scope

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1083](https://github.com/zerocracy/farm/issues/1083) is still not solved; solved: [#613](https://github.com/zerocracy/farm/issues/613).

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1351](https://github.com/zerocracy/farm/issues/1351) is still not solved; solved: [#1083](https://github.com/zerocracy/farm/issues/1083), [#613](https://github.com/zerocracy/farm/issues/613).
