### ISSUE TITLE
Time Remain (to finish the job) instead of added time in Agenda

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#475]
Let's change the "Added" time to "Time Remain" (to finish the job) in Agenda. For example, instead Agenda shows:
```
zerocracy/farm#001 | C3NDPUA8L | 10 hours ago | DEV
```
it will be show:
```
zerocracy/farm#001 | C3NDPUA8L | 9 days, 13 hours and 15 minutes | DEV
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx we don't know how much remains. It depends on the task, on the decisions to be made by 0crat and many other factors. The agenda can't make this decision.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#475` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#475](https://github.com/zerocracy/farm/issues/475) was not in scope
