### ISSUE TITLE
TkShutdown.java:34-36: Shutdown endpoint can be accessed...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#477]
The puzzle `297-c88f3107` from #297 has to be resolved:

https://github.com/zerocracy/farm/blob/8b759229151695942749775de58b9d0139916af5/src/main/java/com/zerocracy/tk/TkShutdown.java#L34-L36

The puzzle was created by g4s8 on 23-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#477](https://github.com/zerocracy/farm/issues/477) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#477](https://github.com/zerocracy/farm/issues/477) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472019323). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0pdd** [comment]
The puzzle `297-c88f3107` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4405](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
