### ISSUE TITLE
add_label_to_github_ticket.groovy:42-44: Right now we are...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#478]
The puzzle `403-fdebb43c` from #403 has to be resolved:

https://github.com/zerocracy/farm/blob/3080a8b17a239370629007ff40b38cc80b596ba0/src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_label_to_github_ticket.groovy#L42-L44

The puzzle was created by Carlos Miranda on 23-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#478](https://github.com/zerocracy/farm/issues/478) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#478](https://github.com/zerocracy/farm/issues/478) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472024452). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #583

**Comment by 0crat** [comment]
> @0crat waiting #583 ([here](https://github.com/zerocracy/farm/issues/478#issuecomment-368331108))

@g4s8 The impediment for [#478](https://github.com/zerocracy/farm/issues/478) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `403-fdebb43c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4705](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#478](https://github.com/zerocracy/farm/issues/478) is now out of scope
