### ISSUE TITLE
Incorrect payment for PR review

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#479]
I received $1.25 instead of $2.5 for PR #439 review. Same as here #443.
0crat [commented](https://github.com/zerocracy/farm/pull/439#issuecomment-360699081):
> Order was successfully finished: +15 points just awarded to g4s8/z, total is +3535

![scrot-2018-01-26-16 26 41](https://user-images.githubusercontent.com/1524988/35441824-1329643a-02b6-11e8-8739-a2174bd3f0f2.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@g4s8 @yegor256 The same for me [here](https://github.com/zerocracy/datum/issues/253).

**Comment by yegor256** [comment]
@g4s8 this is where it happened: https://www.0crat.com/footprint/C3NDPUA8L/260650061

**Comment by 0crat** [comment]
The job [#479](https://github.com/zerocracy/farm/issues/479) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3580](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8520](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 same in estimates for PR review:
![scrot-2018-01-26-19 22 34](https://user-images.githubusercontent.com/1524988/35449538-63f4272a-02ce-11e8-84cb-f2268d71958d.png)

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed in 6158892607d19051d4eb45537f40115ab2525dc8

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8595](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#479](https://github.com/zerocracy/farm/issues/479) is now out of scope
