### ISSUE TITLE
TkClaim.java:45-48: Add link to election claim instead of...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#481]
The puzzle `380-7a7b9529` from #380 has to be resolved:

https://github.com/zerocracy/farm/blob/2cdd0d08669ef7f255f1f9e0c08f4dc6c9bc6dd3/src/main/java/com/zerocracy/tk/project/TkClaim.java#L45-L48

The puzzle was created by g4s8 on 21-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#481](https://github.com/zerocracy/farm/issues/481) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/481#issuecomment-360791912))

@yegor256 The job [#481](https://github.com/zerocracy/farm/issues/481) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8465](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `380-7a7b9529` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#481](https://github.com/zerocracy/farm/issues/481) is now out of scope

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8525](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
