### ISSUE TITLE
Cost of a job is missing in Agenda

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#482]
0crat assigned a job to me saying that the budged is 30 minutes https://github.com/yegor256/cactoos/issues/532#issuecomment-360486873 But the cost of this job is missing in Agenda.

![2018-01-26-213010_822x290_scrot](https://user-images.githubusercontent.com/165283/35444347-de509bc2-02e0-11e8-8270-77adb3f140ad.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rexim I can't check the bug, since the ticket is closed already (yegor256/cactoos#532). Most probably one of your tasks didn't get the Cost value because this feature was introduced just recently. Please, keep an eye on this and report again, if you see similar problems.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#482` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#482](https://github.com/zerocracy/farm/issues/482) was not in scope
