### ISSUE TITLE
Actually assign the person to the Github task

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#484]
Currently, 0crat doesn't actually assign anyone to any task. I think the assignee should also be assigned on Github.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it's technically not possible if the user is not a "contributor" of the repo. We try to assign, but if we fail we just silently ignore this situation.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#484` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#484](https://github.com/zerocracy/farm/issues/484) was not in scope
