### ISSUE TITLE
User awards page refers to a policy paragraph but doesn't properly link it

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#486]
![](https://user-images.githubusercontent.com/165283/35498512-397bde5e-0501-11e8-925f-6cc526ed9a66.png)

"§6" is just a text, not a link

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#486](https://github.com/zerocracy/farm/issues/486) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#486](https://github.com/zerocracy/farm/issues/486) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/501761014). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting zerocracy/datum#303

**Comment by 0crat** [comment]
> @0crat waiting zerocracy/datum#303 ([here](https://github.com/zerocracy/farm/issues/486#issuecomment-368877247))

@g4s8 The impediment for [#486](https://github.com/zerocracy/farm/issues/486) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rexim it was implemented in #303 but disabled then in https://github.com/zerocracy/datum/issues/314 because it brake `templates.xsl`. Now new ticket to fix it in scope: https://github.com/zerocracy/datum/issues/315, so paragraph links will be enabled back after fix. So can we close this issue?

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#486](https://github.com/zerocracy/farm/issues/486) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary.

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/486#issuecomment-368877247).

**Comment by g4s8** [comment]
@ypshenychka fixed, please look again

**Comment by ypshenychka** [comment]
@g4s8 Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
