### ISSUE TITLE
0crat assigns more jobs than allowed

### ISSUE THREAD

**Issue by neonailol** [zerocracy/farm#488]
Account: neonailol

> Currently open jobs: 6 (max allowed: 3).

first 3 jobs are legit, and linked to open issues on github
and new 3 jobs are reviews
this starts happening around 3 days ago

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol it assigns pull requests even if you have no room. That's the logic. If we don't do that, some pull requests may get stuck for very long and the project won't move forward. I updated the policy: https://github.com/zerocracy/datum/commit/a0fdec4acaf0876a86e4a9ad32089ab4cd8a7b34

**Comment by 0crat** [comment]
Job [#488](https://github.com/zerocracy/farm/issues/488) is now in scope, role is `DEV`

**Comment by neonailol** [comment]
Thanks for clarifying this. Closing the issue then.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#488` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#488](https://github.com/zerocracy/farm/issues/488) is now out of scope

**Comment by 0crat** [comment]
Job [#488](https://github.com/zerocracy/farm/issues/488) was not in scope
