### ISSUE TITLE
list of sub-claims in TkClaim

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#489]
Let's show the list of claims, where `cause` is pointing to the claim we are rendering currently in TkClaim. That will help us the the hierarchies of claims.

**Comment by 0crat** [comment]
The job [#489](https://github.com/zerocracy/farm/issues/489) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).We should be aware that g4s8 is on vacation! This ticket may be delayed.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8790](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8790](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#489](https://github.com/zerocracy/farm/issues/489), please stop working

**Comment by 0crat** [comment]
The job [#489](https://github.com/zerocracy/farm/issues/489) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/611514648). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@yegor256 PR #704 is for this

**Comment by 0pdd** [comment]
@yegor256 the puzzle [761](https://github.com/zerocracy/farm/issues/761) is still not solved

**Comment by 0pdd** [comment]
@yegor256 the puzzle [762](https://github.com/zerocracy/farm/issues/762) is still not solved

**Comment by amihaiemil** [comment]
@yegor256 this can be closed now

**Comment by yegor256** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#489](https://github.com/zerocracy/farm/issues/489) is now out of scope

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/489#issuecomment-371422748))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#489](https://github.com/zerocracy/farm/issues/489) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23489%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@yegor256 I think you should put this back in scope, the QA was assigned for final review, but then 0crat took it out of scope for that reason.

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/489#issuecomment-371426003))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#489](https://github.com/zerocracy/farm/issues/489) is not in scope
  * The job is waiting `QA` review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23489%27%7D) (restricted area)

**Comment by yegor256** [comment]
@amihaiemil that's how it should be now. Job goes out of scope and then QA reviews it. Isn't it what you guys were asking for? :) https://github.com/zerocracy/farm/issues/587

**Comment by amihaiemil** [comment]
@yegor256 I see, makes sense. I thought there will also be no payment if the task is out of scope :)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#762](https://github.com/zerocracy/farm/issues/762) is still not solved; solved: [#761](https://github.com/zerocracy/farm/issues/761).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.
