### ISSUE TITLE
Payment not received for the closed issue

### ISSUE THREAD

**Issue by driver733** [zerocracy/farm#490]
I have not received the payment to my paypal account for the issue 537 in cactoos.
Also, I do not understand why zerocrat stated that my rate is 0.00 (it is set to $16).
`@driver733/z will get 0.00 of their hourly rate for this job`
I have received the payment for the previous issue successfully though.
https://github.com/yegor256/cactoos/issues/537#issuecomment-361286000
![screen shot 2018-01-29 at 12 36 22 pm](https://user-images.githubusercontent.com/10466206/35525085-7c445e38-04f1-11e8-866e-008de2988893.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 are you sure you didn't get the payment? There is a PayPal transaction ID, which can't be obtained anyhow except from PayPal API. It means that the money were transferred.

**Comment by t-izbassar** [comment]
@yegor256 I have the same issue. Transactions doesn't appear in the PayPal activities. Can they be on hold or something like that? I couldn't find a way to check status by provided transaction ID. Can you check on your side?
> AP-7H417200GG2163901
> AP-4C51097357899713H

**Comment by driver733** [comment]
@yegor256 I am sure that I did not get the payment. I have completed 2 tasks, but have received the payment only for one of them.
`AP-9RY9243931143003F`
![img_bfbd74e6f72d-1](https://user-images.githubusercontent.com/10466206/35584201-4dae6006-05c2-11e8-9060-a8d5da5fea9a.png)

**Comment by yegor256** [comment]
@driver733 @t-izbassar if we get their payment IDs, we definitely deliver the payments to them. The question is whether they are able to send you the money. I just checked our PayPal account, it seems that it didn't have the credit card attached. Let's keep an eye on it now.

**Comment by t-izbassar** [comment]
@yegor256 seems fixed now as I received new payments.

**Comment by yegor256** [comment]
@driver733 that was a temporary issue.

**Comment by driver733** [comment]
@yegor256 so the payment will be processed eventually?

**Comment by yegor256** [comment]
@driver733 I'm not sure... maybe PayPal will do it later, since it gave us the transaction ID. I just added an extra check to our code: But it's for the future, of course.

**Comment by llorllale** [comment]
@yegor256 I did not receive payment (nor points) for [this](https://github.com/yegor256/jpeek/issues/90) job in jpeek

**Comment by llorllale** [comment]
@yegor256 I also did not receive payment nor points for [this](https://github.com/yegor256/jpeek/issues/120) other job

**Comment by llorllale** [comment]
@yegor256 sounds like a clarification is in order for the policy. The "definition of done" defined as when "the ticket is closed" is commonly understood to be when the GitHub issue is closed, not when the job is out of scope, etc.

**Comment by g4s8** [comment]
@driver733 Paypal payment option was removed, closing this bug

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#490` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
