### ISSUE TITLE
Stale jobs in the agenda

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#496]
We had this problem in #328, but didn't really fix it anyhow.

Let's create a new Groovy stakeholder in `stk/pmo/agenda/delete_stale_jobs.groovy`. It has to react to `Ping daily`. It has to fetch all users from `people.xml`, pick random, say five. And then go through their agendas and check that each job they have there really exist in the correspondent projects. If they don't exist, it should remove them from the agenda.

**Comment by 0crat** [comment]
Job [#496](https://github.com/zerocracy/farm/issues/496) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9000](https://www.0crat.com/u/yegor256)

**Comment by llorllale** [comment]
@yegor256 I think this bug is presenting itself [here](https://github.com/yegor256/jpeek/issues/68)

**Comment by yegor256** [comment]
@llorllale not really, it was a different bug in https://github.com/yegor256/jpeek/issues/68

**Comment by 0crat** [comment]
The job [#496](https://github.com/zerocracy/farm/issues/496) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/521032532). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/496#issuecomment-369999373))

@g4s8 The impediment for [#496](https://github.com/zerocracy/farm/issues/496) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 PR #705 was merged and todo #728 was submitted, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#496](https://github.com/zerocracy/farm/issues/496) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#728](https://github.com/zerocracy/farm/issues/728) is solved here.
