### ISSUE TITLE
Clean up agendas on project termination

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#497]
When `destroy.groovy` happens, we should delete project jobs from user agendas.

**Comment by 0crat** [comment]
Job [#497](https://github.com/zerocracy/farm/issues/497) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9000](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#497](https://github.com/zerocracy/farm/issues/497) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511804117). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#497](https://github.com/zerocracy/farm/issues/497), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#497](https://github.com/zerocracy/farm/issues/497) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641160259). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting https://github.com/zerocracy/farm/issues/792

**Comment by 0crat** [comment]
> @0crat waiting https://github.com/zerocracy/farm/issues/792 ([here](https://github.com/zerocracy/farm/issues/497#issuecomment-372121842))

@amihaiemil The impediment for [#497](https://github.com/zerocracy/farm/issues/497) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@yegor256 PR #806 was merged, can we close this?

**Comment by yegor256** [comment]
@amihaiemil thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#497](https://github.com/zerocracy/farm/issues/497) is now out of scope

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary.

Please add details to the registered [impediment](https://github.com/zerocracy/farm/issues/497#issuecomment-372121842).

**Comment by amihaiemil** [comment]
@ypshenychka done, thanks

**Comment by ypshenychka** [comment]
@amihaiemil Thanks!

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@yegor256 My bad. Wrong quality mark. It can't be undone though.

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
