### ISSUE TITLE
remove from sandbox project is reputation is over 1024

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#498]
We should automatically remove a user from a sandbox project when his/her reputation is over 1024.

**Comment by 0crat** [comment]
Job [#498](https://github.com/zerocracy/farm/issues/498) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9015](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#498](https://github.com/zerocracy/farm/issues/498) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/521036640). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4795](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#498](https://github.com/zerocracy/farm/issues/498) is now out of scope
