### ISSUE TITLE
0crat should state why a person is resigned from the ticket

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#499]
At the moment the resignation message simply states the following:

![image](https://user-images.githubusercontent.com/1917892/35598810-6a7e832a-0660-11e8-949b-e3d8fc73f703.png)

We should state the reason for the resignation (job took too long, task rejected, job out of scope, resigned/reassigned by architect, etc.) in the same message.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#499](https://github.com/zerocracy/farm/issues/499) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1200](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#499](https://github.com/zerocracy/farm/issues/499) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/521541675). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@carlosmiranda PR #642 was merged, can we close?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@g4s8 yes, thank you. :)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4825](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#499](https://github.com/zerocracy/farm/issues/499) is now out of scope
