### ISSUE TITLE
What does these colors mean on "gang" page?

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#501]
I noticed that reputation displayed in "gang" page is colored. However, I haven't found any direct descripion anywhere of what these colors mean. From the context the meaning was obvious only for "red", which means dishonor (reputation below 0). It took me some time to correlate others with policy: I guess that "green" reputation have experienced gang members who passed the threshold of "sandbox-only" participation (reputation is higher than 256), "yellow" have "sandbox-only" members (who has reputation in range [0; 256))

Shouldn't we put some legend on the "gang" page, explaining each color meaning explicitly with references to the policy, for the sake of usability?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#501](https://github.com/zerocracy/farm/issues/501) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#501](https://github.com/zerocracy/farm/issues/501) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/571906076). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #732

**Comment by 0crat** [comment]
> @0crat waiting #732  ([here](https://github.com/zerocracy/farm/issues/501#issuecomment-370953344))

@g4s8 You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`, `REV`.

**Comment by 0crat** [comment]
> @0crat waiting #732  ([here](https://github.com/zerocracy/farm/issues/501#issuecomment-370953344))

@g4s8 The impediment for [#501](https://github.com/zerocracy/farm/issues/501) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@skapral please look at team page https://www.0crat.com/team, I've added legend for reputation colors in #732 PR. Can we close then?

**Comment by skapral** [comment]
@g4s8: Nice, thanks.

> Can we close then?

Sure.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#501](https://github.com/zerocracy/farm/issues/501) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
