### ISSUE TITLE
"Gang" page - sorting by reputation is broken

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#502]
Steps to reproduce:
1. Open "Gang" page on 0crat
2. Click by "reputation" column header

Expected result:

- Reputation is sorted ascendingly or descendingly.

Actual result:

- See attached screenshot

![screenshot from 2018-02-01 15-36-06](https://user-images.githubusercontent.com/1714171/35678780-a87cee72-0765-11e8-9f66-9854290fd978.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#502](https://github.com/zerocracy/farm/issues/502) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#502](https://github.com/zerocracy/farm/issues/502) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/571953259). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@skapral @yegor256 I was already fixed in #504 by @mazdack. Now it's working fine.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#502](https://github.com/zerocracy/farm/issues/502) is now out of scope
