### ISSUE TITLE
Notify ARC about vacation status on manual assignment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#505]
Sometimes ARC uses manual assignment, but assignee may be on vacation and can miss it.
I think ARC should know about vacation status in this case.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
It was implemented already

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#505` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#505](https://github.com/zerocracy/farm/issues/505) was not in scope
