### ISSUE TITLE
PR update cause reviewer unassignment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#506]
If I change a title (#459) or resolve conflicts via Github web tool (#460), or update "Allow edits from maintainers." checkbox (#446), the reviewer (@fabriciofx in these PRs) will be unassigned.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it seems to be a bug in GitHub... did you try to contact them? The only solution I see now is to stop listening to "unassign" events from GitHub if they are coming from pull requests. WDYT?

**Comment by 0crat** [comment]
Job [#506](https://github.com/zerocracy/farm/issues/506) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3715](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 I think it's not Github's bug, because I tested this case in my test repository and didn't find webhook with `unassign` action, only `"action": "edited"`

**Comment by yegor256** [comment]
@g4s8 that's weird... Let's fix it urgently, since it's annoying

**Comment by yegor256** [comment]
@0crat boost 2x

**Comment by 0crat** [comment]
> @0crat boost 2x ([here](https://github.com/zerocracy/farm/issues/506#issuecomment-362626392))

@yegor256 Can't understand "boost", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by g4s8** [comment]
@yegor256 same for issues: #273 (actually I don't have permissions to unassign myself)

**Comment by g4s8** [comment]
@yegor256 same here: #184

**Comment by g4s8** [comment]
@yegor256 same here: https://github.com/zerocracy/datum/pull/266

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/506#issuecomment-365586297))

@yegor256 The job [#506](https://github.com/zerocracy/farm/issues/506) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/451203282). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9619](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed in 7103d344 Let's try?

**Comment by g4s8** [comment]
test

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/506#issuecomment-365663578))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#506](https://github.com/zerocracy/farm/issues/506) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 12days
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for [4hr](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9769](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#506](https://github.com/zerocracy/farm/issues/506) is now out of scope
