### ISSUE TITLE
You have no roles in <project>

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#507]
If I open roles page, I will see this error: 
> You have no roles in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L)

but I have DEV and REV roles here:
> Zerocracy/C3NDPUA8L (your roles: DEV, REV).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 can you please attach screenshots? I can't understand what pages you are talking about.

**Comment by g4s8** [comment]
@yegor256 
project page https://www.0crat.com/p/C3NDPUA8L
![scrot-2018-02-02-17 49 27](https://user-images.githubusercontent.com/1524988/35739090-97776bc0-0841-11e8-9395-b21a1374911b.png)

roles page (`roles` link on project page) https://www.0crat.com/a/C3NDPUA8L?a=pm/staff/roles
![scrot-2018-02-02-17 51 44](https://user-images.githubusercontent.com/1524988/35739168-cb457514-0841-11e8-8b58-b6c1404d38b2.png)

**Comment by yegor256** [comment]
@g4s8 fixed in 772a6d3

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#507` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#507](https://github.com/zerocracy/farm/issues/507) was not in scope
