### ISSUE TITLE
Didn't receive some payments

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#508]
I received messages from 0crat telegram bot:
> 0crat:
We just paid you $1.25 (AP-9K413652WJ9044414) for #773: Order was successfully finished

> 0crat:
We just paid you $1.25 (AP-20600360U05248420) for #776: Order was successfully finished

But didn't receive anything in Paypal.

**Comment by yegor256** [comment]
@g4s8 dup of #490

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#508` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#508](https://github.com/zerocracy/farm/issues/508) was not in scope
