### ISSUE TITLE
skip code review if amount of changes is too small

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#510]
Take this for example: https://github.com/zerocracy/farm/pull/504 The PR is so small, there is no reason to do a code review. Let's check each pull request size in `RbOnPullRequest` and ignore those that are smaller than 10 modified lines.

**Comment by 0crat** [comment]
Job [#510](https://github.com/zerocracy/farm/issues/510) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9090](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#510](https://github.com/zerocracy/farm/issues/510) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/580910393). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/510#issuecomment-370910444))

@g4s8 You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`, `REV`.

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/510#issuecomment-370910444))

@g4s8 The impediment for [#510](https://github.com/zerocracy/farm/issues/510) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#770](https://github.com/zerocracy/farm/issues/770) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PR #740 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#510](https://github.com/zerocracy/farm/issues/510) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#770](https://github.com/zerocracy/farm/issues/770) is solved here.
