### ISSUE TITLE
"Gang" page - how to sort negative reputation?

### ISSUE THREAD

**Issue by mazdack** [zerocracy/farm#514]
after fixing https://github.com/zerocracy/farm/issues/502 we can see that negative reputation is smaller then no reputation. need clarification if this is ok? 
![image](https://user-images.githubusercontent.com/6659876/35743508-e754e386-084e-11e8-9acb-a3f9b5626d48.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@mazdack I believe this is how it should be, isn't it? Just simple arithmetics.

**Comment by mazdack** [comment]
Ok, you guys are right.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#514` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#514](https://github.com/zerocracy/farm/issues/514) was not in scope
