### ISSUE TITLE
REV 0crat commands

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#518]
Let's add PR reviewer commands (`@0crat accept`, `@0crat reject`), when reviewer accepted PR this job will be removed from his agenda and assigned to `ARC` to merge it, or if he rejected, `0crat` will automatically close this PR.
It will reduce 'in-progress' `REV`-jobs in agenda so reviewer will be able to get new jobs from `0crat`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I don't think it's correct to let the REV go when the PR is not yet merged. The REV has to stay with the ticket until it's fully closed, either merged or rejected.

**Comment by g4s8** [comment]
@yegor256 OK, I see.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#518` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#518](https://github.com/zerocracy/farm/issues/518) was not in scope
