### ISSUE TITLE
Page for inviting

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#520]
Currently, if a new user wants to join ZC, they have to go on the Telegram chat and ask someone to invite them. This is not feasable for the future, as that chat grows and grows + maybe the mentors are not checking that chat. 

It would be more elegant if there was a page on 0crat.com, where the new user would ask for invite -- then, the proposal for a new student would appear on the page of all those who have rating > 1024, or maybe sent via mail.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#520](https://github.com/zerocracy/farm/issues/520) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+315](https://www.0crat.com/u/amihaiemil)

**Comment by yegor256** [comment]
@amihaiemil totally agree, thanks! We should create a short form, where a new comer will provide his/her GitHub name, a short description, and a Telegram contact information. Then, we will automatically send this information to everybody who has 1024+ reputation.

**Comment by g4s8** [comment]
@yegor256 could you please assign me this job? I have similar one: https://github.com/zerocracy/datum/issues/122

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/520#issuecomment-364936666))

@yegor256 The job [#520](https://github.com/zerocracy/farm/issues/520) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/431425195). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9685](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 keep this in mind: https://github.com/zerocracy/datum/issues/270 In the `/join` page we have to list things that are important for us, including GitHub profile, SO reputation, etc. Maybe give links to my [blog post](http://www.yegor256.com/2014/10/29/how-much-do-you-cost.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #551

**Comment by 0crat** [comment]
> @0crat waiting #551  ([here](https://github.com/zerocracy/farm/issues/520#issuecomment-366445952))

@g4s8 The impediment for [#520](https://github.com/zerocracy/farm/issues/520) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 let's make sure the results of this testing is also provided at the form: https://www.16personalities.com/free-personality-test

**Comment by g4s8** [comment]
@amihaiemil please, look at https://www.0crat.com/join
can we close this?

**Comment by amihaiemil** [comment]
@g4s8 Yes, looks ok, thanks :)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4300](https://www.0crat.com/u/g4s8)
