### ISSUE TITLE
0crat does not assign user in Github issue sometimes

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#521]
0crat may assign a user internally but not in Github issue:
![scrot-2018-02-05-15 55 46](https://user-images.githubusercontent.com/1524988/35805493-24a2f40e-0a8d-11e8-8063-f6d00121dc69.png)
e.g. here: https://github.com/zerocracy/farm/issues/273#issuecomment-363075092

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 dup of #484

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#521` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#521](https://github.com/zerocracy/farm/issues/521) was not in scope
