### ISSUE TITLE
"can't get start time" comments are redundant

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#522]
If issue was closed when nobody had been assigned to it, 0crat posts a comment:
> Job \<job-id\> is not assigned, can't get start time

I think these messages are redundant.

e.g. this one: https://github.com/zerocracy/farm/issues/207#issuecomment-363075547

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#522` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
