### ISSUE TITLE
don't touch code parts inside Par

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#523]
This test should not fail:

```
assertThat(
  new Par("Hey, `my DEV friend`!").say(),
  equalTo("Hey, `my DEV friend`!")
)
```

But it fails now. We should not touch anything that stays inside those backquotes.

**Comment by 0crat** [comment]
Job [#523](https://github.com/zerocracy/farm/issues/523) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9300](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#523](https://github.com/zerocracy/farm/issues/523) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/611847851). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting PR to merge #785

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #785  ([here](https://github.com/zerocracy/farm/issues/523#issuecomment-372259750))

@g4s8 The impediment for [#523](https://github.com/zerocracy/farm/issues/523) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 it was fixed in #785 PR, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#523](https://github.com/zerocracy/farm/issues/523) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
