### ISSUE TITLE
HTTPS certificate "not completely safe" on some pages

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#524]
On most pages, the HTTPS certificate is ok, we see the green icon lock in the browser: 

![image](https://user-images.githubusercontent.com/6305156/35855958-48e33d64-0b3d-11e8-8c14-c7f377848395.png)

However, at least on the index page and the main profile page (``/u/amihaiemil``), the browser says that the certificate is not entirely safe and we see the grey lock:

![image](https://user-images.githubusercontent.com/6305156/35856022-6a777dc8-0b3d-11e8-8b39-2bc5abac8c9f.png)

I think all the website (and maybe even the Policy, which is currently served over ``http://`` from Gh-Pages) should be secured. I would also move the Policy to 0crat.com, I know gh-pages does not offer HTTPS for CNAME domains.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#524](https://github.com/zerocracy/farm/issues/524) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+345](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9310](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@amihaiemil I removed the badges from the home page and the profile page will be fixed when this bug is gone: https://github.com/terales/socatar/issues/79

**Comment by terales** [comment]
@yegor256 https://github.com/terales/socatar/issues/79 is fixed now

**Comment by yegor256** [comment]
@amihaiemil it seems we are fully secure now, please check

**Comment by amihaiemil** [comment]
@yegor256 yes, seems fine now, thanks :)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9840](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#524](https://github.com/zerocracy/farm/issues/524) is now out of scope
