### ISSUE TITLE
Some cosmetic changes on the Intex page

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#525]
On the index page of 0car.com, we see the following:

![image](https://user-images.githubusercontent.com/6305156/35856157-c893dcee-0b3d-11e8-82d8-ec9ba37de769.png)

1) There is an extra dot before the Github handle

2) The version of 0crat -- is it valid? Is it the one used by Rultor or the one from ``pom.xml`` which Rultor never updates?

3) Displaying info about the server load -- not so good, security wise. Why would you want a possible attacker to just open the index page and see how the server is doing? So he can DDOS faster? Maybe we can leave the "time the server took to generate this page", but I would definetely remove the load and used/available memory.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I made some cosmetic changes, thanks! The security concern is not very important. We are not afraid of hackers. As of yet :)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#525` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#525](https://github.com/zerocracy/farm/issues/525) was not in scope
