### ISSUE TITLE
Rename "Gang" to "Team"

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#527]
This is strictly for the image of the company, "Gang" is not professional at all. It could be a nice joke, but ZC is not known well enough yet. I believe that, so far, the first impression is that we are just a group of russian programmers on a Telegram chat, playing with XDSD.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I agree, but I don't like the "Team" either. Team would mean that these people are our in-house developers, on a payroll. Any other ideas?

**Comment by yegor256** [comment]
@amihaiemil maybe "Crew"?

**Comment by amihaiemil** [comment]
@yegor256 How about simply "Developers"? Taking into account that also, in the future, we may want to filter them on different pages: "Java Developers", "Ruby Developers" etc. Then maybe we will also have "QAs" etc

**Comment by 0crat** [comment]
Job [#527](https://github.com/zerocracy/farm/issues/527) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+375](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#527](https://github.com/zerocracy/farm/issues/527) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/612042117). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 so what is the new name finally?

**Comment by amihaiemil** [comment]
@g4s8 I would say "Developers" so we can also name the technology later. I think we should say which developer does what (Java, Go, php etc). Currently we don't show this info, the prospective customer has no idea what the developers on the platform can do :)

**Comment by yegor256** [comment]
@g4s8 let's go for "team"

**Comment by g4s8** [comment]
@amihaiemil renamed "gang" to "team": https://www.0crat.com/team
can we close?

**Comment by amihaiemil** [comment]
@g4s8 Yes, looks nice, thanks :)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#527](https://github.com/zerocracy/farm/issues/527) is now out of scope
