### ISSUE TITLE
Telegram test case is missed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#528]
Telegram test case `TelegramRadarITCase` was fully removed here: https://github.com/zerocracy/farm/commit/7db21a1d7fadf3eb9529338c16d216e5dbe09f6a#diff-dcf7fd842a91a64d23895f44b938a5ae
so now it's not possible to test Telegram.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#528](https://github.com/zerocracy/farm/issues/528) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3730](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#528](https://github.com/zerocracy/farm/issues/528) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/681512038). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken ([here](https://github.com/zerocracy/farm/issues/528#issuecomment-373762063))

@amihaiemil The impediment for [#528](https://github.com/zerocracy/farm/issues/528) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/528#issuecomment-375904922))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#528](https://github.com/zerocracy/farm/issues/528), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/528#issuecomment-381329476))

@yegor256 The job [#528](https://github.com/zerocracy/farm/issues/528) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1041331321); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
Added test in #934

**Comment by g4s8** [comment]
@ypshenychka updated comment

**Comment by ypshenychka** [comment]
@g4s8 Thank you.

**Comment by ypshenychka** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@ypshenychka what? :)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/528#issuecomment-382043531))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#528](https://github.com/zerocracy/farm/issues/528) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2days
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23528%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@yegor256 Please consider my [remark](https://github.com/zerocracy/farm/issues/528#issuecomment-381402104).

**Comment by yegor256** [comment]
@ypshenychka oh, yes, I missed it. I agree, my bad.

**Comment by ypshenychka** [comment]
@yegor256 Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
