### ISSUE TITLE
Don't show links if the user does not have the appropriate role

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#529]
On a project's page, there are a number of links, like the following:

![image](https://user-images.githubusercontent.com/6305156/35867190-da48fae0-0b61-11e8-89ce-f54316c2b6e5.png)

If I click on any of them, I am redirected to the Index page which has the following orange banner:

![image](https://user-images.githubusercontent.com/6305156/35867277-13931df8-0b62-11e8-8167-a55bcc14feee.png)

I think if I don't have the rights to see a page, I shouldn't even see the link anywhere. The validation should stay, of course, in case I enter the URL directly -- but fix the link, it is currently in Markdown format and it is not rendered correctly. 

It is not only confusing, but rather annoying since those pages also take a lot of time to be rendered.. I wait 2-3 seconds for the page to render only to show me that banner with the broken link.

**Comment by 0crat** [comment]
The job [#529](https://github.com/zerocracy/farm/issues/529) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+360](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9305](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed, please check

**Comment by amihaiemil** [comment]
@yegor256 Yes, it seems to be fixed, I cannot see the links anymore.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9365](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#529](https://github.com/zerocracy/farm/issues/529) is now out of scope
