### ISSUE TITLE
Page to see equity earnings?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#530]
Some of the first developers who joined ZC are paid, in part, through equity.

We should definetely have a page where the earnings are tracked and where all the process is  explained: what exactly does that equity mean? Dividends at the end of the year or something else? Should a contract be signed at some point? etc.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil we have it all already. Those, who have their "vesting" schedules configured, see the numbers and can download the contract with all necessary details: https://github.com/zerocracy/farm/issues/453

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#530` is not assigned, can't get start time

**Comment by amihaiemil** [comment]
@yegor256 Then I think I am not registered there, since I don't see any numbers and no PDF for download. On the other hand, I am paid only a 3rd of my rate of Zerocrat project. I thought you enabled it for me as well, we talked about it on Telegram :D

**Comment by 0crat** [comment]
Job [#530](https://github.com/zerocracy/farm/issues/530) was not in scope

**Comment by yegor256** [comment]
@amihaiemil fixed, reload the project page pls.

**Comment by amihaiemil** [comment]
@yegor256 ok, I see the numbers now; should there also be a link to a PDF? I looked for it but I can't see that anywhere.

**Comment by yegor256** [comment]
@amihaiemil you should see the "proof" link, next to the numbers. Maybe it should be replaced by a PDF icon...

**Comment by amihaiemil** [comment]
@yegor256 I see it now, thanks. But the PDF is broken. it gets downloaded, yet I cannot open it, it looks like it's corrupt. I'll try at home, maybe it's an OS issue, and let you know if the problem persists.

**Comment by yegor256** [comment]
@amihaiemil it's a bug: #453
