### ISSUE TITLE
Replace XML+XSD frontend with Web Standards

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#532]
I know this is a long shot but it's better to think about it now: 

ZC has a lot of potential, yet its frontend is not sexy at all. I believe it needs a lot of redesign and refactoring in order to look better and move faster. 

XML + XSLT is an old technology which has **big drawbacks** for a project of ZC's potential: 

1. it is s-l-o-w; each page load takes 1-2 seconds, unacceptable;

2. design is harder

3. refactoring/changes are harder, you need to rebuild and redeploy

4. browser compatibility, I think it is a lot less than desired and I doubt any browser is making efforts towards supporting this technology

5.  talent pool. Even though the design could be done with stylesheets, I think there are less than 100 developers in the whole world who are proficient in XSL. 

It may have its advantages, I don't know, but **here is what HTML5 + JS offers**:

1. it is fast 

2. clean design with CSS3
 
3. decoupling; We can manage the frontend in a CMS and avoid having to redeploy at each text change. Deployments over deployments for the UI won't be feasable once the platform grows and is used constantly.
 
4. browser compatibility 100%
 
5. a hell lot of talent pool out there.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil the "slow" point is not valid. We are slow because we combine a number of XML documents in order to produce the output. For example, the `/gang` page puts together the data from 60+ XML files, each of which is stored in AWS S3. You can imagine how much time it takes to load them all, parse, and combine. The conversion of XML to HTML takes milliseconds, it's very fast.

All other points are not really important, since we don't need to make too many changes to our front-end. The front-end is not what we sell. It's a product for programmers, that's why the UI has to be very simple and technical.

**Comment by amihaiemil** [comment]
@yegor256 not even browser compatibility? Outputing the HTML from the XML + XSL is the browser's job, how many browsers still support that?

And the target users is a very long discussion. From my point of view, the first people that should be impressed with the product are managers, project owners, clients etc (not technical people at all), since they will make the decision to move their project to this management style.

**Comment by amihaiemil** [comment]
@yegor256 Also, in the end, the users don't care how many XMLs are needed to render a page. If it's so slow due to that, then maybe a better solution for the backend is needed.

**Comment by g4s8** [comment]
@amihaiemil @yegor256 +1 for browser compatibility. I'm using Chrome only to view 0crat.com because it can't be rendered correctly in Firefox

**Comment by yegor256** [comment]
@amihaiemil @g4s8 what we can do is always deliver HTML to the browser, unless it explicitly asks for, say `application/vnd.zerocracy+xml`, just like GitHub is doing: https://developer.github.com/v3/media/

**Comment by yegor256** [comment]
@amihaiemil I'm telling you, this XML+XSL->HTML conversion is super fast, it takes milliseconds

**Comment by 0crat** [comment]
Job [#532](https://github.com/zerocracy/farm/issues/532) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+420](https://www.0crat.com/u/amihaiemil)

**Comment by yegor256** [comment]
@amihaiemil to me it looks very fresh and elegant)

**Comment by 0crat** [comment]
The job [#532](https://github.com/zerocracy/farm/issues/532) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641411825). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/532#issuecomment-373306982))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#532](https://github.com/zerocracy/farm/issues/532), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/532#issuecomment-373306982))

@g4s8 Job `gh:zerocracy/farm#532` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#532](https://github.com/zerocracy/farm/issues/532) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1310417149); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zerocracy/farm/issues/532#issuecomment-390425412))

@proshin-roman The impediment for [#532](https://github.com/zerocracy/farm/issues/532) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/532#issuecomment-393214689))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#532](https://github.com/zerocracy/farm/issues/532), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#532](https://github.com/zerocracy/farm/issues/532) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1501621772); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@2fc46ccc

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait, busy on other tasks

**Comment by carlosmiranda** [comment]
@0crat wait for completion, busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait for completion, busy on other tasks ([here](https://github.com/zerocracy/farm/issues/532#issuecomment-394567047))

@carlosmiranda The impediment for [#532](https://github.com/zerocracy/farm/issues/532) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@proshin-roman can you update your comment (https://github.com/zerocracy/farm/issues/532#issuecomment-390425412) with a reason for impediment?

**Comment by proshin-roman** [comment]
@carlosmiranda mission complete :)

**Comment by carlosmiranda** [comment]
@amihaiemil see PR #1386

**Comment by carlosmiranda** [comment]
@amihaiemil #1386 merged now, may we close this?

**Comment by amihaiemil** [comment]
@carlosmiranda sure, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#532](https://github.com/zerocracy/farm/issues/532) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
