### ISSUE TITLE
Exit/Log out should be a POST, not a GET

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#533]
Currently, Exit/Log Out is a simple GET. This is not ok, since browsers with a prefetch mechanism (fetching pages in advance to speed things up) will automatically log out the user after the login. Plus, anyone could post a link on the Internet, pointing to ``http://www.0crat.com/?PsByFlag=PsLogout`` and anyone who clicked on it would be logged out.

Besides posting a link to click on, one could also post an image with that address as ``src``, then the user who opens the page containing that image loses the 0crat cookie and has no idea why they are logged out the next time they access 0crat.com.

More details on [this](https://stackoverflow.com/questions/3521290/logout-get-or-post) SO question. Also, click [here](http://www.0crat.com?PsByFlag=PsLogout)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I have no idea how POST can be used there, but let's try) Thanks for reporting.

**Comment by 0crat** [comment]
Job [#533](https://github.com/zerocracy/farm/issues/533) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+375](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@yegor256 Well, worst case scenario, a simple, syncronous ``<form action="..." method="post">`` should work

**Comment by 0crat** [comment]
The job [#533](https://github.com/zerocracy/farm/issues/533) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641208552). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@amihaiemil it was fixed in #782 PR, now "Exit" is a submit button inside post form

**Comment by amihaiemil** [comment]
@g4s8 I see. Seems to work fine, but there is a styling issue on the intex page, maybe you can submit an issue?

![image](https://user-images.githubusercontent.com/6305156/37352084-1ec8ac94-26e5-11e8-9448-c935cf7fe19e.png)

**Comment by g4s8** [comment]
@amihaiemil sure, I'll submit it

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/533#issuecomment-372978382))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#533](https://github.com/zerocracy/farm/issues/533) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23533%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/533#issuecomment-372978382))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#533](https://github.com/zerocracy/farm/issues/533) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23533%27%7D) (restricted area)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#533](https://github.com/zerocracy/farm/issues/533) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/533#issuecomment-373169670))

@ypshenychka This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#533](https://github.com/zerocracy/farm/issues/533) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23533%27%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
