### ISSUE TITLE
Concurrency issue when adding reputation points

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#534]
I think there is a concurrency issue when adding reputation points.

My last reputation was **375**, then I resigned from 2 jobs ([here](https://github.com/yegor256/jpeek/issues/8#issuecomment-363785136) and [here](https://github.com/yegor256/jpeek/issues/64#issuecomment-363785158)). 0crat deducted 15 points for each, and the current reputation is **345** (correct), but the comment is the same in both issues.

The comment says ``total is +345`` in both cases and it should have been ``+360`` in one case, and ``+345`` in the other. 

I am not sure if this is just a matter of fetching the latest reputation or if it could affect the calculation itself as well.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it's just a matter of reporting -- we can't guarantee its synchronization. And I don't think we need to do that. However, thanks for reporting, we will keep any eye on that in the future.

**Comment by 0crat** [comment]
Job [#534](https://github.com/zerocracy/farm/issues/534) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#534` is not assigned, can't get start time

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+360](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#534](https://github.com/zerocracy/farm/issues/534) is now out of scope
