### ISSUE TITLE
verbosity

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#535]
Let's collect a new metric per developer: verbosity. Every time we close a job completed by a developer, we should count the amount of messages that person posted in the GitHub issue or a pull request. Let's count not only issue messages, but also commit messages. Then, report it the way we report speed.

**Comment by 0crat** [comment]
Job [#535](https://github.com/zerocracy/farm/issues/535) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9390](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#535](https://github.com/zerocracy/farm/issues/535) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641117029). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by carlosmiranda** [comment]
@yegor256 good to merge

**Comment by g4s8** [comment]
@carlosmiranda you are accepting an issue :) Maybe you wanted to accept PR instead? #753 or zerocracy/datum#322

**Comment by carlosmiranda** [comment]
@g4s8 doh :) All these open windows have the same name! :))

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#783](https://github.com/zerocracy/farm/issues/783) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PRs #753 and zerocracy/datum#322 were merged, puzzle #783 was submitted, can we close then?

**Comment by g4s8** [comment]
@0crat waiting for close

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
> @0crat waiting for close ([here](https://github.com/zerocracy/farm/issues/535#issuecomment-373044551))

@g4s8 The impediment for [#535](https://github.com/zerocracy/farm/issues/535) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/535#issuecomment-373072383))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#535](https://github.com/zerocracy/farm/issues/535) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23535%27%7D) (restricted area)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/535#issuecomment-373072820))

@yegor256 The job [#535](https://github.com/zerocracy/farm/issues/535) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/535#issuecomment-373169704))

@ypshenychka This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#535](https://github.com/zerocracy/farm/issues/535) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23535%27%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1096](https://github.com/zerocracy/farm/issues/1096) is still not solved; solved: [#783](https://github.com/zerocracy/farm/issues/783).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#1096](https://github.com/zerocracy/farm/issues/1096), [#783](https://github.com/zerocracy/farm/issues/783).
