### ISSUE TITLE
blanks

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#536]
Let's add a new metric for each developer: the amount of bugs he/she reported, which were not counted as bugs by project architects. Every time we close a ticket in GitHub, which was not a job, we should increment this metric. Also, when we close a pull request, which was not merged, we should increment this metric. Let's do it the same way we count "speed."

**Comment by 0crat** [comment]
Job [#536](https://github.com/zerocracy/farm/issues/536) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9390](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#536](https://github.com/zerocracy/farm/issues/536) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/620616782). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [760](https://github.com/zerocracy/farm/issues/760) is still not solved

**Comment by g4s8** [comment]
@yegor256 PRs #752 and zerocracy/datum#321 were merged, todo #760 was submitted, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by g4s8** [comment]
@0crat status

**Comment by g4s8** [comment]
@0crat waiting for close

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/536#issuecomment-372818075))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#536](https://github.com/zerocracy/farm/issues/536) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [11days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23536%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat waiting for close ([here](https://github.com/zerocracy/farm/issues/536#issuecomment-372818318))

@g4s8 The impediment for [#536](https://github.com/zerocracy/farm/issues/536) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/536#issuecomment-372986965))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#536](https://github.com/zerocracy/farm/issues/536) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23536%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/536#issuecomment-372986965))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#536](https://github.com/zerocracy/farm/issues/536) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23536%27%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/536#issuecomment-373169749))

@ypshenychka This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#536](https://github.com/zerocracy/farm/issues/536) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23536%27%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#760](https://github.com/zerocracy/farm/issues/760) is solved here.
