### ISSUE TITLE
0crat doesn't unassign PR reviewer after 10 days

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#537]
0crat doen't include PR jobs to "10 days rule". As a result I have 5 PR's that are 2 weeks old. I think if reviewer doesn't have time to review PR's, they should be re-assigned to someone else. Or if review is in progress he can say `waiting`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
I think the simplest solution would be to remove the 10day deadline for DEV if they have made a Pull Request. So count those 10days rule only while the task stays open and doesn't have at least an open PR 
linked to it. Because it's true, the DEV's work is much delayed because of CR and ARCH.

**Comment by amihaiemil** [comment]
Then, of course, a little AI could be needed to determine whether that PR is alive, if someone is actually doing something about it.

**Comment by yegor256** [comment]
@g4s8 I guess you are right, let me fix it now.

**Comment by amihaiemil** [comment]
@yegor256 no no, wait a second, what are you doing after all? :))

**Comment by 0crat** [comment]
The job [#537](https://github.com/zerocracy/farm/issues/537) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3775](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9435](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 fixed in 3a743a53319baaa92dbce4b5fe6460efdd4822ee and updated policy: https://github.com/zerocracy/datum/commit/bb6d172745e47dd6b87697696c23afdcc949b5ed

**Comment by yegor256** [comment]
@g4s8 @amihaiemil impediments are still not allowed for PRs. We must not block the process by putting code reviews on hold, I believe.

**Comment by amihaiemil** [comment]
@yegor256 but what can the reviewer do if the DEV is late? Say I review a PR, suggest some changes and then the DEV takes a lot of time to do them. Then, comes the ARCH, which takes another day or two

**Comment by amihaiemil** [comment]
@yegor256 It seems to me the REV has a deadline but can do almost nothing to speed things up, that's the problem.

**Comment by yegor256** [comment]
@amihaiemil you can simply reject the PR if it takes too long. Just ask the ARC to close the pull request and that's it. The ARC won't be against it, since it's in everybody's favor (except the PR author). The ARC will earn and you will earn.

**Comment by amihaiemil** [comment]
@yegor256 but then the project loses a lot of value. Question is: what is better for the project? lose a little more time or lose the implemented value (which was almost done, just little changes were needed)?

Plus, the project loses more time if the REV simply rejects a PR after 10 days. 10 days have passed for that PR which was almost done and 10 more will pass until the next PR will be merged.

**Comment by yegor256** [comment]
@amihaiemil but the slow developer will be punished. This is priceless!

**Comment by g4s8** [comment]
@yegor256 thanks! I think if REV can't register impediments in a PR he should be able to reject it with 0crat command (`@0crat reject`) because ARC can miss rejection comment so PR will be unassigned and REV will lose a reputation. @yegor256 @amihaiemil what do you think?

**Comment by yegor256** [comment]
@g4s8 the command will not guarantee anything. We need the ticket to get physically closed in GitHub.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9625](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#537](https://github.com/zerocracy/farm/issues/537) is now out of scope
