### ISSUE TITLE
GitHub close keyword abuse problem

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#539]
GitHub makes it super easy to automatically close an issue with [keywords](https://help.github.com/articles/closing-issues-using-keywords/) without the reporter's consent.

Example: https://github.com/yegor256/cactoos/issues/561

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by rexim** [comment]
@yegor256 one of the solutions I see is to make some automatic check that the PR description and commit messages don't contain the keywords.

**Comment by yegor256** [comment]
@rexim that would be a very complex validation software, which would have to go through the entire PR, check all commit messages, all texts, report problems somehow... It seems to be something outside of our scope.

**Comment by rexim** [comment]
@yegor256 another solution that I'm thinking about is to not pay to the DEV without the reporter's approval.

Case 1:
- Issue closed by the reporter.
- 0crat pays to the `DEV`.

Case 2:
- Issue closed by somebody else (for example rultor).
- 0crat asks the reporter to approve the solution.
- If the problem is solved, the reporter just says something like `@0crat approve` and the `DEV` gets paid.
- If the problem is not solved, the reporter reopens the issue and the `DEV` doesn't get any money.
- If the closed issue was not approved by the reporter within some period of time, the problem is considered solved and the `DEV` gets paid.

This solution doesn't require any complex validation. If this solution also doesn't sound good to you, feel free to close the ticket because I don't have any other ideas.

**Comment by 0crat** [comment]
Job [#539](https://github.com/zerocracy/farm/issues/539) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@rexim I like it, thanks! But we will do it simpler. We will check who closed the ticket and add this information to the "closing claim". Then, when it's time to pay, we will check whether the ticket was closed by the reporter or ARC or PO. In these cases, we pay. Otherwise, we say "sorry, we won't pay". Let's do it this way and don't forget to update the policy.

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/539#issuecomment-364919840). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/539#issuecomment-364941010))

@yegor256 The job [#539](https://github.com/zerocracy/farm/issues/539) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/431439328). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9695](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 do we need to remove such jobs (closed by someone else) from WBS?

**Comment by yegor256** [comment]
@g4s8 good question. Let's leave them in the WBS.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #567

**Comment by 0crat** [comment]
> @0crat waiting #567  ([here](https://github.com/zerocracy/farm/issues/539#issuecomment-366445924))

@g4s8 The impediment for [#539](https://github.com/zerocracy/farm/issues/539) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rexim PR with unit-test #567 was merged, also new task to fix it #599 was submitted, can we close?

**Comment by rexim** [comment]
@g4s8 sure!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4225](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@rexim the puzzle [710](https://github.com/zerocracy/farm/issues/710) is solved

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/539#issuecomment-370924372). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/539#issuecomment-370924372). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).
