### ISSUE TITLE
Users are not banned from all jobs if they skip many of them

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#540]
Some users may ignore Zerocracy jobs assigned to them  (do nothing until 0crat unassign job by 10 days rule), which extends result delivery timeline.
I'd siggest to ban them from all jobs (add to `bans.xml` with a wildcard) automatically if they exceed some threshold (maybe 10 ignored jobs one by one) until they ask PO to unban them back.
Another solution may be to automatically turn vacation mode `on`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I would suggest to introduce a new per-user metric (similar to #536 and #535). Let's call it "negligence". Let's record every situation when a user is ejected from a job by delay. Then, let's create a new voter that will seriously downvote those users. Make sense?

**Comment by 0crat** [comment]
Job [#540](https://github.com/zerocracy/farm/issues/540) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3850](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#540](https://github.com/zerocracy/farm/issues/540) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/831654476); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by amihaiemil** [comment]
@0crat waiting #870 need documentation.

**Comment by 0crat** [comment]
> @0crat waiting #870 need documentation. ([here](https://github.com/zerocracy/farm/issues/540#issuecomment-375908132))

@amihaiemil The impediment for [#540](https://github.com/zerocracy/farm/issues/540) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@g4s8 PR #1114 has been merged, can you close this? :D

**Comment by g4s8** [comment]
@amihaiemil sure, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#540](https://github.com/zerocracy/farm/issues/540) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by amihaiemil** [comment]
@g4s8 I keep repeating this, but everyone seems to be against this idea. Nevertheless, I try one more time: there should be an ``architecture.md`` document to describe the *overall* architecture. So far, I understood the following: 

There are the groovy scripts which are handling the Issue concurrently or without a specific order, they simply rely on the **data** to make sense of the current state of the Issue. 

The data in the project is represented in XML files -- each of these files are **animated** by Java classes which are actually used in the groovy scripts. 

This is all I understood so far, but I have no idea how S3 and MongoDB are involved :(

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment]
@amihaiemil it may be helpful, can you submit new ticket about it?

**Comment by amihaiemil** [comment]
@g4s8 Sure. I wanted to write that comment in #1126, not here (must have clicked the wrong window...)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1141](https://github.com/zerocracy/farm/issues/1141) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1450](https://github.com/zerocracy/farm/issues/1450) is still not solved; solved: [#1141](https://github.com/zerocracy/farm/issues/1141).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#1141](https://github.com/zerocracy/farm/issues/1141), [#1450](https://github.com/zerocracy/farm/issues/1450).
