### ISSUE TITLE
Some tests are broken

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#542]
EquityTest.createsPdf and LatexTest.renders are failing with exception:

> java.io.IOException: Failed POST request to https://tex.mendelu.cz/en/

e.g. this build: https://travis-ci.org/zerocracy/farm/builds/340113972?utm_source=github_status&utm_medium=notification

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 disabled them in 5c1abb8d Thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#542` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#542](https://github.com/zerocracy/farm/issues/542) was not in scope
