### ISSUE TITLE
Qulice PMD error in master

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#543]
@yegor256 please fix this in `master` branch:
[ERROR] /src/main/java/com/zerocracy/radars/slack/TkSlack.java[78-78]: Avoid declaring a variable if it is unreferenced before a possible exit point. (PrematureDeclaration)
[INFO] Read our quality policy: http://www.qulice.com/quality.html

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed the build, sorry, my bad

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#543` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#543](https://github.com/zerocracy/farm/issues/543) was not in scope
