### ISSUE TITLE
project advisers

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#546]
Each project must have a "adviser" (one of our users), whose name has to be provided to the `bootstrap` command. We should store the name of the adviser in `catalog.xml`. Then, the adviser should get 4% of every project funding operation. Every time a project gets funded, the adviser receives a payment.

Let's not forget to update the policy too.

**Comment by 0crat** [comment]
Job [#546](https://github.com/zerocracy/farm/issues/546) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9780](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#546](https://github.com/zerocracy/farm/issues/546) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641414894). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@yegor256 could you please clarify, who is the mentor of a project? Does he/she has some roles, or just any person from `people.xml`? Can he/she agree or disagree to be a mentor, or I can put any name without permission to `bootstrap`command? How to upgrade current projects from `catalog.xml`?

**Comment by yegor256** [comment]
@g4s8 the person who sends `bootstrap` command becomes an adviser. Let's call that person an "adviser", to avoid confusion. We put this into `catalog.xml`:

```
<project>
  <adviser>yegor256</adviser>
</project>
```

For current projects let's put `0crat` there, which will mean that there are no advisers and no fee should be paid to anyone.

**Comment by g4s8** [comment]
@0crat waiting for datum release

**Comment by 0crat** [comment]
> @0crat waiting for datum release ([here](https://github.com/zerocracy/farm/issues/546#issuecomment-373307115))

@g4s8 The impediment for [#546](https://github.com/zerocracy/farm/issues/546) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat waiting for datum release ([here](https://github.com/zerocracy/farm/issues/546#issuecomment-373307115))

@g4s8 Job [#546](https://github.com/zerocracy/farm/issues/546) is already on hold

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#833](https://github.com/zerocracy/farm/issues/833) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PRs zerocracy/datum#324 and #827 were merged, `@todo` #833 was submitted, can we close then?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#546](https://github.com/zerocracy/farm/issues/546) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#833](https://github.com/zerocracy/farm/issues/833) is solved here.
