### ISSUE TITLE
"0crat" as a mentor for high-ranked users

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#547]
When a user reaches 2048 reputation points, we should automatically set `0crat` as his/her mentor. We should inform the user about that and his/her mentor. This should also mean, that there will no fees deducted anymore to the benefits of the mentor.

**Comment by 0crat** [comment]
Job [#547](https://github.com/zerocracy/farm/issues/547) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9780](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#547](https://github.com/zerocracy/farm/issues/547) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/541318211). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10789](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10789](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10819](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#547](https://github.com/zerocracy/farm/issues/547) is now out of scope
