### ISSUE TITLE
RFP

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#548]
Let's create a new page `/rfp`, which will contain a form our potential clients will have to fill out:

  * Title
  * Budget
  * Tech stack
  * Deadline(s)
  * Scope of work

Then, we store this RFP (request for proposal) in `pmo/rfps.xml` and announce it for those users who have 2048+ reputation. Some of them may be interested to become an architect in this new project. What happens next I'm not sure yet...

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#548` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#548](https://github.com/zerocracy/farm/issues/548) was not in scope
