### ISSUE TITLE
Link to policy.html#1 page is broken

### ISSUE THREAD

**Issue by msarhan** [zerocracy/farm#550]
When uninvited user login, the home page shows a message "_You (@username) must be invited to us by someone we already know, see §1_".
**§1** in the message is not linked to [http://datum.zerocracy.com/pages/policy.html#1](url) page.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@msarhan thanks, should be fine now

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#550` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#550](https://github.com/zerocracy/farm/issues/550) was not in scope
