### ISSUE TITLE
People.java:43-47: Let's keep person reputation, agenda...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#552]
The puzzle `366-6dccce28` from #366 has to be resolved:

https://github.com/zerocracy/farm/blob/fa3b468d9759edb85fdd1434fe96ccb5f26ff705/src/main/java/com/zerocracy/pmo/People.java#L43-L47

The puzzle was created by rultor on 13-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#552](https://github.com/zerocracy/farm/issues/552) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#552](https://github.com/zerocracy/farm/issues/552) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641514069). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting PR to merge #790

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #790  ([here](https://github.com/zerocracy/farm/issues/552#issuecomment-373307313))

@g4s8 The impediment for [#552](https://github.com/zerocracy/farm/issues/552) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `366-6dccce28` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#840](https://github.com/zerocracy/farm/issues/840), [#841](https://github.com/zerocracy/farm/issues/841) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#552](https://github.com/zerocracy/farm/issues/552) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#841](https://github.com/zerocracy/farm/issues/841) is still not solved; solved: [#1059](https://github.com/zerocracy/farm/issues/1059), [#840](https://github.com/zerocracy/farm/issues/840).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1059](https://github.com/zerocracy/farm/issues/1059), [#840](https://github.com/zerocracy/farm/issues/840), [#841](https://github.com/zerocracy/farm/issues/841).
