### ISSUE TITLE
0crat sends links that I don't have an access to

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#553]
0crat sent me the following text via Telegram:

> The job [#119](https://github.com/yegor256/jpeek/issues/119) was assigned to you in [jPeek](https://www.0crat.com/p/C7JGJ00DP) as DEV a minute ago, here is [why](https://www.0crat.com/footprint/C7JGJ00DP/441813874)

If I click on [why](https://www.0crat.com/footprint/C7JGJ00DP/441813874) I get "Access Denied" page:

![2018-02-14-020859_613x606_scrot](https://user-images.githubusercontent.com/165283/36168558-14884696-112c-11e8-9105-22551da5b26c.png)

I'd expect to either have an access to that page, or don't see the links I'm not allowed to see.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rexim fixed, now you will have access.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#553` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#553](https://github.com/zerocracy/farm/issues/553) was not in scope
