### ISSUE TITLE
remove lost GitHub users

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#555]
Let's create a new stakeholder, which will react to `Ping daily` and check whether everybody we have in `people.xml` is still present in GitHub. At the moment, we already have three people, whose accounts are no longer active in GitHub. Let's just remove them from `people.xml`

**Comment by 0crat** [comment]
Job [#555](https://github.com/zerocracy/farm/issues/555) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9699](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#555](https://github.com/zerocracy/farm/issues/555) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641539502). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat waiting PR to merge #711

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #711  ([here](https://github.com/zerocracy/farm/issues/555#issuecomment-373307377))

@g4s8 The impediment for [#555](https://github.com/zerocracy/farm/issues/555) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #711  ([here](https://github.com/zerocracy/farm/issues/555#issuecomment-373307377))

@g4s8 Job [#555](https://github.com/zerocracy/farm/issues/555) is already on hold

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#835](https://github.com/zerocracy/farm/issues/835) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PR #771 was merged, `@todo` #835 was submitted, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#555](https://github.com/zerocracy/farm/issues/555) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#896](https://github.com/zerocracy/farm/issues/896) is still not solved; solved: [#835](https://github.com/zerocracy/farm/issues/835).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#835](https://github.com/zerocracy/farm/issues/835), [#896](https://github.com/zerocracy/farm/issues/896).
