### ISSUE TITLE
S3ItemTest.java:129-132: S3Item does not handle...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#556]
The puzzle `511-1a49e160` from #511 has to be resolved:

https://github.com/zerocracy/farm/blob/55b8680abb68fdf8aab8eebc43028f7aed58d373/src/test/java/com/zerocracy/farm/S3ItemTest.java#L129-L132

The puzzle was created by g4s8 on 02-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#556](https://github.com/zerocracy/farm/issues/556) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#556](https://github.com/zerocracy/farm/issues/556) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641555839). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@g4s8 see: https://github.com/zerocracy/farm/issues/724#issuecomment-370397740 This happened NOT when the production server was re-deploying.

**Comment by g4s8** [comment]
@0crat waiting PR to merge #805

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #805  ([here](https://github.com/zerocracy/farm/issues/556#issuecomment-373307448))

@g4s8 The impediment for [#556](https://github.com/zerocracy/farm/issues/556) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #805  ([here](https://github.com/zerocracy/farm/issues/556#issuecomment-373307448))

@g4s8 Job [#556](https://github.com/zerocracy/farm/issues/556) is already on hold

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/556#issuecomment-392309275))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#556](https://github.com/zerocracy/farm/issues/556), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#556](https://github.com/zerocracy/farm/issues/556) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1501356082); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@463ef985

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/556#issuecomment-393301061))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#556](https://github.com/zerocracy/farm/issues/556), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#556](https://github.com/zerocracy/farm/issues/556) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1510596210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@7963caaf

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait , I'm working on this right now

**Comment by 0crat** [comment]
> @0crat wait , I'm working on this right now ([here](https://github.com/zerocracy/farm/issues/556#issuecomment-394628981))

@carlosmiranda The impediment for [#556](https://github.com/zerocracy/farm/issues/556) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0pdd** [comment]
The puzzle `511-1a49e160` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#556](https://github.com/zerocracy/farm/issues/556) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality goof

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
