### ISSUE TITLE
0crat resigned DEV and CR without paying

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#560]
One PR, for which I was the reviewer, was closed today and I wasn't paid. Instead, 0crat said that I resigned from the issue. See here: https://github.com/yegor256/cactoos/pull/642#issuecomment-365853549

It did not deduct reputation points, though.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
Happened again, [here](https://github.com/yegor256/cactoos/pull/647#issuecomment-365951409).

**Comment by amihaiemil** [comment]
@yegor256 ping, check this one out :)

**Comment by nick318** [comment]
@yegor256 the same for dev role [here](https://github.com/yegor256/cactoos/issues/595)

**Comment by nick318** [comment]
@amihaiemil could you change a title to cover `DEV` role also.

**Comment by yegor256** [comment]
@amihaiemil I believe it was fixed in 0155c7e Let's close. If it shows up again, report it again please, in a new ticket.

**Comment by amihaiemil** [comment]
@yegor256 ok, sure

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+630](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#560` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#560](https://github.com/zerocracy/farm/issues/560) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/650823290). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/560#issuecomment-371802015))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#560](https://github.com/zerocracy/farm/issues/560) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23560%27%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 please, remove this job from WBS

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#560](https://github.com/zerocracy/farm/issues/560) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
