### ISSUE TITLE
0crat doesn't assign issues although there are free ones

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#561]
I'm assigned to [Cactoos project](https://www.0crat.com/p/C63314D6Z) and have DEV role. 0crat shows that Cactoos project has 15/23 jobs (there are 8 "free" issues that might be assigned to me). My rate is $16 that is the min allowed rate (but anyway the work on this project is not paid).

Is this a bug that 0crat doesn't assign any issues to me?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#561](https://github.com/zerocracy/farm/issues/561) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/461404090). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9844](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@proshin-roman I believe it's fixed

**Comment by proshin-roman** [comment]
@yegor256 it works! Thanks for the fix!

**Comment by yegor256** [comment]
@proshin-roman please, close the ticket. Thanks.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9899](https://www.0crat.com/u/yegor256)
