### ISSUE TITLE
Proposal to make on-demand task assignment option in 0crat

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#563]
Subj.

Currently, 0crat automatically assignes a set of tasks until the [threshold](http://datum.zerocracy.com/pages/policy.html#3) is met. Let's call this mode "automatic". However, there are some cases when automatic mode is unreasonably tough to follow, especially taking into account the fact that higher rates make this threshold larger:

- There is an accident on my side which had heavily impacted my performance and presence (like, laptop is broken).
- I am a part-time hobbyist and full-time slave (reality is a bitch), who can't yet affort being constantly present in 0crat.
- I am preparing for a vacation.

Idea is to make a mode when task assignment is done by explicit command to 0crat from DEV. Lets call it on-demand mode. Like:
`@0crat gimmeabreak on` - enables on-demand mode (or probably reuse `vacation` command for that?)
`@0crat gimmeabreak off` - enables automatic mode.
`@0crat gimmeatask` - searches for task and assigns it to a DEV if possible. Applicable only in on-demand mode.

PS: command names are given just to illustrate the principle and are not the end proposal.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral I'm not against this proposal but would like to understand the reason behind it. What exactly is the problem now? What are the symptoms?

**Comment by skapral** [comment]
@yegor256 Well, I'd formulate it that way: in some situations it is more convenient to control incoming work load manually, instead of letting it be controlled by 0crat. Especially when 0crat is not your main source of income and you are there just out of curiosity.

**Comment by yegor256** [comment]
@skapral we have this ticket: https://github.com/zerocracy/datum/issues/258 It is somehow related, I believe. Would that be enough?

**Comment by skapral** [comment]
@yegor256 yes, this would be sufficient.

**Comment by 0crat** [comment]
Job [#563](https://github.com/zerocracy/farm/issues/563) was not in scope
