### ISSUE TITLE
0crat can assign task silently

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#564]
This task https://github.com/zerocracy/farm/issues/281 was appeared in my agenda, but 0crat didn't comment on it, so I didn't receive notifications in Github. Here is `status` output: https://github.com/zerocracy/farm/issues/281#issuecomment-365898431

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#564](https://github.com/zerocracy/farm/issues/564) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4060](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 it's a mistery... The `Order was given`, for some reason, didn't create the `Notify user` claim:
<img width="865" alt="screen shot 2018-02-16 at 7 13 12 pm" src="https://user-images.githubusercontent.com/526301/36317202-8724b112-134d-11e8-9666-6601773d682e.png">

**Comment by yegor256** [comment]
@g4s8 the only thing I can blame is the re-deployment. We killed the server right when it wanted to notify you and the claim got lost.

**Comment by g4s8** [comment]
@yegor256 what do you think about using Amazon SQS or maybe ApacheMQ for claims delivery? I think they can guaranty message delivery even on app restart/redeploy and are able to work with multiple server intances in the future.

**Comment by yegor256** [comment]
@g4s8 they won't help anyhow, since the problem is our Java code. We kill the server when the claim is still in memory. We don't have a chance to save it to the file, and we won't be able to send it to SQS. So, we have to fix the deployment problem first: https://github.com/zerocracy/farm/issues/297

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/564#issuecomment-373633782))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#564](https://github.com/zerocracy/farm/issues/564), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#564](https://github.com/zerocracy/farm/issues/564) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1310641565); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 is this bug still being experienced? Seems like there was a fix in #695.

**Comment by carlosmiranda** [comment]
@0crat wait for clarifications

**Comment by 0crat** [comment]
> @0crat wait for clarifications ([here](https://github.com/zerocracy/farm/issues/564#issuecomment-389443713))

@carlosmiranda The impediment for [#564](https://github.com/zerocracy/farm/issues/564) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 @yegor256 please see my question above: https://github.com/zerocracy/farm/issues/564#issuecomment-389443626

**Comment by g4s8** [comment]
@carlosmiranda looks like it is not reproducing anymore, but #564 was closed as a duplicate of this bug

**Comment by carlosmiranda** [comment]
@g4s8 looks fixed in #695 then, can we close this?

**Comment by carlosmiranda** [comment]
@g4s8 looks fixed by @yegor256 in https://github.com/zerocracy/farm/commit/dc9c444cda635b706ab5055ebae495e988dcae2f then, can we close this?

**Comment by g4s8** [comment]
@carlosmiranda right, closing

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#564](https://github.com/zerocracy/farm/issues/564) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
