### ISSUE TITLE
'Make payment' is not testable

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#565]
It's not possible to check that 'Make payment' claim was called. I suppose that we can implement `FkPayroll` which will be used if `testing` flag found in `Props`. This `FkPayroll` can log payments to file, that will be accessible during test.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 yes, good idea. We can just set the wallet of a user to `file` instead of `paypal` and the system will just save the payment information into the file, instead of using `Paypal` class.

**Comment by 0crat** [comment]
Job [#565](https://github.com/zerocracy/farm/issues/565) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3985](https://www.0crat.com/u/g4s8)

**Comment by t-izbassar** [comment]
@g4s8 so what implementation is actually considered? If we want to save to `file` we just need the new implementation of `Bank` interface that will save details to file and we will add this to the `banks` map of the `Payroll` class. In that case we don't need `FkPayroll` right?

**Comment by g4s8** [comment]
@t-izbassar yes, we need just new `Bank` implementation whih will be used if user's wallet is a `file`.

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 18days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 18days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@0crat wait for #1040 to be merged.

**Comment by 0crat** [comment]
> @0crat wait for #1040 to be merged. ([here](https://github.com/zerocracy/farm/issues/565#issuecomment-391104874))

@t-izbassar The impediment for [#565](https://github.com/zerocracy/farm/issues/565) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#1066](https://github.com/zerocracy/farm/issues/1066), [#1067](https://github.com/zerocracy/farm/issues/1067), [#1069](https://github.com/zerocracy/farm/issues/1069) are still not solved.

**Comment by t-izbassar** [comment]
@g4s8 skeleton added in #1040, puzzles created. Can you close this one?

**Comment by g4s8** [comment]
@t-izbassar thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#565](https://github.com/zerocracy/farm/issues/565) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1069](https://github.com/zerocracy/farm/issues/1069) is still not solved; solved: [#1066](https://github.com/zerocracy/farm/issues/1066), [#1067](https://github.com/zerocracy/farm/issues/1067).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1428](https://github.com/zerocracy/farm/issues/1428) is still not solved; solved: [#1066](https://github.com/zerocracy/farm/issues/1066), [#1067](https://github.com/zerocracy/farm/issues/1067), [#1069](https://github.com/zerocracy/farm/issues/1069).
