### ISSUE TITLE
0crat assigned closed job

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#571]
Issue https://github.com/yegor256/cactoos/issues/629 was closed without any job done there and requested for QA review, and afterwards 0crat assigned it for some reason.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by flslkxtc** [comment]
I've encountered similar issue. Task https://github.com/yegor256/cactoos/issues/641 was assigned to me shortly after author closed it.

**Comment by 0crat** [comment]
The job [#571](https://github.com/zerocracy/farm/issues/571) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/471542634). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9919](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ypshenychka This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
@[ please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/571#issuecomment-366274668))

@yegor256 The user @yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#571](https://github.com/zerocracy/farm/issues/571), please stop working

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9904](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/571#issuecomment-366275156))

@yegor256 The job [#571](https://github.com/zerocracy/farm/issues/571) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/571#issuecomment-366275156))

@yegor256 Job [#571](https://github.com/zerocracy/farm/issues/571) was not in scope
