### ISSUE TITLE
Reputation mechanism should be configurable/project

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#572]
Currently, 0crat's is only managing **the project** -- the developers are offered by the platform, the client cannot work with his own team easily since everyone has to go through the sandbox/reputation building projects. 

I, as a client, may want to work with my own team. First step is very easy: I ask someone to invite all my team. But then here comes the bottleneck: they can't work on my project since they have 0 reputation. I should be able to decide how that reputation mechanism works for my project and if I want the developers to go thorough sandbox projects or not. 

What do you think? 

I see this situation arising quite often. For instance, there may be nobody on the platform that knows my tech stack, or there may be no available ARCH -- or maybe, since the ARCH is really the God in this model, I would like to at least bring my own architect, a person who I really trust.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 I see. Well, even that -256 -- I understand if they reach that point they are kicked out. Maybe I don't want them to be kicked out? I may not care about the reputation, maybe simply not paying them cash is enough of a "punishment" for me. Again, this is the idea that it's my team, they don't necessarily work on other projects on 0crat.

**Comment by yegor256** [comment]
@amihaiemil if you don't care about reputation and just want to pay them -- go to Upwork :) If you want them to live and work in Zerocracy, you have to follow **our** rules. That's the only way we can guarantee you something.

**Comment by amihaiemil** [comment]
@yegor256 I would just like 0crat to be more flexible. I'm talking about the XDSD/PDD methodology alone, which can be practiced without the competition and punishmend mechanisms, if the client already knows their team. 

I think there will be both kind of clients -- the ones who want to rely 100% on all the platform and the ones who would like to use it for XDSD/PDD alone, with the scope of not having to pay for a human Project Manager. 

Nevertheless, I close this one and open another if I get other ideas :)
