### ISSUE TITLE
0crat doesn't understand quality verdict

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#580]
As described [here](http://datum.zerocracy.com/pages/policy.html#30) Zerocrat should understand verdicts like "quality is good", "quality is acceptable" and "quality is bad".

But looks like there is some [problem](https://github.com/yegor256/jpeek/issues/191#issuecomment-366340078).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
And again this [issue](https://github.com/yegor256/cactoos/pull/572#issuecomment-366347049).

**Comment by 0crat** [comment]
Job [#580](https://github.com/zerocracy/farm/issues/580) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#580](https://github.com/zerocracy/farm/issues/580) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/472035761). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10009](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ypshenychka you are right, there is a problem, fixing it now...

**Comment by yegor256** [comment]
@ypshenychka I believe it's fixed, but the right command is `quality bad` or `quality acceptable` or `quality bad`. Skip the `is`.

**Comment by ypshenychka** [comment]
@yegor256 Works now. Thank you. Should I close the issue?

**Comment by yegor256** [comment]
@ypshenychka yes, please close the ticket

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10084](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@yegor256 Shouldn't 0crat give points for reporting issues?

**Comment by yegor256** [comment]
@ypshenychka yes, only if you are a member of the project. We are going to change this soon: https://github.com/zerocracy/datum/issues/248
