### ISSUE TITLE
Impediments are not removed when job completed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#581]
Impediments will be kept in `xml` file forever at moment. I think it should be removed when job completed or cancelled. (related to #447)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it happens on the level of XML artifacts, we don't need any Groovy code for that.

**Comment by g4s8** [comment]
@yegor256 ok, thanks. I submited an issue about auto: zerocracy/datum#283
