### ISSUE TITLE
0crat should release task from agenda after issue closed

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#587]
Actual behavior: DEV finishing task, issue reporter closed it. Now, he should wait for QA verdict. In meantime, task is done, result is delivered and merged. DEV is ready to take other task, but if he's agenda is full - he's time is wasted on waiting. QA verdict time will may take 10 days or even more, if 1 QA will be resigned. All this time is wasted.

Expected: DEV finishing task, issue reporter closed it. 0crat should release this task from agenda or point it out to status: `waiting QA verdict`. This status should allow to take next task, if he's performance allows him do that. Result is delivered. The only thing DEV waiting is payment, which depends on QA verdict. He perfectly able to tackle next task.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@t-izbassar This issue also applies for PRs. CR does their job, the PR is merged and then a QA is assigned.

Furthermore (and I think it may apply to DEV as well, on their assigned task), 0crat continues to count the 10 days rule for the assignee. For instance [here](https://github.com/yegor256/cactoos/pull/628#issuecomment-366454358) -- 0crat assigned the QA, but later warned me that 5 days already passed and I should close the PR. 

This is probably a more complex issue: 0crat has to assign the task to QA but at the same time remember who was the assignee before (the DEV or the CR, depending if it's an Issue or a PR), so it can also pay them.

**Comment by t-izbassar** [comment]
@amihaiemil I don't think that 10 days rule should change. The only thing that I'm care in this issue is that I can't tackle next task, while waiting for QA review. The fact that I cannot do something in that time anyway is what matters - I can't influence QA review anyway so why my time should be wasted? I already delivered the result.

Imagine you have all of your agenda of such closed tasks only waiting for QA review. Afaik there is no punishments for late QA responds and they don't have 10 days rule. You may end up even be resigned from all the **delivered** tasks due to 10 days rule, even though your job is done.

**Comment by yegor256** [comment]
@t-izbassar that's a good poing

**Comment by 0crat** [comment]
The job [#587](https://github.com/zerocracy/farm/issues/587) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/501225493). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+315](https://www.0crat.com/u/t-izbassar)

**Comment by yegor256** [comment]
@t-izbassar @amihaiemil how about we make a rule that if a QA review is not completed in 48 hours, we consider quality as "acceptable" and move on?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10074](https://www.0crat.com/u/yegor256)

**Comment by amihaiemil** [comment]
> how about we make a rule that if a QA review is not completed in 48 hours, we consider quality as "acceptable" and move on?

@yegor256 I don't think it's correct to make that assumption. On the other hand, I think the 10 day count should stop the moment a QA is assigned -- the DEV and CR have both completed their jobs, why should they be taxed for QA being late? What about the QA, aren't they taxed?

**Comment by yegor256** [comment]
@t-izbassar @amihaiemil it seems we have to finalize everything and put a new record into a special `inspections.xml` XML file. When the QA is completed, we take the information from the file and make all payments.

**Comment by amihaiemil** [comment]
> I don't think that 10 days rule should change.  [...] Imagine you have all of your agenda of such closed tasks only waiting for QA review. Afaik there is no punishments for late QA responds and they don't have 10 days rule. You may end up even be resigned from all the delivered tasks due to 10 days rule, even though your job is done.

@t-izbassar The first statement and the last paragraph contradict each other. That's exactly what I'm saying, the 10 days count should stop the moment a QA is assigned. because the DEV or CR cannot control the QA and make them move fast. Why should they possibly lose the delivered task if the QA takse a lot of time and the 10 days expire?

**Comment by t-izbassar** [comment]
@yegor256 @amihaiemil sorry, but this issue **is not** about punishments, 10 days rule, QA being late, payments and other staff.

This issue is about the fact, that DEV can take new task after the issue is closed (meaning that result is delivered). There are 2 solutions to that:
* release task from agenda (I feel like this is wrong, as job is still in scope and should be visible)
* mark task as `on QA review` (similar to `on hold`) - this status should be enough to not to look at this task, when calculating whether the agenda is full or not.

That's it. @yegor256  can you confirm that marking task with such status and that tasks with such mark should not be affected when calculating the jobs limit for DEV is the issue to address?

**Comment by t-izbassar** [comment]
I created #596 to address issue with possibility of loosing all the jobs.

**Comment by yegor256** [comment]
@t-izbassar it goes all together. We either remove the job from WBS (scope) before the QA verdict or after. Depending on that everything else will happen either faster or slower.

**Comment by amihaiemil** [comment]
@yegor256 What does it have to do with the scope of the job? The job is always in scope no matter to whom it is assigned. It's a matter of assignments only, right? 0crat should count and pay the assignee only + remember past, payment-pending assignees, like the CR.

**Comment by t-izbassar** [comment]
@yegor256 I feel like if we want to work on greed philosophy we should just punish QA, REV and ARC for the late responses. That should be enough.

**Comment by yegor256** [comment]
@amihaiemil here is the logic: https://github.com/zerocracy/datum/commit/bd891e025852fbe7a7063e872f14807f431a502a First, we close order, then we remove job from WBS, then we pay.

**Comment by llorllale** [comment]
This [job](https://github.com/yegor256/jpeek/issues/120) is still on my agenda even after having being completed 2 days ago.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@t-izbassar this will be fixed when we fix #646

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10999](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#587](https://github.com/zerocracy/farm/issues/587) is now out of scope
