### ISSUE TITLE
Can't run tests locally on windows os

### ISSUE THREAD

**Issue by neonailol** [zerocracy/farm#589]
When running `mvn test`, i get failures regarding that i don't have `mongod` file in path
i suggest using embedded mongo for running tests

second failure is
```
Failed tests:
  S3ItemTest.refreshesFilesOnServer:119
Expected: not an empty iterable
     but: was <[]>
```
and i can't understand what should i do

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#589](https://github.com/zerocracy/farm/issues/589) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+570](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#589](https://github.com/zerocracy/farm/issues/589) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/661861497). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat refuse (don't have windows)

**Comment by 0crat** [comment]
> @0crat refuse (don't have windows) ([here](https://github.com/zerocracy/farm/issues/589#issuecomment-371248497))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#589](https://github.com/zerocracy/farm/issues/589), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#589](https://github.com/zerocracy/farm/issues/589) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/831657558); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by amihaiemil** [comment]
@0crat refuse (no windows)

**Comment by 0crat** [comment]
> @0crat refuse (no windows) ([here](https://github.com/zerocracy/farm/issues/589#issuecomment-375905943))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#589](https://github.com/zerocracy/farm/issues/589), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#589](https://github.com/zerocracy/farm/issues/589) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1371350053); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@neonailol Didn't you fix it already in #590? If so pls close this issue.

**Comment by neonailol** [comment]
@krzyk yes, all good now

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#589](https://github.com/zerocracy/farm/issues/589) is now out of scope

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
