### ISSUE TITLE
Payments not received for QA review

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#592]
I've already received 5 awards (15 point for each ticket), but haven't received any payments on PayPal account. My email address is juliakarate@yahoo.com.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
@yegor256 It's pretty urgent as far as a lot of tickets are pending QA review.

**Comment by yegor256** [comment]
@ypshenychka looking into it now

**Comment by amihaiemil** [comment]
@yegor256 Have a look here: https://github.com/zerocracy/farm/issues/587 . Given the behaviour explained there, I think it seems to be a matter of assignment.

**Comment by amihaiemil** [comment]
@yegor256 and I also did not get paid [here](https://github.com/yegor256/cactoos/pull/649#issuecomment-366422817)

**Comment by yegor256** [comment]
@ypshenychka try now, should work, I believe

**Comment by ypshenychka** [comment]
@yegor256 Tried in https://github.com/yegor256/cactoos/issues/608, but haven't received any payment yet.

**Comment by yegor256** [comment]
@ypshenychka can you please try again?

**Comment by ypshenychka** [comment]
@yegor256 reviewed issue https://github.com/yegor256/jpeek/issues/134. No payment as well. I can't do reviews for free :)

**Comment by yegor256** [comment]
@ypshenychka I'm sorry about this situation, we're just starting to use this new QA feature. When it's fixed, everything will work smoothly)

**Comment by ypshenychka** [comment]
@yegor256 Thank you. Please keep me posted with progress. Currently I have to postpone any pending QA reviews.

**Comment by yegor256** [comment]
@ypshenychka the problem was found, it's related to your PayPal account, I emailed you. Let's see what we can do. In the meantime we will make it possible to receive payments in Bitcoin.

**Comment by ypshenychka** [comment]
@yegor256 Thank you. Looks like everything's fine now. Closing the issue.
