### ISSUE TITLE
0crat is silent when QA verdict is bad

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#594]
Actual behavior: there was a verdict in [this issue](https://github.com/yegor256/takes/issues/744). After that, job is out of my agenda with no points and monetary award received. I can only knew about it if I look at job status, check my agenda and awards page. That's too tedious.

Expected behavior: after `quality bad` verdict there should be a message telling something like that:
> Job is now out of scope. There were no rewards for @t-izbassar due to bad quality.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#594](https://github.com/zerocracy/farm/issues/594) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/501201637). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+300](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10079](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@t-izbassar thanks, I belive it's fixed

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10119](https://www.0crat.com/u/yegor256)
