### ISSUE TITLE
DEV can lose all jobs due to QA being late

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#596]
As i pointed out [here](https://github.com/zerocracy/farm/issues/587#issuecomment-366665274)
> Imagine you have all of your agenda of such closed tasks only waiting for QA review. Afaik there is no punishments for late QA responds and they don't have 10 days rule. You may end up even be resigned from all the delivered tasks due to 10 days rule, even though your job is done.

The issue with current behavior of 0crat:
If I as a DEV finished the task, it is merged and issue is closed - I still have 10 days rule applied for me, as job is still in scope waiting for QA to finish his review. That can lead to the point, when all of the jobs are just waiting for QA review even though the result was delivered.

Proposed behavior: as mentioned in #587 if there will be status for task as `on QA review` we can assume from that point that task is delivered. The speed of deliverable should be calculated till that point. However, all information about task should be collected in `inspections.xml` and payments will be made after QA will finish his review as proposed [here](https://github.com/zerocracy/farm/issues/587#issuecomment-366681283)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
This is duplicate for #587 .
