### ISSUE TITLE
Exception due processing task by 0crat

### ISSUE THREAD

**Issue by nick318** [zerocracy/farm#597]
0crat has exception by processing task:
Steps:
1. ARC added label 'Bug'
2. 0crat said:
```
 com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```
here: https://github.com/yegor256/cactoos/issues/670#issuecomment-366700745
3. 0crat added label scope

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nick318 dup of https://github.com/zerocracy/farm/issues/511
