### ISSUE TITLE
_after.groovy:28-33: The ticket should be removed from...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#599]
The puzzle `539-4e7a4000` from #539 has to be resolved:

https://github.com/zerocracy/farm/blob/47767e3480885278ad9cac2452414a75afc11aa4/src/test/resources/com/zerocracy/bundles/close_the_job/_after.groovy#L28-L33

The puzzle was created by g4s8 on 15-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#599](https://github.com/zerocracy/farm/issues/599) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
The puzzle `539-4e7a4000` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#599](https://github.com/zerocracy/farm/issues/599) is now out of scope
