### ISSUE TITLE
0crat unrecoverable failure after QA review

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#603]
As per https://github.com/yegor256/jpeek/issues/162#issuecomment-366797157:

>@ypshenychka There is an unrecoverable failure on my side. Please, submit it here:
>com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor236[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $12.50 to yegor@tpc2.com with memo "Payment for gh:yegor256/jpeek#162 (30 minutes): Order was finished, quality was "acceptable""
com.zerocracy.pmo.banks.Paypal[201] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The sender and each receiver must have different accounts]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
Also [here](https://github.com/yegor256/jpeek/issues/90#issuecomment-366888229) a failure

**Comment by llorllale** [comment]
@yegor256 missed payment after QA review on [this](https://github.com/yegor256/jpeek/issues/90) and received this error via private chat from 0crat:

> We are very sorry, but we failed to pay you $8.00 for #90 (https://github.com/yegor256/jpeek/issues/90): "Failed to pay $8.00 to george.aristy@gmail.com with memo "Payment for #90 (https://github.com/yegor256/jpeek/issues/90) (30 minutes): Order was finished, quality was "acceptable"""; please, ask your mentor to help you out or submit a ticket to https://github.com/zerocracy/farm

**Comment by yegor256** [comment]
@ypshenychka thanks for reporting, it's a temporary problem, will disappear soon.

**Comment by yegor256** [comment]
@llorllale it's better so submit a different ticket, these two problems are not related to each other
