### ISSUE TITLE
personality type format is wrong

### ISSUE THREAD

**Issue by ashtonhogan** [zerocracy/farm#604]
1. Go to: https://www.0crat.com/join
2. Enter all the details
3. Enter INTJ-A as personality type as recommended
4. Try click Submit

-> You get a validation error stating that the personality type format is wrong

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan fixed already, thanks!

**Comment by ashtonhogan** [comment]
@yegor256 in agile, if you fix something but then break something else, it's not considered "done". I'm not sure if you agree with that approach or not. If you don't, I can create another issue...

If you submit the details, it takes you to this url: https://www.0crat.com/join-post

Which is a blank screen, then it does nothing, just stays there

**Comment by yegor256** [comment]
@ashtonhogan that's a separate problem, it's not implemented yet: https://github.com/zerocracy/farm/issues/602

**Comment by ashtonhogan** [comment]
@yegor256 Okay, I'm assuming the details went through
