### ISSUE TITLE
submit an rfp makes negotiations more difficult

### ISSUE THREAD

**Issue by ashtonhogan** [zerocracy/farm#605]
The client doesn't really want to wait to know if we're going to do their work or not WHILE we're asking them for work, it doesn't make sense... I think there's potentially a level of verbal interaction required at the negotiations phase, no?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan what exactly are you suggesting? I didn't get the idea.

**Comment by ashtonhogan** [comment]
@yegor256 that the process makes it difficult to compete against other software consulting companies who have no red tape.

Going through the problems one by one:

1. "You need to make one of them interested in your project" - Let's say I've fished out a client, they're interested and want to use your services but then I can't find anyone interested?

2. "Once you pay us the entrance fee below, we let you fill out and submit the form" - I'm only looking at big clients, I'm not wasting my time with $500 projects, however, if I have to pay money for every client I bring, that's going to start adding up...

3. "One of them will get back to you by email and you will discuss the next steps" - Like discuss price? How do I communicate price to possible clients? Other consulting companies will be able to give this information upfront. They are selling price, quality and speed without red tape, we're selling the same WITH red tape. We're already less competitive?

4. "Statement of work" - This has no field for adding attachments. Some projects require archives and other items to be added to the work description. Maybe consider using private github repositories and linking to those instead so that requirement changes can be versioned as well...

**Comment by yegor256** [comment]
@ashtonhogan Zerocracy is not a consulting company. We are not going to sell our services to clients directly, since they won't be able to understand how we work. This would be a waste of time. They are used to work with slaves and body shops. Zerocracy is not for them. We are going to sell our platform to architects mostly/only. They will bring clients on board. This RFP page is only for those who are very curious and ready to try. I don't think they will actually achieve anything, since, like I said, they are used to working with consulting body-shops full of nine-to-five slaves :)

**Comment by ashtonhogan** [comment]
@yegor256 Realistically I think it's more like this:

Technical people: "Business decisions make us slaves"
Business people: "Technical decisions make us poor"

Tech people are wired differently, they don't spend all their time thinking about budgets and numbers...

It's going to be hard to get through to the people with the keys to the bank with only technical lures...

You have your own system, fine. However, show me the money. Show me proof that it's going to be more profitable. That's what they're going to want to see, is this information public?

**Comment by yegor256** [comment]
@ashtonhogan yes, here: http://www.yegor256.com/2014/04/11/cost-of-loc.html

**Comment by ashtonhogan** [comment]
@yegor256 thanks that's perfect. 

I have a bit more though. Perhaps another issue can be created under the blog repo...

These are the kinds of questions I expect to get asked:

1. Sales - Are you making sales? Are people interested in you? Are you going to disappear in a few months?

2. Cash Flow - Are you desperate? Are you just looking for some quick money? What length of business relationship can you afford?

3. Scalability - If you grow too big, will I as a client remain relevant and get the attention that I need?

4. Uncertainty - It sounds good but I'm not sure, can we try before buy?

5. Remote Workers - In theory you promise 24/7 because of distributed workforce but in reality the quality changes and hits peak at certain times, no?

6. Code Transfer - I want to take the work you've done and give it to another consulting company. How can I do this? Copyrights? Patents? Trademarks? Licenses?

7. Turn around time - Figures compared to competitors?

**Comment by yegor256** [comment]
@ashtonhogan here: https://latexonline.cc/compile?git=https%3A%2F%2Fgithub.com%2Fzerocracy%2Fzerocracy.github.io&target=_pdf%2Fexecutive-summary.tex&command=pdflatex&trackId=1519319446613

The sources is here: https://github.com/zerocracy/zerocracy.github.io/blob/master/_pdf/executive-summary.tex Feel free to contribute or submit tickets to that repo.
