### ISSUE TITLE
Failed payment for DEV after 'quality acceptable'

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#606]
Missed payment after QA review on [this](https://github.com/yegor256/jpeek/issues/90) and received this error via private chat from 0crat:

> We are very sorry, but we failed to pay you $8.00 for #90 (https://github.com/yegor256/jpeek/issues/90): "Failed to pay $8.00 to george.aristy@gmail.com with memo "Payment for #90 (https://github.com/yegor256/jpeek/issues/90) (30 minutes): Order was finished, quality was "acceptable"""; please, ask your mentor to help you out or submit a ticket to https://github.com/zerocracy/farm

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale that's a weird bug. We received "payment source is not available from PayPal" but then all other transactions just go forward without problems. We are planning to switch to [mass payments](https://www.paypal.com/us/webapps/mpp/mass-payout-payments) soon. Hopefully, that will help.

**Comment by 0crat** [comment]
Job [#606](https://github.com/zerocracy/farm/issues/606) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@yegor256 does the change to mass payouts mean that zerocracy will handle payments via batch jobs?

**Comment by yegor256** [comment]
@llorllale no, we'll pay for each job, as before. It's just a new payment API of PayPal. The one we are using now ([Adaptive Payments](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/)) is deprecated. Maybe that's why it fails sporadically.

**Comment by driver733** [comment]
@yegor256 I have faced the same problem today.
![img_3939](https://user-images.githubusercontent.com/10466206/36431696-3d3d23fa-1626-11e8-8b93-64a5c9c02e5c.jpg)

**Comment by yegor256** [comment]
@llorllale @driver733 indeed, the problem manifests itself time to time. We are trying to switch to this new payment API of PayPal soon.

**Comment by 0crat** [comment]
The job [#606](https://github.com/zerocracy/farm/issues/606) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511560135). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10374](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@llorllale does this bug still relevant? I think it was fixed already. Can we close this?

**Comment by llorllale** [comment]
@g4s8 haven't had this issue again. Even forgot about it. Thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#606](https://github.com/zerocracy/farm/issues/606) is now out of scope
