### ISSUE TITLE
Implementation details should not be mentioned in the policy

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#607]
At [vesting](http://datum.zerocracy.com/pages/policy.html#37) the Policy urges the PO to "just modify the rates in ``vesting.xml``". 

How exactly is that? Should there be a ``vesting.xml`` file in the project's repo? Or is there a UI for this (in which case the Policy should point to that)? 

In any case, it's unprofessional and not user friendly to make users modify XML files. Especially since they are paying for the service.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I added this 679cb57 Everything else will be explained in the `Files` tag. I think it's enough. WDYT?

**Comment by amihaiemil** [comment]
@yegor256 strange, it didn't turn into a link to the commit, what exactly did you do?

**Comment by yegor256** [comment]
@amihaiemil oops, you reported the ticket to the wrong repo. I fixed here: https://github.com/zerocracy/datum/commit/679cb57e3ae1122c149490d618ecfcc4fe464263

**Comment by amihaiemil** [comment]
@yegor256 right; looks better now, closing this :D
