### ISSUE TITLE
Unit tests always hangs

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#608]
After merging master with [embedded mongodb](https://github.com/zerocracy/farm/pull/590) version, unit tests started to hang on my laptop after 3-5 passed tests, so I'm not able to run unit-tests at all. But as I can see Travis can run all tests successfully. Looks like it includes some platform-depended binaries.
4b720f0c0e44c712973aa045ebaa971a4af8997b - hangs on this commit
I tried to build on parent commit - it's working fine: 4bf4710b766e5cb99127f28bc755926427091f56

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @neonailol

**Comment by 0crat** [comment]
> @0crat assign @neonailol ([here](https://github.com/zerocracy/farm/issues/608#issuecomment-367002966))

@yegor256 The job [#608](https://github.com/zerocracy/farm/issues/608) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511456005). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat assign @neonailol ([here](https://github.com/zerocracy/farm/issues/608#issuecomment-367002966))

@yegor256 Job `gh:zerocracy/farm#608` already assigned to @neonailol, can't assign to @neonailol

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4375](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10354](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10354](https://www.0crat.com/u/yegor256)

**Comment by neonailol** [comment]
@g4s8 i will look into it soon, what os are you using? i can only test it on linux and windows

**Comment by g4s8** [comment]
@neonailol I'm using Gentoo Linux `x86_64 4.9.76-gentoo-r1`
my java version:
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
Default locale: en_US, platform encoding: UTF-8
```
maven version: `Apache Maven 3.3.9`

**Comment by neonailol** [comment]
@g4s8 sorry i tried different installations of linux, and everythings works fine for me (

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@neonailol looks like this plugin is loading something big from internet without logs, it was fixed when I leaved paused test for 20 minutes

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+344](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#608](https://github.com/zerocracy/farm/issues/608) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +0 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10829](https://www.0crat.com/u/yegor256)
