### ISSUE TITLE
I did not complete the job but still got paid

### ISSUE THREAD

**Issue by neonailol** [zerocracy/farm#610]
Issue in question: https://github.com/zerocracy/farm/issues/186
I registered waiting on this task, but some one else complete it, 
and i still got my 30 points and 5$ in payments,
i believe it does not suppose to work like that

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol it's inevitable, sometimes this may happen. We can't prevent it. Enjoy the payment)
