### ISSUE TITLE
RbOnClose should take some time

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#616]
`RbOnClose` should create a claim, which will be processed in 15 minutes (using `until()`). That claim will check the status of the GitHub job and do what `RbOnClose` is doing now. If the issue is not closed, it will just do nothing.

See what happened here: https://github.com/zerocracy/farm/issues/465#issuecomment-367366704

**Comment by yegor256** [comment]
@0crat  assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/616#issuecomment-367367420))

@yegor256 The job [#616](https://github.com/zerocracy/farm/issues/616) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/521545764). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10574](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10574](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 I believe we need some mechanism for many other radar reactions. We should not react immediately, but do it in a few minutes. But we can't use any "background threads" for that, because the server may be restarted and we will lose everything. We have to create claims immediately, which will do the real work later.

**Comment by t-izbassar** [comment]
@yegor256 I have assigned to already finished task [see](https://github.com/yegor256/takes/issues/780#issuecomment-367603803). Does it related to this issue?

If yes, can you resign it from me? As it eats my agenda.

**Comment by g4s8** [comment]
> I believe we need some mechanism for many other radar reactions

@yegor256 maybe we can specify some claim types which should be delayed and set `until` field automatically for them?

**Comment by yegor256** [comment]
@g4s8 I think we should go this direction. We should set `until` to, say, 15 minutes ahead, for some radar-generated claims. Then, we should introduce a new Groovy stakeholder, which will go through the list of claims in `claims.xml` and delete some of them, using certain logic. For example, if it says `Add job to WBS` and the GitHub ticket is closed -- it deletes the claim.

Some sort of sanity check/cleaning of the list of claims. WDYT?

**Comment by g4s8** [comment]
@yegor256 I think it can be a bit simpler if we do claim's check right before take it from xml (I.e. in `DefaultFlush` after `claim.take()`), WDYT?

**Comment by yegor256** [comment]
@g4s8 but where will the logic be located? There will be a lot of it. At the moment we have just three radars and they understand just a few user operations. In the future there will be many more. Where all that logic be stored?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #650

**Comment by 0crat** [comment]
> @0crat waiting #650  ([here](https://github.com/zerocracy/farm/issues/616#issuecomment-369990812))

@g4s8 The impediment for [#616](https://github.com/zerocracy/farm/issues/616) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 I think you're right - it will be easier to implement it as a stakeholder, I created a ticket about it: #723

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by g4s8** [comment]
@yegor256 so can we close then? PR #650 with fix for `RbOnClose` was merged and ticket for generic mechanism #723 was submited

**Comment by yegor256** [comment]
@g4s8 right, thanks

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#616](https://github.com/zerocracy/farm/issues/616) is now out of scope
