### ISSUE TITLE
0crat did not pay CR

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#617]
QA gave a "good" quality verdict [here](https://github.com/yegor256/cactoos/pull/687#issuecomment-367387223), 0crat said it paid everyone but did not send any money to my paypal (it did award the reputation points, though). 

Maybe it has to do with the fact that another payment was done 2-3min earlier in another PR [here](https://github.com/yegor256/cactoos/pull/575#issuecomment-367389212)?

I also checked paypal and there really is no payment. Unlike other [similar situation](https://github.com/zerocracy/farm/issues/606) I did not receive any message in Slack (I have a private chat with 0crat there).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I can't trace this situation, because the logs were not complete. I fixed them. Let's wait for a similar problem.

**Comment by g4s8** [comment]
@amihaiemil I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#617` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
