### ISSUE TITLE
PO should be able to set 0crat's Github account

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#618]
Currently, 0crat works only via its designated Github account, but we should let POs decide which account to use-- maybe they would like to receive the emails as well when the bot is tagged in a comment. Or maybe they simply want to use 0crat bot with an account that has some special perimissions. Who knows what CI/CD pipeline they could build via a Github webhook and they may need a certain account for it. 

This shouldn't be so hard, just a config on the project's page where the user would specify the Github access token. Or simply instruct 0crat in slack to use a certain token for their account.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil I think ideally 0crat should be converted to GitHub app and use app token instead of GH user token.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#618` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
