### ISSUE TITLE
Equity proof pdf has wrong format

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#619]
Equity proof pdf doesn't open in Ubuntu's standard `Document Viewer`:
![image](https://user-images.githubusercontent.com/24223260/36496568-fa66fe16-1738-11e8-8803-8ca1bc9e910b.png)

And it is also cannot be open in Chrome browser:
![image](https://user-images.githubusercontent.com/24223260/36496603-173d55f8-1739-11e8-89b8-955dd7d908ba.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar see #453

**Comment by yegor256** [comment]
@t-izbassar fixed, please check
