### ISSUE TITLE
Allow performer to set maximum number of tasks

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#621]
Currently, we set the maximum Agenda size of the user [depending on their reputation](http://datum.zerocracy.com/pages/policy.html#3):

> The emptiest agenda wins, but the maximum allowed size of agenda depends on your reputation: 3 jobs if less than 512 points, 8 if less than 2048, 16 if less than 4096, 24 otherwise.

Folks with good performance (i.e. high reputation) may want to limit the amount of tasks they receive for some reason... they may be busy, can't keep up, just want to hang out in the beach, or whatever. In any case they may want to receive a smaller amount of tasks but not be on "vacation mode".

We should allow the user to set their preferred max agenda size. Their agenda size would then be `min(preferred_agenda_size, reputation_agenda_size)`. If the user specifies "0" it means just set it to whatever the agenda size we set in the policy.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@carlosmiranda dup of https://github.com/zerocracy/datum/issues/258
