### ISSUE TITLE
debts.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#625]
Let's create a new document `pmo/debts.xml` which will accumulate all failed payments (like this one: #624). Then, time to time, once a day, we will try to make an aggregated payment for each user.

**Comment by 0crat** [comment]
Job [#625](https://github.com/zerocracy/farm/issues/625) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10694](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#625](https://github.com/zerocracy/farm/issues/625) is now out of scope
