### ISSUE TITLE
after paying for rfp I can't create an rfp

### ISSUE THREAD

**Issue by ashtonhogan** [zerocracy/farm#626]
You (@ashtonhogan) must be invited to us by someone we already know, see §1

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan the payment hasn't been made yet, our backend failed right before the payment step. I fixed the access control in 567a2420f9ea9aee73b0c221680c6cbd2b4c0327 Please, try to make it again.

**Comment by ashtonhogan** [comment]
Works
