### ISSUE TITLE
pay

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#627]
Let's make it possible to pay a user something extra. Just a simple command:

```
@0crat pay 30min @yegor256
```

Zerocrat should initiate `make_payment` but with an extra param `awards` equal to the amount of minutes of the payment. Moreover, we should add -60 points to the initiator of the payment.

Let's not forget to update the policy.

**Comment by 0crat** [comment]
Job [#627](https://github.com/zerocracy/farm/issues/627) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10709](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#627](https://github.com/zerocracy/farm/issues/627) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641205435). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#627](https://github.com/zerocracy/farm/issues/627) is now out of scope
