### ISSUE TITLE
Can not see rfp page

### ISSUE THREAD

**Issue by neonailol** [zerocracy/farm#628]
According to policy http://www.zerocracy.com/policy.html#40 you need 512 reputation to see rfp page, but in code this parameter set to minimum of 2048, and i cant access rpf page with my reputation of 570

https://github.com/zerocracy/farm/blob/0e5c7619b0e895af897f4cc93876341cefa0a04c/src/main/java/com/zerocracy/tk/rfp/TkRfps.java#L68

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol fixed in 32b1b52c92fd373a0d313243a63464aea57ca45e and deployed
