### ISSUE TITLE
Received only +8 points for QA review and in debt the payment is also lower

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#629]
Happened [here](https://github.com/yegor256/jpeek/pull/208#issuecomment-367826756) and [here](https://github.com/yegor256/cactoos/issues/666#issuecomment-367754137).
I've received only 8 points for QA review (instead of 15) and payment transaction in debts is 2.13$ instead of 4$.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
Saw change in policy right now. Closing issue.
