### ISSUE TITLE
enhance policy with responsiveness bonus

### ISSUE THREAD

**Issue by ashtonhogan** [zerocracy/farm#630]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan we have it already: http://www.zerocracy.com/policy.html#36 Or what do you mean?

**Comment by ashtonhogan** [comment]
@yegor256 that link says: `If this interval is shorter than 4 hours, you get extra 10 minutes.`

I meant monetary bonus, not time bonus

**Comment by yegor256** [comment]
@ashtonhogan "extra 10 minutes" means points + money, not just points.
