### ISSUE TITLE
0crat should not reassign a PR which is in QA stage

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#631]
Heppened [here](https://github.com/yegor256/jpeek/pull/179#issuecomment-367991164). PR was merged, closed and was assigned to QA. The QA asked the author to do some changes in order to comply with the quality policy.

The author did not do those changes, so I, the reviewer, lost the task since 10 days passed. Not a problem for the CR, it's his/her punishment. After all, it is the CR's mistake: the PR got merged in the first place, without complying to all QA policies. 

The QA should be paid anyway, but the task should not be reassigned. If a CR lost the pull request in that stage, it's his/her punishment that they allowed it to be merged, but it shouldn't be reassigned since the next CR has no tools to fix it -- the original author has no interest in fixing it, the task will just float around from CR to CR and punish everyone for no reason.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil this will be fixed automatically, once we implement #646
