### ISSUE TITLE
0crat wasn't able to register impediment first time

### ISSUE THREAD

**Issue by valignatev** [zerocracy/farm#633]
![image](https://user-images.githubusercontent.com/7038954/36603832-c3d08da6-1907-11e8-8e1d-d0ba6790bbb2.png)
As you can see in the image, first time it doesn't quite get the message.
Here's first time I've tried say `waiting` to 0crat: [comment link](https://github.com/yegor256/0pdd/issues/24#issuecomment-368050936)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#633](https://github.com/zerocracy/farm/issues/633) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @valentjedi[/z](https://www.0crat.com/u/valentjedi)! If you would be a member of [the project](https://www.0crat.com/p/C3NDPUA8L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#633](https://github.com/zerocracy/farm/issues/633) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/681662672). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/633#issuecomment-374131789))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#633](https://github.com/zerocracy/farm/issues/633), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#633](https://github.com/zerocracy/farm/issues/633) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/831672948); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@yegor256 Could you take this out of scope? I don't think it's applicable anymore.

**Comment by 0crat** [comment]
The job [#633](https://github.com/zerocracy/farm/issues/633) is now out of scope
