### ISSUE TITLE
0crat assigning closed job to DEV again

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#635]
As per https://github.com/zerocracy/farm/issues/571#issuecomment-366269644:

0crat assigned [this](https://github.com/yegor256/jpeek/issues/138#issuecomment-367929373) issue back to me after QA was done

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by llorllale** [comment]
@yegor256 please resign me from [this](https://github.com/yegor256/jpeek/issues/138#issuecomment-367929373) issue

**Comment by llorllale** [comment]
@yegor256 I've been assigned to [another](https://github.com/yegor256/jpeek/issues/119) closed issue again

**Comment by yegor256** [comment]
@llorllale this was the cause: #658  Fixed already, won't happen again.

**Comment by llorllale** [comment]
@yegor256 it just happened again [here](https://github.com/yegor256/jpeek/issues/124)

**Comment by llorllale** [comment]
@yegor256 also [here](https://github.com/yegor256/jpeek/issues/140)
