### ISSUE TITLE
0crat failed to make payment

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#637]
Happened [here](https://github.com/yegor256/cactoos/issues/646#issuecomment-368207616)
>@ypshenychka There is an unrecoverable failure on my side. Please, submit it here:

com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '//*[@id='45.share']/text()' not found in '<?xml version="1.0" encoding="UTF-8"?><html xmlns=..35780..</script>\uA      </body>\uA   \uA</html>': Index (0) is out of bounds (size=0)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka fixed, thanks. won't happen again.
