### ISSUE TITLE
Authorization is not secure

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#640]
@yegor256 It's possible to login to 0crat.com as any user and access all user's projects (or other pages). Can provide more details directly and publish here after fix.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 email me the details please

**Comment by yegor256** [comment]
@g4s8 so your point is that `CcXor` is not strong enough. Let's use `CcAes`.

**Comment by 0crat** [comment]
The job [#640](https://github.com/zerocracy/farm/issues/640) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/560851453). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4630](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10844](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 it's weird, but replacing `CcXor` with `CcAes` five tests fail, but `CcSecureTest` remains "passed"... I can't understand what's going on.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/640#issuecomment-368297836))

@yegor256 The user @yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#640](https://github.com/zerocracy/farm/issues/640), please stop working

**Comment by 0crat** [comment]
Job [#640](https://github.com/zerocracy/farm/issues/640) is already in scope

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10829](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/640#issuecomment-368334853))

@yegor256 The job [#640](https://github.com/zerocracy/farm/issues/640) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/561901926). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10824](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 @g4s8 see PR #647

**Comment by carlosmiranda** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/640#issuecomment-369157249))

@carlosmiranda The impediment for [#640](https://github.com/zerocracy/farm/issues/640) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 fixed in #647, may we close this now?

**Comment by g4s8** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#640](https://github.com/zerocracy/farm/issues/640) is now out of scope
