### ISSUE TITLE
Not clear how to deal with PRs with resigned performer

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#644]
It's not clear what should I do as a CR with PRs where performer was resigned from from ticket, e.g. this one: https://github.com/zerocracy/farm/pull/585 I requested some changes then accepted PR, but merge failed and performer was resigned from the [ticket](https://github.com/zerocracy/farm/issues/220) by 10 days rule. And now I'm going to receive negative points for this job, because it will be resigned from me soon. I think policy should be updated with this case.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 you just ask the ARC to close the PR and that's it. Why would you lose your points?

**Comment by g4s8** [comment]
@yegor256 thanks
