### ISSUE TITLE
pm/qa/reviews.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#646]
I think we have to introduce a new document `pm/qa/reviews.xml` in order to avoid duplicate reviews. Now it's possible to say `quality good` multiple times and the QA inspector will get a few payments. We should place the demand for review into the XML document and then place the mark there, when the review is completed. When the order gets removed from `orders.xml` we automatically destroy the review (should happen in Datum by auto update).

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/646#issuecomment-368338268))

@yegor256 The job [#646](https://github.com/zerocracy/farm/issues/646) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/561947007). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10834](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10834](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 PRs zerocracy/datum#302 and #649 were merged, puzzle #656 was created. Can we close?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#646](https://github.com/zerocracy/farm/issues/646) is now out of scope
