### ISSUE TITLE
List of debts became smaller although no payments were received

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#651]
In list of debts I had 9 items. But today after review instead of 10 items I see there only 6. No payments were received in my BTC wallet since Feb 21.

Also question: when all the debts should be paid? Is there any cumulative amount?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka yes, check this: http://www.zerocracy.com/policy.html#20 I removed two items from the list of debts, they were duplicates. We will send once there is $50. At the moment we are still having a problem with Coinbase. Should be resolved soon. Sorry for the confusion.

**Comment by ypshenychka** [comment]
@yegor256 Looks like one valid 4$ payment is missing in this list. Please see below screenshots from Telegram  - there are non-paid 4$ items for 3 different issues. And in list of debts - only 2 debts with 4$.
![screenshot_20180226-162549](https://user-images.githubusercontent.com/11703257/36678893-9c230bca-1b1a-11e8-9380-7ebca7f48e69.png)
![screenshot_20180226-162601](https://user-images.githubusercontent.com/11703257/36678894-9c455a54-1b1a-11e8-9af2-6a88f1ccf5c4.png)
![screenshot_20180226-162608](https://user-images.githubusercontent.com/11703257/36678895-9c671522-1b1a-11e8-990f-4a97a85ade94.png)
![default](https://user-images.githubusercontent.com/11703257/36678927-ad998e6a-1b1a-11e8-8e0f-9d25fc06f0b5.PNG)

**Comment by yegor256** [comment]
@ypshenychka fixed, thanks.
