### ISSUE TITLE
_after.groovy:27-29: register_impediment stakeholder...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#652]
The puzzle `447-38b7b52b` from #447 has to be resolved:

https://github.com/zerocracy/farm/blob/13e6ed7d6eb5e64ce3e289e222a81bdbccb5725d/src/test/resources/com/zerocracy/bundles/impediments/_after.groovy#L27-L29

The puzzle was created by Kirill on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#652](https://github.com/zerocracy/farm/issues/652) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `447-38b7b52b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#652](https://github.com/zerocracy/farm/issues/652) is now out of scope
