### ISSUE TITLE
complete_qa_review.groovy:29-32: We should place the...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#656]
The puzzle `646-eda38fad` from #646 has to be resolved:

https://github.com/zerocracy/farm/blob/1a9b3ee17b2bfa309fe1d6f38beb223d34a55bd3/src/main/resources/com/zerocracy/stk/pm/qa/complete_qa_review.groovy#L29-L32

The puzzle was created by g4s8 on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#656](https://github.com/zerocracy/farm/issues/656) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/656#issuecomment-370041868))

@yegor256 The job [#656](https://github.com/zerocracy/farm/issues/656) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/612024588). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@g4s8 hope you don't mind

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/656#issuecomment-370499602))

@yegor256 The job [#656](https://github.com/zerocracy/farm/issues/656) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641741017). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 that's fine

**Comment by 0pdd** [comment]
The puzzle `646-eda38fad` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/656#issuecomment-370871943). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/656#issuecomment-370871943). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
The job [#656](https://github.com/zerocracy/farm/issues/656) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/656#issuecomment-428504390))

@ypshenychka This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#656](https://github.com/zerocracy/farm/issues/656) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 7mon
  * @yegor256[/z](https://www.0crat.com/u/yegor256) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23656%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@yegor256 You self-assigned and I don't see any PR here. 
Please confirm you'll try to avoid these mistakes in future.

**Comment by ypshenychka** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
