### ISSUE TITLE
0crat failed Paypal payments?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#657]
Today, I should have received 4 Paypal transactions and received none. Instead, they are in the list of debts, which I understand will be paid when the total debt is > $50.

But still, the payments should not be in that list unless they failed due to [technical reasons](http://www.zerocracy.com/policy.html#20), so something must have gone wrong. 

I received no error message on Slack or somewhere else. I received the reputation points, though.

Maybe there is a bug and 0crat makes no payments < $50? This check should obviously be done only when paying the debts, not when doing any payment :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil are you sure you didn't receive notifications from Zerocrat? We don't make any PayPal/Bitcoin payments if they are smaller than $10, to avoid big commissions. We put the automatically to the debt and pay when it's over $50.

**Comment by amihaiemil** [comment]
@yegor256 yes. I am sure (I also checked Paypal now).

But none of them is >$10, so I guess it is correct. However, this info is nowhere in the policy, in clear? I did not find it anywhere.

**Comment by amihaiemil** [comment]
@yegor256 let me know if I missed something (maybe it's actually explained somewhere) or if I should change the title and description here.

**Comment by yegor256** [comment]
@amihaiemil check this: http://www.zerocracy.com/policy.html#20

**Comment by amihaiemil** [comment]
@yegor256 Yes, but there is still nothing about payments < $10? You said such payments won't be performed and will be added to the debt, since making such small transactions causes a lot of fees.

**Comment by llorllale** [comment]
@yegor256 I agree, policy should be explicit on this issue

**Comment by yegor256** [comment]
@amihaiemil @llorllale see https://github.com/zerocracy/zerocracy.github.io/commit/cdf1dd0a8df0bbc851f0993505c4758418fff0c9

**Comment by llorllale** [comment]
@yegor256 works for me

**Comment by amihaiemil** [comment]
@yegor256 looks better, I close this then :)
