### ISSUE TITLE
"You can't do that, unless you have one of these roles: ARC, PO" from 0crat after each QA review

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#658]
Each time after QA review I receive from 0crat next message:
>@ypshenychka You can't do that, unless you have one of these roles: ARC, PO. Your current roles are: QA.

For example, [here](https://github.com/yegor256/jpeek/issues/124#issuecomment-368597460).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#658](https://github.com/zerocracy/farm/issues/658) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/572026229). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+789](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10934](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ypshenychka thanks, it was a bug, fixed in b1ecedcb

**Comment by 0crat** [comment]
The job [#658](https://github.com/zerocracy/farm/issues/658) is now out of scope

**Comment by ypshenychka** [comment]
@yegor256 Should there be payment as well? I've got only points.

**Comment by yegor256** [comment]
@ypshenychka you are not a member of this project, that's why only points. Here: http://www.zerocracy.com/policy.html#48
