### ISSUE TITLE
Payment not done and not registered in debts

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#659]
I had two payments yesterday, [here](https://github.com/yegor256/jpeek/pull/206#issuecomment-368576911) and [here](https://github.com/yegor256/jpeek/pull/207#issuecomment-368595142). They were neither performed (checked e-mail and Paypal) nor registered as debts. 

I think it was because the project (jpeek) is sandbox and these 2 payments should have been done just after I reached reputation 1024. I understand from the policy that you cannot work on sandbox projects after that, but payments to open tickets should still be performed, right? Note that I still received the reputation points for them,

EDIT:

Happened [here](https://github.com/yegor256/jpeek/pull/210#issuecomment-368783141) and [here](https://github.com/yegor256/jpeek/pull/202#issuecomment-368794289) as well. 

All cases are sandbox projects, since I reached 1024 reputation.

Probably 0crat doesn't make any payments to performers which are not formally part of the project (I was taken out, jpeen and cactoos don't appear on my list anymore) -- members should not be taken out of the project as long as they have assigned tasks.

**Comment by yegor256** [comment]
@amihaiemil definitely a bug, let me fix it ASAP

**Comment by 0crat** [comment]
Job [#659](https://github.com/zerocracy/farm/issues/659) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+1160](https://www.0crat.com/u/amihaiemil)

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed, won't happen again

**Comment by 0crat** [comment]
The job [#659](https://github.com/zerocracy/farm/issues/659) is now out of scope
