### ISSUE TITLE
Lower payout amount

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#660]
There are 3 issues with it (on Chrome):

1. They are inlined, simply appended one after another. I have 5 and they are already hard to understand, (10 lines of text already). They should be displayed in a table, I think. And maybe on a new page since it's going to be a long table.

2. They use Markdown to format links and it is not rendered correctly. -> SOLVED

3. The amounts are less than 25% or 50% of my hourly rate, I suppose the Paypal commision is taken from my rate? But this is not clear and not explained anywhere. -> Clarified; the mentor's fee is taken out the payment.

**Later Edit**

After discussion, we came to the conclusion that it's better to leave it as it is and simply lower the payout amount from $50 to $20.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil can you share the screenshot? Also, the amounts are smaller because you are paying tuition fee: http://www.zerocracy.com/policy.html#45

**Comment by amihaiemil** [comment]
@yegor256 Here it is: 

![image](https://user-images.githubusercontent.com/6305156/36722911-830777b4-1bb7-11e8-8fdc-4c68f6ffdaa7.png)

**Comment by yegor256** [comment]
@amihaiemil can you check the layout now? Should look better. I don't want to use a table, since the list of debts is supposed to be short. We create them temporarily and flush frequently. A table will mean that we are very serious about them and they will stay there for a long time:)

**Comment by amihaiemil** [comment]
@yegor256 It still looks terrible, if you ask me: 

<img width="940" alt="screen shot 2018-02-27 at 18 46 41" src="https://user-images.githubusercontent.com/6305156/36741767-9f30dd9a-1bee-11e8-9633-5794667c8dc1.png">

Are you sure you don't want to make it a table? I think it will be rather long and stay there for some time (for instance, I estimate 1-2 weeks, until I make $50, considering how a task moves).

**Comment by amihaiemil** [comment]
@yegor256 plus, think about responsiveness -- maybe it should even be a different page. Such a table or wall of text should not be displayed on mobile all the time, it's hard to read there either way.

**Comment by 0crat** [comment]
Job [#660](https://github.com/zerocracy/farm/issues/660) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@amihaiemil maybe it's better to lower the payout amount. If we set it to, say, $20 instead of $50, there will be no more than 10 payments in the list...

**Comment by amihaiemil** [comment]
@yegor256 yes, that could also work

**Comment by 0crat** [comment]
The job [#660](https://github.com/zerocracy/farm/issues/660) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/581656002). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@amihaiemil see https://github.com/zerocracy/zerocracy.github.io/commit/30d2d28b47b0dd5a1eee04dbf8555d97650a982a Expect a payment any time soon

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10974](https://www.0crat.com/u/yegor256)

**Comment by amihaiemil** [comment]
@yegor256 I haven't received any payment yet (and 0crat silently put the payment for this bug in the debt list, it did not comment anything here). Should it have been sent already or?

**Comment by yegor256** [comment]
@amihaiemil should happen soon. We had payouts configured as "once per day". Now it's "once per hour", so let's wait a bit and see what happens.

**Comment by amihaiemil** [comment]
@yegor256 The payments disappeared from "debt", but I received no Paypal payment :(

**Comment by yegor256** [comment]
@amihaiemil see #678

**Comment by amihaiemil** [comment]
@yegor256 I see. Could you also put back the 21.46 for me? (see screenshot above)

**Comment by yegor256** [comment]
@amihaiemil I did

**Comment by amihaiemil** [comment]
@yegor256 thanks, it worked now, payment was done

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#660](https://github.com/zerocracy/farm/issues/660) is now out of scope
