### ISSUE TITLE
Duplicate payment for https://github.com/yegor256/jpeek/pull/211

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#661]
Debts list contains duplicate payment for https://github.com/yegor256/jpeek/pull/211. 
Please remove one.

![image](https://user-images.githubusercontent.com/11703257/36723475-ffca0b44-1bb8-11e8-9dde-7ae7b0f0c684.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
@yegor256 Now both records are gone. No payment for yegor256/jpeek#211 at all.
![image](https://user-images.githubusercontent.com/11703257/36944177-8aaf3844-1f9f-11e8-8510-c23d91da78db.png)

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka  ([here](https://github.com/zerocracy/farm/issues/661#issuecomment-370403469))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/pay_extra.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "8min"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/zerocracy/farm/issues/661#issuecomment-370405225))

@yegor256 The user @@ypshenychka is working for free in this project, see [§49](http://www.zerocracy.com/policy.html#49)

**Comment by yegor256** [comment]
@ypshenychka one payment fixed: https://github.com/yegor256/jpeek/pull/211#issuecomment-370413133

**Comment by yegor256** [comment]
@ypshenychka we won't have any more duplicates

**Comment by ypshenychka** [comment]
@yegor256 thanks!
