### ISSUE TITLE
Iterative reputation point calculation 

### ISSUE THREAD

**Issue by driver733** [zerocracy/farm#664]
As per 
https://github.com/zerocracy/farm/issues/662#issuecomment-368924764
https://github.com/zerocracy/farm/issues/662#issuecomment-368929249

I believe that we should remove batch reputation point calculation. Each post made by the 0crat should have its own calculation of the points, not the final one. Otherwise, it might be confusing, especially for newcomers.
See screenshot for the details.
In the first post 0crat should have had `+15, total is 6,565`
In the second one `-5, total is 6,560`
![screen shot 2018-02-27 at 11 58 14 am](https://user-images.githubusercontent.com/10466206/36742480-c31d087a-1bb5-11e8-8e53-daab24f83e94.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#664](https://github.com/zerocracy/farm/issues/664) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591736433). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+550](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+11004](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@driver733 we just won't show the total anymore, see 31024aa5

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+11029](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#664](https://github.com/zerocracy/farm/issues/664) is now out of scope
