### ISSUE TITLE
Codebase filled with hardcoded "types"

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#665]
I noticed that the codebase, especially the groovy part, is filled with hardcoded String constants, called "types", such as "Make Payment", "Assign role" etc.

These constants should clearly be pulled out in an Enum or Class of constants, where they would be referenced from. Also, there should be javadocs there that would explain which is used where. Plus, we would have a good overview of what is used and when we should add a new one etc.

Currently, if I would have to implement something new from scratch, I would have no idea what types to use and where, or if I should add a new type.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 @carlosmiranda what do you think about this?

**Comment by amihaiemil** [comment]
@yegor256 No offense but I think the complaint is quite well founded :) and it's a matter of design as well; duplication everywhere, what if one day you want to change those constants. And having them as literally strings is quite primitive -- how do you implement a report now? Work with strings everywhere? What is someone forgets a space somewhere? Whole hell breaks loose because there is a space in some groovy file.

**Comment by g4s8** [comment]
@yegor256 @amihaemil I agree with documentation for claim types, it was easy to understand what claim can do on early stages with few types, but now it becomes harder. But I don't believe that putting them into enum or class will change something. I would create some page on GitHub (claims.md) with all types and documentation.

**Comment by amihaiemil** [comment]
@g4s8 Why not Enum or Class? Maybe Class, I also hate Enums, could never see their real purporse. 

If you have a class in code, then they are all centralized there, you can change them easily if needed. And the documentation can be right there, in the javadocs. If you simply document the existing ones, it is still not clear: 

1. where do these types come from?
2. how many are they?
3. when do I need to add a new one? 

Not to mention duplication again. I have to remember in all the places how to write them. Are they case sensitive or note? Will something break down the road if I use a different casing? etc etc

**Comment by yegor256** [comment]
@amihaiemil @g4s8 maybe instead of documentation we can create a "flow control" unit, which will check what's going on with claims: which types produce other types. It will know what is allowed and what is not. And this information will be well structured in some XML file. We will have some sort of a "map" for all types of claims. Thus, we will solve two problems: testability and readability.

**Comment by amihaiemil** [comment]
@yegor256 I cannot say, since I have no idea how those claims/types work yet.

**Comment by carlosmiranda** [comment]
@yegor256 that is a good idea which would also serve as documentation somehow. We need to prevent problems such as #235 from happening, and the bigger the claims codebase gets the more confusing all of this becomes.

**Comment by 0crat** [comment]
The job [#665](https://github.com/zerocracy/farm/issues/665) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/600563312). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by proshin-roman** [comment]
@yegor256 @g4s8 @amihaiemil I vote for implementing this ticket - understanding "claims" graph and adding new stakeholders is very hard for now.

**Comment by g4s8** [comment]
@yegor256 do you want to complete this job, or maybe reassign it to someone else?

**Comment by 0crat** [comment]
Job [#665](https://github.com/zerocracy/farm/issues/665) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#665](https://github.com/zerocracy/farm/issues/665) is now out of scope
