### ISSUE TITLE
Build logs filled with stacktraces. Are all the tests working fine?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#670]
The build is succesful, however there are *a lot* of exceptions on the test logs, most of them starting with: ``com.jcabi.log.VerboseCallable: swallowed runtime exception:...``

Are we sure that all the tests are working fine and they are not silently throwing exceptions in separate threads? Check the Travis build, that log is also filled with stacktraces.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I don't see anything... where did you see them? Can you give a link please?

**Comment by amihaiemil** [comment]
@yegor256 For instance [here](https://travis-ci.org/zerocracy/farm/builds/347700471#L692) -- in that log there are only 2 exceptions, but when I build locally (both on Ubuntu 16.04 and MacOS High Sierra), the log has many more exceptions.

**Comment by amihaiemil** [comment]
@yegor256 strange, now the logs are the same locally as in Travis -- did you change something in pom.xml, changed build profiles or anything? The build is also much shorter now and not so demanding as before (and I don't mean the very first build, which is longer than usual since it has to download all the dependencies from maven)

**Comment by yegor256** [comment]
@amihaiemil maybe it was something temporary. The build is pretty clean and stable now.
