### ISSUE TITLE
Split up BundlesTest

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#673]
Currently all the ``.groovy`` bundles test are run by ``BundlesTest`` class, all at once. There is no way of running them separately and at the same timne, ``BundlesTest`` takes between 4 and 6 minutes to execute fully -- tried on 2 laptops, one with i3 and one with i5 processor.

4-6min for a test run is too long considering a task is supposed to be done in 30min. One third of that time goes away if I run the tests only 2 times (and the .groovy stakeholders seems to be a big point of work, many tasks seem to be done in that are). We should be able to run each bundle test separately, what do you think?

Furthermore, BundlesTest class is hard to understand; in general, I hate JUnit's parameterized tests, it involves a lot of messy boilerplate.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil you can run any one of them individually. Here is how: https://www.youtube.com/watch?v=fVfR3pO-5V4

**Comment by yegor256** [comment]
@amihaiemil see 8cee6f36 Also, the video: https://www.youtube.com/watch?v=oWEN-vKEEYk

**Comment by amihaiemil** [comment]
@yegor256 I see, thanks :)
