### ISSUE TITLE
Where is /target/testing-bundles being setup?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#674]
I am trying to understand [BundlesTest](https://github.com/zerocracy/farm/blob/a518b3736a900edd04aaffd573ee0b9e72bfdf85/src/test/java/com/zerocracy/BundlesTest.java) so I can figure out why it fails in #672 (strangely, it only fails locally, the Travis build passes).

The first question is: where is ``/target/testing-bundles`` being written? I couldn't find it anywhere, it seems that all the groovy bundles are tested agains their test projects found in ``/target/testing-bundles``.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#674](https://github.com/zerocracy/farm/issues/674) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/611711678). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil I believe it's solved already in #673?

**Comment by amihaiemil** [comment]
@yegor256 yes, better, thanks :)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#674](https://github.com/zerocracy/farm/issues/674) is now out of scope
