### ISSUE TITLE
Technical documentation needed

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#675]
The project has very little documentation inside README.md and it also lacks Javadocs. Classes such as ``Pmo.java`` with javadocs that say simply "PMO.". 

An architectural overview is really needed in order for new developers to understand the codebase. I would expect an explanation about:

1. Main types: what is a PMO? What is a stakeholder exactly? etc

2. Entry point and overall design. For instance, where do I start if I want to debug end-to-end the "penalize on refuse task" behaviour?

3. Why groovy exactly and why so much XML? 

4. Tests architecture -- the project clearly relies on many integration tests; how are they setup/run, how they could be split up and so on. 

and in general any information you think a new developer would be useful is appreciated.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 You said earlier that we should open issues if documentation is needed. Here it is. Please, take the time to write one, it cannot be that complicated.

**Comment by yegor256** [comment]
@amihaiemil you put too many questions into one ticket. Can you please submit them separately?

**Comment by amihaiemil** [comment]
@yegor256 that's what I thought of initially, then I figured a single ticket for such a file would be cleaner. I'll open more tickets then :)
