### ISSUE TITLE
Got paid 3 times for https://github.com/yegor256/cactoos/pull/698

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#677]
Occured [here](https://github.com/yegor256/cactoos/pull/698)

![image](https://user-images.githubusercontent.com/11703257/36809330-4a43b72a-1cd0-11e8-9ff6-dc394ec3321a.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ypshenychka** [comment]
@yegor256 Only one record left. Closing issue.
