### ISSUE TITLE
0crat cleared out the debt list but no payments were received to the wallet

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#678]
I had there 63.47$ of debt. Today it got cleared, but nothing received in my wallet.
![default](https://user-images.githubusercontent.com/11703257/36810247-cb4eb624-1cd2-11e8-99d4-ad31733c3a37.PNG)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#678](https://github.com/zerocracy/farm/issues/678) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/592005133). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
This is how much we lost:

<img width="704" alt="screen shot 2018-02-28 at 11 14 42 pm" src="https://user-images.githubusercontent.com/526301/36810919-31ef811a-1cdd-11e8-9bef-8ba7bef4201e.png">

**Comment by yegor256** [comment]
@ypshenychka I added 63.47 to your debt again. Let's wait for an hour (the server pays debts every hour).

**Comment by ypshenychka** [comment]
@yegor256 Still failed to buy at Coinbase. It's already a week since the problem occured. When do you expect it to work?

**Comment by yegor256** [comment]
@ypshenychka we are trying to switch to cex.io now, since Coinbase is a pain. In the meantime I would suggest to switch to PayPal. Or wait... :( I'm very sorry.

**Comment by g4s8** [comment]
@ypshenychka @yegor256 it was temporary failure or this bug needs to be investigated?

**Comment by ypshenychka** [comment]
@g4s8 Issue didn't appear anymore.

**Comment by ypshenychka** [comment]
@g4s8 Yes, you're right. Closing it.

**Comment by 0crat** [comment]
Job [#678](https://github.com/zerocracy/farm/issues/678) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#678](https://github.com/zerocracy/farm/issues/678) is now out of scope
