### ISSUE TITLE
Pings are not accurate

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#680]
Class `Pings` is not sending pings correctly. It counts hours and days starting from the moment of `ExecutionService` start. This leads to inaccuracies. If we reboot the system, `Ping daily` only happens in a day, which sometimes means "never", if we reboot multiple times a day.

Instead, it should do `Ping hourly` when it's a sharp hour by the clock. Also, it should do `Ping daily` when it's 12:00am (or nearby) on the clock.

**Comment by 0crat** [comment]
Job [#680](https://github.com/zerocracy/farm/issues/680) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/680#issuecomment-372092082))

@yegor256 The job [#680](https://github.com/zerocracy/farm/issues/680) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/700623111). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 what do you think about moving to some [job scheduler](https://java-source.net/open-source/job-schedulers)? I would suggest [quartz](http://www.quartz-scheduler.org/) because it supports clustering out of box and can move us closer to multi-node server as in #773 ticket.

**Comment by yegor256** [comment]
@g4s8 quartz sounds right, let's use it

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 19days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/680#issuecomment-377547487))

@g4s8 The impediment for [#680](https://github.com/zerocracy/farm/issues/680) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#909](https://github.com/zerocracy/farm/issues/909) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#909](https://github.com/zerocracy/farm/issues/909) is solved here.

**Comment by g4s8** [comment]
@yegor256 PR #884 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#680](https://github.com/zerocracy/farm/issues/680) is now out of scope

**Comment by g4s8** [comment]
@ypshenychka fixed
