### ISSUE TITLE
0crat didn't reply to "waiting" message

### ISSUE THREAD

**Issue by nikialeksey** [zerocracy/farm#682]
I told "waiting" to 0crat, https://github.com/yegor256/cactoos/issues/644#issuecomment-368729877 but it don't reply to me. Then 0crat resigned me.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey I think it's a duplicate of #476
