### ISSUE TITLE
Broken detection for "job creator" when assigning manually

### ISSUE THREAD

**Issue by biboran** [zerocracy/farm#684]
I assigned @driver733 as a `DEV` to the issue that I created. I got incorrectly punished for assigning _job to its creator_ because @driver733 is not the creator of the issue. Here are the screenshots:
![screen shot 2018-03-01 at 12 48 19 pm](https://user-images.githubusercontent.com/8717108/36838360-0cc2c7f8-1d50-11e8-8f4b-471644dddb47.png)
![screen shot 2018-03-01 at 12 48 28 pm](https://user-images.githubusercontent.com/8717108/36838364-0dfa1504-1d50-11e8-8931-8d0272a0abde.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@biboran I believe it's the same bug we fixed in #662 When did this happen?

**Comment by biboran** [comment]
@yegor256 14 hours ago

**Comment by biboran** [comment]
@yegor256 a more concrete timestamp would be `1519852200`
<img width="795" alt="screen shot 2018-03-01 at 1 59 17 pm" src="https://user-images.githubusercontent.com/8717108/36841243-c64480ec-1d58-11e8-986e-577013818d98.png">

**Comment by yegor256** [comment]
@biboran yes, this bug was fixed already in #662

**Comment by biboran** [comment]
@yegor256 I don't think its fixed. I just created a pull request. Take a look at the below screenshots. As you can see I created this PR and never assigned myself but still got punished as if I did assign myself.
![screen shot 2018-03-01 at 3 25 47 pm](https://user-images.githubusercontent.com/8717108/36844748-fd525f8a-1d64-11e8-9468-ce58086203e5.png)
![screen shot 2018-03-01 at 3 25 54 pm](https://user-images.githubusercontent.com/8717108/36844749-fe2474f2-1d64-11e8-8afe-7fd7717e1ec8.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@biboran you are right, the bug is still there

**Comment by 0crat** [comment]
The job [#684](https://github.com/zerocracy/farm/issues/684) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/601437737). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@biboran I believe it's fixed now, in f0de45a

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#684](https://github.com/zerocracy/farm/issues/684) is now out of scope
