### ISSUE TITLE
There are no unit tests for the Slack radar

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#687]
Currently SlackRadar starts the SlackSession internally (using private methods). This needs to be refactored, SlackRadar needs a ctor where SlackSession should be passed, so we can properly unit test this radar. Currently, there are absolutely no unit tests for any of the classes in ``com.zerocracy.radars.slack``, 

Later, the slack Reaction implementations should also be refactored somehow, so they can be unit tested as well. Currently they are too blackbox -- instantiating the Claim and sending it inside ``react``, returning ``true`` or ``false``

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#687](https://github.com/zerocracy/farm/issues/687) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#687](https://github.com/zerocracy/farm/issues/687) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/851524625); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/687#issuecomment-378908476))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#687](https://github.com/zerocracy/farm/issues/687), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#687](https://github.com/zerocracy/farm/issues/687) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1371761143); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for @yegor256 approval in #1031

**Comment by 0crat** [comment]
> @0crat waiting for @yegor256 approval in #1031  ([here](https://github.com/zerocracy/farm/issues/687#issuecomment-391229102))

@krzyk The impediment for [#687](https://github.com/zerocracy/farm/issues/687) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#1060](https://github.com/zerocracy/farm/issues/1060) is still not solved.

**Comment by krzyk** [comment]
@amihaiemil changes have been merged in #1031, please close this issue

**Comment by amihaiemil** [comment]
@krzyk cool, thanks :)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#1060](https://github.com/zerocracy/farm/issues/1060) is solved here.
