### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#689]
From www.0crat.com I'm clicking on `Login` which takes me to a url that looks like `https://www.0crat.com/&PsByFlag=PsGithub&code=fc4a47c75fd4eda92c3e` that doesn't work:

> [GET https://www.0crat.com/&PsByFlag=PsGithub&code=fc4a47c75fd4eda92c3e] failed in 4ms: 404

Because of this, I can't view my agenda

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale dup of #686
