### ISSUE TITLE
Refuse doesn't work as expected

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#694]
See this issue: [118](https://github.com/yegor256/jpeek/issues/118#issuecomment-369858999)

I've refused from the issue. Expected behavior is: get notification about refusal, get -15 points deducted.
Current behavior: 0crat [saying this](https://github.com/yegor256/jpeek/issues/118#issuecomment-369859487) and points were not deducted.

Possibly can be reproduced, if user quits the project and then refuses the task. As that's what I've done before refusal.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#694](https://github.com/zerocracy/farm/issues/694) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641333687). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@t-izbassar you are right, it was a bug, fixed

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#694](https://github.com/zerocracy/farm/issues/694) is now out of scope
