### ISSUE TITLE
0crat assings issue silently

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#695]
Look [here](https://github.com/zerocracy/farm/issues/363#issuecomment-369861988). Status said that the job is assigned to me, however there was no mentioning about that in the ticket. Expected to see the message about assignment.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar dup of #564
