### ISSUE TITLE
0crat site is not available (503 Service Unavailable)

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#697]
When I try to open https://www.0crat.com/ I get "Application error" and `503 Service Unavailable` in Network tab of Developer console. I'm observing this problem about two or three hours since 12:00 UTC+3 of 02.03.2018.

**Comment by yegor256** [comment]
@proshin-roman it's all good now, thanks

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
