### ISSUE TITLE
Got payment for working on sandbox project

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#698]
When I applied to Cactoos (which is a sandbox project), I got the following message from 0crat:
```
You just got role DEV in the Cactoos (https://www.0crat.com/p/C63314D6Z) project; you work for free
```
but then, when I did a few tickets for this project, I got payment for that (on my PayPal wallet).

**What I expect:**
- 0crat shouldn't send "you work for free" **OR** the work should be really "for free"

**Comment by yegor256** [comment]
@proshin-roman your rate in Cactoos is $16. It was set 19 days ago. Most probably you missed a message in Telegram.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
