### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#699]
http://www.0crat.com/ does not work currently, I get the following error (14:58 EET).:

![image](https://user-images.githubusercontent.com/6305156/36899973-1fe84bc0-1e2a-11e8-8e06-ea9ebf4bfc9c.png)

**Comment by amihaiemil** [comment]
@yegor256 see here, 0crat seems to be down

**Comment by yegor256** [comment]
@amihaiemil dup of #697

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
