### ISSUE TITLE
remove old claims from MongoDB

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#701]
Let's remove meaningless claims that are too old from MongoDB. Let's do that by types. We can definitely remove `Notify.*` (regex). Later, we will add more regular expressions to it. Let's do that in a new Groovy stakeholder. It will just ask `Footprint` to clean up the database. The real work should happen inside the `Footprint`.

**Comment by 0crat** [comment]
Job [#701](https://github.com/zerocracy/farm/issues/701) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#701](https://github.com/zerocracy/farm/issues/701) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/910957509); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #904 PR to merge

**Comment by 0crat** [comment]
> @0crat waiting #904 PR to merge ([here](https://github.com/zerocracy/farm/issues/701#issuecomment-380693519))

@g4s8 The impediment for [#701](https://github.com/zerocracy/farm/issues/701) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 PR #904 was merged, can we close?

**Comment by yegor256** [comment]
@0crat thanks!

**Comment by 0crat** [comment]
> @0crat thanks! ([here](https://github.com/zerocracy/farm/issues/701#issuecomment-390396714))

@yegor256 Can't understand "thanks!", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#701](https://github.com/zerocracy/farm/issues/701) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
