### ISSUE TITLE
0crat does not remove closed impediment

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#702]
I registered an impediment for a few of my tasks, an issue which was closed after all. However, it is still registered as an impediment. For instance, [here](https://github.com/zerocracy/farm/issues/226#issuecomment-369351095); ticket 675 was closed, yet the job still has impediments.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil but we don't care what you are "waiting" for. We just add an impediment. It doesn't have a parameter. It's just a status for a job -- either has an impediment or not.

**Comment by amihaiemil** [comment]
@yegor256 but shouldn't 0crat unregister the impediment and start the 10days count again once the impediment has been closed?

**Comment by yegor256** [comment]
@amihaiemil we don't know what is the "impediment". It could be a ticket or just a bad mood of a developer :)
