### ISSUE TITLE
Dept is not well formatted

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#708]
User dept looks like a plain text from error message, I think it will look better if convert dept section to a table.
![scrot-2018-03-02-23 59 33](https://user-images.githubusercontent.com/1524988/36921575-dbd72bc6-1e75-11e8-85db-4679918d783c.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 dup of #660
