### ISSUE TITLE
_after.groovy:27-29: register_impediment stakeholder...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#709]
The puzzle `447-7f13e82b` from #447 has to be resolved:

https://github.com/zerocracy/farm/blob/99f16ec57c5bd35c6de8d1dac0517aa48539b601/src/test/resources/com/zerocracy/bundles/impediments/_after.groovy#L27-L29

The puzzle was created by Yegor Bugayenko on 03-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#709](https://github.com/zerocracy/farm/issues/709) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `447-7f13e82b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#709](https://github.com/zerocracy/farm/issues/709) is now out of scope
