### ISSUE TITLE
_after.groovy:28-33: The ticket should be removed from...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#710]
The puzzle `539-28713f59` from #539 has to be resolved:

https://github.com/zerocracy/farm/blob/99f16ec57c5bd35c6de8d1dac0517aa48539b601/src/test/resources/com/zerocracy/bundles/close_the_job/_after.groovy#L28-L33

The puzzle was created by Yegor Bugayenko on 02-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#710](https://github.com/zerocracy/farm/issues/710) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#710](https://github.com/zerocracy/farm/issues/710) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/651903493). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `539-28713f59` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath 'author/text()' not found in '<claim xmlns:xsi="http://www.w3.org/2001/XMLSchema..328..8-03-06T21:08:36.707Z</until>\uA   </claim>': Index (0) is out of bounds (size=0)
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
The job [#710](https://github.com/zerocracy/farm/issues/710) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
