### ISSUE TITLE
Please, charge attention to this issue typo

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#712]
English is my second language, but this doesn't look right: https://github.com/zerocracy/farm/blob/cbabaa68f1e7f5e9228b7cb6ba1ffa06661ab469/src/main/java/com/zerocracy/radars/github/RbPingArchitect.java#L63

Probably introduced by mass replacement in https://github.com/zerocracy/farm/commit/99f16ec57c5bd35c6de8d1dac0517aa48539b601#diff-0bd7928999472936985e53b1e576c28d

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, charge attention to this issue

**Comment by yegor256** [comment]
@rexim fixed, thanks :)
