### ISSUE TITLE
Awards ctor should accept Pmo, not Project

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#715]
As explained [here](https://github.com/zerocracy/farm/pull/672#issuecomment-370140494), the awards are global, not per project. They can be read either from PMO or directly from Farm.

However, one ctor of Awards accepts Project (Pmo implements Project) -- this is not correct and leads to misuse of that class (as I just did in the PR referenced above). Awards should accept only Pmo, not just any type of Project; the class' parameter name, ``this.pmo``, also suggests that.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, charge attention to this issue

**Comment by 0crat** [comment]
Job [#715](https://github.com/zerocracy/farm/issues/715) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor69[-1] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: Duplicate unique value [QA review completed at gh:yegor256/cactoos#698] declared for identity constraint of element "items".;-1:-1: Duplicate unique value [QA review completed at gh:yegor256/cactoos#698] declared for identity constraint of element "items".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by yegor256** [comment]
@amihaiemil make sense. The same should be done for all other classes in `com.zerocracy.pmo` package.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#715](https://github.com/zerocracy/farm/issues/715) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/951150053); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #897 PR to merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-0
com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1041817213">
   <created>2018-04-14T18:13:11.214Z</created>
   <type>Register impediment</type>
   <token>github;zerocracy/farm;715;381348857</token>
   <author>g4s8</author>
   <params>
      <param name="job">gh:zerocracy/farm#715</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">715</param>
      <param name="comment">381348857</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat waiting #897 PR to merge ([here](https://github.com/zerocracy/farm/issues/715#issuecomment-381348857))

@g4s8 The impediment for [#715](https://github.com/zerocracy/farm/issues/715) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat waiting #897 PR to merge ([here](https://github.com/zerocracy/farm/issues/715#issuecomment-381348857))

@g4s8 Job [#715](https://github.com/zerocracy/farm/issues/715) is already on hold

**Comment by g4s8** [comment]
@amihaiemil few constructors was refactored in #897 and `@todo` for other was added, can we close?

**Comment by amihaiemil** [comment]
@g4s8 yes, looks ok. Just that the PR is very big (21 changed files)... if I were the reviewer I would have rejected it :D

**Comment by g4s8** [comment]
@amihaiemil why? It's a refactoring, so one constructor change requires to change many other classes, like `Votes` and groovy scripts.

**Comment by amihaiemil** [comment]
@g4s8 yes, but then I would have changed only ``Awards``, not 3 classes, to reach 21 changed files. Even if the change seems innocent, maybe there's a bug in some of those classes (or clients of those classes) which now would be very hard to track since we have that huge PR merged :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#715](https://github.com/zerocracy/farm/issues/715) is now out of scope

**Comment by amihaiemil** [comment]
@g4s8 I think such situation should be rare and so it's better for the project to pay you more than risk introducing shady bugs. Besides, you shouldn't spend all your 30min on preparing the first version of the PR, since you will spend some more time discussing and making CR changes.

**Comment by g4s8** [comment]
@amihaiemil thanks, I think it make sense.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#1006](https://github.com/zerocracy/farm/issues/1006) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#1006](https://github.com/zerocracy/farm/issues/1006) is solved here.
