### ISSUE TITLE
Revise Travis Build, more specificaly BundlesTest

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#716]
In PR #672, one bundle test was modified and it was failing locally (consistently). However, Travis CI passed always. We should check to see if ``BundlesTest`` doesn't somehow overlap the test cases in Travis (thus creating the proper setup for that failing test, ``set_boost_factor``, to pass artificially). 

The test was failing locally with [this](https://github.com/zerocracy/farm/pull/672#issuecomment-369342046) exception (the issue was that the Awards were being read from a non-PMO project). You can see there that all the 3 commits before the comment succesfully passed Travis CI when they should have failed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, charge attention to this issue

**Comment by 0crat** [comment]
Job [#716](https://github.com/zerocracy/farm/issues/716) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor69[-1] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: Duplicate unique value [QA review completed at gh:yegor256/cactoos#698] declared for identity constraint of element "items".;-1:-1: Duplicate unique value [QA review completed at gh:yegor256/cactoos#698] declared for identity constraint of element "items".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@amihaiemil it was fixed in #907 PR , can we close?

**Comment by amihaiemil** [comment]
@g4s8 thanks :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#716](https://github.com/zerocracy/farm/issues/716) is now out of scope
