### ISSUE TITLE
Pmo should not be a Project

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#718]
Pmo is actually the central ledger of the farm, where the [information](https://github.com/zerocracy/farm/issues/new) about all the other projects is stored.

It is not actually a project, it has no jobs, no boosts etc. However, in the code, it implements ``Project``. This is not ok since we always have to take care to treat this particular ``Project`` in a specific way, it is a bad abstraction. It's like saying ``Catalogue implements Student`` -- Catalogue holds all the info about objects of type Student and is itself a Student. 

I think it should actually be ``XmlPmo implements Pmo``, its own type.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil but they share a lot of functionality, including items, synchronization, claims, etc.

**Comment by yegor256** [comment]
@amihaiemil no, they are not connected almost anyhow. A PMO is a normal regular project, but it has a different set of artifacts, that's it. They are absolutely identical at the level of Java. They are different by the types of data they store (XML). So, making them as separate types is a wrong idea, I believe.

**Comment by amihaiemil** [comment]
@yegor256 If the 2 are identical in Java, yet they are separate concepts, then it means lower abstractions are too generic. I noticed ``Item`` is the lowest abstraction in the project -- doesn't that seem a little too generic? An Item can be anything, so naturally you have the risk of duplicating code or interfaces in the upper layers.

Do you know what I mean? The abstraction layer should shaped as a funel, always. In our case, becasue of that Item (which is again a broad term), the abstraction is an hourglass -- I hope you visualize it the same as I do, haha. 

So we should probably differenciate between the type of Item and then the issue will be fixed eventually, since they won't have the same interface anymore. Just an idea; what do you think?
