### ISSUE TITLE
Travis fails: "1 threads are still alive, it's a bug, see above"

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#721]
One Travis build failed on [one PR](https://github.com/zerocracy/farm/pull/720): 

https://travis-ci.org/zerocracy/farm/builds/348972422?utm_source=github_status&utm_medium=notification

I assume it's really a bug in the tests' infrastructure. No matter what happens, threads shouldn't be leaking, right?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil definitely a bug, but I can't imagine how it's possible to reproduce it...

**Comment by 0crat** [comment]
Job [#721](https://github.com/zerocracy/farm/issues/721) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@yegor256 I think we shouldn't be playing with threads so much (using that ``VerboseRunnable`` or ``VerboseThreads`` when running a stakeholder. There are also issues with the tests, they are silently swallowing exceptions as explained [here](https://github.com/zerocracy/farm/pull/719#issuecomment-370331149). 

Is it even necessary to run the stakeholders on separate threads?

**Comment by yegor256** [comment]
@amihaiemil yes, we need to use `AsyncFlush`, which runs them all in background threads. If you need to know the reason... you know what to do :)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/990945288); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-382313054))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-390502825))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1432370884); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-394615134))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1580842610); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@amihaiemil see PR #1108

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #1108

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #1108 ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-395444375))

@carlosmiranda The impediment for [#721](https://github.com/zerocracy/farm/issues/721) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@0crat refuse (couldn't fix this somehow)

**Comment by 0crat** [comment]
> @0crat refuse (couldn't fix this somehow) ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-400935918))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1810512654); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-403554322))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1910840506); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-404514049))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#721](https://github.com/zerocracy/farm/issues/721) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1990713266); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-405842154))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#721](https://github.com/zerocracy/farm/issues/721) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [43min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): User was resigned from the ticket
    * @krzyk[/z](https://www.0crat.com/u/krzyk): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23721%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@carlosmiranda hot potato :)

**Comment by carlosmiranda** [comment]
@0crat refuse (darn it, I [refused already](https://github.com/zerocracy/farm/issues/721#issuecomment-400935918) :))

**Comment by 0crat** [comment]
> @0crat refuse (darn it, I [refused already](https://github.com/zerocracy/farm/issues/721#issuecom... ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-405843423))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#721](https://github.com/zerocracy/farm/issues/721), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by rgevaerd** [comment]
@0crat waiting for PR #1512

**Comment by 0crat** [comment]
> @0crat waiting for PR #1512  ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-409407246))

@rgevaerd The impediment for [#721](https://github.com/zerocracy/farm/issues/721) was registered successfully by @rgevaerd[/z](https://www.0crat.com/u/rgevaerd)

**Comment by rgevaerd** [comment]
@amihaiemil fix was merged in #1512, can we close?

**Comment by amihaiemil** [comment]
@rgevaerd sure, thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7bda313d-71fb-41d0-8d6f-eda5801ea74b, thread: pool-675-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-04T06:54:20.027Z"
```

[0.28.15](https://github.com/zerocracy/farm): Issue: zerocracy/farm#721, Action: `closed`

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @rgevaerd[/z](https://www.0crat.com/u/rgevaerd), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/721#issuecomment-410455352))

@g4s8 The job [#721](https://github.com/zerocracy/farm/issues/721) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @rgevaerd[/z](https://www.0crat.com/u/rgevaerd)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
