### ISSUE TITLE
TkDump.java:38-40: Download and analyze heap dump from...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#725]
The puzzle `425-40a20d3d` from #425 has to be resolved:

https://github.com/zerocracy/farm/blob/abf8537e9c3af42589c6d4b56d715b8053c6bb78/src/main/java/com/zerocracy/tk/TkDump.java#L38-L40

The puzzle was created by amihaiemil on 03-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#725](https://github.com/zerocracy/farm/issues/725) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-384889314))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#725](https://github.com/zerocracy/farm/issues/725), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting for clarifications on payments bug

**Comment by 0crat** [comment]
> @0crat waiting for clarifications on payments bug ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-387299635))

@amihaiemil The impediment for [#725](https://github.com/zerocracy/farm/issues/725) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-398682796))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#725](https://github.com/zerocracy/farm/issues/725), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-399076879))

@g4s8 The job [#725](https://github.com/zerocracy/farm/issues/725) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1721151059); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Got heap dump: [heapdump.zip](https://github.com/zerocracy/farm/files/2123479/heapdump.zip)

**Comment by 0pdd** [comment]
The puzzle `425-40a20d3d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1202](https://github.com/zerocracy/farm/issues/1202), [#1203](https://github.com/zerocracy/farm/issues/1203) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1202](https://github.com/zerocracy/farm/issues/1202) is still not solved; solved: [#1203](https://github.com/zerocracy/farm/issues/1203).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: AsyncFlush-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/g4s8.xml" in "PMO" in 2min: 6cc77ffce735/38min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): CID: [1721229203](https://www.0crat.com/C3NDPUA8L/1721229203), Type: "Close job", Author: "0pdd"

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1202](https://github.com/zerocracy/farm/issues/1202), [#1203](https://github.com/zerocracy/farm/issues/1203).

**Comment by 0crat** [comment]
The job [#725](https://github.com/zerocracy/farm/issues/725) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1730634228); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat status

**Comment by krzyk** [comment]
@g4s8 strange, 0crat assigned me to this bug, but it is already closed.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-399341438))

@krzyk This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#725](https://github.com/zerocracy/farm/issues/725) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [39min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23725%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-399354996))

@g4s8 The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#725](https://github.com/zerocracy/farm/issues/725), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-399355983))

@g4s8 Job `gh:zerocracy/farm#725` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/725#issuecomment-399355983))

@g4s8 The job [#725](https://github.com/zerocracy/farm/issues/725) is now out of scope
