### ISSUE TITLE
Too many notifications for one closed issue

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#729]
Every time some job completed I receive 3 notifications in Telegram and few Github notifications.
Telegram:
> 0crat: we pay you some $
> 0crat: you earned some share
> 0crat: you got some points

I'm receiving them all during ~one minute.

Maybe we can wait a little bit and not sent notification immediately, then group notifications with same parent claim then send it as single message?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 yes, that would be great. We need some sanity checker for the list of claims. We discussed it already in #723. We need to introduce a mechanism first and then implement this particular checker/aggregator of `Notify` claims.

**Comment by 0crat** [comment]
Job [#729](https://github.com/zerocracy/farm/issues/729) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting for #723

**Comment by 0crat** [comment]
> @0crat waiting for #723  ([here](https://github.com/zerocracy/farm/issues/729#issuecomment-387299562))

@amihaiemil The impediment for [#729](https://github.com/zerocracy/farm/issues/729) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@g4s8 This one is related to #723, according to Yegor [here](https://github.com/zerocracy/farm/issues/729#issuecomment-370481730). Maybe this one needs to be closed/is outdated as well?

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/729#issuecomment-472961018))

@g4s8 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#729](https://github.com/zerocracy/farm/issues/729), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#729](https://github.com/zerocracy/farm/issues/729) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/fc2cc25c-34b6-41fe-b74d-58128b0b6c19); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/729#issuecomment-541489513))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#729](https://github.com/zerocracy/farm/issues/729), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/729#issuecomment-541489513))

@carlosmiranda Job refused in 2 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#729` is not assigned, can't get performer
