### ISSUE TITLE
Allow OSS projects as sandboxes, free of charge

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#730]
0crat should allow any project on Github to be registered, free of charge, as a sandbox project. It will be the PO decision if they pay the contributors or not, but ZC should take no fee.

This solves the problem of training new developers (nobody has to pay to maintain a sandbox project) + should offer diversity in technologies.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 well, it sounds easy, but we would need a mechanism to determine whether the project is truly a sandbox... what should the criteria be? If we have no mechanism for this, then anyone could register as a sandbox project and pay nothing :D

**Comment by yegor256** [comment]
@amihaiemil at the moment we don't take the management fee from open source projects, see: http://www.zerocracy.com/policy.html#23 So, any project can join and publish itself on the board. However, programmers won't be able to join, unless they have 256 reputation points.

If we allow any project to become "sandbox", they will get very immature programmers and will blame us for that. See?

**Comment by amihaiemil** [comment]
@yegor256 oh, I see. I'll have a look

**Comment by yegor256** [comment]
@amihaiemil we can allow _some_ projects to become sandbox, but they have to be absolutely ready to deal with strangers who have no idea what they are doing. And they will have to be ready to pay for that. See how difficult it will be to find those volunteers? The main question is why they would do that? They can register a normal project and get normal (256+ rank) programmers. Why accepting newbies?

**Comment by amihaiemil** [comment]
@yegor256 I understand now. So basically ZC is a free service for any opensource Github repo (I think you should rephrase that paragraph, the word "waived" is not so common, maybe not everyone understands it. For instance, I did not). 

I think you should tweet about that more, and make it popular. More projects will start using it and improve the platform :) Developers could work for them for free and but they gain reputation on the platform.

**Comment by yegor256** [comment]
@amihaiemil this exactly is the strategy. We will promote the problem for open source projects, but only when it's technically ready. We still have a lot of bugs, you know about them. The plan is to launch it all to public use on April 2, 2018.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
