### ISSUE TITLE
No payment for issue that was queued by 0crat 

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#731]
I was reviewing several issues and gave verdict to 0crat one by one.

No response was from 0crat [here](https://github.com/yegor256/cactoos/pull/717) for one hour, so in order not to duplicate review marks, I've triggered 0crat's "attention" by pinging him.

The points were processed, but no payment actually received. Debt list doesn't contain this issue 717.

![image](https://user-images.githubusercontent.com/11703257/36992775-a8423742-20b4-11e8-9746-f08cdea7136e.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka I belive it's fixed already, correct?

**Comment by ypshenychka** [comment]
@yegor256 I can't chek this now anymore.

**Comment by g4s8** [comment]
@ypshenychka I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#731` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
