### ISSUE TITLE
ARC should be able control 0crat better

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#734]
As far as I know, currently, ARC has no real power over how 0crat handles tasks (assignment, counting, delay etc). At least not without punishment.

Since the ARC is in charge of the project, he/she has to be sure that the project is stable and in good quality (including budget), ARC should be able to tell 0crat to postpone, stop counting, reassign etc without punishment. 

This is because there are situations where:

1. PRs have to be closed because the original Issue has an impediment found after it was opened (so the CR doesn't get punished by 10days rule). This means loss for the project, a PR that is reopened means double spending on reviewing.

2. A task has to not be assigned yet, since it has impediments in its definition

etc

The whole idea is to coordinate 0crat and solve the issue of tangled impediments while avoiding consequences such as:  **indefinite waiting time**, "**collateral punishment**" (e.g. someone gets punished because of someone else's delay) and **double spending**; -- this is one of the ARC's jobs, it's part of maintining the project's clearness and quality. All the 3 consequences above are hurting the project a lot: delays, demotivation and higher costs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil you have to be more specific. I do agree with some of your thoughts and disagree with others. Please, submit more specific issues.
