### ISSUE TITLE
0crat receives other notifications than "mention"

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#735]
See [here](https://github.com/zerocracy/farm/issues/229#issuecomment-370837948). 0crat analyzed my comment and responded, without any mentioning. 

The response was appropriate, since the comment never mentioned 0crat. I think the issue is that 0crat checks all types of notifications, not just the "mention" type.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 I am pretty sure the bug was introduced by in #720, when I took out the uppermost wrapping ``if``:

```java
if(comment.body().contains(self)) {
...
}
```

I was misguided by how those ``Response`` decorators are declared on top of eachother:

```java
...
new ReOnReason(
    "mention",
    new ReOnComment(
        new ExtGithub(frm).value(),
        new ReSafe(
            new ReNotMine(
                new ReIfAddressed(
                    new ReQuestion()
                )
            )
        ),
        new ExtDynamo(frm).value().table("0crat-github")
    )
)
```

This is in ``TkGithub``. See, the reason of the notification is already supposed to be "mention" by the time it gets inside ``ReIfAddressed`` (from where that ``if`` was removed)

So, either there is a bug and that ``ReOnReason`` does not work well, either there is another entrypoint for Github notifications (other than ``TkGithub``), where ``ReIfAddressed`` is not wrapped inside ``ReOnReason``

In this ticket we should have a look because either way you put it, it's not ``ReIfAddressed``'s job to check for ``contains`` -- comment notifications should not even get there without being of type ``mention`` and if they are of this type they clearly contain 0crat's handle.

**Comment by amihaiemil** [comment]
@yegor256 I think you should deploy the previous release, without #720. The bug is annoying and it probably relvealed other issues as well (I don't see how this bug, by itself, could cause repetition of comments as seen [here](https://github.com/zerocracy/farm/issues/736))

**Comment by yegor256** [comment]
@amihaiemil fixed already in 7fe5ceed5578c8f7e9b4e2185d46f5ff59d98edd

**Comment by amihaiemil** [comment]
@yegor256 Well, I didn't want to redo those changed, they are alright. The bug is somewhere else, as I explained in my comment above, the comment shouldn't reach ReIfAddressed if the handle is not in it :)

**Comment by yegor256** [comment]
@amihaiemil the purpose of `ReIfAddressed` is to accept _all_ events and allow only those that are addressed to Zerocrat to go through. You removed that functionality in #720 and neither the code reviewer no me didn't pay attention to it. Our fault. Fixed already.
