### ISSUE TITLE
0crat reacted to QA mark with multiple "Are you speaking to me..." and gave no awards

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#736]
Happened [here](https://github.com/zerocracy/farm/pull/672).
After giving quality verdict, 0crat responded with nore tha 20 messages "Are you speaking to me or about me here. You must always start your message with my name if you want to address it to me, see §1.".

No points or payments were processed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka fixed already, thanks
