### ISSUE TITLE
0crat unrecorevable issue after QA review

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#737]
Happened [here](https://github.com/zerocracy/farm/issues/220#issuecomment-370887641).

>@ypshenychka There is an unrecoverable failure on my side. Please, submit it here:
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/qa/complete_qa_review.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.log.PreFormatter[155] java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.

May be connected with issue #736 as here no points\payments were given as well.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka fixed, please try again
