### ISSUE TITLE
0crat didn't understand what is "acceptable"

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#743]
Happened [here](https://github.com/zerocracy/farm/pull/719#issuecomment-371052088).

0crat didn't give any points\payments.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#743](https://github.com/zerocracy/farm/issues/743) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/661452218). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ypshenychka I believe it's fixed in a28e3b9e166813612afba4f5b7d767a9d9e629b2 Please, try again

**Comment by ypshenychka** [comment]
@yegor256 Looks like it's working now: https://github.com/zerocracy/farm/issues/229

**Comment by ypshenychka** [comment]
@yegor256 oops. [Here](https://github.com/zerocracy/farm/pull/719#issuecomment-371189949) 0crat said that qa review is not needed in this job

**Comment by yegor256** [comment]
@ypshenychka that's because of the transition from an old system of reviews to a new one. Some of them may be "not required". Please, record them and let me know in a few days what is the full list of them.

**Comment by yegor256** [comment]
@ypshenychka this won't happen again

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @yegor256[/z](https://www.0crat.com/u/yegor256), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#743](https://github.com/zerocracy/farm/issues/743) is now out of scope

**Comment by ypshenychka** [comment]
@yegor256 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

No PR was created in scope of this issue.
Please confirm that you'll try to follow the process next time.

**Comment by yegor256** [comment]
@ypshenychka correct, I confirm

**Comment by ypshenychka** [comment]
@yegor256 Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@yegor256 Looks like all tickets that missed payment were covered by direct payments. @amihaiemil Please let us know if I missed something.

**Comment by amihaiemil** [comment]
@yegor256 @ypshenychka this one wasn't yet: #220

**Comment by ypshenychka** [comment]
@yegor256 Issue #220 is still without payment.
