### ISSUE TITLE
Make sure payments are bulletproof

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#745]
Is there a mechanism in the code, exception handling and so on, to make sure that *no matter what happens*, debts or errored payments are not lost? 

If not, we should definetely have it, since errors will happen for sure, shut downs will happen, bugs will be introduced etc, and 0crat can't afford to say "sorry, can't help you", once Beta testing is over. Also, there could be no excuse that could be written in the Policy either. Payments have to work sooner or later, period. 

If there is such a mechanism, then revise its tests -- it should have solid, reliable unit tests and integration tests :) 

As part of this endeavor, there could also be a page that would display all the jobs (open and closed) from the last month for example. Then, worst case scenario, someone manually checks those jobs and wires the money. And we should definetely have a statement in the Policy and say something like: "Make sure to report any missed payments in max 30 days".

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil `make_payment.groovy` is where we send out all payments. As you see, there is a try/catch block, which either sends the money to the `Payroll` or adds them to the `Debts`. Of course, if something happens in the middle, we may miss the payment. What would you suggest?

**Comment by amihaiemil** [comment]
@yegor256 first, I would implement make_payment in java. I am not sure, but those groovy scripts seem hard to test (as we've seen, that BundlesTest is not brilliant), log and debug. 

So, proper Java objects, decorated as follows: 

```java
Payments payments = new SafePayments {
    new MakePayments(...)
}
```

And anyway, the logic of make_payment.groovy, as you explained it now, seems too simplistic -- what about the flow where the payment is too little (< $20) and has to be put in debts? 

Nevertheless, even if we can't do much code improvements, we could have that page, right?

**Comment by yegor256** [comment]
@amihaiemil I think it's pretty solid and stable now. No matter what happens inside `Payroll` will end up in `Debts`. Then, we will pay it out anyway. I don't see any major issues now. Let's close.

**Comment by 0crat** [comment]
The job is not in WBS, can't close
