### ISSUE TITLE
Can't run 0crat locally

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#746]
If I try to run `Main` locally it will immediately fail as I cannot connect to relevant external systems. But sometimes I need to run it locally to see UI changes (I have #402 ui related issue), so I cannot be sure, that my changes are looks as they supposed to look. And also I can simply lack some necessary roles, cause I have only `DEV` role in the projects, so ability to run instance in my dev environment will help in this situation.

So as we operating on files mostly, I propose to create `ItemLocal`, `ProjectLocal` and other necessary objects to be able to run it locally. Maybe even introduce docker, but let me see what I'm dealing with on my machine, where I have full control.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#746](https://github.com/zerocracy/farm/issues/746) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/661806049). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#746](https://github.com/zerocracy/farm/issues/746) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't set title

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
