### ISSUE TITLE
Groovy scripts are resources, which is not convinient

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#747]
Our groovy scripts are just that scripts with `exec` method. However in order to use them we have to do reflection access and distinction between scripts is only the name of file. This leads to testing issues and also maintainability problems as if we want to add additional objects to `exec` it will affect all scripts.

I propose to move groovy to the `src/main/groovy` and use appropriate maven plugin to deal with them, so they will become the standard sources and they can be easily used within java code and other way around. Also the righting tests process will be simplified as they will be tested just with unit tests (maybe even bring popular among groovy devs Spock framework for that). Add to that full support from Intellij IDEA. And I feel like the more we write the more we might have to deal with the fact, that we need to move those "simple" scripts to `java` to be more reliable.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar there were there initially, but I moved them: 86165b4dca3c7767ce174eb033816cb5071152ca I don't remember why, though. Maybe it's time to move them back :)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#747](https://github.com/zerocracy/farm/issues/747) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1020630816); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by g4s8** [comment]
@t-izbassar what maven plugin did you mention here?
> I propose to move groovy to the src/main/groovy and use appropriate maven plugin to deal with them

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@g4s8 you can pick [from maven Integration](http://docs.groovy-lang.org/latest/html/documentation/tools-groovyc.html#_maven_integration) section of the docs. Probably I would choose eclipse option as we have cross java and groovy files.

**Comment by g4s8** [comment]
@t-izbassar thanks

**Comment by g4s8** [comment]
@0crat waiting #949 PR to merge

**Comment by 0crat** [comment]
> @0crat waiting #949 PR to merge ([here](https://github.com/zerocracy/farm/issues/747#issuecomment-383461308))

@g4s8 The impediment for [#747](https://github.com/zerocracy/farm/issues/747) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 this job takes too much time to resolve merge conflicts, can you please boost it?

**Comment by yegor256** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/747#issuecomment-393143645))

@yegor256 Boost 4x was set for [#747](https://github.com/zerocracy/farm/issues/747)

**Comment by yegor256** [comment]
@g4s8 done

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
@t-izbassar 2 puzzles [#1088](https://github.com/zerocracy/farm/issues/1088), [#1089](https://github.com/zerocracy/farm/issues/1089) are still not solved.

**Comment by g4s8** [comment]
@t-izbassar groovy scripts were moved to `src/main/groovy`, can we close?

**Comment by t-izbassar** [comment]
@g4s8 sure, thanks.

**Comment by 0crat** [comment]
Order was finished: +60 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#747](https://github.com/zerocracy/farm/issues/747) is now out of scope

**Comment by 0pdd** [comment]
@t-izbassar 2 puzzles [#1089](https://github.com/zerocracy/farm/issues/1089), [#1391](https://github.com/zerocracy/farm/issues/1391) are still not solved; solved: [#1088](https://github.com/zerocracy/farm/issues/1088).

**Comment by 0pdd** [comment]
@t-izbassar 2 puzzles [#1391](https://github.com/zerocracy/farm/issues/1391), [#1504](https://github.com/zerocracy/farm/issues/1504) are still not solved; solved: [#1088](https://github.com/zerocracy/farm/issues/1088), [#1089](https://github.com/zerocracy/farm/issues/1089).
