### ISSUE TITLE
Todo puzzles are not profitable for developers and for project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#749]
In some situations developer needs to submit issues while doing a job: it may be uncompleted task, or research task, or broken test with todo to fix it. It may be achieved by `todo` pdd-puzzles in code or developer can do in manually on Github. It takes about same time, but in first case performer gets nothing and todo task will be submitted only after code-review, where the reviewer and architect get some money (15min REV + 10min ARC), in second scenario developer will be payed for 15min for bug submitting. Also in first case this todo will be started later, because it needs to pass code review, then it should be merged by architect, then it should be added to WBS by architect.
I would suggest to pay developer for pdd-submitting (only if added to WBS) as for bug posting and skip code review if `todo` comment is the only change in the PR.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 but they are different things. Puzzles are the troubles _you_ make in the code, if you are the author of the changes. While bugs are the troubles _we_ have in the code already. That's why they are paid differently. You can't create bugs for something is not yet present in the code base. You _have_ to use puzzles for that. See the difference?

**Comment by g4s8** [comment]
@yegor256 I see. But can I call not implemented part of the feature as a bug and post it on Github? For instance if I create a schema in datum repo and it was merged I can create a todo puzzle to continue in farm repo or post it as a bug.

**Comment by yegor256** [comment]
@g4s8 it depends on the situation. If something is _broken_ in farm, you post a bug. If there is nothing yet to be broken, since the feature is not yet implemented, your "bug" won't be accepted. A bug always means that something is broken in master branch.

**Comment by g4s8** [comment]
@yegor256 ok, see the diference, thanks.

**Comment by 0crat** [comment]
The job is not in WBS, can't close
