### ISSUE TITLE
0crat didn't remove job from WBS after QA verdict

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#750]
0crat asked me to review this job https://github.com/zerocracy/farm/pull/672 then asked for QA verdict, but after `quality acceptable` https://github.com/zerocracy/farm/pull/672#issuecomment-371210167 it answered:
> @ypshenychka Thanks, but QA review is not required in this job

so this job still in WBS and in my agenda.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it's a duplicate of #742, fixed already

**Comment by 0crat** [comment]
The job is not in WBS, can't close
