### ISSUE TITLE
Document more details about claims

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#756]
In #489 it is implied that a ``claim`` should have the element ``cause`` which should hold the id of the claim which created it, its parent. 

However, it is not clear if that is really the case and if so, if ``cause`` should hold the parent's id or something else. Besides, it is not even clear how a claim could create another one. This mechanism and the technical aspects should be documented, since also [claims.xsd](https://github.com/zerocracy/datum/blob/master/xsd/pm/claims.xsd) doesn't offer much info (I couldn't even find "cause" element there)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#756](https://github.com/zerocracy/farm/issues/756) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/670665892). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil see 824c097 Good enough?

**Comment by amihaiemil** [comment]
@yegor256 I see now, thanks. params is declared in [claims.xsd](https://github.com/zerocracy/datum/blob/master/xsd/pm/claims.xsd#L47)

Then, having in regards that ``cause`` is not an xml node in itself, is the following filter correct, in TkChain (PR was just merged a few minutes ago): https://github.com/zerocracy/farm/blob/40954edd2a528ae70b121238d8035d4fb3e844c4/src/main/java/com/zerocracy/tk/project/TkClaim.java#L86

Do those params turn into mongo Document fields at the same level as ``cid`` or ``project``?

**Comment by yegor256** [comment]
@amihaiemil that's correct, all params will be at the same level as `cid` and `project`, see `Footprint#open()` method.

**Comment by amihaiemil** [comment]
@yegor256 thanks. Then I think we can close this :)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#756](https://github.com/zerocracy/farm/issues/756) is now out of scope

**Comment by yegor256** [comment]
@amihaiemil you made me think about potential clashes, see: 5dce061be419fffc7b17ecc77238b0d997d14667

**Comment by amihaiemil** [comment]
@yegor256 By clash, you mean the following possible claim:

```xml
<claim id="5">
  <type>Add job to WBS</type>
  <created>2016-12-29T09:03:21.684Z</created>
  <author>yegor256</author>
  <token>slack;C43789437;yegor256</token>
  <params>
    <param name="type">Repeat type here</param>
  </params>
</claim>
```

Notic ethere is element ``<type>`` and also ``<param name="type">`` -- that would be a problem, indeed. Maybe, when turning claims into mongo documents and putting them all at the same level, we should add some prefix to param names. Say the above would be ``param-type`` in the Document.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by yegor256** [comment]
@amihaiemil yes, exactly that type of "clash". They won't happen, since I added validation: 5dce061
