### ISSUE TITLE
Don't punish ARC for assignment if there are no available DEVs

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#757]
I noticed 0crat may take a rather long time to assign a performer to a task. For instance [here](https://github.com/zerocracy/farm/issues/487#issuecomment-371277153) it took 10 days to assign a new DEV after the original one had refused. 

I assume this situation happens when all the DEVs are busy (have max number of tasks), are on vacation or whatever other reason.

In this situation, when election is blocked, the ARC should be able to manually assign the task to a performer. 0crat could also inform the ARC that there are currently no available DEVs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil but how is guilty if the project doesn't have enough DEVs available?) The ARC is guilty and he/she has to be punished.

**Comment by amihaiemil** [comment]
@yegor256 actually, I would say that the PO is guilty in that situation. And anyway, in order to always have a "free" programmer, in PDD, you need a hell lot of programmers. Task tree goes to 200 tasks in a few days at the beginning of the project, what do you do with them? You only got 15 programmers, all with 5-8 task slots.

I think you will never be able to have enough programmers to cover the flow of puzzles automatically. ARC has to intervine and manage it at some point. Wouldn't you think?

**Comment by yegor256** [comment]
@amihaiemil I understand how it works, I just don't understand why can't we punish the ARC?) He/she will be interested to solve this situation somehow. We have to find solutions. But removing the punishment element will degrade the entire system. I don't like.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
