### ISSUE TITLE
Building artificial reputation

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#763]
One can build artificial, fake, reputation very easily as follows: 

1) They register their OSS project for free (receiveing ARC and PO roles there)
2) Start opening Issues
3) Put them in scope by using ``in``
4) 0crat grants 15 points

See [here](https://github.com/amihaiemil/docker-java-api/issues/33).

We need a mechanism to prevent this from happening. The first thought that comes to mind is: allow only PO to put jobs in and out of scope + one person should not hold both PO and ARC roles, but I am not sure how much impact would this change have otherwise. What do you think?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I think that `bootstrap` command should be available only to those who has 1024+ reputation. And it should cost, say, 128 points. This is the first step. It won't solve the problem you are describing here, but will help us get rid of random strangers.

**Comment by 0crat** [comment]
The job [#763](https://github.com/zerocracy/farm/issues/763) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/670930415). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by amihaiemil** [comment]
@yegor256 yes, sounds good, it's an improvement

**Comment by yegor256** [comment]
@amihaiemil made fixes in 727e25c0c85a181aa480922269354f7199f9863a

**Comment by g4s8** [comment]
@amihaiemil policy was updated, see http://www.zerocracy.com/policy.html#12. Can we close this task?

**Comment by amihaiemil** [comment]
@g4s8 sure, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#763](https://github.com/zerocracy/farm/issues/763) is now out of scope
