### ISSUE TITLE
Make Claim work with Issue instead of XML

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#772]
This is a big refactoring proposal, certainly not to be started now, but we should think about it: 

Currently, when a claim is registered (for instance, at the Github radar), the Issue is stripped down and only certain elements are taken from it and eventually turned into XML which ClaimIn/ClaimOut are working with all over the project.

This is a very sensitive design -- basically, everytime we will need something new from an Issue we need to add a new ``param`` to the claim and modify methods all over the project to accept that new param as argument.

For instance, in #422, we have to display the Issue's title in the Agenda. This has to be implemented starting with the Github radar, down to the ``add_to_agends.groovy``. Here are the steps:

1) Add the ``title`` param here:

https://github.com/zerocracy/farm/blob/91513b6161574d9c4cda293fa6123afa6d3b736f/src/main/java/com/zerocracy/radars/github/ReQuestion.java#L55

2) Later, in add_to_agenda.groovy, read the param from the ClaimIn and pass it to ``Agenda.add(...)``. 

3) Modify agenda.xsl to read and display that new parameter. 

If the Claim would have encapsulated an Issue instead of a raw XML, we could read everything directly from there, add the Issue in the Agenda and then we would simply have to modify the xsl to read whatever possible from the Issue. 

Not only it is a lot of work, the code is hard to test, you need to have a too big overview, you never know what .xsd is going to pop if you add a new parameter to an XML etc. 

This I think, can be applied to the whole project -- we should work with the objects and interfaces we have. Most of the stuff we need is already provided by jcabi-github, no need to tear them up and shove them into XML only to later build them back again.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil we can't "encapsulate" anything in a claim, since it's a plain piece of XML, stored in `claims.xml`. It's not an object, it's pure data. Radar creates a claim and then someone else (on another machine/node/servrer) picks it up and processes. So, they are not object, they are pure data. `ClaimIn` is just a helper to read the data.

Also, you don't need to pass the title of the GitHub ticket through the claim -- you can always get it from GitHub, right where you do the processing of the claim.

**Comment by amihaiemil** [comment]
@yegor256 Yes, I figured I could read from Github wherever I needed, but I thought of efficiency, why make a dozen calls on a flow when you can make only one, in the beginning :)

But I see the idea. I'll open other Issues if I find more concrete and not so big stuff.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
