### ISSUE TITLE
Refactor/redesign for scalability

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#773]
As discussed bellow, we need to think about scalability and do some progress in that direction. We should start with ``RvFarm/DefaultFlash``

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil why would we deploy it to multiple nodes? I'm kidding. The entire application is not ready yet for multi-node deployment. We have no across-nodes synchronization or any other strategy for multi-node work. I agree that we should start thinking in this direction, but radars is not the top priority thing. `RvFarm`/`DefaultFlash` is where the key problem is.

If you rename the ticket and update its description, I will accept it and we'll start.

**Comment by amihaiemil** [comment]
@yegor256 done :) But I still think the radars should be decoupled, in the end.

**Comment by 0crat** [comment]
Job [#773](https://github.com/zerocracy/farm/issues/773) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#773](https://github.com/zerocracy/farm/issues/773) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1381137931); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/773#issuecomment-390178893))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#773](https://github.com/zerocracy/farm/issues/773), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#773](https://github.com/zerocracy/farm/issues/773) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1381258514); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/773#issuecomment-391540410))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#773](https://github.com/zerocracy/farm/issues/773), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#773](https://github.com/zerocracy/farm/issues/773) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1551150164); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 are we going to use Heroku later for multi-instance application?

**Comment by g4s8** [comment]
@0crat waiting for @yegot256 answer

**Comment by 0crat** [comment]
> @0crat waiting for @yegot256 answer ([here](https://github.com/zerocracy/farm/issues/773#issuecomment-398000098))

@g4s8 The impediment for [#773](https://github.com/zerocracy/farm/issues/773) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 most probably, yet

**Comment by g4s8** [comment]
@amihaiemil @yegor256 I think we can scale groovy stakeholders here as most stateless part of application, to communicate with them we can use centralized claims queue which will receive claims from all sources, and stakeholder workers will take claims from it one by one:
![scaling](https://user-images.githubusercontent.com/1524988/42275666-b3815b58-7f99-11e8-99a6-d8cb10a6037e.png)

Also we need to make synchronization mechanism to controll S3 resource access from stakeholders nodes.

I think we need to start with claims queue here, Heroku suggests to use [RabbitMQ](https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-java) for java apps (they have an addon for it). If we don't want to use external services for claim queue we can keep using `claims.xml` files, but we need additional synchronization between workers and main node on project level.

**Comment by g4s8** [comment]
@yegor256 ping. What do you think about this https://github.com/zerocracy/farm/issues/773#issuecomment-402458468 ?
We need to start thinking and preparing for multi-instance application, now we have about 34.7 requests per second to our `Flush` implementation (when `Ping` claim is submitted for all projects), I think these `Flush`-es and `claims.xml` on S3 will become our "weak point" if we add few more projects to catalog.

**Comment by yegor256** [comment]
@g4s8 I agree with the strategy. How about moving "claims" to Amazon SQS?

**Comment by g4s8** [comment]
@yegor256 yes, SQS will be good for it, I think we need FIFO SQS here. We may even not reach free limit (1_000_000 requests per month): now we have about 416 claims per day (average for Zerocracy project).

**Comment by yegor256** [comment]
@g4s8 let's go for SQS. Let me know what I need to create there and what credentials to add to `settings.xml`

**Comment by g4s8** [comment]
@amihaiemil I added 3 tasks to refactor certain parts in application: #1463 #1464 #1465, can we close?

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#773](https://github.com/zerocracy/farm/issues/773) is now out of scope

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#1464](https://github.com/zerocracy/farm/issues/1464), [#1465](https://github.com/zerocracy/farm/issues/1465) are still not solved; solved: [#1463](https://github.com/zerocracy/farm/issues/1463).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#1465](https://github.com/zerocracy/farm/issues/1465), [#1533](https://github.com/zerocracy/farm/issues/1533) are still not solved; solved: [#1463](https://github.com/zerocracy/farm/issues/1463), [#1464](https://github.com/zerocracy/farm/issues/1464).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#1533](https://github.com/zerocracy/farm/issues/1533), [#1644](https://github.com/zerocracy/farm/issues/1644) are still not solved; solved: [#1463](https://github.com/zerocracy/farm/issues/1463), [#1464](https://github.com/zerocracy/farm/issues/1464), [#1465](https://github.com/zerocracy/farm/issues/1465).

**Comment by 0pdd** [comment]
@amihaiemil 3 puzzles [#1533](https://github.com/zerocracy/farm/issues/1533), [#1680](https://github.com/zerocracy/farm/issues/1680), [#1681](https://github.com/zerocracy/farm/issues/1681) are still not solved; solved: [#1463](https://github.com/zerocracy/farm/issues/1463), [#1464](https://github.com/zerocracy/farm/issues/1464), [#1465](https://github.com/zerocracy/farm/issues/1465), [#1644](https://github.com/zerocracy/farm/issues/1644).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#1680](https://github.com/zerocracy/farm/issues/1680), [#1681](https://github.com/zerocracy/farm/issues/1681) are still not solved; solved: [#1463](https://github.com/zerocracy/farm/issues/1463), [#1464](https://github.com/zerocracy/farm/issues/1464), [#1465](https://github.com/zerocracy/farm/issues/1465), [#1533](https://github.com/zerocracy/farm/issues/1533), [#1644](https://github.com/zerocracy/farm/issues/1644).
