### ISSUE TITLE
IllegalStateException on publish

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#775]
I tried to publish a newly boostrapped project and got IllegalStateException:

![publish_on_ise](https://user-images.githubusercontent.com/6305156/37172742-598b9b26-231a-11e8-8841-6a73402b84dd.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil please, try again. There will be another exception, please post it here.

**Comment by amihaiemil** [comment]
@yegor256 Indeed, now it is IAE instead of ISE (and I get the same behaviour if I try to set the title of the project)

![screenshot_20180309-102158](https://user-images.githubusercontent.com/6305156/37197571-f43e3b1a-2383-11e8-8a59-71fe710229d6.png)

**Comment by 0crat** [comment]
The job [#775](https://github.com/zerocracy/farm/issues/775) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/680837485). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed in 9735415a3e3798b9bdf2b87bcfd31a7fb697e5b3 Try again, pls.

**Comment by amihaiemil** [comment]
@yegor256 publish now works and I can see it on the board, however, right after it responded "your project is no visible...", it sent me a second message with this exception: 

![screenshot_20180309-104405](https://user-images.githubusercontent.com/6305156/37198467-0b92e8b2-2387-11e8-8352-07b138a193d7.png)

**Comment by yegor256** [comment]
@amihaiemil can you please publish again? It should work, I believe, and you will see the exception

**Comment by amihaiemil** [comment]
@yegor256 ``publish off`` worked fine, no error, then ``publish on`` again worked but got this second message:

![screenshot_20180311-102626](https://user-images.githubusercontent.com/6305156/37251340-ddb1caa8-2516-11e8-9ad7-72817de9098d.png)

**Comment by amihaiemil** [comment]
@yegor256 A bit more detailed from Sentry:

```
[Claim param name "author" is prohibited to use in "Project was published", since it will clash with other claim attributes, Processing terminated by xsl:message at line 26 in file:///; SystemID: file:///; Line#: 26; Column#: 5]
    at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:108)
    at com.zerocracy.pm.ClaimOut$postTo.call
    at com.zerocracy.stk.pm.publish_project.exec(publish_project.groovy:47)
...
(42 additional frame(s) were not displayed)

InvocationTargetException: None
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
...
(33 additional frame(s) were not displayed)

IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/publish_project.groovy
```

**Comment by amihaiemil** [comment]
@yegor256 I think is the "anti clash" validation you added a few days ago :D

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed in in dfe6efacdecfc78e958096789f38ecea7250b03c Thanks!

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#775](https://github.com/zerocracy/farm/issues/775) is now out of scope
