### ISSUE TITLE
When adding Zerocracy App to a slack channel, it is too thankful

### ISSUE THREAD

**Issue by jmrobison** [zerocracy/farm#778]
See below:

zerocracy APP [3:25 PM]
joined #zerocracy by invitation from USERNAME.

zerocracy APP [3:25 PM]
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.
Thanks for inviting me here.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@jmrobison it seems that we fixed it today, in https://github.com/zerocracy/datum/issues/163 Thanks for reporting it though, and welcome to Zerocracy! :)
