### ISSUE TITLE
0crat reassigns after requesting QA

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#781]
Right now `@0crat` appears to be reassigning, or resending the assignment notification, after a ticket is closed and QA is requested. Examples:

https://github.com/zerocracy/farm/pull/744#issuecomment-371737294
![image](https://user-images.githubusercontent.com/1917892/37196398-952ad88a-23b1-11e8-99d9-45da2a7c0392.png)

https://github.com/zerocracy/farm/pull/752#issuecomment-371413065
![image](https://user-images.githubusercontent.com/1917892/37196556-3fa6d606-23b2-11e8-9976-fe7fa772dbf9.png)

This may or may not be a huge issue (since it ended up reassigning back to me) but at the very least it's resulting in lots of Github and Telegram spam.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#781](https://github.com/zerocracy/farm/issues/781) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/680821027). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@carlosmiranda fixed in 1dd9735129d1eea667a36e1ed79bf0c0c194caa7

**Comment by carlosmiranda** [comment]
@yegor256 thanks. :)

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#781](https://github.com/zerocracy/farm/issues/781) is now out of scope
