### ISSUE TITLE
Job performers do not get extra +5 points for 'good' quality

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#787]
Please see this ticket #764.
QA mark is good, but code reviewer received only +15 points instead of +20.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka thanks, fixed in 3fa3edc661c36f1d6282a510458cc65ca43932ea

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job [#787](https://github.com/zerocracy/farm/issues/787) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/720550188). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#787](https://github.com/zerocracy/farm/issues/787) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
