### ISSUE TITLE
Ping timer depends on deploy time

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#789]
The server can be restarted few times in a day, it means that `Ping daily` claim may not be called more than few days. I think it's better to use some job scheduler e.g. [quartz-scheduler](http://www.quartz-scheduler.org/).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 dup of #680

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
