### ISSUE TITLE
ISE in start_order.groovy

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#794]
Happened [here](https://github.com/amihaiemil/docker-java-api/issues/36#issuecomment-372136499): 

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#220, gh:zerocracy/farm#435, gh:zerocracy/farm#416, gh:zerocracy/farm#497, gh:zerocracy/farm#512, gh:zerocracy/farm#415, gh:zerocracy/farm#422, gh:zerocracy/farm#528]' and java.lang.Integer with value '32'
```

Seems like 0crat cannot assign a job to the Github assignee and also can't assign it when the ARC tells it to do so (see the second trial). However, punishment for ARC works fine. 

I think it is related to [this](https://github.com/zerocracy/farm/commit/5019099351815d42a80a8e5d3512cc5d0e71e88b) commit (since I already have 8 tasks in the agenda, assigning one more should not be possible anymore, apparently.

**Comment by yegor256** [comment]
@amihaiemil fixed already, thanks
