### ISSUE TITLE
Can't assign role

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#799]
One person applied to the project, I say ``@0crat assign DEV llorllale $0`` and it says "Assignee ``@llorllale``/z must be present on Github"

The check for Github membership has been introduced [here](https://github.com/zerocracy/farm/pull/719/files#diff-6b470f91f81f74907161407bc05e83b3R40), in ``assign_role.groovy`` -- the fact that the ``AssertionError`` is thrown means that the Github response was not the expected one (it is validated inside ``RtUser.json()``) -- maybe the Github quota is exceeded?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I moved validation to invite user command: 74e72b9001d50a41903b3958de3e09b12071a709

**Comment by 0crat** [comment]
The job [#799](https://github.com/zerocracy/farm/issues/799) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/712053003). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#799](https://github.com/zerocracy/farm/issues/799) is now out of scope
