### ISSUE TITLE
0crat ignores QA verdict

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#801]
Happened in #220.
0crat doesn't react when mentioning him.

UPD: 0crat responded after 1 hour.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka it was a temporary bug, it was replying slowly. Thanks for reporting, fixed already.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
