### ISSUE TITLE
Duplicate Paypal debt payment

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#802]
Last March 9 I was paid out some debts because the amount was over the $20 threshold. However I received it twice:

![image](https://user-images.githubusercontent.com/1917892/37316665-62050e7a-269b-11e8-82a1-745d9b9f3266.png)

Note the corresponding Telegram message which only appeared once (in case it might be helpful to find out what's going on):

![image](https://user-images.githubusercontent.com/1917892/37316965-20e86e9e-269d-11e8-8e87-87a54555c3c3.png)

**Comment by carlosmiranda** [comment]
@yegor256 Sent you details on Telegram. I made a refund for one of the payments as well.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@carlosmiranda I can't understand why this happened. I added some extra logging/reporting. Let's keep an eye on this.

**Comment by 0crat** [comment]
The job [#802](https://github.com/zerocracy/farm/issues/802) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/721825453). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by paulodamaso** [comment]
@yegor256 It happened with me too: 0crat payed me $69,28 (id 9UA05728KT849524H) for some issues (yegor256/cactoos#877, yegor256/cactoos#868, yegor256/cactoos#876, yegor256/cactoos#880, yegor256/cactoos#874, llorllale/cactoos-matchers#8, yegor256/cactoos#901, yegor256/cactoos#866, harvest-foundation/telegram-bot#46, harvest-foundation/telegram-bot#4, sunsofterp/portal#56, harvest-foundation/telegram-bot#47, yegor256/cactoos-http#23) an then paid me again for the same issues, plus $19,94 (totalling $89,22, id 9PL614409D753090H) for sunsofterp/portal#53.

**Comment by g4s8** [comment]
@carlosmiranda this job was fixed in #1401, can we close?

**Comment by carlosmiranda** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job [#802](https://github.com/zerocracy/farm/issues/802) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#802](https://github.com/zerocracy/farm/issues/802) is now out of scope
