### ISSUE TITLE
Percentage is rounded half-up on vesting page

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#807]
On a Project's vesting page, the ownership percentage is rounded half up. E.g., on Zerocracy, it displays that I own ``0.01%`` and that is not true, I own less than that: ``0.00721675`` -- it rounded 0.007 to 0.01, which I don't believe is correct, such data should be precise. 

Furthermore, I think this percentage should be written in the ``proof`` PDF, with all decimals (on the page it is only the first 2 decimals, so I should see ``0.00%`` there.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed, pls check

**Comment by amihaiemil** [comment]
@yegor256 Yes, it looks ok now, thanks :)
