### ISSUE TITLE
VsProjectWorkload

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#808]
Let's create `VsProjectWorkload`, which will work exactly like `VsWorkload`, but take into account only orders currently assigned to each person in this particular project.

**Comment by amihaiemil** [comment]
@yegor256 What would that new class do exactly? "take into account only orders currently assigned to each person in this particular project" is not so precise :D

**Comment by yegor256** [comment]
@amihaiemil why not? It will give priority to the user with the lowest amount of orders in this project. Thus, if you are a member of 5 projects, you will get jobs quicker when you are not yet present (have no or almost no orders).

**Comment by amihaiemil** [comment]
@yegor256 so it solves the issue that one project could "starve"? DEVs could move as fast as possible, but how does 0crat decide to which Project to assign tasks? What stops 0crat from always assigning me tasks in ``zerocracy/farm``, when I am also in 2 other projects?

**Comment by yegor256** [comment]
@amihaiemil in those projects it will try to pick you, since you don't have tasks there.

**Comment by amihaiemil** [comment]
@yegor256 makes semse now, thanks

**Comment by 0crat** [comment]
Job [#808](https://github.com/zerocracy/farm/issues/808) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#808](https://github.com/zerocracy/farm/issues/808) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1391546371); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting PR #1051 to merge

**Comment by 0crat** [comment]
> @0crat waiting PR #1051 to merge ([here](https://github.com/zerocracy/farm/issues/808#issuecomment-392313089))

@g4s8 The impediment for [#808](https://github.com/zerocracy/farm/issues/808) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1061](https://github.com/zerocracy/farm/issues/1061) is still not solved.

**Comment by g4s8** [comment]
@yegor256 PR #1051 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#808](https://github.com/zerocracy/farm/issues/808) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1061](https://github.com/zerocracy/farm/issues/1061) is solved here.
