### ISSUE TITLE
Exit button style issues

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#810]
Exit button has some style issues on index page, also it doesn't have underline like all other links
![index-page](https://user-images.githubusercontent.com/6305156/37352084-1ec8ac94-26e5-11e8-9448-c935cf7fe19e.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
