### ISSUE TITLE
Let's add Github links to the debt list

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#811]
Let's make all the Github job labels in the debts section of the user home page into Github links.

![image](https://user-images.githubusercontent.com/1917892/37380857-70700eb2-2775-11e8-87ce-01541ae38e83.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#811](https://github.com/zerocracy/farm/issues/811) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/732124317). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@carlosmiranda check it now, pls

**Comment by carlosmiranda** [comment]
@yegor256 strange, I still don't see any links.

**Comment by yegor256** [comment]
@carlosmiranda can you show what you see in the profile XML? Click "view sources". Also, please attach a new screenshot. Or it's exactly the same?

**Comment by carlosmiranda** [comment]
@yegor256 this is the source:

```xml
      <debt total="$xx.xx">
         <item>
            <ago>6days</ago>
            <amount>$xx.xx</amount>
            <details>Order was finished, quality is "good" at gh:zerocracy/farm#764 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details>
            <details_html>Order was finished, quality is "good" at gh:zerocracy/farm#764 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details_html>
         </item>
         <item>
            <ago>2days</ago>
            <amount>$xx.xx</amount>
            <details>Order was finished, quality is "acceptable" at gh:zerocracy/farm#786 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details>
            <details_html>Order was finished, quality is "acceptable" at gh:zerocracy/farm#786 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details_html>
         </item>
         <item>
            <ago>2days</ago>
            <amount>$xx.xx</amount>
            <details>Bug was reported, see §29 at gh:zerocracy/farm#802 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details>
            <details_html>Bug was reported, see §29 at gh:zerocracy/farm#802 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details_html>
         </item>
         <item>
            <ago>1days</ago>
            <amount>$xx.xx</amount>
            <details>Bug was reported, see §29 at gh:zerocracy/farm#811 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details>
            <details_html>Bug was reported, see §29 at gh:zerocracy/farm#811 (The amount $xx.xx is too small, we won't send now to avoid big payment commission)</details_html>
         </item>
         <item>
            <ago>13hr</ago>
            <amount>$xx.xx</amount>
            <details>Order was finished, quality is "acceptable" at gh:zerocracy/farm#797 (The amount $xx.xx is too small)</details>
            <details_html>Order was finished, quality is "acceptable" at gh:zerocracy/farm#797 (The amount $xx.xx is too small)</details_html>
         </item>
      </debt>
```

Screenshot:
![image](https://user-images.githubusercontent.com/1917892/37496781-7f65aec4-28ef-11e8-8314-37b2c2acbd26.png)

**Comment by carlosmiranda** [comment]
@yegor256 this is working now. Not sure when but I think it's way overdue that I close this. Thanks! :)
