### ISSUE TITLE
Color code "Role" in Agenda page

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#812]
Let's give each role in the Agenda page its own color. Right now it's hard to tell at first glance the difference between REV and DEV:

![image](https://user-images.githubusercontent.com/1917892/37380921-b1276af4-2775-11e8-907d-af46eac8f554.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by carlosmiranda** [comment]
@yegor256 what do you think of this?

**Comment by yegor256** [comment]
@carlosmiranda fixed in https://github.com/zerocracy/datum/commit/088a882d19deed43f2a387ffde54a6bdbacdc15a You will see new colors after the next release of Datum.

**Comment by 0crat** [comment]
The job [#812](https://github.com/zerocracy/farm/issues/812) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/811306551); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#812` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#812](https://github.com/zerocracy/farm/issues/812) is now out of scope
