### ISSUE TITLE
ranks in elections drains the Github API quota

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#813]
Due to Github API quota, many webhook calls respond with 503: 

![image](https://user-images.githubusercontent.com/6305156/37389306-7c94ee82-276c-11e8-8347-c72547ca1f1d.png)

I think we should solve this somehow. The waiting time is rather big and then inconsistencies appear in the project, since 0crat answers much later (call is saved by ReHttp), when the Issue might already be solved.

**Comment by g4s8** [comment]
@amihaiemil @yegor256 @0crat is not responding on Github all day, does it related to this bug?

**Comment by amihaiemil** [comment]
@g4s8 most likely, my repo's Webhook settings is filled with failed requests :)

**Comment by amihaiemil** [comment]
@g4s8 Out of the last few dozen calls only 3 succeded

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/813#issuecomment-373049047); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 yes, the problem was with the quota. We don't have an issue with it, unless we do something wrong. We were doing something wrong recently, sending them too many requests. I belive it's fixed now and everything will be fine. Let's keep an eye on that.

**Comment by amihaiemil** [comment]
@yegor256 It doesn't seem to be fixed. It seemed to work when you redeployed about 4h ago, it left a few comments but now it's again 503 for the past dozens calls

**Comment by yegor256** [comment]
@amihaiemil @g4s8 looks like it was a problem with `cleanup_comments`. It takes a comment from DynamoDB and attempts to delete it in GitHub. But it doesn't exist there. It fails, but GitHub quota is used. And it does it every hour. Eventually, we have a problem. I removed all lines from DynamoDB 0crat-errors table, to fix the issue right now, but we need a proper fix.

**Comment by yegor256** [comment]
@g4s8 it seems that the problem is in `RnkGithubBug`, which we introduced recently in #576. It makes too many queries to GitHub API, one per each ticket/job in each project, which is too many.

**Comment by g4s8** [comment]
@yegor256 I'm working on similar task https://github.com/zerocracy/farm/pull/821/files it will fetch a milestone for each job during election. Maybe we have to postpone this ticket https://github.com/zerocracy/farm/issues/575 ?

**Comment by yegor256** [comment]
@g4s8 yes, it seems we should. We have to find a solution. We can't ping GitHub that frequently. But we need to be able to collect that information. Maybe we should list to webhooks and store the information we receive somewhere...

**Comment by g4s8** [comment]
@yegor256 @amihaiemil I think it can be solved with this issue: https://github.com/jcabi/jcabi-github/issues/1369

**Comment by yegor256** [comment]
@amihaiemil please, rename the ticket and I will accept it. The problem here is that we run out of GitHub quota when using "ranks" during election.

**Comment by amihaiemil** [comment]
@yegor256 done

**Comment by 0crat** [comment]
Job [#813](https://github.com/zerocracy/farm/issues/813) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/813#issuecomment-383497679))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#813](https://github.com/zerocracy/farm/issues/813) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23813%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 can you assign this job to someone? It's blocking another job: #575

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by carlosmiranda** [comment]
@amihaiemil @yegor256 @g4s8 see PR #965.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #965.

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #965. ([here](https://github.com/zerocracy/farm/issues/813#issuecomment-383778907))

@carlosmiranda The impediment for [#813](https://github.com/zerocracy/farm/issues/813) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@amihaiemil fixed (finally) in #965, can we close this now?

**Comment by amihaiemil** [comment]
@carlosmiranda sure, thanks :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#813](https://github.com/zerocracy/farm/issues/813) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
