### ISSUE TITLE
0crat should automatically put 0pdd's tickets in scope

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#814]
Tickets opened by ``0pdd`` should automatically be put in scope, I believe. I merge a PR with 3 puzzles and 0crat asks me to take a look into each new ticket, when I already reviewed them before merging. See [here](https://github.com/amihaiemil/docker-java-api/issues/41). This could also reduce the Github API calls, contributing to fixing the Quota problem :) 

Furthermore, I think 0crat should scan the puzzle and assign the estimation specified there -- currently  0crat assigns 30min to any task. if the puzzle says ``15min``, then that should be 0crat's estimation as well. WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil you just configure 0pdd to add `bug` labels to all new tickets. Then Zerocrat will pick them up automatically. This is how it works in this repository.

As for the estimates, we work with fixed 30-min budgets now. So, we just ignore the information from 0pdd. This is our business case. Other projects may use that information. We don't.

**Comment by amihaiemil** [comment]
@yegor256 I see, thanks
