### ISSUE TITLE
Leading roles should also be assignable to Github Organizations

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#815]
I'm not sure, but I believe 0crat demands that the Github login belongs to a User. If this is true, then wouldn't it be better if it could also belong to an organization?

For instance, a company may manage their projects with ZC and would rather register their Github Organization, so more people (actual POs) could give commands to 0crat in their respective projects. WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil actually we don't check that at the moment. Any GitHub user will work. I think it would be good to validate that the account belongs to a user, not organization.

The other part of your suggestion is not really clear to me. Why do we need all that?

**Comment by amihaiemil** [comment]
@yegor256 well, the overall idea is to have the Organization as an umbrella for more users also from 0crat's perspective. Maybe not necessarily for the current roles, it's actually easier for them to stay like this. But maybe a CEO role, chief of the Organization, could be useful? For instance, the CEO may want to have full control over the budget of all the projects etc. 

Basically, the idea is that 0crat knows nothing about Organizations so any improvement in that area would be a plus. And I certainly wouldn't dismiss them :D

**Comment by yegor256** [comment]
@amihaiemil I don't see what we can do with. I'm closing.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
