### ISSUE TITLE
Broken delayed events sequence processing by 0crat

### ISSUE THREAD

**Issue by biboran** [zerocracy/farm#816]
After 0crat could not communicate to github api due to #813 some of the events were not processed. For example in this case 0crat didn't recognize the assignment (as an `ARC` I assigned myself) as he did in #799:
<img width="896" alt="screen shot 2018-03-14 at 6 52 28 pm" src="https://user-images.githubusercontent.com/8717108/37414716-d2601604-27ba-11e8-995d-12c278e874a9.png">

And after this pr 0crat didn't recognize work performed by `REV`:
<img width="824" alt="screen shot 2018-03-14 at 7 07 35 pm" src="https://user-images.githubusercontent.com/8717108/37414812-0e3d4ec6-27bb-11e8-8cff-2d816a79138a.png">

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@biboran 

> And after this pr 0crat didn't recognize work performed by REV:

Yes, I also had this, 0crat did not pay me, as ARC, for merged PRs. That may also be a bug somewhere else? Maybe it tries to assign a QA and it doesn't find any?

**Comment by biboran** [comment]
@amihaiemil I don't think QA is an issue. It used to work fine without QA up until today.

**Comment by yegor256** [comment]
@biboran it's just a problem with API quota. It should be fixed already and in about an hour everything will be fine.

**Comment by yegor256** [comment]
@biboran I'm closing, it was a temporary issue, already reported in #813

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
