### ISSUE TITLE
Options are not implemented

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#820]
From zerocracy/datum#258 (this [puzzle](https://github.com/zerocracy/farm/pull/693/files) was not submitted because original issue submitted in datum)
Options are not implemented. We should be able to
access `options/{username}.xml` file (where {username} is a person
name from `people.xml`) to read and modify user options.
Also some mechanism should be invented to allow user to change this
options. Also don't forget to remove `@todo` in `OptionsTest`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#820](https://github.com/zerocracy/farm/issues/820) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#820](https://github.com/zerocracy/farm/issues/820) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1591432480); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by proshin-roman** [comment]
@g4s8 it looks like the feature has already been implemented in https://github.com/zerocracy/farm/issues/703. At least now I'm looking at the fresh master and see https://github.com/zerocracy/farm/blob/8439553fd7afe1727270e5649b54c5fcf118ed7d/src/main/java/com/zerocracy/pmo/Options.java class. Let's close the issue then as there is nothing to do here anymore?

**Comment by g4s8** [comment]
@proshin-roman right, thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#820](https://github.com/zerocracy/farm/issues/820) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
