### ISSUE TITLE
Self-assignment processed 3 times

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#824]
See [here](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373636947) 

I self assigned a task (after I gave myself the ``DEV`` role) and apparently 0crat processed it 3 times. 

1) assigned it to me and deducted 5 points
2) said ``Job gh:amihaiemil/docker-java-api#46 already assigned to @amihaiemil, can't assign to @amihaiemil`` and deducted 5 points
3) said again ``Job gh:amihaiemil/docker-java-api#46 already assigned to @amihaiemil, can't assign to @amihaiemil`` and deducted 5 points

0crat's comments in the ticket are not in the right order, but this is what seems to have happened.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil partial solution added in #830

**Comment by amihaiemil** [comment]
@yegor256 I see; should we leave this open or close?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
