### ISSUE TITLE
Slack: "I don't know who you are..."

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#825]
After [this](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373636947) self assignment (with the weird behaviour described in #824), 0crat also told me on Slack: ``I don't know who you are, please click here: ...`` 5 times; in between these 5 messages it also told me that I lost 5 points (3 times).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it's very difficult to say what happened. For some reason, there were 3 identical claims produced. As if we received GitHub messages three times. I added a block for duplicates in #830. Let me continue to investigate.

**Comment by 0crat** [comment]
The job [#825](https://github.com/zerocracy/farm/issues/825) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/751847102). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by amihaiemil** [comment]
@yegor256 actually, if you ask me, I believe it's useless to have 0crat send messages to Slack at each action... I think Slack should be solely for applying to projects (DEV) and managing the project (PO), but reporting Github assignments, awards etc seems rather useless, everyone is notified via e-mail by Github anyway. I would take it out entirely :)

**Comment by yegor256** [comment]
@amihaiemil this bug is fixed

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#825](https://github.com/zerocracy/farm/issues/825) is now out of scope
