### ISSUE TITLE
Handle changing username in GitHub

### ISSUE THREAD

**Issue by valignatev** [zerocracy/farm#826]
Hi, I've changed my GitHub username recently, and it seems that now I can't log into 0crat anymore. It tells me that I have to go through the invitation process again.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@valignatev This is how it works, see: http://www.zerocracy.com/policy.html#39

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
