### ISSUE TITLE
0crat doesn't assign Issues which are in scope

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#832]
There are 5 open Issues in my repo, which are in scope (1-2 days old) and 0crat did not yet assign them to anyone. There are 2 people on the project, 1 DEV and 1 PO/ARC/DEV -- maybe it's a bug? Since we have an ARC which is also DEV, maybe 0crat is confused? 

**Edit:**
The tasks were assigned after all but still, after 2 days. I think the election/assignment mechanism should still be revised. 2 days is a lot of dead time for a project.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I think we should create some mechanism to inform project ARC and PO about election problems. Sometimes our `elect_performer.groovy` may fail to find the right candidate. And this may happen rather frequently. We have to put these situations into some buffer of "problems" and report to ARC/PO daily or when it seems relevant.

**Comment by amihaiemil** [comment]
@yegor256 yes, it could be an improvement, but only doing that is useless. The only thing they can do when receiving that report is assign manually and this is punished. If you want it to be a real improvement, then there should be no punishments for manual assignment if there are registered problems with the election for that task.

**Comment by yegor256** [comment]
@amihaiemil first, we have to see what is the problem. Now it's not obvious. Maybe all your project members had overfull agendas. Let's first see.

**Comment by g4s8** [comment]
@amihaiemil it should be fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#832` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
