### ISSUE TITLE
bootstrap.groovy:66-68: Let's add project adviser in...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#833]
The puzzle `546-c1316cdf` from #546 has to be resolved:

https://github.com/zerocracy/farm/blob/4dcbd6c1c9f880b75baf2ac1579775fbc18f40d2/src/main/resources/com/zerocracy/stk/pm/bootstrap.groovy#L66-L68

The puzzle was created by rultor on 19-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#833](https://github.com/zerocracy/farm/issues/833) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@0crat boost 2x

**Comment by 0crat** [comment]
> @0crat boost 2x ([here](https://github.com/zerocracy/farm/issues/833#issuecomment-374199006))

@yegor256 Boost 2x was set

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/833#issuecomment-374200227))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#833](https://github.com/zerocracy/farm/issues/833) is [in scope](http://www.zerocracy.com/policy.html#14) for 6hr
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23833%27%7D) (restricted area)

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/farm/issues/833#issuecomment-374200799))

@yegor256 The job [#833](https://github.com/zerocracy/farm/issues/833) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/781253424). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/833#issuecomment-374669718))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#833](https://github.com/zerocracy/farm/issues/833) is [in scope](http://www.zerocracy.com/policy.html#14) for 1days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23833%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 11days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting PR #839 to merge

**Comment by 0crat** [comment]
> @0crat waiting PR #839 to merge ([here](https://github.com/zerocracy/farm/issues/833#issuecomment-377547602))

@g4s8 The impediment for [#833](https://github.com/zerocracy/farm/issues/833) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `546-c1316cdf` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#833](https://github.com/zerocracy/farm/issues/833) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="951459788">
   <created>2018-04-05T14:59:51.142Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:zerocracy/farm#835</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">835</param>
      <param name="comment">378966575</param>
   </params>
   <token>github;zerocracy/farm;835;378966575</token>
   <author>ypshenychka</author>
</claim>

com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="951459788">
   <created>2018-04-05T14:59:51.142Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:zerocracy/farm#835</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">835</param>
      <param name="comment">378966575</param>
   </params>
   <token>github;zerocracy/farm;835;378966575</token>
   <author>ypshenychka</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
