### ISSUE TITLE
0crat didn't add pull request to WBS

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#837]
0crat didn't add this PR https://github.com/zerocracy/farm/pull/805 to WBS, see https://github.com/zerocracy/farm/pull/805#issuecomment-374216684

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it seems that we simply missed the webhook from GitHub, most probably due to the problem with API quota. It's a temporary issue, we can't really fix it.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
