### ISSUE TITLE
People.java:44-47: Let's keep agenda inside `people.xml`...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#841]
The puzzle `552-9d3ef349` from #552 has to be resolved:

https://github.com/zerocracy/farm/blob/28423cccaf280316365df9ec972151ac931cdf76/src/main/java/com/zerocracy/pmo/People.java#L44-L47

The puzzle was created by g4s8 on 10-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#841](https://github.com/zerocracy/farm/issues/841) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/841#issuecomment-393214436))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#841](https://github.com/zerocracy/farm/issues/841), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
The job [#841](https://github.com/zerocracy/farm/issues/841) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1551164781); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait for completion, currently busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait for completion, currently busy on other tasks ([here](https://github.com/zerocracy/farm/issues/841#issuecomment-396089853))

@carlosmiranda The impediment for [#841](https://github.com/zerocracy/farm/issues/841) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@0crat wait for #1251

**Comment by 0crat** [comment]
> @0crat wait for #1251 ([here](https://github.com/zerocracy/farm/issues/841#issuecomment-400159550))

@carlosmiranda Job [#841](https://github.com/zerocracy/farm/issues/841) is already on hold

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #1277

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #1277 ([here](https://github.com/zerocracy/farm/issues/841#issuecomment-401019205))

@carlosmiranda Job [#841](https://github.com/zerocracy/farm/issues/841) is already on hold

**Comment by 0pdd** [comment]
The puzzle `552-9d3ef349` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#841](https://github.com/zerocracy/farm/issues/841) is now out of scope

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/841#issuecomment-400159550), as it's not clear what are you waiting exactly from mentioned PR.

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable
