### ISSUE TITLE
Agenda.java:37-42: Title element, of an order in agenda,...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#843]
The puzzle `422-1711e986` from #422 has to be resolved:

https://github.com/zerocracy/farm/blob/4ffd74260a8ce8c0916af24de5b58d004e6b7e31/src/main/java/com/zerocracy/pmo/Agenda.java#L37-L42

The puzzle was created by amihaiemil on 19-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#843](https://github.com/zerocracy/farm/issues/843) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by proshin-roman** [comment]
@0crat wait for #1095

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/843#issuecomment-393214489))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#843](https://github.com/zerocracy/farm/issues/843), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat wait for #1095  ([here](https://github.com/zerocracy/farm/issues/843#issuecomment-394614351))

@proshin-roman Job [#843](https://github.com/zerocracy/farm/issues/843) is not assigned, can't put it on hold

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@g4s8 Could you assign this ticket back to me, please? So that I can continue with the pull request (it needs a few adjustments). I've refused the ticket myself, but 0crat didn't react to it and then I continued working on this ticket by mistake. Now the pull request is already submitted, but 0crat refused the ticket.

**Comment by 0crat** [comment]
The job [#843](https://github.com/zerocracy/farm/issues/843) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1560942954); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @proshin-roman

**Comment by 0crat** [comment]
> @0crat assign @proshin-roman  ([here](https://github.com/zerocracy/farm/issues/843#issuecomment-394653134))

@g4s8 The job [#843](https://github.com/zerocracy/farm/issues/843) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1561003363); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `422-1711e986` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1105](https://github.com/zerocracy/farm/issues/1105) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#843](https://github.com/zerocracy/farm/issues/843) is now out of scope

**Comment by ypshenychka** [comment]
@proshin-roman According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/843#issuecomment-394614351).

**Comment by proshin-roman** [comment]
@ypshenychka I had to set impediment just because I couldn't resolve the issue in 10 days. But anyway the impediment was not registered by 0crat.

**Comment by ypshenychka** [comment]
@proshin-roman Link is good, but there is no reason said what exactly are you waiting in PR. E.g. "wait for #1095 to be reviewed\merged etc." or any other valid reason.

**Comment by proshin-roman** [comment]
@ypshenychka ok, I see you - going to fix the message then.

**Comment by ypshenychka** [comment]
@proshin-roman Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1152](https://github.com/zerocracy/farm/issues/1152) is still not solved; solved: [#1105](https://github.com/zerocracy/farm/issues/1105).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1105](https://github.com/zerocracy/farm/issues/1105), [#1152](https://github.com/zerocracy/farm/issues/1152).
