### ISSUE TITLE
Limit students based on mentor's reputation

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#844]
Right now we allow up to [16 students](http://www.zerocracy.com/policy.html#1) per mentor. We do not appear to be limiting the number of students regardless if someone has zero or negative reputation.

I suggest we set the number of maximum students based on the mentor's reputation. In the current system new and unknown users can basically swamp the platform with suprious invites. Also, we should expect users with higher reputations to be somewhat more reliable mentors, after all.

Since the [penalty for breakup is 256 points](http://www.zerocracy.com/policy.html#47), my suggestion is to allow 1 student per 256 rep points. So if someone has 256 points, he's allowed 1 student,  512 points, two students, and so on up to a maximum of 16.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@carlosmiranda make sense, but I'm proposing a different formula. First, to invite someone you have to have 1024 reputation (this is already in place). Let's add a price for this operation. Every time you invite someone, you pay, say 128 points.

**Comment by carlosmiranda** [comment]
@yegor256 sounds good to me

**Comment by yegor256** [comment]
@carlosmiranda fixed in 590109022c5f31e59106520b2ff23bd4d73834ee

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by carlosmiranda** [comment]
@yegor256 no payment for raising  this ticket?

**Comment by carlosmiranda** [comment]
@yegor256 ping... why was this ticket not paid? I think I raised a valid concern which was eventually addressed after all.

**Comment by yegor256** [comment]
@carlosmiranda I just considered it as a minor improvement, which was quickly fixed. Not all tickets are paid, as you know. It's a decision of an ARC.

**Comment by carlosmiranda** [comment]
@yegor256 fair enough. Just wanted to know the justification since it was actually addressed somehow. :)
