### ISSUE TITLE
Total points seem to have reset on Personal and Team page

### ISSUE THREAD

**Issue by filfreire** [zerocracy/farm#846]
I had more than 500 points.

Recently I only get a display of 60 points on personal and team page.

Username is `filfreire`

![screenshot_20180320-100601](https://user-images.githubusercontent.com/11976836/37648347-a164d39e-2c26-11e8-88b8-736dd285d72b.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire we remove all points earner earlier than 90 days ago in `refresh_awards.groovy`. Most probably your points were earned some time before that.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
