### ISSUE TITLE
Reputation points removed too early

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#849]
According to the Team page, I lost all my reputation:

![image](https://user-images.githubusercontent.com/6305156/37651513-0b77439c-2c41-11e8-82a3-cee96e8018d5.png)

But it hasn't even been 3 months yet since I work with ZC. Started at the beginning of January and 3 months would be somewhere at the beginning of April. 

I say "according to the Team page" because they are still displayed on my profile page. 

![image](https://user-images.githubusercontent.com/6305156/37651577-389fae72-2c41-11e8-9424-c2b26575305d.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil I think you can't see your reputation on "Team" page because we start caching reputation in https://github.com/zerocracy/farm/pull/790 so it will be updated automatically when you get reputation points, try to find it on your profile page: https://www.0crat.com/u/amihaiemil

**Comment by amihaiemil** [comment]
@g4s8 I don't see how caching could play a role here :D

**Comment by amihaiemil** [comment]
@g4s8 I think it's definetely a bug on the Team page (I don't really understand what the caching you mentioned has to do with it), it's not possible that almost everyone reached 0 now. Besides, I think most of us starter working only in January and there aren't yet 3 months since then.

**Comment by g4s8** [comment]
@amihaiemil I mean that you may see different reputation values on team page and on profile page, on team page reputation will be synchronized after first reputation change

**Comment by amihaiemil** [comment]
@g4s8 but why is my reputation ``-`` on Team page? My reputation should not have changed and, according to your explanation, if it did change and reached 0, I should still see ``1680`` on Team page and it would be ``30`` at my next award.

**Comment by g4s8** [comment]
@amihaiemil on your profile page reputation calculated from your awards: https://www.0crat.com/u/amihaiemil/awards
it's expensive operation for "Team" page, so we added field `reputation` in `people.xml` where we keep all awards on every awards update (claim `Award points were added` see `update_reputation.groovy`). On your next award this value will be updated in `people.xml` and become `1680 + 30` and will be displayed on "Team" page.

**Comment by amihaiemil** [comment]
@g4s8 ah, makes sense now... thanks. Closing this, I'll reopen if it's the case :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
