### ISSUE TITLE
Speed bonus §36 almost unachievable

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#854]
It almost not possible to complete the task less than for 4 hours as in [§36](http://www.zerocracy.com/policy.html#36), because the task should pass not only `DEV` stage, but also CR by `REV`, then PR merge by `ARC`, then response from task author to close, then `QA` review. Each stage may wait for performer about few hours.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 the bonus is not implemented yet, that's for starter. Second, I agree that the timing should be increased. See: https://github.com/zerocracy/zerocracy.github.io/commit/0c800d5301799418c1e1b646f4421c00c52f3efa

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
