### ISSUE TITLE
/team should be visible without login

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#857]
Currently, the Team page requires login:

![image](https://user-images.githubusercontent.com/6305156/37721711-ebe07830-2d32-11e8-8e6d-676aa051c6f7.png)

I suppose it's a bug, it is information that should be public to any possible client (and also Yegor linked it on his article, suggesting that it should be visible to anyone)

**Comment by yegor256** [comment]
@amihaiemil is it so difficult to click "login" and authenticate yourself via GitHub?

**Comment by amihaiemil** [comment]
@yegor256 no, it isn't, but prospective clients, managers, who just want to see the table, do not have a Github account :)

**Comment by yegor256** [comment]
@amihaiemil they are not our friends, if they don't have GitHub accounts :)

**Comment by amihaiemil** [comment]
@yegor256 well, this is a contradiction with what you've told me a few days ago. I suggested that messaging Slack everytime with updates, assignments, awards etc is pointless since everyone receives them from Github... and you said that they might not check (I understood might not have) the Github account. 

If everyone must have a Github account, they will receive notifications from Github... and what's the point in disabling notifications from Github if you are going to be spammed eitherway from Slacl -- at least Github notifications are more organized.

**Comment by amihaiemil** [comment]
@yegor256 Anyway, to not deviate, I really think ``/team`` and maybe other pages as well should be visible without login :D

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
