### ISSUE TITLE
Allow Github user update

### ISSUE THREAD

**Issue by allanwsilva** [zerocracy/farm#861]
If I change my Github user, I should be able to update it in 0crat

Maybe implementing a bot command to allow that? That command would automatically replace the "old" user ID with the new one.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@allanwsilva see http://www.zerocracy.com/policy.html#39 It's impossible :(

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
