### ISSUE TITLE
Never received /join notification

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#863]
More people have filed the /join formular, apparently, yet I have never received any notification even though I've been over 1024 rep for a while

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I hope it's fixed in 3ffa5ec Let's monitor...

**Comment by 0crat** [comment]
The job [#863](https://github.com/zerocracy/farm/issues/863) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/821411067); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#863` already assigned to @yegor256, can't assign to @yegor256

**Comment by yegor256** [comment]
@amihaiemil are you receiving them now? Or still nothing?

**Comment by amihaiemil** [comment]
@yegor256 I receive them now, but as messages on the Slack Zerocracy channel (since you added me there). Otherwise, nothing.  Maybe I should also receive a mail? I mean, are all those > 1024 automatically invited to that channel? I don't think so,

**Comment by amihaiemil** [comment]
@yegor256 Yes, I double-checked now; I only receive them on Zerocracy channel, in the direct chat with ``0crat2``; I neve received them in my own channel, where I also have a direct chat with ``0crat`` + a private chat for project management.

**Comment by yegor256** [comment]
@amihaiemil this is how it should be. The systems picks a random Slack private channel with you and notifies you there. That's it.
