### ISSUE TITLE
Punish mentors if students quit or get kicked out?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#864]
This may make sense, but on the other hand, mentors have no real control -- they could make big efforts to explain the model (actually earning that commision), but it's still up to the student. And it is very hard to know the level of determination and commitment just by exchanging a few emails after the person submits the ``/join`` form.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil the mentor earns money when the student works. So, it's mentor's responsibility to take care of the student. If the student fails, we have to punish the mentor. I think so.

**Comment by amihaiemil** [comment]
@yegor256 the mentor earns, but not for nothing. The mentor is supposed to teach the student (e.g. I imagine I would take part in tickets of my students, advise them where to leave puzzles etc). So after all this, what's the mentor's fault that the student did not want to participate anymore?

**Comment by yegor256** [comment]
@amihaiemil "didn't want to participate" and "failed 10 tickets" are two different things. If the student doesn't want to be with us anymore, he/she just has to go on vacation and that's it. But -256 reputation means that the student really caused a lot of damage to some projects.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#864` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
