### ISSUE TITLE
Add Payoneer as a payment method

### ISSUE THREAD

**Issue by hofmanndavid** [zerocracy/farm#865]
It works in 200 countries and has an API you can use to integrate https://www.payoneer.com/products/integrated-payments-api/

In Paraguay, Paypal doesn't work for receiving money and we have no local Exchangers of crypto-currencies.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@hofmanndavid I emailed them and they refused to accept us. I don't know why.

**Comment by amihaiemil** [comment]
@yegor256 I suppose, if there is no wallet set, the earned money will just stay there, right? Until there is a registered wallet and they can be transfered.

**Comment by yegor256** [comment]
@amihaiemil I don't know about the wallet. I filled out their form, they emailed me back with some questions. I answered them. And then they emailed me a few days later:

<img width="515" alt="screen shot 2018-03-23 at 11 50 38 pm" src="https://user-images.githubusercontent.com/526301/37852805-0a422102-2ef5-11e8-87db-b66a4c90383e.png">

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#865` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
