### ISSUE TITLE
Why -256 on both bootstrap and publish?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#868]
According to the Policy, you get -256 rep for both bootstraping and publishing. I understand the reasoning behind the reputation drop, but I think it is too much, publishing should not drop the reputation, especially since it is understood that 9/10 projects will want to be published on the Board. 

If you think 256 is too little and it all should really cost 512, then I think it should drop with 512 only once, when bootstrapping.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I lowered the cost of publishing down to 32: https://github.com/zerocracy/zerocracy.github.io/commit/44cbf3be8e05d9954e55d7053f5c7802792a6bc4

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
