### ISSUE TITLE
Introduce "tasks for ARC"

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#869]
Assign ARC automatically if the boost factor is over a certain limit.

Original text:

> There are certain tasks in any projects, which only the ARC should take care of (e.g. setting up/fixing CI/CD, writing documentation, doing initial research for a new integration with a service etc)

> I suggest we add a functionality so 0crat knows to assign only the ARC... maybe a new label ,``ARC``, on the issue, which would be added instead of ``bug`` and 0crat then assigns only the architect. 

> This solves the issue of "hot potatoes", ghost tasks which fly around the project and nobody can solve them, everyone just refuses -- we've seen this happen a lot also in Teamed's projects.

> For instance, [this](https://github.com/zerocracy/farm/issues/600) documentation task: I have no idea what are those and probably only the ARC knows, together a small number of DEVs who were there from the beginning of the project.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil conceptually, there should be no imbalance between tasks in a single project. We should not have "complex" tasks and "easy" tasks specially labeled as such. What I can offer is somehow shift focus of `election_performer` towards tasks that are "bugs" or highly boosted (this already happens). 

Maybe we can introduce a new rule: if a task is very much boosted (over 6x), it goes to the ARC of the project, even if the person has too many tasks or so... WDYT?

**Comment by amihaiemil** [comment]
@yegor256 Yes, I believe that should cover most of the situations. I was thinking also of the tasks which require a specific OS and such, but I'll open another issue and discuss it there :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 but 6x seems kind of a high boost factor. Wouldn't 3x be enough? I mean, if tasks should be small and broken with PDD anyway, 6x seems high :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by yegor256** [comment]
@amihaiemil the default boost factor is 1x (15 minutes): http://www.zerocracy.com/policy.html. 6x means 90 minutes. I think it's OK for important tasks.

**Comment by amihaiemil** [comment]
@yegor256 I see, ok

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#869` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
