### ISSUE TITLE
Document the election process

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#870]
The election process is not properly documented. How does it work initially? How do a user's actions influence 0crat's election process? E.g. How would [this](https://github.com/zerocracy/farm/issues/540) task start?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#870](https://github.com/zerocracy/farm/issues/870) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/851349172); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#870` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil explained a bit in 4373e57 Enough?

**Comment by g4s8** [comment]
@amihaiemil ping, please see https://github.com/zerocracy/farm/issues/870#issuecomment-376179361

**Comment by amihaiemil** [comment]
@yegor256 Yes, I think we're good for a start. Thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#870](https://github.com/zerocracy/farm/issues/870) is now out of scope
