### ISSUE TITLE
RnkEstimates

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#875]
Let's create a new rank `RnkEstimates` for `elect_performer.groovy`, which will put the most expensive tasks (according to the information from `Estimates`) on top of the list.

**Comment by 0crat** [comment]
Job [#875](https://github.com/zerocracy/farm/issues/875) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#875](https://github.com/zerocracy/farm/issues/875) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1391548447); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting PR to merge #1034

**Comment by 0crat** [comment]
> @0crat waiting PR to merge #1034  ([here](https://github.com/zerocracy/farm/issues/875#issuecomment-392311868))

@g4s8 The impediment for [#875](https://github.com/zerocracy/farm/issues/875) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 PR #1034 was merged, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#875](https://github.com/zerocracy/farm/issues/875) is now out of scope
