### ISSUE TITLE
0crat failed after QA review and said "QA review is not required"

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#879]
Two failurs happened after QA verdict in #862: https://github.com/zerocracy/farm/pull/862#issuecomment-377336545 and https://github.com/zerocracy/farm/pull/862#issuecomment-377336559.
After that 0crat said "Thanks, but quality review is not required in this job", but awarded points.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#879](https://github.com/zerocracy/farm/issues/879) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job [#879](https://github.com/zerocracy/farm/issues/879) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1561945186); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@ypshenychka it should be fixed already

**Comment by 0crat** [comment]
The job [#879](https://github.com/zerocracy/farm/issues/879) is now out of scope

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
