### ISSUE TITLE
No JDBC connection

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#880]
From https://github.com/zerocracy/farm/issues/680#issuecomment-377445509

JDBC connection required for quartz [JDBC-store ](http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/tutorial-lesson-09.html) to save scheduled jobs info. It should be connected to supported database (Oracle, PostgreSQL, MySQL, MS SQLServer, HSQLDB, DB2), I think it can be connected via Heroku plugins.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 you make a puzzle in this case, not a ticket. There is nothing is broken in master at the moment. Without this JDBC connection the project is perfectly fine. It's only you (and your ticket #680) who needst this. So, it's a puzzle.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#880` is not assigned, can't get performer
