### ISSUE TITLE
Duplicate claim when registering impediment

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#888]
See [here](https://github.com/yegor256/s3auth/pull/370#issuecomment-378276980)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale are you sure the link is correct?

**Comment by llorllale** [comment]
@yegor256 It *did* happen but seems like I confused the url and I don't remember any more.

Closing.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
