### ISSUE TITLE
auto-vacation mode

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#889]
Let's put a user on "vacation" mode automatically if he has over 8 negative point reward lines over the last 16 days and no positive ones. Let's not forget to update the Policy.

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/889#issuecomment-378499159))

@yegor256 The job [#889](https://github.com/zerocracy/farm/issues/889) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/940676732); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 a few clarifications:

* Do we turn off vacation mode automatically also? What is the criteria for that?
* Can the user manually turn off vacation mode?
* When will we trigger the evaluation? I am thinking right after/during points award.

**Comment by carlosmiranda** [comment]
@0crat wait, clarifications regarding task needed

**Comment by 0crat** [comment]
> @0crat wait, clarifications regarding task needed ([here](https://github.com/zerocracy/farm/issues/889#issuecomment-379107134))

@carlosmiranda Can't understand "wait,", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by carlosmiranda** [comment]
@0crat wait for clarifications

**Comment by 0crat** [comment]
> @0crat wait for clarifications ([here](https://github.com/zerocracy/farm/issues/889#issuecomment-379107622))

@carlosmiranda The impediment for [#889](https://github.com/zerocracy/farm/issues/889) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by yegor256** [comment]
@carlosmiranda we just put the vacation mode to ON and that's it. We don't turn it back to OFF. The user should do it manually. We have to `Notify user` about it, explaining why this happened. Yes, I agree, let's trigger it on every points award.

**Comment by carlosmiranda** [comment]
@yegor256 also see PR #948.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1036](https://github.com/zerocracy/farm/issues/1036) is still not solved.

**Comment by carlosmiranda** [comment]
@yegor256 ping, can we close this already?

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#889](https://github.com/zerocracy/farm/issues/889) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1036](https://github.com/zerocracy/farm/issues/1036) is solved here.
