### ISSUE TITLE
_before.groovy:30-35: We have to implement simple slack...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#89]
The puzzle `62-6eaaf140` in [`src/test/resources/com/zerocracy/bundles/notify_in_slack_without_user/_before.groovy`](https://github.com/zerocracy/farm/blob/master/src/test/resources/com/zerocracy/bundles/notify_in_slack_without_user/_before.groovy) (lines 30-35) has to be resolved: "We have to implement simple slack session object to use inside 'notify_in_slack' stakeholder-script and fake object for tests. This session object may wrap `SlackSession` from `com.ullink.slack.simpleslackapi`. After that we should get rid of `Mockito` in this test."

The puzzle was created by g4s8 on 18-Jul-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#89](https://github.com/zerocracy/farm/issues/89) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/410723535). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-366430109))

@neonailol The impediment for [#89](https://github.com/zerocracy/farm/issues/89) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by neonailol** [comment]
@yegor256 puzzle is solved

**Comment by neonailol** [comment]
@0crat out

**Comment by neonailol** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-371759989))

@neonailol GitHub issue is still open, won't close

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-371760078))

@neonailol This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#89](https://github.com/zerocracy/farm/issues/89) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol) for [27days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @neonailol[/z](https://www.0crat.com/u/neonailol) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%2389%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-371760078))

@neonailol This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#89](https://github.com/zerocracy/farm/issues/89) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol) for [27days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @neonailol[/z](https://www.0crat.com/u/neonailol) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @caarlos0[/z](https://www.0crat.com/u/caarlos0): User was resigned from the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%2389%27%7D) (restricted area)

**Comment by neonailol** [comment]
@yegor256 please close this

**Comment by neonailol** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@neonailol but the puzzle is still in the code base. Or I miss something?

**Comment by neonailol** [comment]
@yegor256 oh. sorry, my bad, I saw all these messages about `all puzzles are solved` and was thinking that this is resolved

**Comment by neonailol** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-372595565))

@neonailol The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#89](https://github.com/zerocracy/farm/issues/89), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-373762160))

@amihaiemil The impediment for [#89](https://github.com/zerocracy/farm/issues/89) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-375905030))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#89](https://github.com/zerocracy/farm/issues/89), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#89](https://github.com/zerocracy/farm/issues/89) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/951413044); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-391543882))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#89](https://github.com/zerocracy/farm/issues/89), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat wait - I was too busy with other tasks and now need one more day to resolve this one task.

**Comment by 0crat** [comment]
> @0crat wait - I was too busy with other tasks and now need one more day to resolve this one task. ([here](https://github.com/zerocracy/farm/issues/89#issuecomment-395471114))

@proshin-roman The impediment for [#89](https://github.com/zerocracy/farm/issues/89) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0pdd** [comment]
The puzzle `62-6eaaf140` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#89](https://github.com/zerocracy/farm/issues/89) is now out of scope

**Comment by ypshenychka** [comment]
@neonailol According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/89#issuecomment-366430109).

**Comment by ypshenychka** [comment]
@neonailol ping

**Comment by ypshenychka** [comment]
@neonailol Please consider my above [remark](https://github.com/zerocracy/farm/issues/89#issuecomment-396164606).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1139](https://github.com/zerocracy/farm/issues/1139), [#1140](https://github.com/zerocracy/farm/issues/1140) are still not solved.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1544](https://github.com/zerocracy/farm/issues/1544) is still not solved; solved: [#1139](https://github.com/zerocracy/farm/issues/1139), [#1140](https://github.com/zerocracy/farm/issues/1140).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2282](https://github.com/zerocracy/farm/issues/2282), [#2283](https://github.com/zerocracy/farm/issues/2283), [#2284](https://github.com/zerocracy/farm/issues/2284) are still not solved; solved: [#1139](https://github.com/zerocracy/farm/issues/1139), [#1140](https://github.com/zerocracy/farm/issues/1140), [#1544](https://github.com/zerocracy/farm/issues/1544).
