### ISSUE TITLE
It's impossible to make a donation from non-0crat contributors

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#890]
Steps to reproduce:

1. Logout from 0crat, if logged in
2. Go to some 0crat-managed project, click on the donations badge

Actual result:
- You are being redirected to 0crat, and 0crat asks you to log in

Expected result:
- Stripe form for donations is opened.

Not all the sponsors supposed to have account in 0crat.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@skapral this is by design. To donate you have to be logged in. Why it's a problem?

**Comment by skapral** [comment]
@yegor256 The feature is mostly for the project users, not the project developers. They come outside of the system. Making them register to 0crat just to give you the money is already user-unfriendly enough to frighten them out. Moreover, they even can't register. The only way for them to get to the system is find a mentor. This makes the feature almost useless.

**Comment by yegor256** [comment]
@skapral you don't need to be invited to donate. Just login using GitHub, that's all.

**Comment by skapral** [comment]
@yegor256 Rechecked that. My mistake about the mentor. I am closing this issue for now. I am still hesitant about convenience of the feature though, maybe will come with other issues later.
