### ISSUE TITLE
remove_stale_users.groovy:38-41: At moment user.exists()...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#896]
The puzzle `835-3f8bfc99` from #835 has to be resolved:

https://github.com/zerocracy/farm/blob/90dabfec8849d2c34c56678e5d1fae321274632e/src/main/resources/com/zerocracy/stk/pmo/people/remove_stale_users.groovy#L38-L41

The puzzle was created by g4s8 on 05-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#896](https://github.com/zerocracy/farm/issues/896) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#896](https://github.com/zerocracy/farm/issues/896) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1391550531); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/896#issuecomment-392311843))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#896](https://github.com/zerocracy/farm/issues/896), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#896](https://github.com/zerocracy/farm/issues/896) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1591438739); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by proshin-roman** [comment]
@0crat wait until https://github.com/jcabi/jcabi-github/issues/1370 is fixed

**Comment by 0crat** [comment]
> @0crat wait until https://github.com/jcabi/jcabi-github/issues/1370 is fixed ([here](https://github.com/zerocracy/farm/issues/896#issuecomment-396037189))

@proshin-roman The impediment for [#896](https://github.com/zerocracy/farm/issues/896) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/896#issuecomment-399742982))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#896](https://github.com/zerocracy/farm/issues/896), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#896](https://github.com/zerocracy/farm/issues/896) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1751343200); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `835-3f8bfc99` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#896](https://github.com/zerocracy/farm/issues/896) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
