### ISSUE TITLE
remove GitHub organizations

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#898]
We started at #555

Now there is another problem. Some users may upgrade their GitHub accounts to organizations. We should delete them too. When we see that a user is an organization in GitHub, we notify him and delete in 24 hours.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/898#issuecomment-411289239))

@carlosmiranda The impediment for [#898](https://github.com/zerocracy/farm/issues/898) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 see PR #1689

**Comment by carlosmiranda** [comment]
@yegor256 PR #1689 merged, may we close this now?

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#898](https://github.com/zerocracy/farm/issues/898) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
