### ISSUE TITLE
check GitHub repo existence beforehand

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#899]
Let's check GitHub repo existence before touching it. Otherwise, now we are getting runtime exceptions from jcabi-github.

**Comment by yegor256** [comment]
When this is ready we can continue: https://github.com/jcabi/jcabi-github/issues/1379

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`
