### ISSUE TITLE
Java 8's "Files.exists" should not be used

### ISSUE THREAD

**Issue by VsSekorin** [zerocracy/farm#902]
`FtProject`, `GsProject`, `RdItem`, `S3Item`, `SpyItem`, `Xocument` use `Files#exists`.

> The Files.exists method has noticeably poor performance in JDK 8, and can slow an application significantly when used to check files that don't actually exist.

Sonar rule: https://rules.sonarsource.com/java/RSPEC-3725
Solution: `path.toFile().exists()`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vssekorin[/z](https://www.0crat.com/u/vssekorin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#902](https://github.com/zerocracy/farm/issues/902) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
The job [#902](https://github.com/zerocracy/farm/issues/902) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1411371210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting PR #1039 to merge

**Comment by 0crat** [comment]
> @0crat waiting PR #1039 to merge ([here](https://github.com/zerocracy/farm/issues/902#issuecomment-392265622))

@g4s8 The impediment for [#902](https://github.com/zerocracy/farm/issues/902) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@VsSekorin PR #1039 was merged, can we close?

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/902#issuecomment-394097196))

@g4s8 GitHub issue is still open, won't close

**Comment by g4s8** [comment]
@yegor256 can you close this please? @VsSekorin is not responding

**Comment by yegor256** [comment]
@g4s8 sure

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#902](https://github.com/zerocracy/farm/issues/902) is now out of scope
