### ISSUE TITLE
TkJoin.java:40-51: Requests to /join should add an entry...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#908]
The puzzle `800-10ded7b0` from #800 has to be resolved:

https://github.com/zerocracy/farm/blob/b9f6ac2b2363593ef901d2131721acc6b7a3d454/src/main/java/com/zerocracy/tk/TkJoin.java#L40-L51

The puzzle was created by g4s8 on 26-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#908](https://github.com/zerocracy/farm/issues/908) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#908](https://github.com/zerocracy/farm/issues/908) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562019158); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat waiting PR #1111 to merge

**Comment by 0crat** [comment]
> @0crat waiting PR #1111 to merge ([here](https://github.com/zerocracy/farm/issues/908#issuecomment-395807185))

@g4s8 The impediment for [#908](https://github.com/zerocracy/farm/issues/908) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `800-10ded7b0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147) are still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#908](https://github.com/zerocracy/farm/issues/908) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1146](https://github.com/zerocracy/farm/issues/1146), [#1179](https://github.com/zerocracy/farm/issues/1179) are still not solved; solved: [#1147](https://github.com/zerocracy/farm/issues/1147).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1179](https://github.com/zerocracy/farm/issues/1179), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1352](https://github.com/zerocracy/farm/issues/1352).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1353](https://github.com/zerocracy/farm/issues/1353), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1486](https://github.com/zerocracy/farm/issues/1486).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1353](https://github.com/zerocracy/farm/issues/1353), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1569](https://github.com/zerocracy/farm/issues/1569) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1569](https://github.com/zerocracy/farm/issues/1569) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1645](https://github.com/zerocracy/farm/issues/1645) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1569](https://github.com/zerocracy/farm/issues/1569).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1568](https://github.com/zerocracy/farm/issues/1568), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1649](https://github.com/zerocracy/farm/issues/1649) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1569](https://github.com/zerocracy/farm/issues/1569).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1568](https://github.com/zerocracy/farm/issues/1568), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1666](https://github.com/zerocracy/farm/issues/1666) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1649](https://github.com/zerocracy/farm/issues/1649).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1568](https://github.com/zerocracy/farm/issues/1568), [#1645](https://github.com/zerocracy/farm/issues/1645) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1568](https://github.com/zerocracy/farm/issues/1568), [#1774](https://github.com/zerocracy/farm/issues/1774) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1774](https://github.com/zerocracy/farm/issues/1774), [#1805](https://github.com/zerocracy/farm/issues/1805) are still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1805](https://github.com/zerocracy/farm/issues/1805) is still not solved; solved: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666), [#1774](https://github.com/zerocracy/farm/issues/1774).

**Comment by 0pdd** [comment]
@0pdd all 15 puzzles are solved here: [#1146](https://github.com/zerocracy/farm/issues/1146), [#1147](https://github.com/zerocracy/farm/issues/1147), [#1179](https://github.com/zerocracy/farm/issues/1179), [#1352](https://github.com/zerocracy/farm/issues/1352), [#1353](https://github.com/zerocracy/farm/issues/1353), [#1486](https://github.com/zerocracy/farm/issues/1486), [#1506](https://github.com/zerocracy/farm/issues/1506), [#1552](https://github.com/zerocracy/farm/issues/1552), [#1568](https://github.com/zerocracy/farm/issues/1568), [#1569](https://github.com/zerocracy/farm/issues/1569), [#1645](https://github.com/zerocracy/farm/issues/1645), [#1649](https://github.com/zerocracy/farm/issues/1649), [#1666](https://github.com/zerocracy/farm/issues/1666), [#1774](https://github.com/zerocracy/farm/issues/1774), [#1805](https://github.com/zerocracy/farm/issues/1805).
