### ISSUE TITLE
quartz.properties:1-6: Change jobStore to JDBC to store...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#909]
The puzzle `680-5b4d7868` from #680 has to be resolved:

https://github.com/zerocracy/farm/blob/769b26cfd5dc94588ca9860de157d719cae777ff/src/main/resources/quartz.properties#L1-L6

The puzzle was created by g4s8 on 02-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Job [#909](https://github.com/zerocracy/farm/issues/909) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#909](https://github.com/zerocracy/farm/issues/909) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1000852166); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `680-5b4d7868` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#909](https://github.com/zerocracy/farm/issues/909) is now out of scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`
