### ISSUE TITLE
Zerocrat fails to pay and keeps Closed Issue in Agenda

### ISSUE THREAD

**Issue by SilasReinagel** [zerocracy/farm#910]
Today, an issue with a registered impediment was closed. There are two problems

https://github.com/yegor256/0pdd/issues/133

1. The payment was not made for closing this issue
2. The issue still shows as active on `Agenda` page

![image](https://user-images.githubusercontent.com/10834339/38509639-59e0091a-3bd7-11e8-9621-d5dfb8e17eaa.png)

0crat's message is:

![image](https://user-images.githubusercontent.com/10834339/38509971-5da29e86-3bd8-11e8-8a6a-95f9f9662e35.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by SilasReinagel** [comment]
@yegor256 The message is fine but the behavior is wrong.

From 0crat policy:

```
§7 “Definition of Done.” A job is completed when its ticket is closed. Until then only one person is responsible for it: the performer. It doesn’t matter why the job is not finished, who its success depends on, where is the problem. The 0/100 rule is simple: it’s either done or not.
```

The ticket is closed, but 0crat has done treated it as done. This is a behavior flaw in 0crat. Closed ticket should result in payment and removal from Agenda.

**Comment by yegor256** [comment]
@SilasReinagel but Zerocrat explained that the closer of the ticket is not its author. And asked the author to reopen.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#910` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
