### ISSUE TITLE
Join form is broken: I submitted the form with the necessary info, but no notification was sent to high-rep users

### ISSUE THREAD

**Issue by izrik** [zerocracy/farm#914]
I navigated to `https://www.0crat.com/join`, filled in my information, and clicked the `Submit` button. My browser was then redirected to `https://www.0crat.com/`, with a green information banner that read "The request has been sent to all high-ranked users". However, in the Telegram chat, Kirill and yegor256 both said that they did not receive any such request. I expect the request to be sent to the high-rep users, so that they could properly review my request. I didn't find any other open issues like this in the repo.

I have attached screen shots of the page:
![1-izrik-join-form](https://user-images.githubusercontent.com/1711679/38567157-1887fb06-3cab-11e8-8358-e1602ff3ddc5.png)
![2-izrik-join-form-after-submitting](https://user-images.githubusercontent.com/1711679/38567156-18730336-3cab-11e8-8d72-bb1b3cd9434e.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@izrik it seems that it was a problem with Telegram API. They were not allowing us to post anything, for some reason...

**Comment by izrik** [comment]
@yegor256 Ok. Should I re-submit the form then?

**Comment by yegor256** [comment]
@izrik you are right, fixed.
