### ISSUE TITLE
Policy says points are gained for Refuse Job. 0crat takes away points.

### ISSUE THREAD

**Issue by SilasReinagel** [zerocracy/farm#916]
From the 0crat policy:

> §6 “Refusal.” You may refuse to complete any job by saying refuse. You will get 15 points for that.

From 0crat upon refusal:

> You got -15 point(s) in the job #105 (https://github.com/yegor256/0pdd/issues/105) in PDD (https://www.0crat.com/p/C3T46CUJJ), your total is +30 (https://www.0crat.com/u/silasreinagel/awards), see §18 (http://www.zerocracy.com/policy.html#18): Tasks refusal is discouraged, see §6 (http://www.zerocracy.com/policy.html#6)

Points should be refunded and policy or behavior should be fixed.

**Comment by amihaiemil** [comment]
@SilasReinagel Policy needs to be edited, the behaviour is correct. You get -15 points since refusing jobs is discouraged.

**Comment by SilasReinagel** [comment]
@amihaiemil Okay, makes sense. So, should I open a new ticket to enable refund of points when Zerocracy software or policy has a bug?

**Comment by amihaiemil** [comment]
@SilasReinagel I think that's a good idea, although hard to implement in the current architecture of it, I believe. Nevetheless, you can rename this Issue and edit its description, so the Policy gets updated here. Let's wait for Yegor (I am not an ARCH, I cannot accept the ticket).

**Comment by yegor256** [comment]
@SilasReinagel I explained the policy: https://github.com/zerocracy/zerocracy.github.io/commit/e52747d8cdedb55c07ed28c04bd5c62adbdcda5d

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
