### ISSUE TITLE
rebills

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#917]
Let's implement them

**Comment by yegor256** [comment]
it was started here: https://github.com/zerocracy/datum/issues/325

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1257](https://github.com/zerocracy/farm/issues/1257) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1543](https://github.com/zerocracy/farm/issues/1543) is still not solved; solved: [#1257](https://github.com/zerocracy/farm/issues/1257).
