### ISSUE TITLE
Notify Team members about the new projects on the Board

### ISSUE THREAD

**Issue by driver733** [zerocracy/farm#918]
Let's give all team members an option to sign up for notifications (in Telegram or Slack) about the new projects posted on the "Board". The Telegram and Slack should have commands such as `new_projects_updates on` and `new_projects_updates off`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@driver733 we have this already. Once a new project gets into the board, everybody (who is over 256) get a notification.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
