### ISSUE TITLE
0crat ignores debt on new payment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#921]
If 0crat has some debt to me (e.g. $5) which can't be sent because it's to small, and I'm receiving bigger payment (e.g. $30) 0crat will skips this $5 and just sends me $30. I think it should accumulate payments from debts and new payment and send them together as $35 payment.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#921](https://github.com/zerocracy/farm/issues/921) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1020815165); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#921` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 do you want to complete this job, or I can reassign it?

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@g4s8 reassign it pls

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-404196744))

@yegor256 The user @yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#921](https://github.com/zerocracy/farm/issues/921), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#921](https://github.com/zerocracy/farm/issues/921) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1971104010); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#921` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat status

**Comment by paulodamaso** [comment]
@0crat wait for #1428 (from #565 , make payment is not fully testable yet)

**Comment by 0crat** [comment]
> @0crat wait for #1428 (from #565 , make payment is not fully testable yet) ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-407269286))

@paulodamaso The impediment for [#921](https://github.com/zerocracy/farm/issues/921) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
> @0crat wait for #1428 (from #565 , make payment is not fully testable yet) ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-407269286))

@paulodamaso Job [#921](https://github.com/zerocracy/farm/issues/921) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't set impediment

**Comment by paulodamaso** [comment]
@g4s8 Please take a look at this, 0crat looks lost.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-407304744))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#921](https://github.com/zerocracy/farm/issues/921) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23921%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@paulodamaso this job is assigned to you and impediment was registered, but looks like it fails to add this job to your agenda because of duplicate claim error. We are going to fix such issues when we migrate claim system to Amazon SQS queues.

**Comment by paulodamaso** [comment]
@0crat wair for #1626 review

**Comment by 0crat** [comment]
> @0crat wair for #1626 review ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-414542730))

@paulodamaso Can't understand "wair", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by paulodamaso** [comment]
@0crat wait for #1626 review

**Comment by 0crat** [comment]
> @0crat wait for #1626 review ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-414544371))

@paulodamaso Job [#921](https://github.com/zerocracy/farm/issues/921) is already on hold

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1647](https://github.com/zerocracy/farm/issues/1647) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso done, thanks

**Comment by 0crat** [comment]
Job [#921](https://github.com/zerocracy/farm/issues/921) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#921](https://github.com/zerocracy/farm/issues/921) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#921](https://github.com/zerocracy/farm/issues/921) is now out of scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/921#issuecomment-416009902))

@paulodamaso This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#921](https://github.com/zerocracy/farm/issues/921) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2days
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23921%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka please take a look, looks like 0crat forgot to notify you

**Comment by ypshenychka** [comment]
@paulodamaso thanks! looking into it

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1647](https://github.com/zerocracy/farm/issues/1647) is solved here.
