### ISSUE TITLE
resign phantom users

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#924]
Let's regularly go through all roles in each project and check whether users are still in `people.xml`. If they are not, we should resign them automatically from all roles in the project and terminate their orders.

**Comment by 0crat** [comment]
Job [#924](https://github.com/zerocracy/farm/issues/924) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait (too many tasks)

**Comment by 0crat** [comment]
> @0crat wait (too many tasks) ([here](https://github.com/zerocracy/farm/issues/924#issuecomment-411289267))

@carlosmiranda The impediment for [#924](https://github.com/zerocracy/farm/issues/924) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 see PR #1685

**Comment by carlosmiranda** [comment]
@yegor256 PR #1685 merged, may we close this now?

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#924](https://github.com/zerocracy/farm/issues/924) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
