### ISSUE TITLE
Assignments are broken: 0crat assigns more jobs than allowed by stated policy

### ISSUE THREAD

**Issue by izrik** [zerocracy/farm#926]
From [/u/izrik](https://www.0crat.com/u/izrik):
> Your currently open jobs: 5 (max allowed: 3)

I am currently assigned 5 jobs, when the [policy states that the max should be 3](http://www.zerocracy.com/policy.html#3).I expected that the number of assigned jobs would not exceed the state policy. They are all `DEV` jobs, none are reviews, so the exception for code reviews doesn't factor into it (c.f. https://github.com/zerocracy/farm/issues/488).

If the policy changed, then the text needs to be updated on the policy page. If not, then 0crat is assigning too many jobs and needs to be fixed.

![too-many-jobs](https://user-images.githubusercontent.com/1711679/38718207-799fa7b0-3eb1-11e8-8fe5-96e5fdd8f822.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@izrik can you how your agenda please? I need to understand in how many projects you have jobs.

**Comment by 0crat** [comment]
Job [#926](https://github.com/zerocracy/farm/issues/926) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @izrik[/z](https://www.0crat.com/u/izrik)

**Comment by yegor256** [comment]
@izrik that's what I expected. You are a member of three projects. And you were elected for tasks there at the same time. The election mechanism didn't know that you have anything in the agenda and assigned too many to you. We need to add some mechanism of synchronization between projects... I'm not sure yet.

**Comment by 0crat** [comment]
The job [#926](https://github.com/zerocracy/farm/issues/926) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562023321); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@izrik 2 puzzles [#1388](https://github.com/zerocracy/farm/issues/1388), [#1389](https://github.com/zerocracy/farm/issues/1389) are still not solved.

**Comment by g4s8** [comment]
@izrik the problem here was that you coud be elected to multiple jobs before assigned to them, so agenda check didn't help. I added additional check to prevent "over-election" (situation when you was  elected but not assigned) for one project and added todo to for cross-project fix. Can we close then?

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#926](https://github.com/zerocracy/farm/issues/926) is now out of scope

**Comment by 0pdd** [comment]
@izrik the puzzle [#unknown]() is still not solved.
