### ISSUE TITLE
Still don't like PMO abstraction

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#927]
After looking around more, I still can't wrap my head around why we have the PMO Project. 

The way I understand it PMO is zerocracy/farm itself, and in the codebase, PMO implements Project because we want ZC to be able to manage itself (e.g. be iterated together with the other Projects) and at the same time have access to configuration data/properties. 

But why can't we separate this? It is really a forced abstraction. Instead, /farm should be a Project like any other and PMO should be a different abstraction... or is it wanted that, at code level, /farm have different treatments? Why would that be?

It is like Rultor would have a separate abstraction for itself, instead of managing its own repo as any other.

Like it is now, all the logic is polluted with checks for PMO, it is hard to understand and bugs are easily introduced.

**Comment by yegor256** [comment]
@amihaiemil PMO has everything any other project has: claims, artifacts, synchronization, everything. How would you suggest to design it differently?

**Comment by amihaiemil** [comment]
@yegor256 Yes, it does have all that, but it is zerocracy/farm itself, represented by zerocracy/farm in its code, it doesn't make sense. Don't you see the twist?

/farm works with Projects from Github. In the code, /farm represents itself as a Project, from which it extracts its own properties and configuration. That's how I understand it.

**Comment by yegor256** [comment]
@amihaiemil I don't understand. The way it now seems clear to me. We have projects. One of them is PMO. That's all.

**Comment by amihaiemil** [comment]
@yegor256 It is not clear, because all the codebase is polluted with forks! 

The only difference between PMO and another Project is that PMO has something all the others don't -- yet it implements the same interface and always has to be treated specifically. This alone, means it should not implement Project :(

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
