### ISSUE TITLE
Hiring message does not include project id to apply

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#929]
`Par` replaces project id with project title automatically, so a person can't see project id which he/she needs to apply (`apply <project-id> <rate>`).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed in f54b8bc5 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
