### ISSUE TITLE
Telegram doesn't work anymore

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#931]
To my knowledge, we didn't change anything in our code. But Telegram doesn't work anymore. Let's test and fix.

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by yegor256** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031708035">
   <created>2018-04-13T17:08:29.183Z</created>
   <type>Set boost</type>
   <params>
      <param name="factor">4x</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381200893</param>
   </params>
   <token>github;zerocracy/farm;931;381200893</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031708035">
   <created>2018-04-13T17:08:29.183Z</created>
   <type>Set boost</type>
   <params>
      <param name="factor">4x</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381200893</param>
   </params>
   <token>github;zerocracy/farm;931;381200893</token>
   <author>yegor256</author>
</claim>

com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031708035">
   <created>2018-04-13T17:08:29.183Z</created>
   <type>Set boost</type>
   <params>
      <param name="factor">4x</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381200893</param>
   </params>
   <token>github;zerocracy/farm;931;381200893</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031709049">
   <created>2018-04-13T17:09:45.919Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">g4s8</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381201225</param>
   </params>
   <token>github;zerocracy/farm;931;381201225</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031709049">
   <created>2018-04-13T17:09:45.919Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">g4s8</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381201225</param>
   </params>
   <token>github;zerocracy/farm;931;381201225</token>
   <author>yegor256</author>
</claim>

com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1031709049">
   <created>2018-04-13T17:09:45.919Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">g4s8</param>
      <param name="job">gh:zerocracy/farm#931</param>
      <param name="repo">zerocracy/farm</param>
      <param name="issue">931</param>
      <param name="comment">381201225</param>
   </params>
   <token>github;zerocracy/farm;931;381201225</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/931#issuecomment-381200893))

@yegor256 Boost 4x was set for [#931](https://github.com/zerocracy/farm/issues/931)

**Comment by g4s8** [comment]
It may be related:
```
IllegalStateException: Session already running
    at com.zerocracy.entry.ExtTelegram.lambda$static$0(ExtTelegram.java:46)
    at com.zerocracy.entry.ExtTelegram.value(ExtTelegram.java:72)
    at com.zerocracy.entry.Main.exec(Main.java:116)
    at com.zerocracy.entry.Main.main(Main.java:81)
...
```

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/931#issuecomment-381200893))

@yegor256 Current boost factor of [#931](https://github.com/zerocracy/farm/issues/931) is 4x, nothing changed

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zerocracy/farm/issues/931#issuecomment-381200893))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/elections/invalidate_all_elections.groovy
sun.reflect.GeneratedMethodAccessor157[-1] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by yegor256** [comment]
@g4s8 I see this in logs:

```
java.lang.NoSuchMethodError: org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(Ljava/util/List;)V
    at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:311)
```

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/931#issuecomment-381204357))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#931](https://github.com/zerocracy/farm/issues/931) is [in scope](http://www.zerocracy.com/policy.html#14) for 16min
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [10min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23931%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 should be fixed in #932

**Comment by yegor256** [comment]
@g4s8 I guess we need an integration test (which we had some time ago, but deleted)

**Comment by g4s8** [comment]
@yegor256 yes, I submitted a bug some time ago, it's in WBS now: https://github.com/zerocracy/farm/issues/528

**Comment by yegor256** [comment]
@g4s8 oops, my bad, fixed: b64dbd6

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da044789-3a52-46a3-9276-7cb0d37b26bd, thread: BkParallel-6
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#931](https://github.com/zerocracy/farm/issues/931) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/farm/issues/931#issuecomment-381203025) by indicating an addressee in the beginning.

**Comment by g4s8** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@g4s8 Thanks

**Comment by ypshenychka** [comment]
@g4s8 The quality of ticket will be bad as the job was closed without a soultion provided. Agree?

**Comment by g4s8** [comment]
@ypshenychka not in full, there were two different issues in this bug, I found only one (related to this stacktrace: https://github.com/zerocracy/farm/issues/931#issuecomment-381206154) and fixed it in #932 PR, then @yegor256 fixed another issue in commit b64dbd63932c56e208c962075aab92e2c7fbb8fa

**Comment by ypshenychka** [comment]
@g4s8 OK, I see. Thanks for clarification.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a76ab069-1a31-44c1-a9e4-d0654d38fb62, thread: BkParallel-3
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a76ab069-1a31-44c1-a9e4-d0654d38fb62, thread: BkParallel-3
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
