### ISSUE TITLE
0crat assigns reviewer to a hijacked PR 

### ISSUE THREAD

**Issue by Vatavuk** [zerocracy/farm#937]
0crat assigns a reviewer to a PR which is not created by a person who owns this job.
[Link](https://github.com/yegor256/cactoos/pull/767) to PR which is supposed to be solved by @flslkxtc for [issue ](https://github.com/yegor256/cactoos/issues/764).

**Comment by g4s8** [comment]
@Vatavuk issue and PR are independent entities, 0crat is not linking them.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#937` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
