### ISSUE TITLE
Zerocracy should handle gracefuly an unwanted resignation by delay

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#938]
The following situation happened:
 - User U got an issue assigned
 - U did the job and made a PR
 - the review took some time
 - U forgot to ask 0crat to wait
 - 0crat resigned U from the job after the 10 days delay

This situation will obviously arise more than once (for various reasons, in U's case, it was because he was busy and didn't see the time pass between the last warning and the deadline).

There are two possible ways to handle that:
1. too bad for U, U should have respected the letter of rules even though their spirit was respected
2. it happens, the situation should be fixed

This issue concerns 2 simply because I think it is unrealistic to be so uncompromising: the system should adapt to humans, no the opposite.

So this is what happened next:
 - U bothered the architect of the project until it reassigned U to the issues
 - the architect lost some time to do some management
 - U lost some points

I think it is normal for U to be punished by loosing some points, but it is not normal that so much time was lost be people around this question. Worst, maybe 0crat would have assigned the issue to another user inbetween, and then the overhead would have been even bigger.

I'm not sure how to fix this. Maybe there should be some way to put 0crat on pause after a drastic decision is taken and ask for arbitration by a third party (QA maybe?).
Drastic could be defined as "money will be potentially lost".

Or maybe 0crat should know about PRs that are open and related to the ticket and act different in that case? But I'm worried there will always be cases when some situations like this won't be taken into account by 0crat as expected.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@victornoel @yegor256 maybe we should notify in Telegram/Slack about these jobs (assigned more than 5 days), not only in Github?

**Comment by victornoel** [comment]
@g4s8 IMHO, the point of having a bot is to reduce noise, efforts and overhead. We already have lots of emails, and I think that if we add to that messages in the chat, there is even more chances that they will be ignored (like I did).

The solution should at the same time avoid any effort/noise/overhead when things go well, and limit efforts when things go wrong.

That's a major problem in IA (false negative and false positive) and there is always a tradeoff to make. With 0crat being more and more "intelligent", I predict that this question is going to be a challenge.

**Comment by yegor256** [comment]
@victornoel I'm sure we had a similar question before, can't find it. There is not really a solution. We can't break the rule we have: 0/100. We can't take into account anything that is happening inside a ticket. It's either complete or not. What exactly do you suggest?

**Comment by victornoel** [comment]
@yegor256 I agree with you, but I'm not talking about changing the rules. My point is  that any automated action by a bot will eventually lead to an unwanted (for everyone) situation.

My suggestion is that the system could take this into account so that when it happens, it's not a big problem for the people involved.
One idea I proposed in the description of the issue is to have a way, for a subset of all 0crat's actions, by the person involved with this action, to challenge it. Then have a role (QA maybe? ARC?), for a user that is not involved with the action, that statute on it to correct the problem.

It's an idea because I forecast this kind of problem when more people come, II'm not worried about myself.

Another solution is of course to continue as it is but when money is involved, it's going to create problems. What if the PR of a person that got resigned from a job is merged? You will have to resolve this manually and it will take more time than if you have a way to solve this early.

**Comment by yegor256** [comment]
@victornoel 

> One idea I proposed in the description of the issue is to have a way, for a subset of all 0crat's actions, by the person involved with this action, to challenge it. Then have a role (QA maybe? ARC?), for a user that is not involved with the action, that statute on it to correct the problem.

I don't understand. Please, be more specific. What exactly should be done?

**Comment by victornoel** [comment]
@g4s8 for the record, this happened again, see #1373, I think something should be done at least to better inform users of this, maybe add an extra sentence when 0crat says that 5 days has passed:
```
@user/z this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see §8. Read this and this, please. If you started working on it, you can put it on hold by saying wait.
```

Or something like that :)

**Comment by yegor256** [comment]
@victornoel I don't think I like this. I don't like compromises in general. If it's off, it's off.

**Comment by victornoel** [comment]
@yegor256 np, it seemed more important at the time that it feels right now anyway :)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#938` is not assigned, can't get performer
