### ISSUE TITLE
Viber radar

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#939]
Let's implement Viber radar, similar to what we have for Telegram. https://developers.viber.com/docs/api/rest-bot-api/

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/939#issuecomment-381903441))

@yegor256 The job [#939](https://github.com/zerocracy/farm/issues/939) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1070882254); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait , currently busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait , currently busy on other tasks ([here](https://github.com/zerocracy/farm/issues/939#issuecomment-383419632))

@carlosmiranda The impediment for [#939](https://github.com/zerocracy/farm/issues/939) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@yegor256 see PR #1001

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1070](https://github.com/zerocracy/farm/issues/1070), [#1071](https://github.com/zerocracy/farm/issues/1071), [#1072](https://github.com/zerocracy/farm/issues/1072) are still not solved.

**Comment by carlosmiranda** [comment]
@yegor256 #1001 has been merged, can we close this now?

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#939](https://github.com/zerocracy/farm/issues/939) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1070](https://github.com/zerocracy/farm/issues/1070), [#1071](https://github.com/zerocracy/farm/issues/1071) are still not solved; solved: [#1072](https://github.com/zerocracy/farm/issues/1072).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1071](https://github.com/zerocracy/farm/issues/1071) is still not solved; solved: [#1070](https://github.com/zerocracy/farm/issues/1070), [#1072](https://github.com/zerocracy/farm/issues/1072).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1449](https://github.com/zerocracy/farm/issues/1449) is still not solved; solved: [#1070](https://github.com/zerocracy/farm/issues/1070), [#1071](https://github.com/zerocracy/farm/issues/1071), [#1072](https://github.com/zerocracy/farm/issues/1072).
