### ISSUE TITLE
Tweet is missing Github repo link

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#940]
Currently, 0crat is tweeting about projects which are in need of developers: https://twitter.com/0crat/status/986312456334176257

The tweet should contain the Github repo link, rather than the 0crat.com one, because it is not accessible to those who are not members, even if we are logged in. I am logged in and get the orange banner: "You are not a member of C3T46CUJJ"

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#940](https://github.com/zerocracy/farm/issues/940) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1081157200); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#940` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil it's fixed, now you can see the project, even if being a non-member. But only if it's published on the board.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#940](https://github.com/zerocracy/farm/issues/940) is now out of scope
