### ISSUE TITLE
Problem in zerocrat telegram chat

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#941]
Zerocrat asked to make this bug report here:

There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@3240236f-eb34-475e-b7b0-614f79eff8ee, thread: zerocrat_bot Telegram Executor
com.zerocracy.radars.Question[143] java.lang.IllegalStateException: The question doesn't match, you can call invited().

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
Same issue for me, I can't apply to any project because of this.

**Comment by 0crat** [comment]
The job [#941](https://github.com/zerocracy/farm/issues/941) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1081237998); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#941` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@paulodamaso I believe it's fixed, please confirm and close.

**Comment by paulodamaso** [comment]
Fixed.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c0ff7e3-e0b9-4bc8-930d-80f60a6be371, thread: BkParallel-7
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#941](https://github.com/zerocracy/farm/issues/941) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
