### ISSUE TITLE
Master is broken (Qulice)

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#943]
Master branch can't pass Qulice validation because of error:
```
Checkstyle: src/main/java/com/zerocracy/pmo/GoodPeople.java[72]: Line is longer than 80 characters (found 81). (LineLengthCheck)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 hm... that's an encoding problem, since it's not broken on my machine.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@yegor256 Rultor failed to merge 2 PRs with this error: 
https://github.com/zerocracy/farm/pull/897#issuecomment-382361942
and
https://github.com/zerocracy/farm/pull/881#issuecomment-381972230
looks like it started to fail after c8286fa364af2e5673ecf41cd7beab57eb9fb4f3 commit.

**Comment by yegor256** [comment]
@g4s8 I guess it's fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
