### ISSUE TITLE
setting rate with currency is broken

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#945]
1. `/rate` command description should mention the format of the rate including all the supported currencies, right now it only gives example in dollars, which is `rate $25`, but according to http://www.zerocracy.com/policy.html#16 it is possible to use EUR, GPB and JPY.

Using just `/rate` should give an explanation like:
```
Your rate is $16.00. To change it just say rate <currency_symbol><amount>, for example rate $25 or rate €25.
```

2. `/rate` should support also providing the rate without using the currency symbol but using the abbreviation of currency, so I should be able to do:
`/rate 25 USD` or `/rate 25 EUR` etc.

The help text should change to:
```
Your rate is $16.00. To change it just say rate <currency_symbol><amount> or rate <amount> <currency_abbreviation>, for example rate $25 or rate €25 or rate 25 USD or rate 25 GBP.
```

Why? Because not all keyboards have the symbol for given currency (e.g. my natural rate would be in Euro, but I don't have Euro symbol on my keyboard, I need to look it up on the web and copy paste).

3. Any format that is not supported by 0crat should print the help text of the `/rate` (besides the error message).
Right now it is not the case:
request: `/rate 42`
reply: `Can't parse "42"`
reply should be: 
```
Can't parse "42"
To change it just say rate <currency_symbol><amount> or rate <amount> <currency_abbreviation>, for example rate $25 or rate €25 or rate 25 USD or rate 25 GBP.
````

request: `/rate 42USD`
reply: `Can't parse cash value pair "42USD"`
reply should be:
```
Can't parse cash value pair "42USD".
To change it just say rate <currency_symbol><amount> or rate <amount> <currency_abbreviation>, for example rate $25 or rate €25 or rate 25 USD or rate 25 GBP.
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@yegor256 This would also help in the future if you would introduce new currencies, not all of them have a single char symbol, but all of them have an three letter code (ISO 4217).

**Comment by 0crat** [comment]
The job [#945](https://github.com/zerocracy/farm/issues/945) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1140844398); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#945` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@krzyk I believe it's fixed, please try

**Comment by krzyk** [comment]
@yegor256 OK works, but I had to try out, for `/rate` I got following response:
```
Your rate is $42.00; to change it just say rate $25, for example; you can format the rate differently, see §16
Zerocracy
Policy
Policy of Zerocrat, a project manager
that never sleeps, owned and maintained by Zerocracy.
```

So I went to [§16](http://www.zerocracy.com/policy.html#16) and there I see:
> §16 “Rate.” To make money in any project you must define your hourly rate. To do that just say rate to Zerocrat. This rate is for marketing purpose only, since each project will set their own rates for you. Your rate can only be between $16 and $256. You can use USD, EUR, GBP, or JPY, but all payments will be made in USD (converted by apilayer).

So still no info how to format the `/rate` command, so I tried `/rate 42 USD` (which seamed natural to me) and got:
```
Can't parse "42"; use $25 or 18.50RUR or 25EUR or 18GBP
```

Which finally got me the format I need to use - I think it is quite a long way, I would expect to see this e.g. in `/rate` command first.

And BTW, the ISO code should be separated by a space from the number, it is usually written like: `42 USD` or `USD 42` (depends on the country/language, but there is alwasy space between those).

**Comment by yegor256** [comment]
@krzyk explained: https://github.com/zerocracy/zerocracy.github.io/commit/866256e97692e966cdd45e8b552f536a8482af81

**Comment by yegor256** [comment]
@krzyk I believe it's fixed: 4917c7226d7eb7d696eef2a94a686bffa29b2e6f

**Comment by krzyk** [comment]
@yegor256 cool, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#945](https://github.com/zerocracy/farm/issues/945) is now out of scope
