### ISSUE TITLE
Documentation issue in Stripe class

### ISSUE THREAD

**Issue by skapral** [zerocracy/farm#946]
https://github.com/zerocracy/farm/blob/61145b72632a429902d4be52be124c4ee79e7a16/src/main/java/com/zerocracy/pmo/recharge/Stripe.java#L60-L70

Isn't it wrong method description?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@skapral thanks, fixed in https://github.com/zerocracy/farm/commit/17f02ff7b6e858fc3c5abf4672b8933a27a80123

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#946` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
