### ISSUE TITLE
0crat messages are broken: when quitting a project, messages from 0crat contradict stated policy

### ISSUE THREAD

**Issue by izrik** [zerocracy/farm#947]
I resigned from a project by telling 0crat `quit <project id>` in Telegram. He responded by saying that I was no longer in the project and that I was resigned from the two tasks in the project that I had been assigned. In particular, he said "please stop working". However, this directly contradicts the [policy page, section 35](http://www.zerocracy.com/policy.html#35), where it says "You can always quit a project, just say quit to Zerocrat. You will still have to _finish the jobs_ assigned to you in the project.". Furthermore, 0crat did not add any comments to the github tickets for the jobs stating that they were no longer assigned to me.

If the _intention_ is that the developer complete the tasks, even though he is no longer on that project, then the messages from 0crat in Telegram should be changed to say so, instead of saying that the developer resigned from the jobs. However, if the intention is that the developer _not_ work on the tasks any more, then the policy page should be changed to say that.

![izrik-quit-job-stop-working](https://user-images.githubusercontent.com/1711679/38972133-6c2b0c84-4364-11e8-88d9-5eaf6e3f059c.png)

![policy-quit-finish-the-jobs](https://user-images.githubusercontent.com/1711679/38972125-66193ac8-4364-11e8-85df-ad1c9be7d4e3.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@izrik[/z](https://www.0crat.com/u/izrik) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@izrik it was fixed already, see https://www.zerocracy.com/policy.html#35

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#947` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
