### ISSUE TITLE
It is unclear what grayed out means in the team page

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#951]
On the team page (https://www.0crat.com/team) some of the team members are grayed out.
I can only assume it means they are on vacation, right?
If yes then it should be clearly marked as such:

Add a hover over when mouse moves over a given users row and show: `@someone is on vacation since 2018-01-01`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@krzyk fixed in 3d69dd8faa1bb1a36fd3ded8d3b448d0d02ed253 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
