### ISSUE TITLE
Public and private projects

### ISSUE THREAD

**Issue by artem-p** [zerocracy/farm#955]
Seems like projects in Zerocracy can be public or private. There is no mention of it in the Policy. For example, it is evident that Takes project manages by Zerocracy, but I don't see it on my board. I would like to know exactly that private projects exists, why I don't see them on my board, what should I do to apply to them etc.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@artem-p[/z](https://www.0crat.com/u/artem-p) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@artem-p only published projects are displayed on board, it's PO decision to display or not the project on board. To display, `publish` command can be used in PM Slack channel

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#955` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
