### ISSUE TITLE
TkJoin.java:40-43: We should allow user to send `/join`...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#956]
The puzzle `653-b9d34fcf` from #653 has to be resolved:

https://github.com/zerocracy/farm/blob/2d5997a5340b9cd38d032b590a21a9892a574789/src/main/java/com/zerocracy/tk/TkJoin.java#L40-L43

The puzzle was created by g4s8 on 01-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#956](https://github.com/zerocracy/farm/issues/956) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#956](https://github.com/zerocracy/farm/issues/956) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562028507); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `653-b9d34fcf` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#956](https://github.com/zerocracy/farm/issues/956) is now out of scope
