### ISSUE TITLE
Notification of job was assigned 5 days ago

### ISSUE THREAD

**Issue by VsSekorin** [zerocracy/farm#958]
I did not get notification of new task from 0crat bot when this task was assigned to me. If it has been more than 5 days, 0crat should send a re-notification. Since usually this means some problems.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vssekorin[/z](https://www.0crat.com/u/vssekorin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
