### ISSUE TITLE
Issue closing #941

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#959]
Zerocrat notified an error when I closed #941 

PID: 4@9c0ff7e3-e0b9-4bc8-930d-80f60a6be371, thread: BkParallel-7
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@paulodamaso should be fixed already

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#959` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
