### ISSUE TITLE
Documentation issue of zerocrat telegram and github commands

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#960]
Couldn't find comprehensive documentation about telegram and github commands; maybe you should have a help page in https://www.0crat.com/

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso just say `help` to Zerocrat and you will get a full help.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
