### ISSUE TITLE
SyncFarmTest.java:124-127: Method freeze should wait for...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#963]
The puzzle `476-cbedeee7` from #476 has to be resolved:

https://github.com/zerocracy/farm/blob/d519e8dae3a2d8add27ea861b94739d17d387d22/src/test/java/com/zerocracy/farm/sync/SyncFarmTest.java#L124-L127

The puzzle was created by g4s8 on 23-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#963](https://github.com/zerocracy/farm/issues/963) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#963](https://github.com/zerocracy/farm/issues/963) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562030608); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `476-cbedeee7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#963](https://github.com/zerocracy/farm/issues/963) is now out of scope
