### ISSUE TITLE
Estimates are not recalculated after rate change

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#964]
If user was added to a project with zero rate, then some task was assigned to him and then his rate was changed, estimate for this task will not be updated. I think it's not clear for user and estimate should be updated when rate changed.

**Comment by yegor256** [comment]
@g4s8 this by design. We don't update estimates of previous tasks, see: https://github.com/zerocracy/zerocracy.github.io/commit/aed86af7c04a0c6bd58498b71af30b34b6b1082b

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
