### ISSUE TITLE
0crat throws exception when closing issue

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#966]
When I closed issue https://github.com/yegor256/cactoos/issues/780#issuecomment-383936784 0crat responded with following:

```
PID: 4@346df6c8-40cd-4f70-ba65-5999eead80a1, thread: BkParallel-2
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 4 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1141468386">
   <created>2018-04-24T14:58:41.293Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;780</token>
   <author>krzyk</author>
   <params>
      <param name="job">gh:yegor256/cactoos#780</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-04-24T15:13:41.299Z</until>
</claim>
```

It should not do something like that, even when the issue reported closed the issue.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@krzyk it should be fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#966` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
