### ISSUE TITLE
Ledger should be able to work without a Project

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#967]
Currently [Ledger](https://github.com/zerocracy/farm/blob/75dd306ccac34da7168d0f31559ced097d06fda1/src/main/java/com/zerocracy/pm/cost/Ledger.java) is a class with no interface, it cannot have multiple implementations. However, I noticed at least [here](https://github.com/zerocracy/farm/blob/d06f16c3ef055e3dd5827fb4f044d7083f745d53/src/main/resources/com/zerocracy/stk/pmo/debts/pay_all_debts.groovy#L62) that ``Ledger`` is supposed to also work without a ``Project`` (it is initialized with ``FkProject``). 

Instead of trying to "fool" the objects and pass them fake dependencies, we should have more implementations of the interface, one for each scenario.

I noticed this problem in more areas of the project, fake implementations are used in production code, which is really not ok.

**Comment by yegor256** [comment]
@amihaiemil it's a good thinking, but we will have to change the entire system. We have many classes now that don't have interfaces, and it's OK, since they all our one-time-use entities. They are not supposed to be decorated anyhow. Let me explain it in the documentation...

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dda423bf-f743-481b-8efe-d9b489cae20a, thread: BkParallel-5
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 12 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1241026091">
   <created>2018-05-04T10:26:08.683Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">bad</param>
      <param name="job">gh:yegor256/cactoos#770</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">770</param>
      <param name="comment">386561333</param>
   </params>
   <token>github;yegor256/cactoos;770;386561333</token>
   <author>elenavolokhova</author>
</claim>

com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 12 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1241026091">
   <created>2018-05-04T10:26:08.683Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">bad</param>
      <param name="job">gh:yegor256/cactoos#770</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">770</param>
      <param name="comment">386561333</param>
   </params>
   <token>github;yegor256/cactoos;770;386561333</token>
   <author>elenavolokhova</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#967](https://github.com/zerocracy/farm/issues/967) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1241033268); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#967` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/967#issuecomment-386565709))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#967](https://github.com/zerocracy/farm/issues/967) is [in scope](http://www.zerocracy.com/policy.html#14) for 15min
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for [15min](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23967%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by amihaiemil** [comment]
@yegor256 

> but we will have to change the entire system

I imagine that, in the end, the redesign would be huge, but would the impact be so big we we did it gradually, through puzzles? :/

It doesn't seem that complicated (at least at a first glance).

**Comment by g4s8** [comment]
@amihaiemil can we close this job or it requires more changes?

**Comment by amihaiemil** [comment]
@g4s8 well, yes, but I still don't like that we have no interfaces :(

I understood that it would be too much of a change, though, so let's close...

**Comment by 0crat** [comment]
Job [#967](https://github.com/zerocracy/farm/issues/967) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#967](https://github.com/zerocracy/farm/issues/967) is now out of scope
