### ISSUE TITLE
 Unable to execute HTTP request in make_payment.groovy

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#969]
0crat responded with an unrecoverable failure when trying to make the payment for a closed issue, see [here](https://github.com/sunsofterp/portal/issues/8#issuecomment-384597406). The payment worked after all, I guess at the second trial.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it's a temporary issue, can't fix it anyhow. We are trying a few times and if we fail, we put the amount to the list to debts. The programmer won't lose anyway.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
