### ISSUE TITLE
0crat allows assignment of DEV to issue with active PR

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#973]
0crat allows assignment of DEV to issue with active PR. It happened in https://github.com/yegor256/cactoos/issues/747 : 0crat assigned an issue which had already an opened PR to another DEV. 

There are some suggestions to avoid / correct this problem:
- 0crat should block PRs referencing that issue not made by the issue responsible, if there is one;
- 0crat should auto-assign the issue when someone makes a PR referencing it, if the issue is not assigned to anyone;
- 0crat should automatically reject opened PRs referencing an issue when assigning it to someone;
- enforce issue control policy, notifying project ARC when similar situation happens (if someone which is not assigned to issue is committing / requesting pull related to the issue).

It is related to https://github.com/zerocracy/farm/issues/937 and https://github.com/zerocracy/farm/issues/562 .

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@paulodamaso issue and PRs are independent entities for 0crat, it should not make an assignment decision based on referenced PRs

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#973` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
