### ISSUE TITLE
0crat assignes issue but user is not set as assignee

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#974]
0crat assigned issue #747 to me (at least said so in https://github.com/yegor256/cactoos/issues/747#issuecomment-384782094 ), but I'm not realy assigned to it.

May be related to #973.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@paulodamaso it's not possible to assign ticket in Github to first-time contributor if user was not added to project members list, even repo admin can't do that

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#974` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
