### ISSUE TITLE
Following the instructions to join Qulice project doesn't work

### ISSUE THREAD

**Issue by nqafield** [zerocracy/farm#975]
@0crat suggests that it's possible to join the project, but the instructions don't work.

Initially reported here: https://github.com/teamed/qulice/issues/882

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@nqafield[/z](https://www.0crat.com/u/nqafield) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#975` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
