### ISSUE TITLE
Resign or refuse a task

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#981]
0crat shows in a list of available commands `resign`, but [§6](http://www.zerocracy.com/policy.html#6) mentions `refuse`. 

When I do `refuse` or `resign` the effect is the same - I get unassigned from the task (and get negative points).

We should either update the policy or the 0crat list of commands to include all that are available and make either refuse or resign work, but not both.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@yegor256 and a list of comands displayed by 0crat also should be updated.
Is it possible for it to be always up to date? I didn't look into the code, but it should be possible to keep a single list of commands that 0crat understands and can print out in the help text.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#981` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
