### ISSUE TITLE
Error refusing task

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#982]
Zerocrat showed an error when I refused a task today (https://github.com/sunsofterp/portal/issues/2), an asked to file a issue here:

PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-3
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoWriteException: quota exceeded
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso it was a temporary bug, it's gone already
