### ISSUE TITLE
What's the purpose of `out` command

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#986]
It is not clear what is the purpose of `out` command. I thought it is a inverse of `in`, but I can't do `out` on a issue that is not closed.
But closed issues are automatically being `outed` by 0crat, so why have a command that is not needed?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
