### ISSUE TITLE
`out` doesn't remove "scope" tag

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#988]
When I did `@0crat out` (and the issue wasn't assigned) in https://github.com/teamed/qulice/issues/869 it said that it removed it from the scope, but it didn't remove the "scope" tag from the issue.
Having that tag is misleading and makes browsing issues harder.
Please make sure that after issueing `out` command the the "scope" tag is removed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#988](https://github.com/zerocracy/farm/issues/988) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#988](https://github.com/zerocracy/farm/issues/988) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1620052713); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by proshin-roman** [comment]
@0crat wait until PR #1137 is merged

**Comment by 0crat** [comment]
> @0crat wait until PR #1137 is merged ([here](https://github.com/zerocracy/farm/issues/988#issuecomment-396625197))

@proshin-roman The impediment for [#988](https://github.com/zerocracy/farm/issues/988) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@krzyk the issue wasn't reproduced, but I've added more unit tests in #1137. Please, check if the ticket can be closed.

**Comment by krzyk** [comment]
@proshin-roman thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#988](https://github.com/zerocracy/farm/issues/988) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
