### ISSUE TITLE
assign_role must validate GitHub access permissions

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#989]
When we assign role to a new person in a project, `assign_role` must validate that the person has access to all GitHub repos linked to the project.

**Comment by 0crat** [comment]
Job [#989](https://github.com/zerocracy/farm/issues/989) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#989](https://github.com/zerocracy/farm/issues/989) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562035850); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat waiting PR #1118 to merge

**Comment by 0crat** [comment]
> @0crat waiting PR #1118 to merge ([here](https://github.com/zerocracy/farm/issues/989#issuecomment-395808333))

@g4s8 The impediment for [#989](https://github.com/zerocracy/farm/issues/989) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1145](https://github.com/zerocracy/farm/issues/1145) is still not solved.

**Comment by g4s8** [comment]
@yegor256 it was implemented in #1118 PR, can we close?

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#989](https://github.com/zerocracy/farm/issues/989) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1145](https://github.com/zerocracy/farm/issues/1145) is solved here.
