### ISSUE TITLE
Payment failed with no debt registered

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#991]
In [this](https://github.com/sunsofterp/portal/pull/18#issuecomment-386121887) Pull Request, the payments seem to have failed entirely. I only received the reputation points but no Paypal payment or debt registration was made. 

3 failures are visible in that PR: one in ``make_payment.groovy``, one in ``pay_architect_for_pull_request.groovy`` and the other in ``reject_people_below_score.groovy``. I have no idea what the ``reject_people_below_score.groovy`` is supposed to do in this scenario, 

What changed for me just yesterday is that I graduated, passed 2048 reputation, maybe that has something to do with it?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@amihaiemil I think it was fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#991` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
