### ISSUE TITLE
Tweet containing IDs instead of Names

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#992]
When 0crat is tweeting to ask for developers on a project, it uses the project's internal ID instead of its name. See here: https://twitter.com/0crat/status/991959781693943808

We had a similar Issue a month ago: https://github.com/zerocracy/farm/issues/940, but that one was concerning the link: it was poiting to 0crat instead of Github -- the fix there was that we now allow any 0crat user to see the Project's page, not only the ones which are part of the project's team.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#992](https://github.com/zerocracy/farm/issues/992) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1231235373); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#992` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil should be OK now

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#992](https://github.com/zerocracy/farm/issues/992) is now out of scope
