### ISSUE TITLE
NPE in Xocument ctor

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#993]
```
java.lang.NullPointerException
	at com.zerocracy.Xocument.<init>(Xocument.java:111)
	at com.zerocracy.pmo.Catalog.bootstrap(Catalog.java:79)
	at com.zerocracy.entry.Ping.post(Ping.java:78)
	at com.zerocracy.entry.Ping.post(Ping.java:66)
	at com.zerocracy.entry.Ping.execute(Ping.java:53)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Job pings.hour threw an unhandled Exception:
java.lang.NullPointerException
	at com.zerocracy.Xocument.<init>(Xocument.java:111)
	at com.zerocracy.pmo.Catalog.bootstrap(Catalog.java:79)
	at com.zerocracy.entry.Ping.post(Ping.java:78)
	at com.zerocracy.entry.Ping.post(Ping.java:66)
	at com.zerocracy.entry.Ping.execute(Ping.java:53)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

I can't understand what's going on and why... I see this sometimes.

**Comment by 0crat** [comment]
Job [#993](https://github.com/zerocracy/farm/issues/993) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The score of @yegor256[/z](https://www.0crat.com/u/yegor256) -449 is too low and will be reset: +449 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#993](https://github.com/zerocracy/farm/issues/993) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1611053816); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/993#issuecomment-396706758))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#993](https://github.com/zerocracy/farm/issues/993), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#993](https://github.com/zerocracy/farm/issues/993) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1700842384); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256 Do you have any information on `pings.hour` job?

**Comment by yegor256** [comment]
@paulodamaso not really... what kind of information do you need?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@yegor256 Anything you could provide about it, but we could start with which class implements it.

**Comment by yegor256** [comment]
@paulodamaso I suspect that the problem is in `Txn.acq()`:

```
    public Item acq(final String file) throws IOException {
        final Txn.TxnItem item;
        if (this.items.containsKey(file)) {
            item = this.items.get(file);
        } else {
            synchronized (this.items) {
                if (this.items.containsKey(file)) {
                    item = this.items.get(file);
                } else {
                    item = this.item(file);
                    this.items.put(file, item);
                }
            }
        }
        return item;
    }
```

This code, obviously, may return NULL sometimes. Don't you think?

**Comment by paulodamaso** [comment]
@yegor256 I think that is true. So we could fail fast here and throw some exception upon 'this.items.containsKey(file)' being NULL WDYT?

**Comment by yegor256** [comment]
@paulodamaso maybe it's better to make this method thread safe? @g4s8 what's your take on this?

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@paulodamaso I think it may help, but I'd try to reproduce it with test first

**Comment by paulodamaso** [comment]
@0crat wait for #1271

**Comment by 0crat** [comment]
> @0crat wait for #1271  ([here](https://github.com/zerocracy/farm/issues/993#issuecomment-400909435))

@paulodamaso The impediment for [#993](https://github.com/zerocracy/farm/issues/993) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1284](https://github.com/zerocracy/farm/issues/1284) is still not solved.

**Comment by paulodamaso** [comment]
@yegor256 merged, please close

**Comment by yegor256** [comment]
@paulodamaso thanks!

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details on registered [impediment](https://github.com/zerocracy/farm/issues/993#issuecomment-400909435).

**Comment by paulodamaso** [comment]
@ypshenychka What else could I write there?

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1284](https://github.com/zerocracy/farm/issues/1284) is solved here.
