### ISSUE TITLE
"We owe you these N payments" is unreadable

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#995]
The section about debt in user page (https://www.0crat.com/u/login) lists all the pending payments in one line. This is unreadable.

This list should be put in a table so it can be easily inspected by the user.

**Comment by yegor256** [comment]
@krzyk we tried to fix this in #660

**Comment by krzyk** [comment]
@yegor256 OK, I'll close this. But considering that there are now 2 duplicates of #660, that it should be somehow formatted differently (less ugly)?
Maybe make it at least a list? Add newlines after each debt entry?

**Comment by yegor256** [comment]
@krzyk we just don't want to keep those lists too long. They have to include 10 items, at most. Creating a full-scale table would make the layout uglier than it is now, I believe.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
